:title: TDD 
:number: 04
:duration: 35
include::../../../../adoc/libs/header-saison.adoc[]

// tag::intro[]
Approche de développement orientée tests pour garantir la qualité du code.
// end::intro[]

== Objectifs pédagogiques

// tag::objectifs[]
Comprendre les principes du développement piloté par les tests
Intégrer le TDD dans le développement d’applications
Savoir écrire et exécuter des tests unitaires
// end::objectifs[]

== Notions

// tag::notions[]
Cycle Red-Green-Refactor
Écriture de tests unitaires
Test d’intégration
Mocking et stubbing
Couverture de code
Bonnes pratiques de TDD
// end::notions[]



== Prérequis formateur

// tag::prerequis[]
Expertise en développement avec TDD
Connaissance des frameworks de test
Expérience en écriture de tests et couverture de code
// end::prerequis[]

== Résumé

// tag::resume[]
Cette saison permet aux apprenants de se lancer sereinement dans leur formation. On les aide à installer tous les outils, on leur présente quelques notions d'introduction, on les prépare à savoir cloner les challenges et lancer des DevContainer.
// end::resume[]

== Déroulement

link:./overview.html[Vue kanban]

// tag::deroulement[]
include::episodes/*/*.adoc[opts=episodes]
// end::deroulement[]