:title: Analyse et conception
:number: 01
:duration: 35
include::../../../../adoc/libs/header-saison.adoc[]

// tag::intro[]
Cette première saison pose les bases de l'analyse et de la conception de projets. Les apprenants apprendront à décomposer un besoin, à structurer et à modéliser les fonctionnalités attendues d’une application, ainsi qu'à choisir les technologies adéquates pour répondre aux objectifs du projet.
// end::intro[]

== Objectifs pédagogiques

// tag::objectifs[]
Comprendre les bases de la modélisation UML
Utiliser les diagrammes UML pour modéliser des systèmes de données
Formaliser les besoins d’un projet à travers UML
// end::objectifs[]

== Notions

// tag::notions[]
Diagrammes de cas d'utilisation
Diagrammes de classes
Diagrammes de séquence
Diagrammes d'activité
Modélisation de base de données
Spécifications fonctionnelles
// end::notions[]

== Prérequis formateur

// tag::prerequis[]
Maîtrise des concepts UML
Expérience en analyse fonctionnelle
Connaissances en modélisation de données
// end::prerequis[]

== Résumé

// tag::resume[]
Cette saison permet aux apprenants de se lancer sereinement dans leur formation. On les aide à installer tous les outils, on leur présente quelques notions d'introduction, on les prépare à savoir cloner les challenges et lancer des DevContainer.
// end::resume[]

== Déroulement

link:./overview.html[Vue kanban]

// tag::deroulement[]
include::episodes/*/*.adoc[opts=episodes]
// end::deroulement[]