:title: DevOps 
:number: 02
:duration: 35
include::../../../../adoc/libs/header-saison.adoc[]

// tag::intro[]
Cette saison introduit les pratiques et outils de DevOps, pour automatiser et améliorer la collaboration entre le développement et l’exploitation. Les participants mettront en place des pipelines CI/CDet à utiliserons des outils de containerisation.
// end::intro[]

== Objectifs pédagogiques

// tag::objectifs[]
* *Comprendre* la philosophie DevOps
* *Appliquer* un déploiement continu (CD)
* *Créer* des conteneurs pour lancer les applications
* *Analyser* un processus de CI/CD
// end::objectifs[]

== Notions

// tag::notions[]
* CI/CD
* GitHub Actions
* Docker
* Reverse Proxy
// end::notions[]

== Prérequis formateur

// tag::prerequis[]
* Connaissances sur les GitHub actions
* Bonnes connaissances de Docker
// end::prerequis[]

== Résumé

// tag::resume[]
L'objectif de cette saison est de donner un but aux apprenants (aka mettree en production sa propre application) et de leur donner les outils pour y arriver. L'angle d'apprentissage est d'atteindre rapidement ce but sans forcément comprendre tous les concepts sous-jacents et les garder motivés.

Une fois les bases fonctionnelles, on reprend chaque partie en appliquant les bonnes pratiques et en améliorant la compréhension.

Le métier Ops est complexe pour un développeur et demande des compétences variées. Cette saison est une ouverture montrant le principe et les possibilités de DevOps. La mise en production dans les règles de l'art est un métier à part entière et n'est donc pas appliquée ici.
// end::resume[]

== Déroulement

link:./overview.html[Vue kanban]

// tag::deroulement[]
include::episodes/*/*.adoc[opts=episodes]
// end::deroulement[]