:titre: Cisco Academy - CCNA
:module: Programme
:duree: 20
:description: Modalités et informations sur la Cisco Academy et la certification CCNA
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../adoc/libs
endif::[]

== Objectifs pédagogiques
// tag::objectifs[]
* Connaître la plateforme Cisco Academy, la certification CCNA, ses étapes, et ses prérequis
* Appréhender les domaines de compétences évalués par la certification CCNA
* Acquérir les bases pour se préparer efficacement à l'examen CCNA
// end::objectifs[]

// tag::deroulement[]
== Cisco Academy

Cisco Academy est un programme de formation en ligne qui propose des cours sur les technologies réseaux et les certifications Cisco. Il est conçu pour les étudiants, les professionnels de l’IT et les enseignants.

O'Clock est partenaire Cisco et vous fait donc bénéficier de contenus de qualité pour vous préparer à la certification CCNA.

https://www.netacad.com/[ça se passe par ici !]

[NOTE.speaker]
--
⚠️ **Attention** : le passage de l'examen n'est pas compris dans la formation, si tu souhaites passer l'examen, il faudra le faire par tes propres moyens. La certification CCNA n’est pas obligatoire dans le cadre de la formation DevOps chez O'clock. Même si on te prépare aux compétences nécessaires pour réussir l'examen, tu n’es pas tenu de la passer durant ou après la formation. Cela reste totalement à ta discrétion.
--

== CCNA, c'est quoi ?

Cisco Certified Network Associate est une certification délivrée par Cisco Systems, un des leaders mondiaux en technologies réseaux

* atteste des compétences professionnelles dans le domaine des réseaux
* couvre un large éventail de sujets, y compris les concepts fondamentaux des réseaux, la sécurité réseau, le routage et la commutation
* incontournable pour les professionnels de l’IT

=== Pourquoi cette certification ?

* augmentation des opportunités d’emploi
* reconnaissance professionnelle
* avancement de carrière
* maîtrise des technologies réseau

== Structure de l'examen

* Questions à choix multiple (QCM) pour tester la compréhension théorique des concepts clés en réseaux
* Simulations de laboratoire pour démontrer la capacité à configurer et dépanner des équipements réseau dans un environnement simulé
* Scénarios de troubleshooting pour démontrer la capacité à identifier et résoudre des problèmes réseau basés sur des scénarios donnés

=== Exemple de question

**La table de routage d’un routeur Cisco a quatre routes statiques pour le réseau 10.0.0.0. Quelle route est la meilleure correspondance pour un paquet entrant dans le routeur avec une destination de 10.16.0.10?**

* 10.0.0.0/16 is directly connected, GigabitEthernet 0/1
* 10.16.0.0/16 is directly connected, GigabitEthernet 0/0
* 10.0.0.0/8 [1/0] via 202.16.0.2
* 10.16.0.0/24 [1/0] via 202.16.0.2

== Plan de préparation

**La plupart du temps, vos journées du vendredi seront dédiées à la préparation de la certification.**

**Quelques conseils pour réussir **

* Suivre les cours O’Clock 😏
* Etudier les ressources officielles de Cisco
* Pratiquer régulièrement les notions abordées (notamment via les différents laboratoires mis à disposition)
* Utiliser des simulateurs de réseaux

=== Quelques ressources supplémentaires

* 🔗 https://www.cisco.com/c/m/en_sg/partners/cisco-networking-academy/index.html#~start-your-it-learning-journey-now[cours en ligne Cisco]
* 🔗 https://mkto.cisco.com/ccna-cert-guide.html[manuels et guide officiels Cisco]

// end::deroulement[]

== Conclusion
// tag::conclusion[]
* Compréhension du rôle et de l'importance de la certification CCNA
* Familiarisation avec la structure de l'examen et les compétences évaluées
// end::conclusion[]
