services:
  devcontainer:
    build:
      context: ./.devcontainer
    volumes:
      - .:/workspace
      # Copy ssh keys to the container
      - ~/.ssh:/root/.ssh:ro
      # Copy docker socket to the container
      - /var/run/docker.sock:/var/run/docker.sock
  webserver:
    image: nginx:latest
    container_name: mon-site-webserver
    ports:
      - "8282:80"
    volumes:
      - ./le-build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: mon-site-backend
    ports:
      - "4000:4000"
