version: "3.9"

services:
  web:
    build: .
    container_name: mon-site-web
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mon-site-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: exempleRoot123
      MYSQL_DATABASE: monsite
      MYSQL_USER: monsiteuser
      MYSQL_PASSWORD: exempleUser123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql   # <- ici on utilise le volume défini plus bas

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mon-site-phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: monsiteuser
      PMA_PASSWORD: exempleUser123
    ports:
      - "8080:80"

volumes:
  db_data:   # <- le volume doit être déclaré ici
