user nginx;
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    sendfile on;

    server {
        listen 80;
        error_page 401 = 302 /login;
        error_page 403 = /403.html;
        error_page 404 = /404.html;


        # ---- PROTECTION JWT ----
        location / {
            auth_request /jwt-verify;
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }

        location /admin {
            auth_request /jwt-verify-admin;
            root /usr/share/nginx/html;
            try_files $uri /admin/index.html;
        }

        # Vérification spécifique admin
        location = /jwt-verify-admin {
            internal;
            proxy_pass http://backend:4000/auth/verify;
            proxy_set_header Cookie $http_cookie;
            proxy_set_header X-Required-Role "admin";
        }

        #Zone user seulement :
        location /dashboard {
            auth_request /jwt-verify;
        }

        #Zone admin :
        location /admin {
            auth_request /jwt-verify-admin;
        }

        #Tout le site mais laisser /public
        location /public {
            # pas de protection
        }

        # ---- VERIFY JWT ----
        location = /jwt-verify {
            internal;
            proxy_pass http://backend:4000/auth/verify;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Cookie $http_cookie;
        }

        # ---- LOGIN API ----
        location /auth/login {
            proxy_pass http://backend:4000/auth/login;
        }

        # ---- LOGIN PAGE (static) ----
        location /login {
            root /usr/share/nginx/html;
            try_files $uri /login.html;
        }
    }
}
