user nginx;
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    sendfile on;

    server {
        listen 80;

        # ---- PROTECTION JWT ----
        location / {
            auth_request /jwt-verify;
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }

        # ---- VERIFY JWT ----
        location = /jwt-verify {
            internal;
            proxy_pass http://backend:4000/auth/verify;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Cookie $http_cookie;
        }

        # ---- LOGIN API ----
        location /auth/login {
            proxy_pass http://backend:4000/auth/login;
        }

        # ---- LOGIN PAGE (static) ----
        location /login {
            root /usr/share/nginx/html;
            try_files $uri /login.html;
        }
    }
}
