user  nginx;
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    sendfile on;
    resolver 127.0.0.11;

    server {
        listen 80;

        # Protège tout le site
        location / {
            auth_request /authelia-auth;
            error_page 401 =302 /authelia-redirect;
            root /usr/share/nginx/html;
            try_files $uri $uri/ =404;
        }

        # Endpoint interne pour demander l’auth
        location = /authelia-auth {
            internal;
            proxy_pass http://authelia:9091/api/authz/auth-request;
            proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Content-Length "";
            proxy_pass_request_body off;
        }

        # Page de redirection vers login Authelia
        location /authelia-redirect {
            return 302 http://$host:8282/authelia/?rd=$scheme://$host$request_uri;
        }

        # Portail Authelia
        location /authelia/ {
            proxy_pass http://authelia:9091/;
        }
    }
}
