# Identifiants du projet SonarCloud
sonar.projectKey=wololobzh_VPSPow
sonar.organization=wololobzh-1

# Code source
sonar.sources=./src
sonar.tests=./tests
sonar.sourceEncoding=UTF-8

# Rapport de coverage PHPUnit
sonar.php.coverage.reportPaths=coverage.xml