:title: BEM, Positions et Grid
:number: 04
include::../../../../../../adoc/libs/header-episode.adoc[]

// tag::intro[]
Découverte de la méthodologie BEM pour structurer le CSS, maîtrise du positionnement des éléments, dont Grid pour des mises en page modernes.
// end::intro[]

== Objectifs pédagogiques

// tag::objectifs[]
* *Comprendre* la méthodologie BEM pour organiser son CSS
* *Comprendre* les possibilités offertes par CSS Grid
* *Appliquer* les différents types de positionnement CSS
* *Analyser* le choix de grid ou flexbox
// end::objectifs[]

== Prérequis formateur

// tag::prerequis[]
* Pas de pré-requis
// end::prerequis[]

== Déroulement

// tag::deroulement[]
include::../../../../modules/bases-web/bem.adoc[options=modules]

TIP: ☕ Pause café

:correction: https://github.com/O-clock-FS-JS/Shop-oFig/tree/correction
:temps: 120 minutes
:description: Correction de l'exercice de la veille en appliquant BEM
include::../../../../../../adoc/libs/intro-correction.adoc[]

.Indications complémentaires pour la correction
[%collapsible]
====
⚠️ Il faut utiliser le BEM :

* On pose la structure HTML de base en posant le css en même temps
* On part de l'extérieur vers l'intérieur
* Pas nécessaire de faire toutes les images s3 ou 4 suffisent
* Les figurine sont dans des éléments article mis dans une flexbox wrap (ils doivent donc avoir une taille).
* Pour le lien ajouter au panier : transition CSS sur le a autour des deux éléments lors du survol.
* On peut enchainer sur les positions, par exemple je voudrais que la barre de menu reste toujours en haut
====

TIP: 🍕 Pause déjeuner

include::../../../../modules/bases-web/position.adoc[options=modules]

:correction: https://github.com/O-clock-FS-JS/oFig-home/tree/grid
:temps: 30 minutes
:description: Découverte de la version Grid de la correction
include::../../../../../../adoc/libs/intro-correction.adoc[]

.Indications complémentaires pour la correction
[%collapsible]
====
* Utiliser la branche "grid" du repo oFig pour passer l'affichage de la grille de produits de flex vers grid.
* L'idée ici est de leur montrer les bases de Grid, il n'est donc pas nécessaire de rentrer dans les moindres détails (d'autant que Flex et le positionnement leur a déjà bien pris la tête)
* L'intérêt principal d'utiliser Grid dans ce contexte est de pouvoir faire varier l'affichage des cartes pour présenter le contenu de manière moins monotone ou prévisible.
====

*Atelier pair programming*

Expliquer en 15 min le principe de l'atelier qui est le premier :

* à 9h on présente le sujet et les groupes pendant environ 15 minutes
* Les groupes sont fait de façon automatique (par niveau si possible mais ne pas le dire)
* Puis présentation du principe du pair programming
* L'atelier dur toute la journée de 9h15 à 17h
* Si besoin faire des rappels sur git, liveshare et discord

*Fin du cours*

On peut proposer aux étudiants : https://flexboxfroggy.com/#fr[Flexbox Froggy,window=_blank] ou http://www.flexboxdefense.com/[Flexbox tower defense,window=_blank] pour s'entrainer.

S'ils veulent faire de la grid css : https://cssgridgarden.com/#fr[Grid garden,window=_blank]

:challenge: https://github.com/O-clock-FS-JS/oNews-homepage
:description: Page d'accueil d'un site de news étudiantes.
:correction:
include::../../../../../../adoc/libs/intro-challenge.adoc[]
// end::deroulement[]
