classDiagram
    class Entreprise {
        - nom : string
        - adresse : string
    }
    class Employe {
        - nom : string
        - poste : string
    }
    Employe "0..*" --> "1" Entreprise : travaille pour