classDiagram
    class Etudiant {
        - nom : string
        - matricule : int
    }
    class Cours {
        - titre : string
        - code : string
    }
    Etudiant "0..*" -- "0..*" Cours : s'inscrit à