flowchart TD
    Start[Début] --> A[Passer commande]
    A --> B{Stock disponible ?}
    B -->|Oui| C[Confirmer commande]
    B -->|Non| D[Informer client du manque de stock]
    C --> E[Informer client]
    E --> F[Envoyer commande]
    E --> G[Mettre à jour stock]
    F --> Join((Fin))
    G --> Join