:titre: Ansible Galaxy
:module: Ansible
:duree: 90
:description: Tour d'horizon d'Ansible Galaxy et de son utilisation pour simplifier le travail d'un DevOps.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
* *Comprendre* le concept d'Ansible Galaxy et ses avantages pour le DevOps
* *Rechercher* et *installer* des rôles depuis Ansible Galaxy
* *Utiliser* des rôles dans des playbooks Ansible
* *Créer* et *publier* des rôles sur Ansible Galaxy
// end::objectifs[]

// tag::deroulement[]
== Introduction à Ansible Galaxy

Ansible Galaxy est un hub communautaire où les utilisateurs peuvent partager et télécharger des rôles pour automatiser diverses tâches avec Ansible.

* Simplifie la gestion des configurations répétitives
* Encourage la réutilisation de rôles existants
* Centralise les ressources pour la gestion des rôles

[NOTE.speaker]
--
Ansible Galaxy est conçu pour faciliter le partage de configurations entre équipes et au sein de la communauté. En réutilisant des rôles existants, les DevOps peuvent gagner du temps et éviter de réinventer la roue.
--

== Avantages des rôles partagés

* Réutilisation de code et gain de temps
* Facilité de maintenance et d'amélioration continue
* Standardisation des configurations dans les équipes

[NOTE.speaker]
--
L'utilisation de rôles partagés permet aux équipes de maintenir des configurations cohérentes et de réduire les erreurs humaines en automatisant des tâches répétitives. 
--

== Recherche et installation de rôles

Pour rechercher des rôles sur Ansible Galaxy, utilisez la commande suivante :

```bash
ansible-galaxy search <role_name>
```

Pour installer un rôle, utilisez :

```bash
ansible-galaxy install <role_name>
```

[NOTE.speaker]
--
La commande `ansible-galaxy search` permet de rechercher des rôles directement depuis la ligne de commande. Une recherche directement sur le site https://galaxy.ansible.com/ui/[Ansible Galaxy] est également possible et permet d'identifier les rôles les plus populaires.
--

// tag::demo[]
=== Démonstration

[NOTE.speaker]
--
. Recherchez un rôle `Caddy` sur Ansible Galaxy en utilisant `ansible-galaxy search`.
. Recherchez via le site web Ansible Galaxy pour montrer les résultats.
. Installez le rôle `caddy_ansible.caddy_ansible` en utilisant `ansible-galaxy install`.
. Affichez le contenu du rôle installé pour montrer sa structure.
--
// end::demo[]

== Utilisation des rôles dans les playbooks

Les rôles sont organisés selon une structure spécifique qui permet de les intégrer facilement dans les playbooks.

* Chaque rôle contient des tâches, des handlers, des variables, etc.
* Importer un rôle dans un playbook en utilisant la directive `roles`

Exemple d'utilisation dans un playbook :

```yaml
- hosts: all
  roles:
    - role: caddy_ansible.caddy_ansible
      vars:
        caddy_version: 2.4.5
        caddy_config:
          ...
```

[NOTE.speaker]
--
Pour intégrer un rôle dans un playbook, il suffit d'ajouter le nom du rôle sous la directive `roles`. Les rôles sont généralement bien structurés, avec des fichiers dédiés pour les tâches, les variables et autres configurations.
--

// tag::demo[]
=== Démonstration

Utiliser caddy_ansible.caddy_ansible dans un playbook pour configurer un serveur web Caddy.

[NOTE.speaker]
--
.caddy.yml
```
- name: Install caddy from caddy_ansible.caddy_ansible
  hosts: debian1
  become: yes
  gather_facts: yes

  roles:
    - role: caddy_ansible.caddy_ansible
```

En exécutant ce playbook, on trouve un message d'erreur car debian n'a pas systemd.

```json
fatal: [debian1]: FAILED! => {
    "assertion": "ansible_service_mgr == 'systemd'",
    "changed": false,
    "evaluated_to": false,
    "msg": "This module only works with systemd"
}
```

Il faut donc faire attention à quel module on utilise pour quel OS.
--

== Rôles vs Collections

* Rôle : ensemble de tâches, de variables, de fichiers, de templates et de modules organisés de manière à accomplir une fonction spécifique.
* Collection : regroupement plus large qui peut contenir des rôles, des modules, des plugins...

https://galaxy.ansible.com/ui/repo/published/community/mongodb/[Collection community.mongodb]

[NOTE.speaker]
--
Les rôles sont conçus pour être réutilisables et faciles à partager. Un rôle suit généralement une structure de répertoire spécifique, ce qui facilite son intégration dans des playbooks.

Les collections sont une manière plus moderne et flexible de distribuer du contenu Ansible. Elles permettent de regrouper plusieurs rôles et autres composants nécessaires pour gérer une application ou une infrastructure complète.
--

== Collection

Les collections sont des ensembles de contenus Ansible qui peuvent inclure :

* des rôles
* des modules
* des plugins
* des playbooks
* des inventaires
* etc.

=== Installation et utilisation

Pour installer une collection, utilisez la commande suivante https://galaxy.ansible.com/ui/repo/published/community/mongodb/[(doc)] :

```bash
ansible-galaxy collection install community.mongodb
```

On peut ensuite utiliser le rôle `mongodb_install` dans un playbook https://galaxy.ansible.com/ui/repo/published/community/mongodb/content/role/mongodb_install/[(doc)]:

```yaml
- hosts: all
  - roles:
    - role: community.mongodb.mongodb_repository
    - role: community.mongodb.mongodb_install
```

// tag::exercice[]
== Exercice

Réalisez les actions suivantes avec un playbook Ansible :

. Recherchez et installez un rôle pour configurer Nginx.
. Créez un playbook qui utilise ce rôle pour configurer un serveur web.
. Vérifiez le bon fonctionnement avec un `curl`.
// end::exercice[]

// end::deroulement[]

== Conclusion

// tag::conclusion[]
* Ansible Galaxy simplifie la gestion des configurations en facilitant le partage et la réutilisation de rôles.
* La recherche et l'installation de rôles via la ligne de commande sont simples et efficaces.
* Créer et publier des rôles permet aux DevOps de partager leurs solutions avec la communauté.
// end::conclusion[]