:titre: Playbook databases
:module: Ansible
:duree: 120
:description: Mise en pratique d'un playbook pour créer des bases de données postgresql et mongodb
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
* *Appliquer* un playbook Ansible pour configurer des bases de données
* *Comprendre* les rôles
* *Comprendre* les tags
* *Modifier* la configuration d'ansible
// end::objectifs[]

// tag::deroulement[]
== Objectif

Installation sur :

- alpine1 et alpine2 : postgresql
- debian3 : mongodb

[NOTE.speaker]
--
On démontrera que l'installation de mongodb est plus complexe que postgresql car le paquet n'existe pas dans les dépôts officiels. Il faudrait ajouter un dépôt tiers ce qui est compliqué. 

On ouvre la porte sur l'utilisation d'anisble galaxy pour récupérer un rôle déjà existant sans le mettre en place
--

// tag::demo[]
=== Démonstration Postgresql

* Groupement des serveurs alpine1, alpine2 et debian3 dans le groupe `databases` dans le fichier `inventory.yml`
* Création des tâches pour l'installation de postgresq : https://wiki.alpinelinux.org/wiki/Postgresql[Documentation Alpine]
* Création d'une fichier sql pour alimenter la base de données

Les commandes suivantes permettent de lancer les playbooks en utilisant les tags et éviter de relancer l'installation à chaque fois qu'on teste la configuration :

```bash
ansible-playbook -i inventory.yml playbooks/databases.yml --tags config
# ou
ansible-playbook -i inventory.yml playbooks/databases.yml ---skip-tags install
```

[NOTE.speaker]
--
.invetory.yml
```yaml
# Groupe de serveurs de bdd avec des sous-groupes
databases:
  children:
    db_alpine:
      hosts:
        alpine1:
        alpine2:
    db_debian:
      hosts:
        debian3:
```

.databases.yml
```yaml
- name: Installation des bases de données PostgreSQL sur Alpine et MongoDB sur Debian
  hosts: databases
  become: yes
  gather_facts: yes

  vars:
    # Variables pour PostgreSQL
    pgsql_package: postgresql
    pgsql_service: postgresql
    pgsql_data_file: /root/data.sql
    pgsql_dest: /var/lib/postgresql/data.sql

  tasks:
    - name: Installer PostgreSQL
      apk:
        name: "{{ pgsql_package }}"
        state: present
      tags: 
        - install
      when: ansible_facts['os_family'] == "Alpine"

    - name : Initialise la base de données PostgreSQL
      command: initdb -D /var/lib/postgresql/data
      become_user: postgres
      tags: 
        - install
      when: ansible_facts['os_family'] == "Alpine"

    - name: Démarrer le service PostgreSQL
      service:
        name: "{{ pgsql_service }}"
        state: started
      tags: 
        - install
      when: ansible_facts['os_family'] == "Alpine"

    - name: Ajouter le service PostgreSQL au démarrage
      service:
        name: "{{ pgsql_service }}"
        enabled: yes
      tags:
        - install
      when: ansible_facts['os_family'] == "Alpine"
      
    - name: Copier le fichier SQL pour PostgreSQL
      copy:
        src: data.sql
        dest: "{{ pgsql_dest }}"
      notify: Alimentation des données PostgreSQL
      tags: 
        - config
      when: ansible_facts['os_family'] == "Alpine"

  handlers:
    - name: Alimentation des données PostgreSQL
      command: psql -U postgres -f "{{ pgsql_dest }}"
      become_user: postgres
```

L'utilisation de become_user permet de lancer la commande en tant qu'utilisateur postgres. Sur alpine, pour changer d'utilisateur, il faut utiliser `su` et non `sudo`. Il faut donc le définir dans la configuration d'ansible :

.ansible/ansible.cfg
```ini
[privilege_escalation]
become_method = su
```

.data.sql
```sql
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);
```

--

// tag::exercice[]
== Exercice

Lancer le playbook et vérifier la présence de la base de données avec un client psql et de données avec un `select * from users`.

// end::exercice[]

== Utilisation de rôles

Pour rappel, les rôles sont des ensembles préorganisés de tâches, handlers, templates, variables, etc., qui permettent de structurer des playbooks complexes.

// tag::demo[]
=== Démonstration

Utilisation d'un rôle pour installer pgsql.

* Modification du playbook pour utiliser un rôle
* Création d'un rôle pour l'installation de pgsql

[NOTE.speaker]
--

.databases.yml
```yaml
- name: Installation des bases de données PostgreSQL sur Alpine et MongoDB sur Debian
  hosts: databases
  become: yes
  gather_facts: yes

  vars:
    # Variables pour PostgreSQL
    pgsql_package: postgresql
    pgsql_service: postgresql
    pgsql_data_file: /root/data.sql
    pgsql_dest: /var/lib/postgresql/data.sql
    # Variables pour MongoDB
    mongodb_package: mongodb-org
    mongodb_service: mongod
    mongodb_conf_file: ./files/mongod.conf
    mongodb_dest: /etc/mongod.conf

  # Utilisation d'un rôle pour structurer le playbook
  roles:
    - role: install_pgsql
      when: ansible_facts['os_family'] == "Alpine"
```

* Création d'un dossier `roles` dans le répertoire `ansible/playbooks`
* Création d'un dossier `install_pgsql` dans le dossier `roles`
* Création des dossiers `tasks`, `handlers`, et `files` dans le dossier `install_pgsql`
* Copie du fichier sql dans le dossier `files`

.roles/install_pgsql/tasks/main.yml
```yaml
- name: Installer PostgreSQL
  apk:
    name: "{{ pgsql_package }}"
    state: present
  tags: 
    - install

- name : Initialise la base de données PostgreSQL
  command: initdb -D /var/lib/postgresql/data
  become_user: postgres
  tags: 
    - install

- name: Démarrer le service PostgreSQL
  service:
    name: "{{ pgsql_service }}"
    state: started
  tags: 
    - install

- name: Ajouter le service PostgreSQL au démarrage
  service:
    name: "{{ pgsql_service }}"
    enabled: yes
  tags:
    - install
  
- name: Copier le fichier SQL pour PostgreSQL
  copy:
    src: data.sql
    dest: "{{ pgsql_dest }}"
  notify: Alimentation des données PostgreSQL
  tags: 
    - config
```

.roles/install_pgsql/handlers/main.yml
```yaml
- name: Alimentation des données PostgreSQL
  command: psql -U postgres -f "{{ pgsql_dest }}"
  become_user: postgres
```

--
// end::demo[]

== Installation complexe

// tag::demo[]
=== Démonstration

Création des tâches pour l'installation de mongodb.

[NOTE.speaker]
-- 

.databases.yml
```yaml
....

  tasks:
    # Tâches pour MongoDB sur Debian
    - name: Installer MongoDB Community Server
      apt:
        name: "{{ mongodb_package }}"
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Copier le fichier de configuration MongoDB
      copy:
        src: "{{ mongodb_conf_file }}"
        dest: "{{ mongodb_dest }}"
      when: ansible_facts['os_family'] == "Debian"
      notify: Redémarrer MongoDB

  handlers:
    - name: Redémarrer MongoDB
      service:
        name: "{{ mongodb_service }}"
        state: restarted
```

En lançant une première fois le playbook, on obtient une erreur car le paquet `mongodb-org` n'est pas présent dans les dépôts officiels. Il faudrait ajouter un dépôt tiers pour l'installer.

Voir la https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-debian/[documentation MongoDB].
--

=== Solution mannuelle

Pour installer mongodb, il faut ajouter un dépôt tiers, ce qui nécessite de :

* Importer la clé GPG de MongoDB
* Convertir la clé GPG en format binaire
* Créer le fichier de liste des dépôts MongoDB
* Mettre à jour la liste des paquets
* Installer MongoDB Community Server

[NOTE.speaker]
--

.Exemple à ne pas reproduire :D
```yaml
- name: Installation MongoDB sur Debian
  hosts: databases
  become: yes
  gather_facts: yes

  vars:
    # Variables pour MongoDB
    mongodb_package: mongodb-org
    mongodb_service: mongodb
    mongodb_conf_file: ./files/mongod.conf
    mongodb_dest: /etc/mongod.conf
    mongodb_version: "8.0" 
    mongodb_key: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
    mongodb_key_file: "/usr/share/keyrings/mongodb-server-{{ mongodb_version }}.gpg"
    mongodb_list_file: "/etc/apt/sources.list.d/mongodb-org-{{ mongodb_version }}.list"

  tasks:
    # Tâches pour MongoDB sur Debian
    - name: Installer gnupg et curl
      apt:
        name:
          - gnupg
          - curl
          - systemctl
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Importer la clé GPG de MongoDB
      get_url:
        url: "{{ mongodb_key }}"
        dest: "/tmp/mongodb-server-{{ mongodb_version }}.asc"
      when: ansible_facts['os_family'] == "Debian"

    - name: Convertir la clé GPG en format binaire
      command: >
        gpg --dearmor -o {{ mongodb_key_file }} /tmp/mongodb-server-{{ mongodb_version }}.asc 
      when: ansible_facts['os_family'] == "Debian"

    - name: Créer le fichier de liste des dépôts MongoDB
      copy:
        dest: "{{ mongodb_list_file }}"
        content: "deb [ signed-by=/usr/share/keyrings/mongodb-server-{{ mongodb_version }}.gpg ] http://repo.mongodb.org/apt/debian {{ ansible_facts['distribution_release'] | lower }}/mongodb-org/{{ mongodb_version }} main"
      when: ansible_facts['os_family'] == "Debian"

    - name: Installer MongoDB Community Server
      apt:
        name: "{{ mongodb_package }}"
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Copier le fichier de configuration MongoDB
      copy:
        src: "{{ mongodb_conf_file }}"
        dest: "{{ mongodb_dest }}"
      when: ansible_facts['os_family'] == "Debian"
      notify: Redémarrer MongoDB

  handlers:
    - name: Redémarrer MongoDB
      service:
        name: "{{ mongodb_service }}"
        state: restarted
```

--

=== Solution avec ansible galaxy

Une solution plus avisée et plus simple est d'utiliser un rôle déjà existant sur ansible galaxy.

https://galaxy.ansible.com/ui/repo/published/community/mongodb/

[NOTE.speaker]
--
On reviendra plus tard sur l'utilisation d'ansible galaxy pour récupérer des rôles déjà existants.
--
// end::deroulement[]

== Conclusion

// tag::conclusion[]
* L'utilisation des rôles permet de structurer les playbooks et de les rendre plus modulaires
* La création de playbooks à la main pour des installations complexes peut être fastidieuse, l'utilisation d'ansible galaxy permet de gagner du temps.
// end::conclusion[]
