:titre: Playbook policies
:module: Anisble
:duree: 60
:description: Utilisation d'un playbook pour gerer des groupes, users et droits sur les fichiers. Utilisation de vault pour les mots de passe.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
* *Appliquer* un playbook Ansible pour configurer des politiques de sécurité
* *Comprendre* les vault
* *Modifier* la configuration d'ansible
// end::objectifs[]

// tag::deroulement[]
== Objectif

- gerer les utilisateurs (et donc des mots de passes)
- gerer les groupes
- gerer les droits sur les fichiers

== Vault

Ansible permet de chiffrer les données sensibles dans un fichier `vault.yml` et de les déchiffrer lors de l'exécution du playbook.

* Création du vault : `ansible-vault create secrets.yml`
* Edition du vault : `ansible-vault edit secrets.yml`

https://docs.ansible.com/ansible/2.8/user_guide/vault.html[Documentation Ansible]

// tag::demo[]
=== Démonstration

Création d'un mot de passe chiffré.

[NOTE.speaker]
--

* `ansible-vault create secrets.yml`
* Définir le mot de passe `1234`
* `ansible-vault edit secrets.yml`
* Entrer le mot de passe `1234`
* Ajouter les variables

```yaml
vault_user_password: "pwd"
```

--
// end::demo[]

=== Lancement du playbook

Le vault doit être inclus dans le playbook pour être utilisé grâce à `vars_files`.

```yaml
- name: Gérer les utilisateurs, groupes et permissions
  hosts: all
  become: yes
  vars_files:
    - ../secrets.yml
```

.Lancement du playbook
```bash
ansible-playbook -i inventory.yml playbooks/policies.yml --ask-vault-pass
```

Le mot de passe sera demandé pour déchiffrer le fichier `secrets.yml` et continuer le playbook.

== Policies

=== Groups

Pour gérer les groupes, il suffit d'utiliser le module `group`.

```yaml
- name: Créer un groupe
  group:
    name: mygroup
    state: present
```

=== Users

Pour gérer les utilisateurs, il suffit d'utiliser le module `user`.

```yaml
- name: Créer un utilisateur
  user:
    name: myuser
    password: "{{ vault_user_password | password_hash('sha512') }}"
    state: present
    groups: mygroup
```

// tag::exercice[]
=== Exercice

Avec un playbook Ansible, réaliser les actions suivantes :

. Créer un groupe `devops`
. Créer un groupe `admin`
. Créer un utilisateur `john` dans le groupe `devops` et `admin`
. Créer un utilisateur `jane` dans le groupe `devops`

// end::exercice[]

=== Permissions

Pour gérer les permissions, il suffit d'utiliser le module `file`.

.Dossier
```yaml
- name: Changer les permissions
  file: ~/myfolder
    owner: myuser
    group: mygroup
    mode: 0755
```

.Fichier
```yaml
- name: Changer les permissions
  file: ~/myfile.txt
    state: touch
    owner: myuser
    group: mygroup
    mode: 0644
```

// tag::exercice[]
=== Exercice

Avec un playbook Ansible, réaliser les actions suivantes :

. Créer un fichier `test.txt` dans le dossier `/home/jane/test.txt` avec les permissions lecture seule pour le groupe `devops`
. Créer un dossier `test` dans le dossier `/home/john/test` avec les permissions ecriture pour le groupe `admin`
. Créer un fichier `test.txt` dans le dossier `/home/john/test` avec les permissions les permissions lecture ecrirure pour tout le monde
. Modifier les permissions du fichier `/home/john/test/test.txt` pour les rendre en lecture seule pour tout le monde
// end::exercice[]

// end::deroulement[]

== Conclusion

// tag::conclusion[]
* Les vault permettent de chiffrer les données sensibles
* Les modules `group`, `user` et `file` permettent de gérer les groupes, utilisateurs et permissions
// end::conclusion[]
