:titre: Playbook webserver
:module: Ansible
:duree: 60
:description: Mise en pratique d'un playbook pour créer un serveur web
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
* *Appliquer* un playbook Ansible pour configurer un serveur web
* *Comprendre* les variables, boucles, conditions
* *Comprendre* les ansible_facts
* *Comprendre* les templates
// end::objectifs[]

// tag::deroulement[]
== Objectif

Installation sur :

- debian1 et debian2 : apache et php
- alpine3 : nginx et node

[NOTE.speaker]
--
L'installation sur alpine devra être réalisée en challenge.
--

// tag::demo[]
=== Démonstration

Création du fichier `webserver.yml` dans le dossier `ansible/playbooks` du repo.

[NOTE.speaker]
--

* Groupement des serveurs alpine3, debian1 et debian2 dans le groupe `webservers` dans le fichier `inventory.yml`
* Ciblage des serveurs `webservers`

.invetory.yml
```yaml
# Groupe de serveurs web
webservers:
  hosts:
    alpine3:
    debian1:
    debian2:
```

.webserver.yml
```yaml
- name: Installer LAMP sur Debian ou Nginx + Node.js sur Alpine
  hosts: webservers
  become: yes
  gather_facts: yes
```

* Utilisation d'une variable `php_version` pour définir la version de PHP à installer
* Utilisation de la boucle `loop` pour installer les paquets `apache2` et `php{{ php_version }}`
* Utilisation de la condition `when` et `ansible_facts`` pour n'exécuter les tâches que sur les systèmes Debian

.webserver.yml
```yaml
- name: Installer LAMP sur Debian ou Nginx + Node.js sur Alpine
  hosts: webservers
  become: yes
  gather_facts: yes
  vars:
    php_version: "8.2"

  tasks:
    # Tâches pour Debian
    - name: "Installer Apache et PHP{{ php_version }} sur Debian"
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - "php{{ php_version }}"
      when: ansible_facts['os_family'] == "Debian"
    
    - name: S'assurer qu'Apache est démarré sur Debian
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "Debian"
```

--

// tag::exercice[]
=== Exercice

Lancer le playbook et vérifier la réussite avec un `curl`.
// end::exercice[]

== Templating Jinja2

Le templating Jinja2 permet de générer des fichiers de configuration dynamiques en fonction des variables définies dans le playbook.

link:https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_templating.html[Documentation Ansible]

[NOTE.speaker]
--
Les cas d'utilisation du templating Jinja2 sont nombreux. Il permet de générer des fichiers de configuration, des scripts, des fichiers de logs, etc.

Dans le challenge, il servira à modifier la configuration nginx.
--

=== Exemple

.Dossier de travail
```
├── hostname.yml
├── templates
    └── test.j2
```

.hostnames.yml
```yml
---
- name: Write hostname
  hosts: all
  vars:
    outro: "Bisous"
  tasks:
  - name: write hostname using jinja2
    ansible.builtin.template:
       src: templates/test.j2
       dest: /tmp/hostname
```

.templates/test.j2
```jinja
My name is {{ ansible_facts['hostname'] }}. {{ outro }} !
```
// end::deroulement[]

== Conclusion

// tag::conclusion[]
* Application d'un playbook sélectif en fonction du système
* Utilisation de variables, boucles et conditions
* Découverte des template
// end::conclusion[]
