:title: Introduction à Ansible
:number: 01
include::../../../../../../adoc/libs/header-episode.adoc[]

// tag::intro[]
Les apprenants découvriront les principes de base d’Ansible et apprendront à installer et configurer l’outil sur une machine Debian. Ils exécuteront leur premier playbook pour automatiser une tâche simple et se familiariseront avec la gestion d’inventaires.
// end::intro[]

== Objectifs pédagogiques

// tag::objectifs[]
* *Comprendre* les concepts fondamentaux d’Ansible
* *Appliquer* : Installer et configurer Ansible sur une machine Debian
* *Appliquer* : Créer et exécuter un playbook simple pour automatiser une tâche basique
// end::objectifs[]

// tag::prerequis[]
* Avoir une VM serveur Kourou fonctionnelle
// end::prerequis[]

== Déroulement

// tag::deroulement[]
WARNING: *Fournir l'ebook de la saison aux apprenants : link:./pdf.html[Ebook]*

include::../../../../modules/ansible/introduction.adoc[options=modules]

TIP: ☕ Pause café

Lors de ce module, il est important que tous les apprenants le fasse en même temps. Il faut que chacun ait réussi une connexion ssh avec la VM Kourou avant de continuer.

Si le temps le permet, avant la pause repas, faire l'exercice en mode exploratoire. Pas de correction, le module suivant sera dédié à refaire le même style d'exercice.

include::../../../../modules/ansible/installation.adoc[options=modules]

TIP: 🍕 Pause déjeuner

include::../../../../modules/ansible/first-use.adoc[options=modules]

:challenge: https://github.com/O-clock-Devops-Peda/S08-Challenge
:description: Exploratoire : Créer un environnement de tests avec Docker
:correction: 
include::../../../../../../adoc/libs/intro-challenge.adoc[]

.👨‍🏫 Référent de promo
[.suivi]
[sidebar]
--
include::../../../../suivi.adoc[tags=s08e01]
--

// end::deroulement[]