[background-color=var(--r-oclock-color)]
== Create

Nous pouvons déjà créer des notes, on passe par un formulaire, car on a une application monolithique.

Dans le cadre d'une SPA (Single Page Application) ou plus simplement d'un front découplé de NestJS, on devra passer par la technique AJAX pour nos fonctionnalités.

On va voir dans ce module comment réaliser ces actions.

[background-color=var(--r-demonstration)]
=== Create : demo

Examinons d'abord les méthodes `index` dans `Notescontroller`, on a le décorateur `@Render` qui dit à NestJS de renvoyer une vue, il suffit d'enlever ce décorateur pour renvoyer les données en format JSON.

Au passage, on enlève (ou on commente) la méthode `create`, cette méthode ne sera plus utilisé dans le cadre d'une API REST JSON.

[source,typescript]
----
// notes.controller.ts
import { Controller, Get, Post, Body, Render } from '@nestjs/common';
@Get()
index() {
    return { notes: this.notesService.getNotes() };
}
----

[background-color=var(--r-demonstration)]
=== Create : démo

Si on va sur l'URL http://localhost:3000/notes[], on devrait voir les notes en format JSON.

[background-color=var(--r-demonstration)]
=== Create : demo

On peut déjà créer une note. Il s'agit, là aussi, d'enlever un décorateur le `@Redirect` pour modifier notre API.

En effet, nous n'avons plus besoin de rediriger l'utilisateur, car les actions seront réalisées différemment : On a changé de contexte.

Pour vérifier que tout se passe bien, on crée une note avec insomnia en envoyant un POST avec un JSON comme body de la requête.

Il faudra modifier voir enlever les middlewares et Guard pour y arriver.