[background-color=var(--r-oclock-color)]
== Update

Pour la fonctionnalité de mise à jour, on souhaite persister les données en BDD, il nous faut une nouvelle méthode et un nouveau DTO qui héritera du précédent.

[background-color=var(--r-demonstration)]
=== Update : le DTO

Voici ce nouveau DTO :

[source ,typescript]
----
// dto/update-note.dto.ts
import { PartialType } from '@nestjs/mapped-types';
import { CreateNoteDto } from './create-note.dto';

export class UpdateNoteDto extends PartialType(CreateNoteDto) {}
----

=== Update : le DTO

Comme préciser dans https://docs.nestjs.com/techniques/validation#mapped-types[la documentation de Nest], on a une classe qui hérite du premier DTO, et qui précise que l'on pourrait recevoir que partiellement le type `CreateNoteDto`.

En effet, on ne veut pas forcément tout modifier sur la note, l'objet sera donc partiel.

[NOTE.speaker]
--
Au moment voulu, on pourra le modifier pour y inclure l'ID de ceux qui ont modifié une note, ajouter des collaborateurs etc, etc.
--

[background-color=var(--r-demonstration)]
=== update : le contrôleur

Voici la méthode update du contrôleur, cette méthode possède un nouveau décorateur : `@Patch`

`Patch` est la méthode HTTP utilisé pour mettre à jour une ressource.

N'oublions pas d'importer le nouveau DTO dans le contrôleur.

On a ajouté le suffix `/update` à l'URL pour être constant et on a enlevé le décorateur `@Redirect` :

[source,typescript]
----
// notes.controller.ts
import {/*...*/,  Patch } from '@nestjs/common';
import { UpdateNoteDto } from './dto/update-note.dto';
// ...
@Patch(':id/update')
update(@Param('id') id: string, @Body() updateNoteDto: UpdateNoteDto) {
    return this.notesService.update(+id, updateNoteDto);
}
----

[background-color=var(--r-demonstration)]
=== update : le service

Voyons la méthode update du service `notes` :

[source ,typescript]
----
import { UpdateNoteDto } from './dto/update-note.dto';
// notes.service.ts
async update(id: number, updateNoteDto: UpdateNoteDto) {
    return await this.noteModel.update(updateNoteDto, { where: { id } });
}
----

Rien de particulier, si ce n'est que l'on continue à utiliser le DTO et qu'il faut donc l'importer.

À ce stade, on devrait pouvoir effectuer une mise à jour avec Insomnia.


