[background-color=var(--r-oclock-color)]
== Authentification avec JWT

On a fait en sorte de modifier nos fonctionnalités pour gérer uniquement le format JSON.

Pour réussir, on a dû annuler notre fonctionnalité d'authentification, car on n'utilise plus de session.

Dans ce module, on va voir comment implémenter un système d'authentification en utilisant les JSON Web Token (JWT)

* https://jwt.io[]
* https://docs.nestjs.com/security/authentication#jwt-token[]

[background-color=var(--r-oclock-color)]
== JWT : définition

Les JWT sont un standard  qui permet de transmettre des informations de façon sécurisée au sein d'une chaîne de caractères chiffrée.

L'aspect sécurité s'entend par le fait que la validité du token est vérifié par le biais d'une clé que l'on doit garder secrète et qui sert à confirmé (ou non) l'intégrité des données(non modifiées), et également d'une date limite de validité.

Les données contenues dans un token sont lisibles par tout le monde, n'importe qui peut déchiffrer un JWT,  on n'y stockera donc jamais d'informations sensibles (mot de passe, etc).

[background-color=var(--r-oclock-color)]
== JWT

On va se servir de ce token comme d'un lien entre le front et le back, on va le transférer du serveur au front, et du front au serveur où il sera systématiquement vérifié avant d'autoriser l'exécution des fonctionnalités.

[background-color=var(--r-oclock-color)]
== JWT : le module

On commence par installer un nouveau module :

[source,bash]
----
npm install --save @nestjs/jwt
----

Pour la démonstration, on va modifier la méthode `signIn` du `AuthService`, afin de lui faire générer un token, et par la suite, on va retourner ce token dans le contrôleur.

On s'inspire largement de https://docs.nestjs.com/security/authentication#jwt-token[la doc], pas besoin de réinventer la roue.

[background-color=var(--r-demonstration)]
=== JWT : implémentation

On commence par modifier le constructeur de `auth.service`, on injecte le service jwt, que l'on importe depuis le nouveau module `@nestjs/jwt` :

[source,typescript]
----
// auth/auth.service.ts
// ...
import { JwtService } from '@nestjs/jwt';
// ...
constructor(
        // ...
        private jwtService: JwtService
    ) {}
----

[background-color=var(--r-demonstration)]
=== JWT : implémentation

Puis, on modifie les deux lignes qui suivent la vérification du mot de passe, si celui-ci est valide :

[source,typescript]
----
// auth/auth.service.ts
// ...
async signIn(email: string, pass: string = 'secret'): Promise<any> {
    // ...
    if (!ok) {
        throw new UnauthorizedException();
    }
    const payload = { userId: user.id, username: user.username };
    return {
        access_token: this.jwtService.signAsync(payload),
    };
}
----

[background-color=var(--r-demonstration)]
=== JWT : implémentation

La méthode `jwtService.sign` a besoin d'une chaîne de caractères aléatoires que l'on garde secrètement. C'est cette chaîne qui garantira la validité du token.

Pour générer un token aléatoire et complexe, on va dans la console nodejs, et on tape la commande suivante :

[source,typescript]
----
const {randomBytes} = await import('node:crypto');
randomBytes(128).toString('base64');
----

On récupère la chaîne (sans les guillemets) et on la met dans le fichier `.env` :

[source,text]
----
JWT_SECRET=sziHO9MK+1JmW3TQA2RhxeKxPFq+1ynYJNclprdpdwBpJ7zuhbK4X8JdKlnNWBfHeLgmpNJdmVVvRCVfGlr9nbkoMXu5pWJEJk08VNfdoh4NPcFYijHlLIbxlQ77kPZ+Mx00nbaYEvqkIwLpq+w7TWpMm6WJgkJsDs+UIxOkdPU=
----

[background-color=var(--r-demonstration)]
=== JWT : implémentation

On doit maintenant configurer le service JWT pour qu'il prenne en compte cette nouvelle donnée, ça se passe dans le module `auth.module`, on importe le module JWT ainsi que la config :

[source,typescript]
----
// auth/auth.service.ts
@Module({
    imports: [
        UserModule,
        ConfigModule.forRoot({ isGlobal: false }),
        JwtModule.register({
            global: true,
            secret: process.env.JWT_SECRET,
            // * il faudra surement réduire le temps de validité du token..
            signOptions: { expiresIn: '6000s' },
        }),
    ],
    controllers: [AuthController],
    providers: [AuthService],
})
----

Avec ça, on peut déjà générer un token, il nous manquera la logique pour le valider à chaque requête.

[background-color=var(--r-demonstration)]
=== JWT : Le token

On teste avec Insomnia pour générer un token : voici le JSON à envoyer, on devrait recevoir le token :

[source,json]
----
{
  "email": "admin@admin.com",
  "password": "secret"
}
----

[background-color=var(--r-oclock-color)]
=== JWT : Guard

On doit implémenter un nouveau _Guard_, c'est lui qui interceptera la requête et validera ou non le token.

On s'en servira à chaque fois que c'est approprié, c'est-à-dire sur les routes que l'on souhaite protéger.

[background-color=var(--r-demonstration)]
=== JWT : Guard

Voici ce guard, on a repris celui fourni dans la doc, on a juste modifié la ligne qui permet de vérifier le token pour lui donner le secret correct :

[source,typescript]
----
// guards/auth.guard.ts
import { CanActivate, ExecutionContext, Injectable, UnauthorizedException } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { Request } from 'express';

@Injectable()
export class AuthGuard implements CanActivate {
    constructor(private jwtService: JwtService) {}

    async canActivate(context: ExecutionContext): Promise<boolean> {
        const request = context.switchToHttp().getRequest();
        const token = this.extractTokenFromHeader(request);
        if (!token) {
            throw new UnauthorizedException();
        }

        try {
            const payload = await this.jwtService.verifyAsync(token, {
                secret: process.env.JWT_SECRET,
            });
            // 💡 We're assigning the payload to the request object here
            // so that we can access it in our route handlers
            request['user'] = payload;
        } catch {
            throw new UnauthorizedException();
        }
        return true;
    }

    private extractTokenFromHeader(request: Request): string | undefined {
        const [type, token] = request.headers.authorization?.split(' ') ?? [];

        return type === 'Bearer' ? token : undefined;
    }
}
----

[background-color=var(--r-oclock-color)]
=== JWT : implémentation

Pour tester ce Guard, on va encore devoir modifier des choses, il faut se souvenir que puisque notre front est à présent découplé du back, on ne fait plus de sessions.

Les middlewares de sessions sont donc inutiles, et les guards présent doivent être modifié. On peut déjà commenter la ligne qui charge un middleware dans le module `App`.

[background-color=var(--r-oclock-color)]
=== JWT : implémentation

On va interroger notre serveur depuis un front découplé, qui n'est donc pas dans le même contexte, pour que le serveur accepte de répondre, il faut lui dire explicitement de le faire en autorisant les requêtes 'cross-origin'.

[background-color=var(--r-demonstration)]
=== JWT : implémentation

Voici le code à ajouter dans le fichier `main.ts` :

[source,typescript]
----
// main.ts
app.enableCors({ origin: 'http://localhost' });
----

Le site avec l'URL http://localhost[] pourra contacter notre serveur.

[background-color=var(--r-demonstration)]
=== JWT : implémentation

Ensuite, on doit modifier le Guard `roles.guard` pour lui dire de décoder le token et d'aller chercher un utilisateur afin de vérifier ses rôles (le code suivant ne montre que les modifications apportées au Guard) :

[source,typescript]
----
// roles.guard.ts
import { /* ... */, UnauthorizedException } from '@nestjs/common';
// ...
import { JwtService } from '@nestjs/jwt';
import { UserService } from '../users/user.service';

@Injectable()
export class RolesGuard implements CanActivate {
    constructor(
        // ...
        private jwtService: JwtService,
        private userService: UserService
    ) {}

    async canActivate(context: ExecutionContext) {
        // ...
        const request = context.switchToHttp().getRequest();
        const token = request.headers.authorization.split(' ')[1];

        try {
            const decoded = await this.jwtService.verifyAsync(token, {
                secret: process.env.JWT_SECRET,
            });

            const user = await this.userService.findOne(decoded.userId);
            const userRoles = user.roles.map((role: Role) => role.name);
            request['userId'] = decoded.userId;
            return requiredRoles.some(
                (role: string) =>
                    userRoles?.includes(role) || userRoles?.includes('admin')
            );
        } catch {
            throw new UnauthorizedException();
        }
    }
}
----


[background-color=var(--r-oclock-color)]
=== JWT : implémentation
:tip-caption: 💡
[TIP]
====
*__
Notez qu'on a ajouté l'ID de l'utilisateur sur la requête, ainsi, on pourra récupérer cette id dans le contrôleur si besoin.
__*
====

[background-color=var(--r-demonstration)]
=== JWT : implémentation

On va tester sur une seule fonctionnalité dans une méthode, ce sera la méthode où on retourne les notes d'un utilisateur.

Le seul changement est la façon de récupérer l'ID de l'utilisateur, on le cherche sur la requête :

[source,typescript]
----
@Get()
@Roles(Role.Admin)
@Render('index')
async index(
    @Req() request: Request,
    @Session() session: Record<string, any>
): Promise<object> {
    session.visits = session.visits ? session.visits + 1 : 1;
    // On devrait peut-être utiliser DI
    const user = await User.findByPk(request['userId']);

    return { notes: await this.notesService.getNotes(user) };
}
----

On applique le guard role sans rien changer, ça ne fonctionnera pas encore, on doit d'abord importer le module `User` au module `Note`.

[background-color=var(--r-demonstration)]
=== JWT : implémentation

Importation du module `User` dans le module `Note`

[source,typescript]
----
// notes.module.ts
// ...
import { UserModule } from '../users/user.module';
@Module({
    imports: [/* ... */, UserModule],
})
export class NotesModule {}
----

[background-color=var(--r-demonstration)]
=== JWT : le front

On teste le tout avec une requête `fetch`.

On exécute le code suivant depuis un navigateur.

[source,javascript]
----
include::./sources/app.js[]
----