:title: 📚️ Journée async
:number: 05
include::../../../../../../adoc/libs/header-episode.adoc[]

// tag::intro[]
Pas de face à face pédagogique sur cette journée, les apprenants travaillent sur des tâches en autonomie.
// end::intro[]

// == Objectifs pédagogiques
// tag::objectifs[]
* Présenter le projet et les attendus pour le titre
* Travailler en autonomie sur des tâches connexes à la formation
// end::objectifs[]

== Prérequis formateur
// tag::prerequis[]
- Plannifier un message Slack aux apprenants pour 8h30 en leur fournissant le programme de la journée et les ressources nécessaires.
// end::prerequis[]

== Déroulement

// tag::deroulement[]
* Dupliquer https://drive.google.com/drive/folders/1lB7I6IWe23x_l8wmzAYCPhlqfoaa1ZnU[l'ECF] dans le drive de la promo et remplacer le lien dans le message Slack
* Générer un lien pour le https://inside.oclock.io/pedagogie/qs-formateurs[questionnaire de satisfaction de fin de saison] et le remplacer dans le message Slack
* Propgrammer le message suivant pour 8h30 :

*Message Slack :*

```
Bonjour à tous,

Aujourd'hui, pas de face à face pédagogique,enfin presque, vous avez une journée en autonomie pour travailler sur des tâches connexes à la formation et une présentation de 2 heures du projet et des attendus pour le titre.

Voici le programme de la journée :

- Présentation du projet et des attendus pour le titre à 10h30.
- Défense du réseau : https://www.netacad.com/fr/courses/network-defense?courseLang=fr-FR
    - Aller jusqu'au module 10

Bonne journée à tous !
```
// end::deroulement[]