:title: Chaines de livraison
:number: 09
:duration: 70
include::../../../../adoc/libs/header-saison.adoc[]

// tag::intro[]
Utilisation avancée des chaines de livraison pour automatiser le déploiement d'applications.
// end::intro[]

== Objectifs pédagogiques

// tag::objectifs[]
- **Comprendre** et *appliquer* les chaines de livraison
- **Appliquer** Github Actions
- **Auditer** ses propres chaînes
// end::objectifs[]

== Notions

// tag::notions[]
- Team workflow
- CI/CD
- Github actions
- Docker
- Tests unitaires
- Tests de charge
- Analyse sécurité
// end::notions[]

== Prérequis formateur

// tag::prerequis[]
- Penser à fournir le ebook O'clock
// end::prerequis[]

== Résumé

// tag::resume[]
Cette saison de saison sur les chaînes de livraison DevOps est conçue pour doter les apprenants de compétences pratiques et avancées dans l'automatisation des processus de développement et de déploiement. En mettant l'accent sur l'utilisation de GitHub Actions, les apprenants vont créer et configurer des workflows efficaces, intégrer des tests unitaires, et sécuriser leurs pipelines. 

La saison couvre également l'utilisation de Docker pour l'isolement des environnements, les stratégies de déploiement automatisé, et les meilleures pratiques de collaboration en équipe. 

En explorant les tendances émergentes telles que GitOps et DevSecOps, cette saison offre une vision complète et moderne des pratiques DevOps.
// end::resume[]

== Déroulement

link:./overview.html[Vue kanban]

// tag::deroulement[]
include::episodes/*/*.adoc[opts=episodes]
// end::deroulement[]