graph TD;
    A[Interface Utilisateur Initiale] --> B[Création du DOM Virtuel]
    B --> C[Interaction Utilisateur]
    C --> D[Nouvelle Création du DOM Virtuel]
    D --> E[Algorithme de Diff]
    E --> F[Modification du DOM Réel]
    F --> G[Interface Utilisateur Mise à Jour]

    subgraph Processus de DOM Virtuel
        B
        D
    end

    subgraph Mise à Jour du DOM Réel
        F
        G
    end

    classDef process fill:#f9f,stroke:#333,stroke-width:2px;
    classDef realdom fill:#bbf,stroke:#333,stroke-width:2px;

    class ProcessusdeDOMVirtuel process;
    class MiseàJourduDOMRéel realdom;