:titre: Analyse statique
:module: CICD
:duree: 120
:description: Introduction aux outils d'analyse statique (Dependabot, Snyk, SonarQube)
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
* **Comprendre** l'importance de l'analyse statique dans le développement logiciel.
* **Appliquer** des outils d'analyse statique comme Dependabot, Snyk, et SonarQube.
* **Évaluer** la qualité du code et identifier les vulnérabilités.
// end::objectifs[]

// tag::deroulement[]
== Introduction

* Détection des problèmes dans le code
* Aucune exécution du code (complément de l'analyse dynamique)
* Crucial pour la qualité et la sécurité du logiciel

[NOTE.speaker]
--
L'analyse statique permet de détecter des problèmes dans le code sans l'exécuter, ce qui est crucial pour la qualité et la sécurité du logiciel. Elle complète l'analyse dynamique qui se fait pendant l'exécution.
--

== Dependabot

* Gestion des dépendances de divers écosystèmes
* Mise à jour automatique des dépendances
* Vérifications de sécurité
* Facile à intégrer dans github

.dependabot.yml
```yaml
version: 2
updates:
  # Mise à jour des dépendances pour un projet Node.js
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10

  # Mise à jour des dépendances pour un projet Ruby
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
```

https://github.com/dependabot

[NOTE.speaker]
--
Dependabot vérifie les dépendances de votre projet et propose des mises à jour lorsque de nouvelles versions sont disponibles. Cela aide à garder le projet à jour et sécurisé.

* version : Indique la version du fichier de configuration de Dependabot.
* updates : Liste des configurations pour les différents gestionnaires de paquets.
* package-ecosystem : Spécifie le gestionnaire de paquets à utiliser (par exemple, npm pour Node.js, bundler pour Ruby).
* directory : Le répertoire du projet où se trouvent les fichiers de dépendances (ex. package.json pour npm, Gemfile pour bundler).
* schedule : Définit la fréquence à laquelle Dependabot vérifie les mises à jour (daily, weekly, monthly).
* commit-message : Personnalisation du message de commit pour les pull requests créées par Dependabot, ici avec un préfixe "deps".
* open-pull-requests-limit : Limite le nombre de pull requests ouvertes simultanément par Dependabot.
--

// tag::exercice[]
=== Exercice

Création d'un dependabot.yml

[NOTE.speaker]
--
1. Créez un fichier dependabot.yml dans votre dépôt.
2. Configurez-le pour vérifier les mises à jour hebdomadaires des dépendances.
3. Simulez la création de pull requests pour les mises à jour.
4. Vérifiez que les dépendances sont bien mises à jour en fonction de la configuration.
--
// end::exercice[]

== Snyk

* Détection précoce des vulnérabilités de sécurité
** Dépendances
** Conteneurs
** Code
** IaC
* BDD des vulnérabilités connues
* Correction automatique
* Intégration dans les pipelines CI/CD

https://snyk.io/fr/

[NOTE.speaker]
--
Snyk est particulièrement utile pour les développeurs qui souhaitent intégrer la sécurité dans leur processus de développement sans perturber leurs workflows.

Avec son intégration dans les outils CI/CD, Snyk aide les équipes DevOps à maintenir la sécurité tout au long du pipeline de livraison.

Les équipes de sécurité peuvent utiliser Snyk pour surveiller et gérer de manière proactive les risques liés aux dépendances open source et à l'infrastructure du projet.
--

== SonarQube

* Analyse de la qualité du code
* Détection des bugs, code smells et vulnérabilités
* Gestion de règles de qualité personnalisées
    ** Réduction de la dette technique
    ** Sécurité renforcée du code
* Intégration dans les pipelines CI/CD

https://www.sonarsource.com/products/sonarqube/

[NOTE.speaker]
--
Les développeurs utilisent SonarQube pour obtenir des feedbacks immédiats sur la qualité de leur code et pour s'assurer qu'ils respectent les normes de codage.

Les équipes peuvent suivre la qualité globale du projet et identifier les zones nécessitant une attention particulière.

Managers et responsables techniques peuvent utiliser les rapports pour prendre des décisions éclairées sur les améliorations à apporter et pour suivre la conformité aux normes de qualité.
--

// tag::demo[]
=== Démonstration 

Analyse de code avec SonarQube en local.

[NOTE.speaker]
--
. Utiliser l'image docker pour lancer SonarQube en local.

```bash
docker run --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube
```

[start=2]
. Se rendre sur http://localhost:9000 et se connecter avec les identifiants par défaut (admin/admin).
. Configurer un projet local (de type "Other")
. Ouvrir un terminal et se placer à la racine du projet à analyser.
. Utiliser docker pour sonar-scanner (https://docs.sonarsource.com/sonarqube-server/10.7/analyzing-source-code/scanners/sonarscanner/#sonarscanner-from-docker-image[Doc]) 

```bash
docker run \
    --rm \
    --network="host" \
    -e SONAR_HOST_URL="http://localhost:9000"  \
    -e SONAR_TOKEN="${TOKEN}" \
    -v ".:/usr/src" \
    sonarsource/sonar-scanner-cli \
    -Dsonar.projectKey=${PROJECT_KEY}
```

[start=6]
. Examiner les résultats dans le tableau de bord SonarQube.
. Faire une des corrections suggérées et relancer l'analyse.
--
// end::demo[]

// end::deroulement[]

== Conclusion

// tag::conclusion[]
* L'analyse statique est essentielle pour maintenir la qualité et la sécurité du code.
* Dependabot, Snyk, et SonarQube sont des outils précieux pour automatiser l'évaluation du code.
* Intégrer ces outils dans vos workflows améliore la robustesse et la sécurité de vos projets.
// end::conclusion[]