:titre: Préparation du déploiment
:module: CICD
:duree: 120
:description: Frontière entre le Dev et le Ops, on va préparer les images docker pour le déploiement et les envoyés sur un registry (+ analyse des différents registres existants).
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
* **Comprendre** l'importance des images Docker dans le déploiement
* **Utiliser** GitHub Actions pour builder et pousser des images Docker
* **Analyser** les différents registres Docker disponibles
* **Appliquer** les bonnes pratiques pour la gestion des registres
// end::objectifs[]

// tag::deroulement[]
== Introduction

* Facilite le passage entre dev et ops
* Importance des images Docker

[NOTE.speaker]
--
Dans le cycle DevOps, la préparation du déploiement est cruciale pour garantir une transition en douceur entre le développement et les opérations. L'utilisation d'images Docker standardise l'environnement d'exécution, ce qui facilite le déploiement.
--

== Process

. Les développeurs utilisent Docker en local
. Une version de l'application est prête pour le déploiement
. Les images sont créées
. Elles sont poussées sur un registre
. Les opérations les déploient sur les serveurs

=== Avec GitHub Actions

* Automatisation du build et du push des images
* Sécurisation des informations d'identification pour le registre

[NOTE.speaker]
--
GitHub Actions permet d'automatiser le processus de build et de push des images Docker, en intégrant directement ces étapes dans votre workflow de CI/CD. Assurez-vous de sécuriser vos informations d'identification pour protéger l'accès à votre registre Docker.
--

```yaml
name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
```

[NOTE.speaker]
--
Ce workflow GitHub Actions effectue trois tâches principales : 

1. Récupérer le code source.
2. Se connecter à Docker Hub en utilisant les secrets pour sécuriser les informations d'identification.
3. Builder et pousser l'image Docker vers Docker Hub.
--

// tag::demo[]
=== Démonstration

Utiliser GitHub Actions pour builder et pousser une image Docker.

[NOTE.speaker]
--
. Créer un projet à partir d'un template Vite
. Ajouter un Dockerfile
. S'assurer qu'en local l'image est utilisable
. Builder l'image en local et l'utiliser pour vérifier que tout fonctionne
. Créer un fichier `.github/workflows/docker-build-push.yml`.
. Configurer le workflow pour récupérer le code source.
. Ajouter des étapes pour se connecter à Docker Hub.
. Ajouter les secrets dans le repository.
. Ajouter des étapes pour builder et pousser l'image.
. Vérifier que l'image est correctement poussée sur Docker Hub.
--
// end::demo[]

== Registres Docker

* Docker Hub
* AWS ECR
* Google Container Registry
* Github Container Registry

[NOTE.speaker]
--
Il existe plusieurs registres Docker disponibles, chacun ayant ses propres caractéristiques. Docker Hub est le plus populaire, mais AWS ECR et Google Container Registry offrent des intégrations plus poussées avec leurs services cloud respectifs. Choisissez en fonction de vos besoins en matière de sécurité, de coût, et de facilité d'intégration.
--

=== Bonnes pratiques pour la gestion des registres

* Versionnement des images pour suivre les changements
* Gestion des accès et des autorisations pour sécuriser le registre

[NOTE.speaker]
--
Versionnez vos images Docker pour suivre les changements et faciliter le rollback en cas de problème. Gérez les accès au registre en utilisant des autorisations appropriées pour assurer la sécurité de vos images.
--

// tag::demo[]
=== Démonstration

Créer une nouvelle version de l'image précédente et la pousser sur Docker Hub.

[NOTE.speaker]
--

. Mettre à jour le code source pour inclure des modifications.
. Modifier la version dans package.json.
. Créer une nouvelle version de l'image en utilisant un tag différent.
    .. Récupérer la version depuis package.json.
. Pousser la nouvelle version de l'image sur Docker Hub avec son tag de version et le tag `latest`.
. Vérifier que les nouvelles versions sont correctement poussées sur Docker Hub.

```yaml
name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from package.json
        id: version
        run: echo "VERSION=$(jq -r '.version' < package.json)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ env.VERSION }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/myapp:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
```
--
// end::demo[]

// tag::exercice[]
== Exercice

Configurer un workflow GitHub Actions pour pousser une image vers un registre privé

* Configurer Github Container Registry
* Utiliser les secrets pour sécuriser les informations d'identification
* Créer un workflow pour pousser une image
// end::exercice[]

// end::deroulement[]

== Conclusion

// tag::conclusion[]
* L'utilisation d'images Docker est essentielle pour un déploiement standardisé
* GitHub Actions permet d'automatiser le build et le push des images
* Le choix du registre Docker dépend des besoins spécifiques de l'organisation
* Utiliser les secrets pour sécuriser les informations d'identification
* Versionner les images
// end::conclusion[]