:titre: Github Actions
:module: CICD
:duree: 120
:description: Introduction à la pipeline made in Github avec les actions. Présentation des concepts, avantages et mise en pratique avec un dépôt de code.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
* **Comprendre** le concept de CI/CD et GitHub Actions
* **Analyser** les avantages par rapport aux outils concurrents
* **Créer** un workflow basique avec GitHub Actions
* **Appliquer** les concepts de bases
// end::objectifs[]

// tag::deroulement[]
== Introduction

https://github.com/features/actions[GitHub Actions] est un service d'intégration et de déploiement continu (CI/CD) qui permet d'automatiser, de personnaliser et d'exécuter des workflows directement dans votre dépôt GitHub.

[NOTE.speaker]
--
CI/CD signifie Intégration Continue et Déploiement Continu. C'est une méthode pour livrer des applications aux clients en introduisant l'automatisation dans les étapes de développement d'applications. 

GitHub Actions permet d'automatiser, de personnaliser et d'exécuter vos workflows de développement logiciel directement dans votre dépôt GitHub.
--

== Avantages

* Intégration native avec GitHub
* Flexibilité et extensibilité
* Large communauté et marketplace d'actions

[NOTE.speaker]
--
GitHub Actions est intégré nativement dans GitHub, ce qui facilite son utilisation sans besoin de configuration supplémentaire. 

Il est très flexible et permet d'automatiser une large gamme de tâches, de la simple exécution de tests à des déploiements complexes.

Grâce à une grande communauté, il existe de nombreuses actions déjà prêtes sur le marketplace que vous pouvez utiliser dans vos workflows.
--

== Outils concurrents

* Jenkins : plus de contrôle et de personnalisation, mais nécessite une gestion serveur
* GitLab CI : bien intégré si vous utilisez GitLab, mais moins de fonctionnalités que GitHub Actions
* CircleCI : facile à configurer, mais peut être coûteux pour des projets plus importants
* Travis CI : gratuit pour les projets open source, mais moins flexible que GitHub Actions

[NOTE.speaker]
--
Jenkins offre un contrôle total sur votre pipeline CI/CD, mais nécessite de gérer votre propre serveur, ce qui peut être complexe et coûteux.

GitLab CI est intégré à GitLab, ce qui est pratique si vous utilisez déjà cette plateforme, mais il manque certaines fonctionnalités avancées de GitHub Actions.

CircleCI est connu pour sa facilité de configuration, mais son coût peut rapidement augmenter pour les grands projets.

Travis CI est idéal pour les projets open source, mais il est moins flexible et offre moins de fonctionnalités que GitHub Actions.
--

== Structure d'une action GitHub

```yaml
name: Nom du workflow
on: [push, pull_request]

jobs:
  nom-du-job:
    runs-on: ubuntu-latest
    steps:
      - name: Étape 1
        run: echo "Hello, world!"
```

[NOTE.speaker]
--
Les workflows dans GitHub Actions sont définis à l'aide de fichiers YAML, qui décrivent les déclencheurs, les jobs, et les étapes à exécuter.

Les déclencheurs déterminent quand un workflow doit être exécuté, comme un push ou une pull request. 

Un job est une série de commandes à exécuter sur une machine runner. 
--

== Démonstration : Création d'une simple action GitHub

Configurer un workflow pour builder l'application front-end du Challenge.

// tag::demo[]
[NOTE.speaker]
--
Nous allons créer un workflow simple pour exécuter un script lorsque du code est poussé vers le dépôt.

* Créer un fichier `.github/workflows/main.yml`
* Définir un `on` trigger pour le déclenchement lors d'un push sur main
* Ajouter un job qui utilise une image Ubuntu
* Inclure une étape pour exécuter le build de l'application
* Commit et push pour voir le workflow en action

```yaml
name: Build Frontend

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: npm install
        - name: Build
          run: npm run build
```
--
// end::demo[]

// tag::exercice[]
== Exercice 1

Créer un workflow pour builder le backend du Challenge.
// end::exercice[]

// tag::exercice[]
== Exercice 2

Modifier le workflow pour qu'il se déclenche que si des fichiers du dossier `backend` sont modifiés.
// end::exercice[]

// end::deroulement[]

== Conclusion

// tag::conclusion[]
* GitHub Actions permet d'automatiser les workflows directement dans votre dépôt
* Offre des avantages significatifs par rapport à certains outils concurrents
* La création de workflows est simple et flexible grâce à l'utilisation de fichiers YAML
* Les démonstrations et exercices permettent de voir comment appliquer ces concepts en pratique
// end::conclusion[]
