:titre: Optimisation
:module: CICD
:duree: 90
:description: Introduction aux techniques d'optimisation des workflows avec utilisation de caches et parallélisation pour améliorer les pipelines. Analyse des performances des workflows et identification des améliorations.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
* **Comprendre** l'importance de l'optimisation des workflows CI/CD
* **Appliquer** des techniques de cache pour améliorer les performances
* **Appliquer** la parallélisation pour accélérer les pipelines
* **Analyser** les coûts associés aux workflows CI/CD
* **Évaluer** les performances des workflows et identifier des améliorations
// end::objectifs[]

// tag::deroulement[]
== Introduction

Optimisation des workflows CI/CD :

* Impact sur performances, productivité et coût
* Utilisation de caches et parallélisation

[NOTE.speaker]
--
L'optimisation des workflows CI/CD est cruciale pour améliorer la vitesse et l'efficacité des déploiements. Cela impacte directement les performances, la productivité des équipes et les coûts liés à l'utilisation des ressources.
--

== Concepts clés

=== Utilisation de caches

* Types de caches
** Cache des dépendances
** Cache des artefacts de construction
* Avantages
** Réduction du temps de construction
** Réutilisation des résultats précédents
** Economie de ressources

[NOTE.speaker]
--
Les caches peuvent réduire le temps de construction en réutilisant les résultats précédents. Cela est particulièrement utile pour les dépendances et les artefacts de construction.
--

=== Parallélisation

Techniques de parallélisation :

* Division en tâches indépendantes
* Utilisation de conteneurs multiples
* Pipeline parallèle
* Partitionnement des données
* Utilisation de workers parallèles

[NOTE.speaker]
--
La parallélisation permet d'exécuter plusieurs tâches en même temps, ce qui réduit le temps total de traitement. Cependant, elle nécessite une gestion soigneuse des dépendances entre les tâches.

* Identifiez les étapes du workflow qui n'ont pas de dépendances entre elles et peuvent être exécutées en parallèle. Par exemple, des tests unitaires qui n'affectent pas d'autres parties du système.
* Exécutez différentes parties d'un workflow dans des conteneurs séparés. Cela permet de tirer parti de l'isolement des conteneurs pour exécuter des tâches en parallèle.
* Configurez votre pipeline CI/CD pour exécuter des jobs parallèles. Par exemple, construire différentes parties d'une application ou exécuter des tests sur différentes configurations de système ou versions de dépendances.
* Divisez les données en segments qui peuvent être traités indépendamment. Cela est particulièrement utile pour les tests ou les analyses qui peuvent être distribués sur plusieurs machines.
* Pour les tâches de calcul intensif ou de traitement en arrière-plan, utilisez plusieurs workers pour traiter les éléments de travail en parallèle.
--

=== Impact du coût

* Réduction des coûts grâce à l'optimisation
* Équilibre entre performance et coût

[NOTE.speaker]
--
Optimiser les workflows peut réduire les coûts en diminuant le temps d'exécution et l'utilisation des ressources. Il est important de trouver un équilibre entre la performance souhaitée et le budget disponible en cas d'augmentation des puissances de calcul.
--

== Techniques d'optimisation

=== Mise en cache dans les workflows

```yaml
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node.js modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
             
```

[NOTE.speaker]
--
Configurer le cache dans vos workflows peut considérablement réduire le temps de construction. Par exemple, le cache des dépendances de projet ou des résultats de tests permet des exécutions plus rapides.

* actions/cache@v3 : Cette action est utilisée pour mettre en cache les modules Node.js. Elle vérifie si un cache existant peut être restauré à l'aide de la clé générée.
* Key : La clé est définie en fonction du système d'exploitation du runner et du hash du fichier package-lock.json. Cela garantit que le cache est spécifique à l'état actuel des dépendances.
* Restore-keys : Cette option permet de spécifier des clés de secours à utiliser si le cache exact n'est pas trouvé. Dans cet exemple, il tente de restaurer un cache basé uniquement sur le système d'exploitation.
* npm install : Cette étape installe les dépendances. Si le cache est trouvé, cette étape sera plus rapide car les dépendances sont déjà présentes.
--

// tag::demo[]
=== Démonstration

Intégrer le cache dans un workflow existant.

[NOTE.speaker]
--
. Sélectionner un workflow CI/CD existant.
. Ajouter une étape de mise en cache pour les dépendances.
. Exécuter le workflow et observer les améliorations de performance.
--
// end::demo[]

=== Parallélisation des tâches

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ...

  test-unit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      ...
  
  test-integration:
    runs-on: ubuntu-latest
    needs: build
    steps:
      ...
```

[NOTE.speaker]
--
La parallélisation des tâches peut être configurée dans vos pipelines CI/CD pour exécuter des étapes indépendantes simultanément, réduisant ainsi le temps de traitement global.

* Jobs : Le pipeline est divisé en trois jobs distincts : build, test-unit, et test-integration.
* Build Job : Ce job prépare l'environnement en installant les dépendances nécessaires. Il est requis par les deux jobs de test.
* Needs : Les jobs test-unit et test-integration dépendent du job build via le mot-clé needs. Cela signifie qu'ils ne commenceront que lorsque le build sera terminé.
* Parallélisation : Les jobs test-unit et test-integration s'exécutent en parallèle, car ils sont indépendants l'un de l'autre. Cela permet d'accélérer le pipeline global.
--

== Analyse des performances des workflows

* GitHub Actions : Offre des vues de journalisation détaillées et des graphiques de durée des jobs pour identifier les étapes lentes.
* Buildkite : Fournit des outils d'analyse intégrés pour examiner les temps de build et optimiser les pipelines.

https://buildkite.com/

[NOTE.speaker]
--
Utilisez des outils d'analyse de performance pour identifier où se trouvent les goulots d'étranglement dans vos workflows. Cela vous aidera à cibler les zones à optimiser.

Github Actions peut s'avérer limité pour des analyses plus poussées. Dans ce cas, des outils comme Buildkite offrent des fonctionnalités plus avancées pour l'analyse des performances.
--

// tag::exercice[]
== Exercice

Optimiser un workflow CI/CD existant en utilisant le cache et la parallélisation

. Créer un template de projet Nestjs
. Créer un workflow GitHub Actions optimisé avec 
.. mise en cache
.. parallélisation des tests et du build
// end::exercice[]

// end::deroulement[]

== Conclusion

// tag::conclusion[]
* L'optimisation des workflows CI/CD améliore 
** les performances
** la productivité 
** réduit les coûts
* L'utilisation de caches et la parallélisation sont des techniques clés
* Analyser régulièrement les performances pour identifier des améliorations continues
// end::conclusion[]