:titre: Variables et secrets
:module: CICD
:duree: 60
:description: Découverte des variables et secrets dans les pipelines CI/CD. Présentation des concepts, avantages et mise en pratique avec un dépôt de code.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
* **Comprendre** la distinction entre variables et secrets
* **Appliquer** l'utilisation des variables dans un pipeline
* **Appliquer** les secrets de manière sécurisée
* **Évaluer** les bonnes pratiques de sécurité pour les secrets
// end::objectifs[]

// tag::deroulement[]
== Introduction

* Les variables et secrets sont essentiels dans les pipelines CI/CD
* Ils permettent de configurer les workflows sans exposer d'informations sensibles
* Importance de la gestion sécurisée des secrets

[NOTE.speaker]
--
Les variables et secrets jouent un rôle crucial dans la gestion des pipelines CI/CD. Ils permettent de configurer vos workflows de manière flexible tout en protégeant les informations sensibles. 

Il est primordial de comprendre comment gérer ces éléments pour assurer la sécurité de vos opérations.

Une variable pourrait être utilisée pour stocker le nom de l'application, tandis qu'un secret pourrait contenir une clé API.
--

== Concepts clés

* Variables : stockent des valeurs utilisées de façon lisible
* Secrets : stockent des valeurs utilisées de façon sécurisée
* Ce sont des données dynamiques dans les workflows

[NOTE.speaker]
--
Les variables sont utilisées pour stocker des valeurs qui peuvent changer selon l'environnement ou la configuration, comme les chemins de fichiers ou les options de build. 

Les secrets, en revanche, contiennent des informations sensibles comme les mots de passe ou les clés API, qui ne doivent pas être exposées dans le code.
--

== Avantages

* Sécurisation de l'information sensible
* Flexibilité et réutilisation du code grâce aux variables
* Intégré nativement dans GitHub Actions

[NOTE.speaker]
--
L'utilisation de secrets permet de protéger les informations sensibles contre les accès non autorisés. Les variables, quant à elles, offrent une flexibilité accrue, car elles permettent de modifier facilement les configurations sans changer le code source.
--

// tag::demo[]
== Démonstration 1

* Mise en place de variables et secrets
* Configurer des variables et secrets dans un pipeline GitHub Actions.

[NOTE.speaker]
--
Nous allons configurer un pipeline simple qui utilise des variables et des secrets dans GitHub Actions.

* Créer un fichier `.github/workflows/ci.yml`
* Définir une variable pour le nom de l'application
* Ajouter un secret pour une clé API
* Utiliser ces valeurs dans un job simple
* Commit et push pour voir le résultat

```yaml
name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Print application name
      run: echo "App Name is ${{ vars.APP_NAME }}"
    - name: Use secret API key
      run: echo "Using secret API key: ${{ secrets.API_KEY }}"
```
--
// end::demo[]

== Bonnes pratiques

* Toujours chiffrer les secrets
* Limiter l'accès aux secrets aux seules personnes nécessaires
* Mettre à jour régulièrement les secrets
* Utiliser les variables et secrets génériques au niveau de l'organisation

[NOTE.speaker]
--
Il est essentiel de chiffrer vos secrets pour garantir qu'ils ne puissent pas être lus s'ils sont interceptés. 

Limitez l'accès aux secrets aux seules personnes et systèmes qui en ont besoin, et mettez-les à jour régulièrement pour minimiser le risque de compromis.
--

// tag::demo[]
== Démonstration 2

Utilisation d'une variable pour modifier le résultat de l'application

[NOTE.speaker]
--
Nous allons modifier le pipeline pour utiliser la variable de l'application dans le code.

* Modifier le front end pour utiliser un fichier `.env` contenant la variable `VITE_APP_NAME`

```
VITE_APP_NAME=My App
```

* Modifier le code pour inclure le nom de l'application dans le DOM

```javascript
<h1>{import.meta.env.VITE_APP_NAME}</h1>
```

* Modifier le workflow `main.yml` pour créer un fichier `.env` avec la variable

```yaml
 - name: Create env file
        run: |
          echo "VITE_APP_NAME=${{ vars.VITE_APP_NAME }}" >> .env
```

* Ajouter la variable `VITE_APP_NAME` dans le repository
* Commit et push pour voir le résultat

--
// end::demo[]

// end::deroulement[]

== Conclusion

// tag::conclusion[]
* Variables et secrets sont essentiels pour sécuriser et configurer les pipelines CI/CD
* Les bonnes pratiques de sécurité sont cruciales pour protéger les informations sensibles
* L'utilisation correcte de ces éléments améliore la flexibilité et la sécurité de vos workflows
// end::conclusion[]
