:titre: Initiation à l’administration Windows en powershell
:module: Système
:duree: 180
:description: Powershell est un outil essentiel pour l’administration Windows. Ce module explique les bases de Powershell et comment l’utiliser pour gérer les serveurs Windows.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
[cols="1,1"]
|===
a| 
* Comprendre PowerShell 
* Maîtriser les Cmdlets de Base 
* Gérer Active Directory 
* Administrer les Politiques de Groupe 
* Contrôler les Services et Processus 
a|
* Gérer le Stockage et les Partages Réseau 
* Permissions NTFS
* Mettre à Jour et Surveiller le Système 
* Automatiser les Tâches Administratives 
|===
// end::objectifs[]

// tag::deroulement[]
== Comprendre PowerShell

**Définition :**

* PowerShell est une interface en ligne de commande et un langage de script développé par Microsoft.
* Conçu pour l'automatisation des tâches d'administration et de configuration des systèmes Windows.

include::../../../../adoc/libs/slide-notitle.adoc[]

**Explication :**

* PowerShell combine la puissance de l'interface en ligne de commande (CLI) avec la flexibilité du scripting.
* C’est un langage Objet
* les commandes sont appelées des CmdLet

**Exemple :**

* `Write-Host "AIS win"` : Affiche le message "AIS win" dans la console.
* `Get-Process` : Liste tous les processus en cours d'exécution sur le système.

include::../../../../adoc/libs/slide-notitle.adoc[]

Processus d'installation et de mise à jour de PowerShell sur un système Windows.

* Par défaut, PowerShell est installé sur Windows Server.
* Les mises à jour peuvent être obtenues via PowerShell Gallery ou directement depuis le site de Microsoft.

**Exemple :**

* `Install-Module -Name “MonModule” -Force` : Installe ou met à jour le module en allant récupérer les sources sur les dépôts de microsoft.
* `Import-Module -Name “MonModule” -Force` : installe ou met à jour le module en allant récupérer les sources en local sur la machine

== CmdLet de base

**Définition :**

Cmdlets sont des commandes légères utilisées dans l'environnement PowerShell.

include::../../../../adoc/libs/slide-notitle.adoc[]

**Explication :**

* Chaque cmdlet suit le format Verbe-Nom et exécute une tâche spécifique.
* Utilisation des cmdlets pour découvrir et gérer le système Windows.

**Exemple :**

* `Get-Command` : Lister toutes les cmdlets disponibles.
* `Update-Help -Force` : met à jour l’aide de powershell
* `Get-Help Get-Command` : Obtenir de l'aide sur la cmdlet Get-Command.
* `Get-Module` : Voir les modules actuellement chargés dans la session PowerShell.

== Gérer Active Directory

* Permet la création, la modification et la suppression d'utilisateurs AD.
* Nécessite le module `ActiveDirectory` pour utiliser ces cmdlets.

include::../../../../adoc/libs/slide-notitle.adoc[]

**Exemple :**

* Récupérer les informations de l'utilisateur  : `Get-ADUser -Identity jdoe`
* Modifier le titre de l'utilisateur jdoe : `Set-ADUser -Identity jdoe -Title "Manager"`
* Créer un nouvel utilisateur John Doe :

```powershell
New-ADUser -Name "John Doe" -SamAccountName jdoe -Path "OU=Users,DC=example,DC=com" -AccountPassword (ConvertTo-SecureString "P@ssw0rd" -AsPlainText -Force) -Enabled $true
```

=== Gestions des groupes AD

* Récupérer les informations du groupe Admins : `Get-ADGroup -Identity "Admins"`
* Créer un nouveau groupe Developers : `New-ADGroup -Name "Developers" -GroupScope Global -Path "OU=Groups,DC=example,DC=com"` 
* Ajouter l'utilisateur jdoe au groupe Developers : `Add-ADGroupMember -Identity "Developers" -Members "jdoe"`

=== Gestion des Ordinateurs AD

* Récupérer les informations de l'ordinateur `PC01` : `Get-ADComputer -Identity "PC01"`
* Créer un nouvel ordinateur `PC02` : `New-ADComputer -Name "PC02" -Path "OU=Computers,DC=example,DC=com"`

== Gérer les GPO

* Permet la création et la gestion des GPO dans Active Directory.
* Nécessite le module `GroupPolicy`.

=== Exemple

* Récupérer les informations de la GPO Default Domain Policy : `Get-GPO -Name "Default Domain Policy"`
* Créer une nouvelle GPO Security Settings : `New-GPO -Name "Security Settings"`
* Lier la GPO Security Settings à l'unité d'organisation Finance : 

```powershell
Set-GPLink -Name "Security Settings" -Target "OU=Finance,DC=example,DC=com" -LinkEnabled Yes
```

== Services et Processus

* Permet de lister, démarrer, arrêter et configurer les services.
* Utilisation pour assurer que les services critiques sont en cours d'exécution.

=== Exemple

* `Get-Service -Name "wuauserv"` : Lister le service de mise à jour Windows.
* `Start-Service -Name "wuauserv"` : Démarrer le service de mise à jour Windows.
* `Stop-Service -Name "wuauserv"` : Arrêter le service de mise à jour Windows.

=== Gestion des processus

* `Get-Process -Name "notepad"` : Lister le processus notepad.
* `Start-Process -FilePath "notepad.exe"` : Démarrer le processus notepad.
* `Stop-Process -Name "notepad"` : Arrêter le processus notepad.

== Stockage et Partages Réseau

* Permet de lister, formater et configurer les disques et volumes.
* Utilisation pour gérer le stockage et les partitions.

=== Exemple

* `Get-Disk` : Lister tous les disques présents sur le système.
* `Get-Volume` : Lister tous les volumes.
* `Format-Volume -DriveLetter D -FileSystem NTFS` : Formater le volume D en NTFS.

=== Gestion des partages réseau

* `Get-SmbShare` : Lister tous les partages SMB.
* `New-SmbShare -Name "Docs" -Path "C:\Documents" -FullAccess "Everyone"` : Créer un nouveau partage `Docs` avec un accès complet pour tous.
* `Remove-SmbShare -Name "Docs"` : Supprimer le partage `Docs`.

== Permissions NTFS

* Permet de récupérer et définir les permissions ACL (Access Control List).
* Utilisation pour sécuriser les fichiers et dossiers.

=== Exemple

* `Get-Acl -Path "C:\Docs"` : Récupérer les ACL pour le dossier `C:\Docs`.
* `$acl = Get-Acl -Path "C:\Docs"`
* `$permission = "DOMAIN\User", "FullControl", "Allow"`
* `$accessRule = New-Object System.Security.AccessControl.FileSystemAccessRule $permission`
* `$acl.SetAccessRule($accessRule)`
* `Set-Acl -Path "C:\Docs" -AclObject $acl` : Définir les ACL pour le dossier `C:\Docs`.

== Mise à jour et Surveillance du Système

* Permet de rechercher, installer et configurer les mises à jour pour maintenir le système à jour et sécurisé.
* Utilisation pour assurer que toutes les mises à jour critiques et de sécurité sont appliquées.

=== Exemple

* `Get-WindowsUpdate` : Rechercher les mises à jour disponibles.
* `Install-WindowsUpdate -KBArticleID KB5008218` : Installer la mise à jour spécifique KB5008218.
* `Get-WindowsUpdateLog` : Récupérer les journaux des mises à jour.

=== Surveillance et journalisation

* `Get-EventLog -LogName System` : Récupérer les événements du journal système.
* `Get-EventLog -LogName Application -Newest 100` : Récupérer les 100 derniers événements du journal d'application.
* `Get-PerformanceCounter -Counter "\Processor(_Total)\% Processor Time"` : Obtenir les données de performance du processeur.

== Automatisation

* créer et gérer des tâches planifiées pour automatiser des tâches répétitives ou critiques.
* Utilisation pour améliorer et réduire les erreurs humaines dans la gestion

=== Exemple

* `$action = New-ScheduledTaskAction -Execute "PowerShell.exe" -Argument "-File C:\Scripts\Backup.ps1"` : Créer une action de tâche planifiée.
* `$trigger = New-ScheduledTaskTrigger -Daily -At "3AM"` : Créer un déclencheur de tâche planifiée pour une exécution quotidienne à 3h du matin.
* `Register-ScheduledTask -TaskName "DailyBackup" -Trigger $trigger -Action $action -User "SYSTEM" -RunLevel Highest` : Enregistrer une tâche planifiée `DailyBackup`.

// tag::demo[]
== Démonstration

[NOTE.speaker]
--
Montrer au fure et mesure des slide les différentes commandes et expliquer leurs fonctionnements
--
// end::demo[]
// end::deroulement[]

== Conclusion
// tag::conclusion[]
* vous connaissez à présent quelques commandes PowerShell pour administrer depuis la ligne de commande
// end::conclusion[]