flowchart TB
    A[Client] -->|Envoie un message| B[Chiffrement avec Clé Publique]
    B --> C{Serveur}
    C -->|Reçoit le message chiffré| D[Déchiffrement avec Clé Privée]
    D -->|Lit le message déchiffré| C

    subgraph Chiffrement
        direction TB
        B --> E[Clé Publique]
        E -->|Utilisée pour chiffrer les données| B
    end

    subgraph Déchiffrement
        direction TB
        D --> F[Clé Privée]
        F -->|Utilisée pour déchiffrer les données| D
    end