sequenceDiagram
    participant Bot1
    participant Bot2
    participant ServeurWeb

    Bot1->>ServeurWeb: Trafic massif
    Bot2->>ServeurWeb: Trafic massif
    Note right of ServeurWeb: Serveur surchargé