graph TD
    Navigateur -->|SSL/TLS| Web_App
    Web_App -->|SSL/TLS| Serveur_VPN

    subgraph Utilisateur
        U2[Utilisateur final]
    end

    subgraph Serveur
        Serveur_VPN[Serveur VPN SSL/TLS]
        Web_App[Application web sécurisée]
    end