:titre: Introduction à Helm
:module: Conteneurs et orchestration
:duree: --
:description: Introduction et approfondissement de l'utilisation de Helm, le gestionnaire de paquets pour Kubernetes.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
*Comprendre* les concepts de base de Helm
*Utiliser* Helm pour déployer et gérer des applications Kubernetes
*Créer* vos propres charts Helm personnalisés
*Gérer* les dépendances et les mises à jour des releases
*S'initier* aux fonctionnalités avancées de Helm comme les hooks et les tests
// end::objectifs[]

// tag::deroulement[]
== Helm et Kubernetes

Helm simplifie le management des applications Kubernetes.

[NOTE.speaker]
--
Dans le monde des conteneurs et de l’orchestration, Kubernetes s’est imposé comme le standard pour déployer et gérer des applications conteneurisées. Cependant, la gestion des configurations et des déploiements complexes peut rapidement devenir un casse-tête. C’est ici qu’intervient Helm souvent décrit comme le gestionnaire de paquets pour Kubernetes.
Helm simplifie le processus de gestion des applications Kubernetes en permettant de définir, installer et mettre à jour des ensembles de ressources Kubernetes de manière cohérente et reproductible.
Avec Helm, vous pouvez empaqueter vos applications et leurs dépendances en charts, déployer ces applications à l’aide de commandes simples et gérer leur cycle de vie avec facilité.
Dans ce guide, nous allons vous accompagner pour comprendre et utiliser Helm efficacement.
--

=== Historique

- 2015 : Création par Deis
- Premières versions (v1) : Limitations en termes de gestion des dépendances et de flexibilité
- 2016 : Helm v2 avec Tiller, meilleur gestion des dépendances, support des hooks
- 2018 : Adoption par CNCF, soutien communautaire élargi
- 2019 : Helm v3 sans Tiller, amélioration de la sécurité et de l'interaction directe avec l'API Kubernetes

[NOTE.speaker]
--
Helm a été développé à l’origine par l’équipe de Deis et est devenu populaire pour simplifier le déploiement d’applications sur Kubernetes. En 2016, Helm v2 a introduit Tiller avec des améliorations telles qu'une meilleure gestion des dépendances et l'ajout de hooks. En 2019, Helm v3 a marqué une étape importante avec la suppression de Tiller pour améliorer la sécurité, grâce à une interaction directe avec l'API Kubernetes.
--

=== Concepts de base de Helm
- Repositories : Emplacements de stockage et distribution des charts (publics ou privés)
- Charts : Ensembles de fichiers décrivant les ressources Kubernetes nécessaires à l'application
- Releases : Instances déployées de charts, permettant le suivi et la gestion des versions
- Values : Fichier values.yaml contenant les valeurs par défaut pour les templates
- Templates : Fichiers YAML de définition des ressources Kubernetes
- Helmfile : Outil pour gérer plusieurs charts et releases dans un seul fichier
- Hooks : Actions exécutées à des moments spécifiques du cycle de vie des releases 

[NOTE.speaker]
--
Pour utiliser efficacement Helm, il est important de comprendre ses concepts fondamentaux. Les principales notions incluent les repositories, charts, releases, values, templates, l'outil Helmfile pour orchestrer des déploiements complexes, et les hooks pour des actions spécifiques.
--

=== Fonctionnement général

Les charts sont au cœur du fonctionnement de Helm, facilitant le déploiement et la gestion des applications Kubernetes.

[NOTE.speaker]
--
Helm V3 est conçu pour simplifier le déploiement, la gestion et la mise à jour des applications sur Kubernetes. Le fonctionnement général repose sur les charts, qui sont des paquets contenant toutes les ressources nécessaires pour déployer une application Kubernetes. Helm permet la personnalisation des déploiements via les fichiers values.yaml, et supporte les mises à jour et rollbacks avec facilité. 
La gestion des dépendances offre l'installation automatique des composants nécessaires. Enfin, Helm s'intègre bien avec les outils d'automatisation et CI/CD, pour assurer des déploiements cohérents et fiables.
--

== Installation de Helm

Installation de la CLI Helm sur Linux, macOS, et Windows. Assurez-vous de disposer d'un cluster Kubernetes et de kubectl.

[NOTE.speaker]
--
Pour commencer à utiliser Helm, la première étape consiste à installer la CLI (Command Line Interface) Helm sur votre machine. Helm interagit avec Kubernetes via l’API, donc kubectl est nécessaire pour certaines opérations...
--

// tag::exercice[]
=== Exercice : Installation manuelle

Procéder à l'installation de Helm sur votre machine en suivant différentes méthodes suivant votre OS.

[NOTE.speaker]
--
Linux:
- asdf-vm : `asdf plugin-add helm && asdf install helm latest && asdf global helm latest`
- Installer manuellement les binaires après téléchargement sur GitHub

macOS:
- `brew install helm` via Homebrew
- Installer les binaires manuellement

Windows:
- `choco install kubernetes-helm` via Chocolately
- Installer manuellement les binaires

Vérifier l’installation avec : `helm version`
--
// end::exercice[]

== Premier déploiement avec Helm

Ajout et déploiement via les repositories de charts.

[NOTE.speaker]
--
Après avoir installé Helm, il est temps de l’utiliser pour déployer votre première application. Pour cela :
1. Ajouter un repository de charts tel que le repository Bitnami : `helm repo add bitnami https://charts.bitnami.com/bitnami && helm repo update`
2. Rechercher un chart spécifique, par exemple Nginx : `helm search repo nginx`
3. Installer une version spécifique d’un chart pour garantir la stabilité et la reproductibilité des déploiements, par exemple `helm install my-release bitnami/nginx --version 8.8.0`
4. Vérifier le déploiement avec : `kubectl get all -l app.kubernetes.io/instance=my-release`
5. Personnaliser l’installation avec un fichier de valeurs personnalisé ou en ligne de commande.
--

=== Création de vos propres Charts

Créez et structurez un chart personnalisé, apprenez à packager et partager vos applications.

[NOTE.speaker]
--
Créer votre propre chart Helm vous permet de packager vos applications et leurs configurations. La structure d’un chart généré par `helm create` inclut des fichiers tels que Chart.yaml pour les métadonnées, values.yaml pour les valeurs par défaut, et des templates définissant les ressources Kubernetes nécessaires. Utilisez des helpers pour rendre les templates plus maintenables et packagez votre chart avec `helm package` pour le partager.
--

=== Gestion des dépendances

Utilisation du fichier `Chart.yaml` pour les dépendances.

[NOTE.speaker]
--
Pour définir des dépendances pour votre chart, vous devez les spécifier dans le fichier Chart.yaml avec le nom, la version, et le repository. Utilisez la commande `helm dependency update` pour télécharger et ajouter les chart nécessaires au répertoire charts/. 
La gestion des versions des dépendances est cruciale pour garantir la stabilité des déploiements, et Helm les installe automatiquement lors du déploiement. 
Pour mettre à jour, appliquez les mises à jour en utilisant `helm upgrade` après avoir exécuté `helm dependency update`.
--

// tag::exercice[]
== Exercice : Installer et mettre à jour avec dépendance

Mettre en pratique en créant un chart avec dépendance typique requise (comme `mysql`), mettre à jour les dépendances et tester le déploiement.

[NOTE.speaker]
--
Créer un chart dépendant de `mysql`, définir la dépendance dans Chart.yaml, mettre à jour les dépendances avec `helm dependency update`, puis déployer et mettre à jour le chart en utilisant `helm install` et `helm upgrade`.
--
// tag::exercice[]

== Mise à jour et suppression des releases


.Mise à jour
```
helm upgrade my-release ./mychart
```

.Rollback
```
helm rollback my-release 1
```

.Suppression
```
helm uninstall my-release
```

[NOTE.speaker]
--
Pour mettre à jour une release Helm, utilisez `helm upgrade`. Pour ramener une release à une révision précédente, `helm rollback` est utilisé. Lorsque vous n'avez plus besoin d'une application, supprimez la release associée pour libérer les ressources avec `helm uninstall`. 

Ensuite, nettoyez les ressources restantes avec `kubectl` pour vous assurer que rien n'est resté bloqué.
--

// tag::demo[]
=== Démonstration

Exercice en utilisant les commandes `upgrade`, `rollback`, et `uninstall`. Vérifiez la suppression des ressources associées avec `kubectl`.

[NOTE.speaker]
--
Pratiquez la mise à jour d'une release, effectuez un rollback en cas d'échec, et appliquez la suppression d'une application pour libérer les ressources.
--
// end::demo[]

== Utilisation avancée de Helm

Explorez les hooks, tests, et meilleures pratiques de sécurité.

[NOTE.speaker]
--
Helm offre des fonctionnalités avancées telles que l'utilisation de hooks pour exécuter des actions spécifiques durant le cycle de vie d'une release, des tests pour vérifier les applications déployées, et des meilleures pratiques de sécurité avec des RBACs adaptés. 
Integrez Helm dans vos pipelines CI/CD pour des processus automatisés et déployez en usage multi-environnements pour gérer les configurations spécifiques de vos applications en développement, test, et production.
--

== Exercice : Hooks et Tests

// tag::exercice[]
Implémentez un hook pre-install et configurez un test pour une application déployée.

[NOTE.speaker]
--
Définissez un hook dans un template pour exécuter une tâche avant l’installation, puis ajoutez un test pour valider le bon fonctionnement de l’application après déploiement.
--
// end::exercice[]

// tag::conclusion[]
== Conclusion

Helm est un outil essentiel pour gérer les déploiements d’applications sur Kubernetes.

[NOTE.speaker]
--
Helm simplifie la gestion des configurations, des déploiements et des mises à jour, tout en offrant des fonctionnalités avancées pour des environnements de production robustes et sécurisés. Il permet de définir des configurations standardisées et reproductibles, facilitant la gestion à grande échelle et intégrant des processus de CI/CD pour automatiser les déploiements continus. Helm améliore non seulement l’efficacité des déploiements, mais aussi la résilience et la sécurité de vos applications en production.
--
// end::conclusion[]