:titre: Installer des clusters Kubernetes avec Kubeadm
:module: Kubernetes
:duree: --
:description: Apprendre à installer et gérer un cluster Kubernetes avec Kubeadm.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
* *Comprendre* les fonctionnalités et l'historique de Kubeadm.
* *Installer* et *configurer* un cluster Kubernetes avec Kubeadm.
* *Gérer* les mises à jour et la configuration d'un cluster Kubernetes.
// end::objectifs[]

// tag::deroulement[]
== Introduction

Kubeadm est un outil conçu pour simplifier le déploiement de clusters Kubernetes sur vos serveurs.

[NOTE.speaker]
--
Kubeadm permet d’initialiser un cluster Kubernetes en quelques commandes seulement et assure la configuration de tous les composants nécessaires pour le faire fonctionner. Avec Kubeadm, vous pouvez créer des clusters vanilla avec une installation plus rapide et plus fiable. L’outil est extensible et adaptable, permettant aux administrateurs de personnaliser les configurations selon les besoins spécifiques de leur environnement. Kubeadm gère également la mise à jour et la configuration des clusters, ce qui simplifie grandement le processus d’administration continue.
--

=== Historique

Kubeadm a été introduit par la communauté Kubernetes pour répondre à la complexité croissante de l’installation et de la gestion des clusters Kubernetes.

[NOTE.speaker]
--
Avant Kubeadm, le déploiement de Kubernetes nécessitait de nombreuses étapes manuelles, une configuration complexe et une bonne compréhension des composants internes de Kubernetes. Cela rendait le processus non seulement fastidieux, mais aussi sujet aux erreurs, surtout pour les nouveaux utilisateurs. L’outil Kubeadm a été lancé officiellement avec la version 1.6 de Kubernetes en 2017. Son objectif principal était de fournir une méthode simple, rapide et reproductible pour installer Kubernetes, sans pour autant compromettre la flexibilité et la robustesse des déploiements. Avec chaque nouvelle version de Kubernetes, Kubeadm a été amélioré pour prendre en compte les changements de l’API de Kubernetes et en charge de nouvelles fonctionnalités. Aujourd’hui, Kubeadm est largement utilisé dans les environnements de production, les environnements de test et par les développeurs souhaitant configurer des clusters Kubernetes sur leurs machines.
--

=== Fonctionnalités

*Kubeadm* offre plusieurs fonctionnalités clés :

* Initialisation automatique du cluster : Configure automatiquement les composants critiques du plan de contrôle.
* Ajout sécurisé de nœuds : Génère des jetons d’adhésion sécurisés pour intégrer de nouveaux nœuds au cluster.
* Gestion simplifiée des mises à jour : Simplifie la mise à jour des composants du plan de contrôle et des nœuds de travail.
* Gestion et distribution des certificats : Génère, renouvelle et distribue les certificats de sécurité nécessaires.
* Configuration du réseau de pods : Supporte plusieurs plugins de réseau comme Calico et Flannel.
* Compatible multi-plateforme : Compatible avec plusieurs systèmes d’exploitation et architectures matérielles.
* Automatisation possible avec Ansible, Terraform : S’intègre avec des outils pour automatiser les tâches d’administration.
* Vérification de l'état du cluster : Fournit des outils pour diagnostiquer et vérifier l’état du cluster.

== Prérequis

Avant de commencer, il est essentiel de s'assurer que votre environnement est correctement configuré.

=== Infrastructure matérielle

- **Nœud maître** :
  - CPU : 2 cœurs minimum
  - Mémoire : 2 GB de RAM minimum
  - Stockage : 20 GB de disque
- **Nœud de travail** :
  - CPU : 1 cœur minimum
  - Mémoire : 1 GB de RAM minimum
  - Stockage : 20 GB de disque

[NOTE.speaker]
-- 
Vous aurez besoin d’un ensemble de machines virtuelles ou physiques pour constituer les nœuds de votre cluster. Typiquement, un **cluster Kubernetes** comprend un nœud maître et plusieurs nœuds de travail. Voici les spécifications matérielles recommandées pour chaque type de nœud :

Dans cet exemple, nous utiliserons des machines virtuelles instanciées sur le cloud Outscale avec 3 maîtres et 2 workers.
--

=== Système d’exploitation

*Kubeadm* supporte plusieurs distributions Linux, notamment Ubuntu 22.04+, Rocky Linux 8+, et Debian 11+.

=== Logiciels nécessaires

1. Runtime de conteneur : Un parmi les suivants
   - containerd : Un runtime de conteneur léger et rapide, maintenu par la CNCF.
   - CRI-O : Optimisé pour Kubernetes, conforme à l'interface CRI.
   - Docker : Utilise containerd en interne.
   - gVisor : Un runtime sécurisé offrant une isolation renforcée.

2. Kubeadm, Kubelet, et Kubectl : Ces composants sont essentiels pour gérer le cluster Kubernetes.

=== Configuration réseau

- **Port 6443** (kube-apiserver) sur le nœud maître
- **Ports 10250, 10251, 10252** (kubelet, scheduler, controller-manager) sur le nœud maître
- **Port 10250** (kubelet) sur les nœuds de travail
- **Port 179** (BGP) si vous l’utilisez

[NOTE.speaker]
-- 
Kubernetes nécessite une configuration réseau correcte pour permettre la communication entre les nœuds. Assurez-vous que les ports suivants sont disponibles sur vos machines :

Les nœuds doivent pouvoir communiquer entre eux sans restriction.
--

=== Accès utilisateur

Vous aurez besoin d’un accès `root` ou `sudo` sur toutes les machines pour exécuter les commandes nécessaires à l’installation et à la configuration de Kubernetes.

=== Synchronisation de l’heure

Il est indispensable que toutes les machines du cluster aient des horloges synchronisées. Utilisez un service comme NTP ou Chrony pour assurer la synchronisation de l’heure.

== Création des machines AWS

Utilisez Terraform pour provisionner des machines et configurez-les avec Ansible.

[NOTE.speaker]
--
Assurez-vous d’avoir installé les outils nécessaires comme Terraform, Ansible et d’avoir vos identifiants d’accès pour AWS. Créez les 5 machines dans le subnet privé.
--

=== Installation des prérequis

[NOTE.speaker]
--
Pour installer Kubeadm, Kubelet, et Kubectl, configurez containerd comme runtime de conteneur. Utilisez Packer pour créer une OMI.
--

=== Ansible

*Ansible Playbook :* provision_kube_nodes.yaml

```yaml
----
# Sections omises pour concision
tasks:
- name: Add Kubernetes GPG key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v{{ kube_version }}/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
mode: '0644'
force: true
# Continuer avec les autres tâches...
```

=== Configuration

.config.toml
```toml
# Sections omises pour concision
sandbox_image = "registry.k8s.io/pause:3.9"
systemd_cgroup = false
# Continuer la configuration...
```

=== Crictl

.crictl.yml
```yaml
runtime-endpoint: unix:///run/containerd/containerd.sock
image-endpoint: unix:///run/containerd/containerd.sock
timeout: 2
debug: false
pull-image-on-create: false
```

Créez votre inventaire statique ou utilisez un inventaire dynamique qui crée automatiquement ces groupes : kube_masters, kube_workers.

=== Exécutez le playbook

```shell
ansible-playbook provision_kube_nodes.yml
```

== Utilisation d’haproxy comme Load Balancer

Utilisez HAProxy pour le Load Balancing au lieu du service de Load Balancer d'Outscale.

[NOTE.speaker]
--
HAProxy sera installé sur le bastion. Voici comment configurer HAProxy pour gérer les requêtes vers vos nœuds Kubernetes.
--

=== Ansible

*Ansible Playbook :* install_haproxy.yaml

```yaml
----
tasks:
- name: Install packages
  ansible.builtin.apt:
    name: 
    - haproxy
  state: present
# Continuer avec les autres tâches...
```

=== HaProxy

*haproxy.cfg.j2*

```plaintext
global
daemon
maxconn 256
defaults
mode http
log global
option redispatch
retries 3
timeout connect 5000ms
timeout client 50000ms
timeout server 50000ms
frontend kubernetes-frontend
bind *:6443
option tcplog
mode tcp
default_backend kubernetes-backend
backend kubernetes-backend
mode tcp
balance roundrobin
option tcp-check
{% for host in cplanes %}
server kube_api{{loop.index}} {{ hostvars[host]["private_ip_address"] }}:6443 check
{% endfor %}
```

=== Relancez le playbook

```shell
ansible-playbook install_haproxy.yml
```

== Initialisation du cluster

Commencez par initialiser le cluster sur le nœud maître.

```shell
sudo kubeadm init --control-plane-endpoint <bastion_ip>:6443 --upload-cert --pod-network-cidr=192.168.0.0/16
```

Pour permettre à l’utilisateur non-root d’accéder au cluster, exécutez les commandes suivantes sur votre machine (dans cet exemple, le bastion) :

```shell
mkdir -p $HOME/.kube
sudo scp -i <MASTER_IP>:/etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
```

=== Ajout de nœuds au cluster

Utilisez le jeton d’adhésion pour ajouter d'autres nœuds au cluster.

[NOTE.speaker]
--
Pour ajouter des nœuds masters supplémentaires au cluster, utilisez le jeton d’adhésion fourni par **Kubeadm** lors de l’initialisation. Exécutez cette commande sur chaque nœud master.

```
kubeadm join <bastion_ip>:6443 --token <TOKEN> --discovery-token-ca-cert-hash sha256:<HASH> --control-plane --certificate-key <HASH_CERT>
```

Pour ajouter des nœuds workers supplémentaires au cluster, utilisez le jeton d’adhésion fourni par **Kubeadm**. 
--

```shell
sudo kubeadm join <bastion_ip>:6443 --token <TOKEN> --discovery-token-ca-cert-hash sha256:<HASH>
```

Remplacez `<bastion_ip>`, `<TOKEN>`, `<HASH>` et `<HASH_CERT>` par les valeurs retournées par `kubeadm init`.

=== Déploiement d’un réseau de pods

Utilisez Calico pour le réseau de pods :

```shell
kubectl create -f https://docs.projectcalico.org/manifests/calico.yaml
```

=== Vérification du cluster

Assurez-vous que le cluster fonctionne correctement.

```shell
kubectl get nodes
kubectl get pods -n kube-system
```

== Mise à jour et gestion du cluster

Mettez à jour régulièrement votre cluster pour garantir sa sécurité et fiabilité.

[NOTE.speaker]
--
Effectuez des mises à jour régulières et surveillez activement le cluster pour assurer un fonctionnement optimal. 
--

=== Mise à jour du plan de contrôle

Appliquez les mises à jour avec les commandes appropriées.

```shell
sudo kubeadm upgrade plan
sudo kubeadm upgrade apply vX.Y.Z
```

Après l'exécution, redémarrez les composants :

```shell
sudo systemctl restart kubelet
```

Vérifiez que les composants du plan de contrôle sont à jour :

```shell
kubectl get nodes
kubectl get pods -n kube-system
```

Il faudra répéter cette procédure sur les autres nœuds masters, mais au lieu d’utiliser la commande `sudo kubeadm upgrade apply`, utilisez :

```shell
sudo kubeadm upgrade node
```

=== Mise à jour des nœuds de travail

Mettez à jour les nœuds de travail sans perturber le service.

Pour éviter les interruptions de service, drainez chaque nœud de travail avant la mise à jour.

```shell
kubectl drain <node-name> --ignore-daemonsets
```

Sur chaque nœud de travail, mettez à jour `kubelet` et `kubectl` :

```shell
sudo apt-get update
sudo apt-get install -y kubelet kubectl
sudo apt-mark hold kubelet kubectl
```

Redémarrez le service `kubelet` :

```shell
sudo systemctl restart kubelet
```

Après la mise à jour, annulez le drainage pour rendre le nœud à nouveau disponible :

```shell
kubectl uncordon <node-name>
```

== Conclusion

*Kubeadm* est un outil puissant pour simplifier le déploiement et la gestion des clusters Kubernetes.

[NOTE.speaker]
--
Gardez votre cluster sécurisé et performatif en suivant les bonnes pratiques de gestion continue. 
--
// end::deroulement[]

== Conclusion

// tag::conclusion[]
* Kubeadm simplifie le déploiement de Kubernetes.
* Gestion continue essentielle pour la sécurité et performance du cluster.
// end::conclusion[]