:titre: Minikube
:module: Orchestration
:duree: --
:description: Découvrez comment utiliser Minikube pour explorer Kubernetes sans complexité.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
* *Comprendre* l'utilisation de Minikube pour tester Kubernetes localement.
* *Savoir* installer Minikube sur divers systèmes d'exploitation.
* *Appliquer* les configurations de clusters Minikube.
* *Analyser* les avantages de différents drivers et add-ons.
// end::objectifs[]

// tag::deroulement[]
== Introduction

Minikube est la solution idéale pour créer un cluster Kubernetes localement sans passer par un processus de déploiement complexe.

[NOTE.speaker]
--
Minikube est un outil qui vous permet de créer un cluster Kubernetes sur votre machine locale, facilitant ainsi l'apprentissage et le test rapide.
Historique de Minikube: Né pour simplifier la manipulation des clusters Kubernetes en local, avec l'appui de la Cloud Native Computing Foundation. Évolué pour inclure multiples drivers, add-ons, et gestion de clusters multi-nœuds.
Minikube a comblé un besoin pour les développeurs lorsqu'il s'agit de manipuler Kubernetes sans les complications inhérentes à un déploiement sur une infrastructure complète.
--

== Installation

=== Vérification des prérequis

Avant de commencer, assurez-vous d'avoir:
* 2 CPU, 2 Go de RAM et 20 Go d'espace disque.
* Docker ou VirtualBox installé, selon le driver choisi.
* La virtualisation activée (VT-x ou AMD-V).
* La possibilité d'installer Docker (selon le driver choisi), de même que kubectl pour interagir avec le cluster.

[NOTE.speaker]
--
Linux: `egrep -q 'vmx|svm' /proc/cpuinfo && echo "Virtualisation activée" || echo "Activez-la dans le BIOS"`  
Windows: Exécutez `msinfo32`, et vérifiez si "Virtualization Enabled" est sur Oui.
Pour garantir un bon fonctionnement, vérifiez que votre processeur supporte la virtualisation.
--

=== Installation par OS

Pour Linux:
```bash
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
sudo install minikube-linux-amd64 /usr/local/bin/minikube
```

Pour macOS:
```bash
brew install minikube
```

Pour Windows:
Utilisez l'un des moyens suivants pour l'installation: Téléchargez l’exécutable depuis le [site officiel](https://minikube.sigs.k8s.io/docs/start/) ou utilisez **choco**:

```bash
choco install minikube
```

Vérification de l'installation:
Pour vérifier que Minikube est correctement installé, exécutez la commande suivante:
```bash
minikube version
```

== Démarrage d’un cluster Minikube basique

Pour lancer votre cluster:
```bash
minikube start
```

Selon vos besoins, vous voudrez peut-être ajuster la configuration des ressources que Minikube utilise. Allez plus loin en allouant des ressources spécifiques:
```bash
minikube start --cpus=4 --memory=8192 --disk-size=30g
```

Si vous avez besoin de modifier les ressources après avoir démarré le cluster, Minikube rend cela assez facile :
```bash
minikube config set memory 4096
minikube config set cpus 2
```

Après avoir modifié ces configurations, il vous faudra redémarrer le cluster :
```bash
minikube stop
minikube start
```

== Choix et Utilisation des Drivers

Configurer un cluster Minikube offre une grande flexibilité grâce à ses nombreux drivers. Ces derniers définissent comment Kubernetes s'exécute sur votre machine.

Minikube supporte plusieurs drivers, chaque driver a ses propres avantages:
* **Docker**: Léger et rapide. Recommandé si Docker est déjà installé.
* **VirtualBox**: Parfait comme environnement universel si Docker n'est pas disponible.
* **KVM2** (Linux): Haute performance sur les environnements Linux.
* **Hyper-V** (Windows): Une alternative performante pour Windows.
* **Podman**: Pour ceux qui utilisent Podman au lieu de Docker.

Pour spécifier le driver que vous voulez utiliser avec Minikube:
```bash
minikube start --driver=docker
```

Pour éviter de spécifier le driver à chaque démarrage, vous pouvez choisir de le définir par défaut :
```bash
minikube config set driver kvm2
minikube start
```

Après avoir lancé votre cluster, vous pouvez vérifier quel driver est utilisé grâce à la commande :
```bash
minikube profile list
```

== Profils Minikube

Les profils permettent de gérer plusieurs clusters Kubernetes sur la même machine. Chaque profil est un cluster Kubernetes unique avec ses propres configurations distinctes.

Un profil dans Minikube vous permet de :
* Gérer sa propre configuration.
* Allouer ses propres ressources CPU, RAM, et choisir son driver.

Pour créer un cluster avec un profil que vous avez personnalisé:
```bash
minikube start --profile=kvm --cpus=4 --memory=8192 --driver=kvm2
```

Pour voir la liste de tous vos profils disponibles, utilisez :
```bash
minikube profile list
```

Pour basculer vers un autre profil, utilisez :
```bash
minikube profile kvm
```

Vérifiez le contexte actif pour être sûr du profil sur lequel vous travaillez :
```bash
kubectl config current-context
```

Lorsque vous n'avez plus besoin d'un profil, vous pouvez le supprimer ainsi que le cluster qui lui est associé avec :
```bash
minikube delete --profile=kvm
```

== Utilisation de kubectl

kubectl est l’outil en ligne de commande officiel pour interagir avec un cluster Kubernetes. Avec Minikube, kubectl est indispensable pour gérer vos ressources (pods, services, déploiements). Si kubectl n’est pas déjà installé sur votre machine, vous pouvez utiliser la version intégrée de Minikube.

Pour vérifier l'état de votre cluster actuel:
```bash
kubectl cluster-info
```

Si vous souhaitez utiliser le kubectl de Minikube, la commande est :
```bash
minikube kubectl -- cluster-info
```

== Les Add-ons Minikube

Les add-ons sont l’une des fonctionnalités les plus intéressantes de Minikube. Ils permettent d’ajouter des fonctionnalités supplémentaires à votre cluster local, comme un tableau de bord, la gestion des métriques, ou encore des outils de surveillance comme Prometheus et Grafana. Ces modules intégrés simplifient les expérimentations avec Kubernetes.

Quelques add-ons populaires incluent :
* **Dashboard** : Interface graphique pour gérer vos ressources Kubernetes.
* **Ingress** : Gérer les entrées HTTP/HTTPS.
* **Metrics Server** : Collecte et affichage des métriques de performance.

Pour afficher tous les add-ons que Minikube propose:
```bash
minikube addons list
```

Si vous souhaitez activer un add-on:
```bash
minikube addons enable ingress
```

Lorsque vous n'avez plus besoin d’un add-on, économisez des ressources en le désactivant :
```bash
minikube addons disable dashboard
```
// end::deroulement[]

== Conclusion

// tag::conclusion[]
* Minikube est un outil polyvalent pour explorer et maîtriser Kubernetes.
* Idéal pour les développeurs et administrateurs système cherchant à tester des configurations avancées.
* Gestion des profils permettant de créer et exécuter plusieurs clusters isolés avec des paramètres distincts.
* Fonctionnalité essentielle pour travailler sur plusieurs projets ou environnements.
* Add-ons intégrés comme le dashboard, Ingress, et Metrics Server pour simuler des environnements proches de la production.
* Simplicité d’installation et flexibilité avec les drivers.
* Un allié précieux pour comprendre et manipuler Kubernetes.
// end::conclusion[]
