:titre: Syntaxe et règles de base en NFTables
:module: Flux entrants
:duree: 90
:description: Comprendre la syntaxe de NFTables et créer des règles de base
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../adoc/libs
endif::[]

== Objectifs pédagogiques
// tag::objectifs[]
* Comprendre la syntaxe de NFTables
* Création de règles de base avec NFTables
* Savoir traduire des règles IPtables en NFTables
// end::objectifs[]

// tag::deroulement[]

== Composants clés

* **Tables** : Servent de conteneurs pour organiser les chaînes. Chaque table peut regrouper des chaînes selon leur fonction (filtrage, NAT, etc.).
* **Chaînes** : Contiennent les règles spécifiques qui déterminent le traitement des paquets. Les chaînes sont associées à des hooks (points d'entrée) dans le processus de traitement des paquets.
* **Règles** : Spécifient les actions à prendre pour les paquets qui correspondent à certains critères (adresses IP, ports, protocoles).
* **Ensembles** : Permettent de gérer des collections de valeurs, comme des adresses IP ou des ports, simplifiant ainsi les règles en évitant la duplication.

=== Tables

* servent de conteneurs pour organiser les chaînes
* permettent de regrouper des chaînes selon leur fonction (filtrage, NAT, etc.)
* définies par un nom et un type (ip, arp, bridge, etc.)

```sh
table ip filter {
    ...
}
```

[NOTE.speaker]
--
Dans cet exemple, la table filter est utilisée pour les règles de filtrage IPv4.
--

=== Chaînes

* contiennent les règles spécifiques qui déterminent le traitement des paquets
* associées à des hooks (points d'entrée) dans le processus de traitement des paquets
* définies par un nom, un type (filter, nat, etc.), un hook et une priorité

```sh
chain input {
    type filter hook input priority 0;
    ...
}
```

[NOTE.speaker]
--
La chaîne input est utilisée pour traiter les paquets entrants. Le hook input indique que cette chaîne s'applique aux paquets dès leur entrée dans le système.
--

=== Règles

* spécifient les actions à prendre pour les paquets qui correspondent à certains critères
* peuvent inclure l'acceptation, le rejet, le marquage, la redirection, etc.
* composées de critères (adresses IP, ports, protocoles) et d'actions

```sh
rule ip saddr 192.168.1.100 drop;
```

[NOTE.speaker]
--
Cette règle stipule que les paquets provenant de l'adresse IP 192.168.1.100 doivent être abandonnés.
--

=== Ensembles

* permettent de gérer des collections de valeurs
* simplifient les règles en évitant la duplication
* utiles pour gérer des listes d'adresses IP, de ports, etc.
* définis par leur type et peuvent être utilisés dans les règles

```sh
set blocked_ips {
    type ipv4_addr;
    elements = { 192.168.1.100, 192.168.1.101 }
}
```

[NOTE.speaker]
--
L'ensemble blocked_ips contient plusieurs adresses IP.
--

**Utilisation d'un ensemble dans une règle**

```sh
rule ip saddr @blocked_ips drop;
```

[NOTE.speaker]
--
La règle utilise l'ensemble `blocked_ips` pour bloquer tous les paquets provenant des adresses listées.
--

== Exemple de syntaxe complète

```sh
table ip filter {
    chain input {
        type filter hook input priority 0;
        policy accept;
    }
}
```

[NOTE.speaker]
--
* `table ip filter` : Crée une table nommée filter pour les règles IPv4.
* `chain input` : Crée une chaîne input dans la table filter.
* `type filter hook input priority 0;` : Spécifie que cette chaîne est de type filter et est accrochée au point d'entrée input avec une priorité de 0.
* `policy accept;` : Définit la politique par défaut pour cette chaîne à accept.
--

// tag::demo[]

== Démonstration

**Syntaxe de nftables**

[NOTE.speaker]
--
* **Créer une table et une chaîne**

Commande pour créer une table

```sh
sudo nft add table ip my_table
```

Commande pour créer une chaîne

```sh
sudo nft add chain ip my_table my_chain { type filter hook input priority 0\; }
```

* **Table `my_table`** : Contient les chaînes pour organiser les règles.
* **Chaîne `my_chain`** : Attachée au hook input, elle traite les paquets entrants.

* **Ajouter une règle simple**

Commande pour ajouter une règle

```sh
sudo nft add rule ip my_table my_chain ip saddr 192.168.1.100 drop
```

* `ip saddr 192.168.1.100` : Spécifie que la règle s'applique aux paquets provenant de l'adresse IP 192.168.1.100.
* `drop` : Action à prendre pour ces paquets, ici, les abandonner.
--

// end::demo[]

// tag::exercice[]

== Exercice

**Consignes** : 

* traduire les règles suivantes d'ufw en NFTables

```sh
sudo ufw deny from 192.168.1.100

sudo ufw allow 80/tcp

sudo ufw allow out 22/tcp
```

[NOTE.speaker]
--
```sh
sudo nft add rule ip filter input ip saddr 192.168.1.100 drop

sudo nft add rule ip filter input tcp dport 80 accept

sudo nft add rule ip filter output tcp dport 22 accept
```
--

// end::exercice[]

// end::deroulement[]

== Conclusion
// tag::conclusion[]
* Compréhension de la syntaxe de NFTables
* Capacité à créer des règles de base avec NFTables
* Capacité à traduire des règles IPtables en NFTables
// end::conclusion[]