:titre: Installation DNS Linux
:module: Réseau
:duree: 120
:description: Installer et configurer BIND sur Linux
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]


== Objectifs pédagogiques

// tag::objectifs[]
* Installer et configurer BIND sur Linux
* Configurer les fichiers de zone et les résolutions DNS
* Effectuer les opérations post-configuration et tester le serveur DNS
// end::objectifs[]

// tag::deroulement[]

== Installation sur Linux

=== Paquet d'installation

Le paquet qui régit l'installation du serveur DNS sous Linux s'appelle `bind`.

Bind existe déjà en plusieurs versions.. La version courante est la version 9.

=== Installation

Comme tout paquet linux, il plusieurs méthodes d'installation, 

exemple, sous Debian, on lance la commande: 

```sh
apt-get install bind9
```

=== Après installation

* les répertoires /etc/bind/ et /var/bind/ (ou /var/cache/bind/) sont créés. 
* peuvent être différents sous d'autres distributions
* Ils contiennent les fichiers qui assurent le fonctionnement du serveur DNS.

== Configuration BIND

**Configuration du fichier principal**

* Le fichier principal de configuration de notre serveur est named.conf. 
* situé dans le répertoire /etc/bind/.  (peut changer selon les distributions). 

=== Les principaux paramètres de configuration sont

[cols="2,8"]
|===
| PARAMÈTRE     | EXPLICATION

| options       | ouvre les balises pour les options générales de configuration

| directory     | pour définir le dossier dans lequel sera sauvegardé les fichiers de zone

| query-source  | le port d'écoute du serveur

| forward       | option de transfert de la requête vers un autre serveur

|===

include::../../../../adoc/libs/slide-notitle.adoc[]

[cols="2,8"]
|===
| PARAMÈTRE     | EXPLICATION

| forwarders    | serveur DNS de réception des requêtes transférées

| zone          | ouvre les balises pour la configuration d'une zone

| type          | type de la zone

| file          | fichier de configuration de la zone
|===

=== Exemple de configuration

A l'installation, le fichier named.conf existe déjà avec un contenu. 

Les options générales y sont déjà définies. On a par exemple :

```sh
options { 
	directory "/var/bind"; 
	query-source port 53; 
	forward only; 
	forwarders { x.x.x.x;};
};
```

Au contenu existant, on ajoute les lignes suivantes pour la recherche Direct et indirecte:

```sh
#Déclaration du fichier de résolution directe
zone "Mondomain.lcl" in {
	type master ;
	file "/var/bind/mondomaine.lcl.direct" ;
}
#Déclaration du fichier de résolution inverse
zone "1.168.192.in-addr.arpa" in {
	type master ;
	file "/var/bind/mondomain.lcl.reverse";
}
```

== Fichiers de zones

Le répertoire /var/bind/ créé pendant l'installation de bind, est vide. 

* il faut créer les fichiers de zone mondomaine.lcl.direct  et mondomaine.lcl.reverse
* puis définir les paramètres de configuration de la zone (domaine) mondomaine.lcl.

=== Principaux paramètres de configuration des fichiers de zone

* **SOA**	: démarre la configuration d'une zone. C'est la délégation d'autorité.
* **TTL**	: Time To Live : durée de vie du SOA
* **Serial**	: Numéro de version du fichier, sert à la synchronisation. 
* **Refresh** : Intervalle pour le refresh, sert à la synchro entre serveurs primaires et secondaires
* **Retry**	: Fréquence essaie en cas d'échec des refresh. 
* **Expire**	: Principalement utilisé par un serveur secondaire, temps maximal  de validité des informations reçues d'un serveur primaire.
* **Negative Cache TTL**	Durée de vie, en cache d'un serveur n'ayant  pas d'autorité sur la zone.

include::../../../../adoc/libs/slide-notitle.adoc[]

* **IN**	: Désigne l'allocation. Commande utilisé pour attribuer les valeurs aux options.
* **NS**	: Pour définir le nom du serveur de nom de la zone.
* **A / AAAA** : Pour attribuer un nom à une machine à partir de son adresse IP V4 ou V6. 
* **MX**	: Pour définir un serveur de messagerie
* **CNAME** : Option pour donner un alias à une machine déjà définis avec A.
* **HINFO**	 : Description d'un hôte, d'une machine.
* **TXT**	: Chaîne de caractères, utilisé pour des commentaires
* **PTR**	: Utilisé dans le fichier de résolution inverse, permet d'associer l'adresse IP à un nom.

== Configuration résolution directe

Le premier fichier (résolution directe) mondomaine.lcl.direct :

* On délègue l'administration de cette zone à root@mondomaine.lcl
* le @ est remplacé par ‘ . ’ dans l'adresse du root

```sh
$TTL 604800
@ IN SOA mondomaine.lcl. root.mondomaine.lcl. (
20080605 ; Serial
604800 ; Refresh
86400 ; Retry
2419200 ; Expire
604800 ) ; Negative Cache TTL
; Serveur de noms
@ IN NS mondomaine.lcl.
; Les serveurs
www IN A 192.168.1.10
mail IN A 192.168.1.10
mail IN MX 10 mail.mondomaine.lcl.
```

== Configuration résolution indirecte


Le deuxième fichier (résolution inverse) mondomaine.lcl.reverse

```sh
$TTL 604800
1.168.192.in-addr.arpa IN SOA mondomaine.lcl. root.mondomaine.lcl. (
20080605 ; Serial
604800 ; Refresh
86400 ; Retry
2419200 ; Expire
604800 ) ; Negative Cache TTL
; Serveur de noms
@ IN NS mondomaine.lcl.
; Les machines et les serveurs
10 IN PTR mail.mondomaine.lcl.
10 IN PTR www.mondomaine.lcl.
```

== Opérations post-configurations

=== redémarrer le serveur DNS

** Sous RedHat et Fedora : `/etc/rc.d/init.d/bind9 start`
** Sous Debian : `/etc/init.d/bind9 start`

=== inscrire le serveur comme DNS préféré des machines clientes.

* Pour les machines du réseau sous Windows :
** Allez dans Connexions Réseaux
** Entrer dans les propriétés du réseau local
** Choisir Protocole internet TCP/IP
** Saisir l’IP du  serveur DNS dans les champs requis
** Valider toutes ses modifications
* Pour les machines du réseau sous Linux, il s'agit d'éditer le fichier /etc/resolv.conf 

```sh
search mondomaine.lcl
nameserver 192.168.37.240
```

**Le serveur lui-même doit aussi être configuré comme son propre client.**

== Tests de configuration

=== nslookup

* Fonction : Permet de retrouver l’adresse IP associée à un nom de domaine, et inversement.
* Spécificité : Utilisable sur le réseau configuré, interroge par défaut le premier serveur DNS spécifié dans la configuration réseau.
* Remarque : Obsolète sous UNIX mais toujours pertinent sous Windows.

=== dig

Fonction : Similaire à nslookup mais offre plus de flexibilité dans le choix des types de requêtes DNS (par exemple, MX pour les enregistrements de messagerie).

// tag::demo[]

== Démonstration

[NOTE.speaker]
--
**faire l’installation et la configuration d’un serveur DNS sur Linux **
--

// end::demo[]

// end::deroulement[]