:titre: Introduction au VLan
:module: Réseau
:duree: 120
:description: 
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]


== Objectifs pédagogiques

// tag::objectifs[]
* Comprendre le concept et les avantages des VLAN
* Maîtriser les bases techniques et le fonctionnement des VLAN
* Assurer la sécurité et la configuration des VLAN 
// end::objectifs[]

// tag::deroulement[]

== Un Vlan c'est quoi ?

Un VLAN (Virtual Local Area Network) est un réseau logique créé sur une infrastructure réseau physique. 

* Permet de diviser un réseau en plusieurs sous-réseaux distincts,
* chacun ayant ses propres règles et ses propres utilisateurs, tout en utilisant le même matériel physique.

=== Segmentation réseau

Le VLAN introduit une segmentation logique dans le réseau. 

* Chaque VLAN agit comme un réseau autonome, 
* avec son propre domaine de diffusion, 
* empêchant le trafic entre VLANs sans un routeur ou un switch de niveau 3.

=== Communication inter-VLAN

Pour que des dispositifs dans des VLANs différents communiquent entre eux, un routeur ou un commutateur de niveau 3 est nécessaire pour effectuer le routage inter-VLAN.

=== Isolation des flux de données

Les VLANs offrent une isolation du trafic réseau, ce qui permet d'éviter la propagation de broadcast et d'améliorer les performances réseau.

== Avantages des VLAN

* **Sécurité accrue** : Isoler des groupes de travail ou des départements spécifiques, empêchant ainsi l'accès non autorisé entre eux.
* **Meilleure gestion** : Simplifient la gestion des utilisateurs en fonction de leurs rôles ou départements, facilitant les politiques de sécurité et de gestion.
* **Réduction de la congestion** : En séparant les réseaux logiques, on peux mieux contrôler et isoler le trafic pour éviter qu'un segment ne surcharge le réseau global.

=== Pourquoi utiliser des VLANs ?

* **Segmentation fonctionnelle** : Séparer les utilisateurs selon leurs fonctions, par exemple un VLAN pour les RH et un autre pour la comptabilité.
* **Gestion simplifiée** : Faciliter la gestion des groupes de travail dans les grandes entreprises avec des départements distincts.
* **Réduction de la congestion réseau** : En isolant les différents types de trafic (données, voix, gestion), vous évitez que tout le trafic ne passe par les mêmes canaux.

== Notions fondamentales Vlan

=== Broadcast Domain (Domaine de diffusion)

* Sans VLANs, un switch transmet les trames de diffusion à tous les périphériques connectés. Chaque trame de diffusion (comme ARP, DHCP Discover) traverse l’ensemble du réseau.
* **Impact des VLANs** : Chaque VLAN devient un domaine de diffusion distinct, empêchant les broadcasts de se propager au-delà du VLAN auquel ils appartiennent.

=== Collision Domain (Domaine de collision)

Un domaine de collision est une section du réseau où les trames peuvent entrer en collision. Avec les VLANs, chaque port de switch dans un VLAN est dans un domaine de collision distinct, réduisant ainsi les conflits.

== Fonctionnement des VLAN

=== Balise VLAN (Tagging) :

* Dans les VLANs, chaque trame qui circule à travers un lien trunk (vu plus tard) est taguée avec un identifiant VLAN (802.1Q). Ce tag contient des informations sur le VLAN d'origine de la trame.
* **Importance du tag VLAN** : Le tag VLAN aide les switches à savoir à quel VLAN appartient une trame lorsqu'elle traverse des liens partagés, notamment entre plusieurs switches.

=== Ports VLAN :

* **Port en mode access** : Un port configuré en mode access appartient à un seul VLAN et ne traite pas les trames avec des tags VLAN.
* **Port en mode trunk** : Un port trunk peut transporter le trafic de plusieurs VLANs, chaque trame étant taggée avec son identifiant VLAN.

=== Encapsulation VLAN (802.1Q) :

Le standard **IEEE 802.1Q** définit comment ajouter des tags VLAN aux trames Ethernet. L'encapsulation insère un champ de 4 octets dans l'en-tête Ethernet qui contient l'identifiant VLAN et des informations de priorité.

== Types de Vlan

=== VLAN de données

Utilisé pour séparer le trafic des utilisateurs finaux. Exemple un VLAN pour les employés de l'entreprise.

=== VLAN de gestion

* Conçu pour la gestion des équipements réseau (switches, routeurs).
* Garder le trafic de gestion séparé du trafic utilisateur pour une sécurité renforcée.

=== VLAN voix

* Dédié au trafic VoIP (Voice over IP) pour garantir une meilleure qualité de service .
* Les appels voix étant sensibles à la latence, il est important d’isoler ce trafic des autres types de données.

=== VLAN natif

VLAN utilisé par défaut sur un lien trunk lorsqu’une trame n’est pas marquée (non taggée).
Le VLAN natif est souvent défini comme le VLAN par défaut d'un switch, mais il est recommandé de changer ce paramètre pour des raisons de sécurité.

== Sécurité des Vlan

=== Isolation des VLANs

* Les VLANs agissent comme des réseaux indépendants,
* Sans routage inter-VLAN, les dispositifs dans des VLANs différents ne peuvent pas communiquer.
* Cela renforce la sécurité interne, limitant les mouvements latéraux d'attaquants dans le réseau.

=== Politiques de sécurité au niveau VLAN

* **Contrôle d'accès :**
** L'utilisation d'ACL (Access Control List) au niveau du switch ou du routeur permet de filtrer les communications entre les VLANs.
* **Rôles et permissions :**
** Chaque VLAN peut être associé à des niveaux de permissions spécifiques en fonction des besoins de l'entreprise.

=== Attaques VLAN hopping

* **VLAN hopping** 
** technique où un attaquant exploite les mauvaises configurations de port trunk pour accéder à des VLANs non autorisés.
* **Solution** : 
** Configurer correctement les trunks, limiter les VLANs autorisés sur les liens trunk, et désactiver le mode trunk sur les ports inutilisés.

=== Trames non taggées (VLAN natif)

* Les trames non taggées peuvent être transmises sur le VLAN natif, ce qui peut représenter un risque si le VLAN natif est mal configuré.
* **Recommandation** : Ne jamais utiliser le VLAN 1 comme VLAN natif, et toujours le configurer de manière explicite pour éviter les vulnérabilités.

== Configuration Vlan Switch Cisco

**Accéder au mode de configuration sur le switch :**

Passez en mode administrateur : `Switch> enable`

Cette commande permet de passer du mode utilisateur (limité) au mode administrateur, où des configurations avancées peuvent être effectuées.

include::../../../../adoc/libs/slide-notitle.adoc[]

**Entrer en mode de configuration globale :**

Passez au mode de configuration du switch : `Switch# configure terminal`

En mode de configuration globale, vous pouvez apporter des changements à la configuration du switch entier, y compris la gestion des VLANs.

include::../../../../adoc/libs/slide-notitle.adoc[]

**Créer un VLAN spécifique :**

Création du VLAN 10 : `Switch(config)# vlan 10`

Cette commande crée un VLAN avec l'ID 10 sur le switch. Le VLAN 10 n’est qu’un conteneur logique à ce stade, il n’a pas encore de ports attribués.

include::../../../../adoc/libs/slide-notitle.adoc[]

**Nommer le VLAN :**

Donner un nom explicite au VLAN : `Switch(config-vlan)# name Comptabilité`

Cette commande associe un nom descriptif au VLAN, facilitant la gestion future du réseau en permettant d'identifier rapidement les VLANs.

include::../../../../adoc/libs/slide-notitle.adoc[]

**Affecter un port au VLAN :**

Spécifiez quel port du switch doit appartenir à ce VLAN :

```sh
Switch(config)# interface fastethernet 0/1
```

Sélection du port `FastEthernet 0/1` pour le configurer.

```sh
Switch(config-if)# switchport mode access
```

Met le port en mode access, signifiant qu'il sera affecté à un seul VLAN.

```sh
Switch(config-if)# switchport access vlan 10
```

Associe le port au VLAN 10.

include::../../../../adoc/libs/slide-notitle.adoc[]

**Vérification de la configuration des VLAN  :**

```sh
show vlan brief
```

include::../../../../adoc/libs/slide-notitle.adoc[]

Désactiver le mode trunk sur les ports inutilisés

```sh
Switch(config)# interface range fastethernet 0/1 - 24
```

```sh
Switch(config-if-range)# switchport mode access
```

```sh
Switch(config-if-range)# switchport nonegotiate
```

Cette série de commandes configure une gamme de ports en mode access et désactive le mode négociation du trunking (ce qui empêche la communication sur des liens non sécurisés).

// tag::demo[]

== Démonstration

[NOTE.speaker]
--
avec packet tracer prendre un switch et rejouer les commandes de création d’un vlan exemple de scénario

`Switch> enable`

`Switch# show interface` montrer les interfaces du switch 

`Switch# show vlan brief` Montrer les Vlan présent et insister sur le Vlan 1 par défaut 

`Switch# configure terminal`  Entrer en mode de configuration globale 

`switch(config)# vlan 10` Créer un VLAN

`Switch(config-vlan)#name info`  nommer le vlan

`Switch(config-vlan)# interface fastethernet 0/1` intégrer l’interface 0/1 

`Switch(config-if)#switchport mode access` 

`Switch(config-if)#switchport access vlan 10`

`Switch(config-if)#exit`

`Switch# show vlan brief` Montrer les Vlans

créer un second vlan, attribution des interface avec la commande range 

```sh
enable 
configure terminal
vlan 50 
interface range FastEthernet 0/11 - 20 
switchport mode access 
switchport access vlan 50 
exit
```

`Switch# show vlan brief` Montrer les Vlans
--

// end::demo[]

// end::deroulement[]

== Conclusion
// tag::conclusion[]
* Les VLANs segmentent un réseau physique en réseaux logiques distincts, offrant isolation, sécurité, et performances améliorées.
* Il existe différents types de VLANs (données, gestion, voix, natif), chacun ayant un rôle spécifique dans la gestion du réseau.
* L'utilisation de VLANs doit être accompagnée de bonnes pratiques de sécurité pour éviter des vulnérabilités comme le VLAN hopping.
// end::conclusion[]