:titre: Service NTP y compris Windows
:module: Réseau
:duree: 120
:description: Comprendre le protocole NTP et sa mise en place sur les OS
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]


== Objectifs pédagogiques

// tag::objectifs[]
* Comprendre le rôle du protocole NTP et ses sources de temps
* Configurer un serveur NTP sur différents OS
* Assurer la gestion et le maintien de la synchronisation NTP
// end::objectifs[]

// tag::deroulement[]

== Présentation

**NTP** (Network Time Protocol) :

* Protocole publié en septembre 1985, documenté dans la **RFC 958**.
* Développé grâce aux travaux du professeur **David L. Mills**.
* Depuis **2010**, NTP est dans sa **quatrième version**, référencée par la **RFC 5905**.

=== Objectifs

* Synchronisation de l'horloge locale d'une machine via le réseau.
* Utilisation d'une machine de référence, appelée **serveur NTP**.

=== Caractéristiques techniques :

Utilise le **protocole de transport UDP** et fonctionne sur le **port 123**.

=== Serveur NTP (serveur de temps) :

* Distribue la date et l'heure aux postes clients.

=== Organisation multi-niveaux :

* Permet de diffuser la date et l'heure mondialement.
* Assure l'équilibrage de charge.
* Améliore la réactivité de la synchronisation.

== A quoi sert NTP ?

* **Fonction dans le système d'information :**
** Permet aux équipements (ordinateurs, serveurs, imprimantes, routeurs, pare-feu) de rester à l'heure.
* **Importance de la synchronisation :**
** Une mauvaise synchronisation peut causer des problèmes, notamment en matière d'**authentification** (validité des jetons d'authentification, etc.).
* **Consultation des journaux (logs) :**
** Des logs correctement horodatés facilitent leur analyse et évitent les complications.
** Critique pour l'**archivage légal** des logs, où l'heure et la date doivent être correctes.

== Quelle source de temps utiliser ?


* **Choix de l'horloge de référence :**
** Dépend de l'environnement utilisé.
* **Cas de Windows :**
** Par défaut, utilise la source de temps `time.windows.com`.
** Si l'ordinateur rejoint un domaine **Active Directory**, il se synchronise avec le **contrôleur de domaine (PDC)** pour la cohérence horaire dans le domaine.
* **Synchronisation du contrôleur de domaine :** 
** Peut être configuré pour utiliser une source de temps personnalisée.
** Exemple : les serveurs du **"NTP Pool Project"** avec `fr.pool.ntp.org` pour des serveurs NTP français redondés.

include::../../../../adoc/libs/slide-notitle.adoc[]

* **Équipements réseaux (switchs) :**
** La configuration manuelle des serveurs de temps est nécessaire.
** Par défaut, ces équipements ont souvent une date d'usine

== Configurer NTP sur Windows

* **Ouvrir l’éditeur de registre**
* **Accéder au chemin NtpServer**
** **Ordinateur > HKEY_LOCAL_MACHINE > SYSTEM > CurrentControlSet > Services > W32Time > TimeProviders > NtpServer**
* **Activer Ntp Server**
** Éditer l’entrée « Enabled ».
** Modifiez la valeur « Données de valeur » de 0 à 1.
** Valider

include::../../../../adoc/libs/slide-notitle.adoc[]

* **Modifier AnnounceFlags**
** **Ordinateur > HKEY_LOCAL_MACHINE > SYSTEM > CurrentControlSet > Services > W32Time > Config**
** Éditer l’entrée « AnnounceFlags ».
** Modifier la valeur « Données de valeur » à 5.

=== Explication des valeurs

* **0 (0x00)** : Le serveur ne s'annonce pas.
* **1 (0x01)** : S'annonce comme **serveur de temps**, non fiable.
* **3 (0x03)** : S'annonce comme **disponible** mais **non fiable**.
* **4 (0x04)** : Rarement utilisé, indique un comportement spécifique.
* **5 (0x05)** : S'annonce comme **fiable et autoritaire**, source de temps principale.
* **8 (0x08)** : S'annonce comme **contrôleur de domaine**.
* **10 (0x0A)** : S'annonce comme **contrôleur de domaine fiable**, offrant la synchronisation.

include::../../../../adoc/libs/slide-notitle.adoc[]

* **Redémarrer NtpServer**
** Redémarrer le service  « Windows Time »
* **Ouvrir le port UDP 123 dans le pare-feu**

=== Configuration via PowerShell

**Activer Ntp Server :**

```powershell
Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\w32time\TimeProviders\NtpServer" -Name "Enabled" -Value 1
```

**Modifier AnnounceFlags :**

```powershell
Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\services\W32Time\Config" -Name "AnnounceFlags" -Value 5
```

**Redémarrer NtpServer :**

```powershell
Restart-Service w32Time
```

== Configurer NTP sur Linux

Sur linux pour mettre en place le service NTP il faut : 

Mettre à jour la liste de paquets :

```sh
apt-get update
```

Installer le paquet ntp : Utiliser un compte super-utilisateur ou utiliser **sudo**.

```sh
apt-get install ntp
```

=== Arrêter - Démarrer le service NTP

Démarrer le service NTP :

```sh
/etc/init.d/ntp start
```

Arrêter le service NTP :

```sh
/etc/init.d/ntp stop
```

=== Configuration du serveur NTP

Fichier de configuration : `/etc/ntp.conf` ou `/etc/xntp.conf` selon la distribution de Linux

```sh
# Serveurs NTP de référence
server 0.ubuntu.pool.ntp.org iburst
server 1.ubuntu.pool.ntp.org iburst
server 2.ubuntu.pool.ntp.org iburst
server 3.ubuntu.pool.ntp.org iburst

# Drift file pour corriger la dérive de l'horloge locale
driftfile /var/lib/ntp/ntp.drift

# Restriction d'accès : autoriser uniquement le réseau local
restrict default kod nomodify notrap nopeer noquery
restrict 127.0.0.1
restrict ::1
restrict 192.168.1.0 mask 255.255.255.0 nomodify notrap

# Diffusion de l'heure pour le réseau local
broadcast 192.168.1.255

# Configuration de logs
logfile /var/log/ntp.log

# Options supplémentaires pour un meilleur contrôle
# Pour limiter le nombre de serveurs NTP à synchroniser en cas de surcharge
tos maxclock 5
```

[NOTE.speaker]
--
* **server ... iburst** : Spécifie les serveurs NTP avec l'option iburst, qui accélère la synchronisation initiale.
* **driftfile** :  Stocker la dérive de l'horloge locale pour permettre au service NTP de corriger la fréquence de l'horloge et maintenir une synchronisation précise.
* **restrict** : Définit les règles de restriction pour limiter l'accès à certaines adresses IP ou réseaux.
* **broadcast** : Permet de diffuser l'heure à tous les appareils sur le réseau local.
* **logfile** : Spécifie l'emplacement du fichier de logs pour suivre les activités du service NTP.
* **tos maxclock** : Limite le nombre de serveurs utilisés simultanément pour la synchronisation.
--

=== Redémarrer le service NTP

Commande pour redémarrer le serveur NTP : `/etc/init.d/ntp restart`

// tag::demo[]

== Démonstration

[NOTE.speaker]
--

**Sur un windows serveur :**

* Ouvrir l’éditeur de registre
* Accéder au chemin NtpServer
** **Ordinateur > HKEY_LOCAL_MACHINE > SYSTEM > CurrentControlSet > Services > W32Time > TimeProviders > NtpServer**
* Activer Ntp Server
** Éditer l’entrée « Enabled ».
** Modifiez la valeur « Données de valeur » de 0 à 1.
** Valider
* Modifier AnnounceFlags
** **Ordinateur > HKEY_LOCAL_MACHINE > SYSTEM > CurrentControlSet > Services > W32Time > Config**
** Éditer l’entrée « AnnounceFlags ».
** Modifier la valeur « Données de valeur » à 5.
* relancer le service W32Time

```powershell
Restart-Service w32Time
```

**cette démo peut également être faite coté linux**

Mettre à jour la liste de paquets :

```sh
apt-get update
```

Installer le paquet ntp : Utiliser un compte super-utilisateur ou utiliser **sudo**.

```sh
apt-get install ntp
```

Fichier de configuration : `/etc/ntp.conf` ou `/etc/xntp.conf` selon la distribution de Linux

```sh
# Serveurs NTP de référence
server 0.ubuntu.pool.ntp.org iburst
server 1.ubuntu.pool.ntp.org iburst
server 2.ubuntu.pool.ntp.org iburst
server 3.ubuntu.pool.ntp.org iburst

# Drift file pour corriger la dérive de l'horloge locale
driftfile /var/lib/ntp/ntp.drift

# Restriction d'accès : autoriser uniquement le réseau local
restrict default kod nomodify notrap nopeer noquery
restrict 127.0.0.1
restrict ::1
restrict 192.168.1.0 mask 255.255.255.0 nomodify notrap

# Diffusion de l'heure pour le réseau local
broadcast 192.168.1.255

# Configuration de logs
logfile /var/log/ntp.log

# Options supplémentaires pour un meilleur contrôle
# Pour limiter le nombre de serveurs NTP à synchroniser en cas de surcharge
tos maxclock 5
```

**Arrêter - Démarrer le service NTP**

Démarrer le service NTP :

```sh
/etc/init.d/ntp start
```

Arrêter le service NTP :

```sh
/etc/init.d/ntp stop
```
--

// end::demo[]

// end::deroulement[]

== Conclusion
// tag::conclusion[]
* **Synchronisation** : Permet de maintenir une horloge uniforme et précise à travers l'ensemble du réseau, évitant les erreurs dues à des désynchronisations.
* **Dérive de l'horloge** : Le fichier de dérive (comme ntp.drift) est utilisé pour ajuster l'horloge locale et compenser les variations naturelles de l'horloge matérielle.
* **Sécurité et restrictions** : La configuration peut inclure des restrictions d'accès pour contrôler quels appareils peuvent interroger ou se synchroniser avec le serveur NTP, garantissant ainsi un niveau de sécurité adapté.

include::../../../../adoc/libs/slide-notitle.adoc[]

* **Fiabilité** : L'utilisation de multiples serveurs de temps garantit une redondance et une précision accrue, permettant de continuer à fonctionner même si l'un des serveurs de référence devient indisponible.
* **Diffusion de l'heure** : NTP peut également servir à transmettre l'heure à d'autres appareils du réseau, facilitant la synchronisation au sein d'une infrastructure locale.
// end::conclusion[]