:title: Scalabilité et maintenance des applications avec GraphQL
:number: 04 
include::../../../../../../adoc/libs/header-episode.adoc[]

// tag::intro[]
Dans ce dernier épisode, l'accent est mis sur la scalabilité et la maintenance des applications en production avec Apollo Server. Les apprenants découvriront comment structurer leur application pour répondre à de fortes charges et assurer la durabilité de l’architecture. 
// end::intro[]

== Objectifs pédagogiques

// tag::objectifs[]
Comprendre les principes de scalabilité et de durabilité des applications GraphQL
Optimiser la structure des applications pour des charges de données importantes
Gérer la sécurité des requêtes et configurer les autorisations d’accès
Monitorer et tester les performances de GraphQL sous Docker
Maîtriser l’architecture d’Apollo Server pour une maintenance facilitée 
// end::objectifs[]

== Prérequis formateur

// tag::prerequis[]
Connaissance des concepts de scalabilité pour les API
Maîtrise des concepts de sécurité et autorisations en GraphQL
Expérience dans le déploiement et le monitorage d’applications sous Docker
Compétences pédagogiques 
// end::prerequis[]

== Déroulement

// tag::deroulement[] 
:correction: https://github.com/Oclock-CDA/S07-Challenge/tree/04-Challenge-D04-Correction
:temps: jusqu'à 60 minutes
:description: Passer du temps à bien corriger le challenge d'hier.
include::../../../../../../adoc/libs/intro-correction.adoc[]

TIP: ☕ Pause café

include::../../../../modules/GraphQL/09DataSources.adoc[options=modules]

TIP: 🍕 Pause déjeuner

include::../../../../modules/GraphQL/10BatchingAndCaching.adoc[options=modules]

:challenge: :description: Configurer une application GraphQL évolutive et sécurisée en production 
include::../../../../../../adoc/libs/intro-challenge.adoc[]
// end::deroulement[]