:title: Introduction à GraphQL et aux bases de données orientées graphes
:number: 01 
include::../../../../../../adoc/libs/header-episode.adoc[]

// tag::intro[]
Cet épisode introduit les concepts de base de GraphQL et des bases de données orientées graphes, en les comparant aux API REST. Les apprenants découvriront l'installation d'un projet Apollo Server sous Docker et créeront leurs premières requêtes simples avec GraphQL. 
// end::intro[]

== Objectifs pédagogiques

// tag::objectifs[]
Comprendre les concepts de GraphQL et ses différences avec REST
Découvrir les bases de données orientées graphes et leur utilité
Installer Apollo Server sous Docker
Créer et exécuter des requêtes simples en GraphQL
Se familiariser avec les outils graphiques de développement pour GraphQL 
// end::objectifs[]

== Prérequis formateur

// tag::prerequis[]
Maîtrise des concepts de base des API REST et des langages de requêtes
Bonne connaissance de JavaScript et de Node.js
Expérience en développement d’API et utilisation de Docker
Compétences pédagogiques 
// end::prerequis[]

== Déroulement

// tag::deroulement[] 

include::../../../../modules/GraphQL/01IntroductionGQ.adoc[options=modules]

TIP: ☕ Pause café

include::../../../../modules/GraphQL/02Installation.adoc[options=modules]

include::../../../../modules/GraphQL/04TypesAndResolvers.adoc[options=modules]

TIP: 🍕 Pause déjeuner

:challenge: https://github.com/Oclock-CDA/S07-Challenge/blob/main/documentation/challenges/D01.md
:description: Créer un schéma simple avec Apollo Server et interroger des données de base 
include::../../../../../../adoc/libs/intro-challenge.adoc[]
// end::deroulement[]
