:titre: Création de Modules, Controlleurs, Providers et autres joyeusetés
:module: nestJs
:duree: 60
:description: Comprendre la Création de Modules, Controlleurs, Providers et autres joyeusetés
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../adoc/libs
endif::[]

== Objectifs pédagogiques
// tag::objectifs[]
* **Comprendre** l'architecture modulaire de NestJS
* **Comprendre** la différence entre Providers et Services
* **Appliquer** l'injection de dépendances dans NestJS
* **Créer** des modules, contrôleurs et services fonctionnels
// end::objectifs[]


// tag::deroulement[]
== Modularité

Dans ce chapitre, nous verrons la création d'un module complet, qui inclue le module à proprement parler, ainsi qu'un contrôleur et d'autres fichiers.

Un des avantages de NestJS, c'est sa CLI, nous allons nous en servir pour générer les fichiers et les relier au module principal (racine) de l'application.

== Les modules

Dans NestJS, un module est une unité de structure qui organise et encapsule un ensemble de fonctionnalités, telles que des contrôleurs et des services, facilitant la gestion et la réutilisabilité du code.

[NOTE.speaker]
--
On les branche dans le module racine de l'application ou dans un autre module pour bénéficier de leur fonctionnalité.
--

== Options de la CLI

La CLI est remplie d'options, pour les voir, il faut taper la commande :

[source,bash]
----
nest g --help
----

[NOTE.speaker]
--
On parle de quelques commandes et à quoi elles servent
--

// tag::demo[]
== Démonstration 01

Creation de modules

[NOTE.speaker]
--
*Creation de modules*

On peut créer un module ainsi :

[source,bash]
----
nest generate module notes
----

La commande génère un répertoire `notes`, et dans ce répertoire notre module avec du code boilerplate.

La commande a également modifié le module principal de l'app : `/src/app.module.ts` pour y inclure le module fraîchement créer. 

Ouvrons les fichiers et lisons le code pour comprendre.

*Les contrôleurs*

La responsabilité des contrôleurs NestJS est la même que dans Express, mais ils sont liés à un chemin spécifique : `/notes` pour la ressource `notes`, respectant ainsi les principes d'une API RESTful.

Les contrôleurs peuvent profiter de l'injection de dépendances pour utiliser des providers du même module ou d'un autre module.

Les contrôleurs sont définis en utilisant le décorateur `@Controller`, ce décorateur accepte une string qui représente la route qui actionnera le contrôleur.

[source,typescript]
----
@Controller('notes')
export class NotesController {}
----

*Les contrôleurs*

Expliquer le code du contrôleur puis en créer un.

Les contrôleurs font aussi usage de décorateurs pour spécifier le type de routes qu'ils vont gérer, voici un exemple de contrôleurs avec une route `GET`.

On va en créer un dans une minute :

[source,typescript]
----
@Controller('notes')
export class NotesController {
    @Get()
    getNotes() {}
}
----

Notez que la requête sera routé automatiquement vers le bon contrôleur.

*Création d'un contrôleur*

[source,bash]
----
nest g controller notes --no-spec
----

On dit `--no-spec` pour ne pas créer de fichiers de tests (on verra les tests plus tard).

Le contrôleur a été créé et le fichier `notes.module.ts` a été mis à jour pour inclure le contrôleur.

À nous de créer les routes correspondantes avec des décorateurs.

[source,typescript]
----
@Controller('notes')
export class NotesController {
    // /notes
    @Get()
    index() {}
}
----
--
// end::demo[]

== Les Providers

Dans NestJS, un provider est une classe ou une valeur injectable qui encapsule une logique métier ou une dépendance, permettant son utilisation dans différentes parties de l'application grâce au système d'injection de dépendances.

== Les Services

Dans NestJS, un service est une classe qui contient la logique métier de l'application et est généralement injectée dans les contrôleurs ou autres services pour gérer les opérations nécessaires à l'exécution des fonctionnalités.

== Différences entre providers et service ?

En résumé, un service est un type de provider utilisé principalement pour la logique métier, tandis que "provider" est un terme plus large pour tout ce qui peut être injecté dans l'application.

[NOTE.speaker]
--
Dans NestJS, la différence entre un provider et un service réside principalement dans leur rôle et leur portée d'utilisation :

Provider est un terme générique pour désigner toute classe ou valeur qui peut être injectée dans d'autres parties de l'application via le système d'injection de dépendances. Tous les services, répositories, et autres dépendances sont des providers dans NestJS.

Service est un type spécifique de provider qui contient généralement la logique métier de l'application. Bien que tous les services soient des providers, tous les providers ne sont pas nécessairement des services (par exemple, un provider pourrait être un repository de données ou une valeur de configuration).

En résumé, un service est un type de provider utilisé principalement pour la logique métier, tandis que "provider" est un terme plus large pour tout ce qui peut être injecté dans l'application.

Les providers peuvent être des classes, ou des valeurs que l'on doit importer dans un module pour pouvoir s'en servir.

Les services sont implémentés en utilisant des providers.

Les services sont la source de https://en.wikipedia.org/wiki/Business_logic[la logique dite 'business'] (ou _logique métier_), c'est-à-dire, ils vont valider des données, créer des ressources dans la BDD et retourner des réponses (qui auraient besoin d'être calculé par exemple).

On pourrait imaginer un contrôleur qui importe plusieurs services, par exemple le service `Note` pour gérer la ressource `notes` et le service `Logger` qui enregistre les actions qui ont été effectuées.
--

== L'injection de dépendances

Rend le code plus modulable et plus facile à tester

[NOTE.speaker]
--
L'injection de dépendances est un concept qui consiste à fournir automatiquement à une classe les objets dont elle a besoin pour fonctionner, plutôt que de les créer elle-même. Cela rend le code plus modulable et facile à tester, car les dépendances sont "injectées" de l'extérieur, souvent par le framework (comme NestJS).
--

== L'injection de dépendances

Quand on a besoin d'ajouter des fonctionnalités à une classe, on a deux solutions :

* on utilise l'héritage si les classes peuvent être liées,
* ou l'injection de dépendance : on passe une instance d'une classe dans le constructeur d'un autre objet.

== L'injection de dépendances

`@Injectable`

[NOTE.speaker]
--
Avec NestJS, on utilise le décorateur `@Injectable` sur les providers pour les rendre injectables, à partir de là, on les importe dans un module et on pourra les rendre disponibles dans nos contrôleurs en les référençant dans le constructeur.
--

[NOTE.speaker]
--
Éventuellement, refaire une démo d'injection de dépendances from scratch.
--

// tag::demo[]
== Démonstration 02

Injection de dépendance

[NOTE.speaker]
--
*La creation et l'injection de services*

En créant le service notes, on va ajouter une fonctionnalité qui permet de gérer les notes. Le contrôleur associé sera capable de s'en servir, car le service sera décoré avec le tag `@Injectable`.

`nest g service notes --no-spec`

Le service a été créé et le module notes a été mis à jour, on voit dans le module que le service a été défini en tant que provider, on peut donc l'injecter dans le constructeur du contrôleur et s'en servir dans une méthode, on est dans le domaine de la POO classique :

[source,typescript]
----
@Controller('notes')
export class NotesController {
    notesService: NotesService;
    constructor(notesService: NotesService) {
        this.notesService = notesService;
    }
    @Get()
    index() {
        console.log(this.notesService);
    }
}
----

*L'injection de services : syntaxe simplifiée*

On peut raccourcir cette syntaxe grâce à `typescript`, en disant au constructeur que `NotesService` est privée. `NestJS` et `typescript` vont se servir de cette information pour relier automatiquement le service et le constructeur.

Ainsi, on assigne implicitement une valeur a une propriété membre du contrôleur.

*L'injection de services : syntaxe simplifiée*

Voici notre contrôleur après ces modifications :

[source,typescript]
----
@Controller('notes')
export class NotesController {
    constructor(private notesService: NotesService) {}
    @Get()
    index() {
        console.log(this.notesService);
    }
}
----

L'air de rien, on avance, on a une route avec un contrôleur prêt à gérer des ressources, et tout ce qu'on a fait, c'est quelque lignes de commande.
--
// end::demo[]


// tag::exercice[]
== Exercice

1. Créer un module `categories`
2. Créer un contrôleur `categories`
3. Créer un service `categories`
4. Injecter le service `categories` dans le controller `categories`
5. Le service doit implémenter une méthode qui retourne un `tableau de catégories` de produits (jeux videos, électroménager etc), on le console.log() dans le terminal
6. Faire la même chose avec un module `products`
7. Testez les routes correspondantes

[NOTE.speaker]
--
*Solutions*

* Créer un module `categories`
** `nest g module categories`
* Créer un contrôleur `categories`
** `nest g controller categories --no-spec`
* Créer un service
** `nest g service categories --no-spec`
* Injecter le service `categories` dans le controller `categories`
+
[source,typescript]
----
import { Controller, Get } from '@nestjs/common';
import { CategoriesService } from './categories.service';

@Controller('categories')
export class CategoriesController {
  constructor(private categoriesService: CategoriesService) {}
  @Get()
  index() {
    console.log(this.categoriesService.findAll);
  }
}
----

* Le service doit implémenter une méthode qui retourne un `tableau de catégories` de produits (jeux videos, électroménager, etc), on le `console.log()` dans le terminal :
+
[source,typescript]
----
import { Injectable } from '@nestjs/common';

@Injectable()
export class CategoriesService {
  findAll(): string[] {
    return ['Jeux vidéos', 'Chaussures', "Sports d'hiver"];
  }
}
----

* Faire la même chose avec un module `products`:

** `nest g module products`
** `nest g controller products --no-spec`
** `nest g service products --no-spec`
+
[source,typescript]
----
import { Controller, Get } from '@nestjs/common';
import { ProductsService } from './products.service';

@Controller('products')
export class ProductsController {
  constructor(private productsService: ProductsService) {}

  @Get()
  index() {
    console.log(this.productsService.findAll());
  }
}
----
+
[source,typescript]
----
import { Injectable } from '@nestjs/common';

@Injectable()
export class CategoriesService {
  findAll(): string[] {
    return ['Jeux vidéos', 'Chaussures', "Sports d'hiver"];
  }
}
----

* Tester les routes correspondantes
** http://localhost:3000/categories[]
** http://localhost:3000/products[]
--
// end::exercice[]

// end::deroulement[]

== Conclusion
// tag::conclusion[]
* Maîtrise de la création de modules NestJS et leurs composants
* Compréhension du rôle des contrôleurs et leur interaction avec les services
* Capacité à implémenter l'injection de dépendances
* Aptitude à organiser le code de manière modulaire et maintenable
* Maîtrise des commandes CLI pour générer les différents composants
// end::conclusion[]

