:title: Modélisation NoSQL et pipeline d’agrégation
:number: 02
include::../../../../../../adoc/libs/header-episode.adoc[]

// tag::intro[]
Journée sur la modélisation NoSQL et les pipelines d’agrégation. Les participants apprendront à concevoir des modèles de données adaptés aux bases de données NoSQL, en tenant compte des spécificités de chaque type de base (documentaire, clé-valeur, colonnes larges, graphes). La formation couvrira également les techniques avancées d’agrégation pour extraire et transformer les données efficacement. Des exercices pratiques permettront aux participants de mettre en œuvre ces concepts à l’aide de bases de données NoSQL populaires telles que MongoDB et Cassandra.
// end::intro[]

== Objectifs pédagogiques

// tag::objectifs[]
* Comprendre comment modéliser un projet NoSQL.
* Utiliser les opérations avancées d’agrégation.
// end::objectifs[]

== Prérequis formateur

// tag::prerequis[]
* Avoir une bonne connaissance des bases de données NoSQL et de leurs types.
* Maîtriser les concepts de modélisation des données et les techniques d’agrégation.
* Être capable de guider les participants dans la conception de modèles NoSQL adaptés à différents cas d’utilisation.
// end::prerequis[]

== Déroulement

// tag::deroulement[]
:correction: 
:temps: 60 minutes
:description: 
include::../../../../../../adoc/libs/intro-correction.adoc[]




:challenge: https://github.com/O-clock-Formations-courtes/GoChallenge
:description: Création d'une application de quizz en Go
:correction: 
include::../../../../../../adoc/libs/intro-challenge.adoc[]

.👨‍🏫 Référent de promo
[.suivi]
[sidebar]
--


--
// end::deroulement[]
