:title: Les fondamentaux
:number: 02
:duration: 14
include::../../../../adoc/libs/header-saison.adoc[]

// tag::intro[]
Cette formation de 2 jours sur le NoSQL permet d’acquérir les compétences nécessaires pour comprendre et utiliser les bases de données NoSQL dans le développement d’applications modernes. Les participants découvriront les concepts fondamentaux des bases de données NoSQL, les différents types de bases de données (documentaires, clé-valeur, colonnes larges, graphes), ainsi que les cas d’utilisation appropriés pour chaque type. La formation inclut des exercices pratiques pour manipuler des bases de données NoSQL populaires telles que MongoDB, Cassandra et Redis, et aborde également les meilleures pratiques en matière de modélisation des données, de performance et de scalabilité.
// end::intro[]

== Objectifs pédagogiques

// tag::objectifs[]
* Comprendre les concepts fondamentaux des bases de données NoSQL et leurs différences avec les bases de données relationnelles.
* Explorer les différents types de bases de données NoSQL : documentaires, clé-valeur, colonnes larges et graphes.
* Apprendre à modéliser des données pour les bases de données NoSQL en fonction des cas d’utilisation.
* Manipuler la bases de données NoSQL populaire MongoDB.
// end::objectifs[]

== Notions

// tag::notions[]
* NoSQL
* MongoDB
* Modélisation des données
* CRUD
// end::notions[]

== Prérequis formateur

// tag::prerequis[]
- Savoir utiliser le language NoSQL
// end::prerequis[]

== Résumé

// tag::resume[]
Cette formation de 14 heures couvre les fondamentaux des bases de données NoSQL, y compris les différents types de bases de données, la modélisation des données et les meilleures pratiques pour leur utilisation dans le développement d'applications modernes.
// end::resume[]

== Déroulement

link:./overview.html[Vue kanban]

// tag::deroulement[]
include::episodes/*/*.adoc[opts=episodes]
// end::deroulement[]