:titre: Variables PowerShell
:module: Scripting
:duree: 150
:description: Les variables en PowerShell
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../adoc/libs
endif::[]

== Objectifs pédagogiques
// tag::objectifs[]
* Les structures
* Structure If
* Structure Else
* Structure Else If
* Structure While
* Structure Do While
* Structure Do Until
* Structure ForEach
* Structure ForEach {Break}
* Structure ForEach {Continue}
* Structure Switch
* Structure et imbrication
// end::objectifs[]

// tag::deroulement[]
== Les structures

Il existe plusieurs types de structures couramment utilisées dans les scripts. Nous allons en explorer quelques-unes :

* `If` : la condition 
* `While` : la boucle infinie
* `Foreach` : la boucle dédiée aux objets
* `Switch` : le menu

== Structure `if`

La structure `If` va tester des valeurs grâce à un ou plusieurs opérateurs de comparaison.

Si la condition est validée, `If` renvoie le message `Boolean $True`.

```powershell
 If ($x –eq $y)
  	{
  	Write-Host "Le test est validé $True"  
  	}
```

Dans ce cas-là, les commandes présentent entre les accolades sont exécutées.

Si `If` renvoie `$False`, la ou les commandes ne seront pas exécutées

[.highlight.bg-blue-500.text-white]
====
Algo :
si condition vrai
alors “instruction”
====

== Structure `Else`

La structure `ELSE` permet l’exécution de commandes lorsque le résultat du test est `$False`.

```powershell`
If ($x –eq $y)
  	{
  	Write-Host " Le test est validé $True"  
  	}
Else
  	{
  	Write-Host "Le test n’est pas valide $False’’ 
  	}
```

Si le premier test est `$False`, alors on exécute la commande contenue dans le `Else`.

[.highlight.bg-blue-500.text-white]
====
Algo :
si condition vrai
alors “instruction”
Sinon “instruction”
====

== Structure `ELSE IF`

La structure `Else` permet d'imbriquer les tests afin de créer un second test sur une réponse $False.

[cols="1,1"]
|===
a|
```powershell
If ($x –eq $y)
  	{
  	Write-Host ’’Le test est validé $True’’ 
  	}
ElseIf ($x –eq $z)
  	{
  	Write-Host ’’Le test est validé’ $True’ 
  	}
Else
  	{
  	Write-Host ’’Le test n’est pas validé $False’’ 
  	}
```
a|
[.highlight.bg-blue-500.text-white]
====
Algo :
si condition vrai
alors “instruction”
sinon si condition2 vrai
alors “instruction”
Sinon “instruction”
====
|===

Si le résultat du premier test est `$False`, alors on effectue un second test. Si le second test est `$False` alors on affiche la commande contenue dans le `Else`.

== Structure `WHILE`

La structure `While` permet de boucler sur un bloc de commandes tant que la condition est `$True` :

La boucle `while` est utilisable à condition que la variable de test ici `$x` possède une valeur avant le test.

On doit lui attribuer une valeur pour que la boucle démarre.

Si `$x` est égale à `$Null`, on n’entrera pas dans la boucle.

Donc il faut initialiser la valeur de la variable de test avant la boucle.

[cols="1,1"]
|===
a|
```powershell
$x  = « A » 
While ($x –ne « q » )
  {
  $x = Read-Host « Veuillez faire un choix »
  #Si l’utilisateur saisit la lettre « q » la boucle s’arrête. 
  }
```
a| 
[.highlight.bg-blue-500.text-white]
====
Algo :
Tant que condition vrai
alors “instruction”
====
|===

== Structure `DO WHILE`

La structure Do While contrairement à While, la condition se fait en fin de boucle et non pas en début de boucle, on passe donc obligatoirement dans la boucle.
On peut donc accéder à notre boucle et laisser l’utilisateur saisir sa première valeur sans avoir à initier la valeur avant la boucle.

[cols="1,1"]
|===
a|
```powershell
Do {
  $x = Read-Host « Veuillez faire un choix »
  #Si l’utilisateur saisit la lettre « q » la boucle s’arrête. 
  } While ($x –ne « q » )
```
a|
[.highlight.bg-blue-500.text-white]
====
Algo :
Fait  “instruction”
Tant  que condition Vrai
====
|===

== Structure `DO UNTIL`

La structure de boucle `Do Until` à la différence du `Do While`, la sortie se fera lorsque la condition est vraie.
 C’est la seule différence entre les deux structures.

[cols="1,1"]
|===
a|
```powershell
Do {
  $x = Read-Host « Veuillez faire un choix »
  #Si l’utilisateur saisit la lettre « q » la boucle s’arrête. 
  } Until ($x –eq « q » )
```
a|
[.highlight.bg-blue-500.text-white]
====
Algo :
Fait  “instruction”
jusqu'à condition Vrai
====
|===

== Structure `FOREACH`

La structure `ForEach` ne s’utilise que dans un seul cas.

Lorsque l’on dispose d’une variable de type `Array` ou `ArrayList`.

```powershell
$liste = « PC1 »,  « PC2 », « PC3 »

Foreach ( $i in $liste)
  {
  Write-Host ’’Le nom de la machine est $i ’’ 
  }
```

Le nombre de tours de boucle est déterminé par le nombre de valeurs dans la variable.

À chaque tour de boucle, la variable $i prend la valeur suivante dans le tableau.

[.highlight.bg-blue-500.text-white]
====
Algo :
Pour chaque entrée dans liste “instruction”
====

include::../../../../adoc/libs/slide-notitle.adoc[]

La structure `ForEach` avec une variable `Arraylist`.

C’est le cas lorsque la variable est le résultat d’une commande.

```powershell
$liste = Get-AdUser –Filter *
Foreach ( $i in $liste)
  {
  Write-Host ’’Le nom de l’utilisateur est $i.name ’’
  Write-Host ’’Le prénom de l’utilisateur est $i.surname ’’
  }
```

La variable `$i` contient un objet différent à chaque tour de boucle.

On utilise le `.` pour indiquer la valeur de la propriété de l’objet que l’on souhaite afficher.

[.highlight.bg-blue-500.text-white]
====
Algo :
Pour chaque entrée dans liste “instruction et recupération de valeur”
====

== Structure `FOREACH {Break}`

Il est possible d’interagir avec la structure de boucle pour prendre une décision sur l’action à effectuer :

Passer à l’objet suivant sans traiter l’actuel `{continue}` ou Sortir de la boucle `{break}`

Utilisation de {break}

[cols="1,1"]
|===
a|
```powershell
ForEach ($i in $liste)
  	{
  	If ($i –eq ’’PC2’’)
  		{Break}
  	Write-Host ’’  Le nom de la machine est $i’’ 
  	}
```
a|
[.highlight.bg-blue-500.text-white]
====
On teste la valeur de `$i`. Si elle est égale à **PC2** alors on arrête la boucle, sinon la boucle continue normalement.
====
|===

== Structure `FOREACH {Continue}`

Utilisation de {continue}

[cols="1,1"]
|===
a|
```powershell
Foreach ( $i in $liste)
  	{
  	If ($i –eq ’’PC2’’)
  		{Continue}
  	Write-Host ’’  Le nom de la machine est $i’’ 
  	}
```
a|
[.highlight.bg-blue-500.text-white]
====
On teste la valeur de `$i`. Si elle est égale à `PC2` alors on ne traite pas l’objet et on passe au suivant.
====
|===

== Structure `SWITCH`

En fonction de la valeur d’une propriété, le `Switch` va déclencher la ou les commandes indiquée(s) pour cette valeur.

Le `Switch` est la structure permettant de créer des menus à choix multiples.

```powershell
Switch ($AdGroup)
{
  	’User’  {Write-Host ’’Le groupe est Utilisateur’’}
  	’Administrator’ {Write-Host ’’Le groupe est Admin’’}
  	’Default’ {Write-Host ’’ Le groupe n’est pas valide’’} 
}
```

[.highlight.bg-blue-500.text-white]
====
Si plusieurs valeurs correspondent au critère, les blocs d’actions correspondants sont appliqués
====

include::../../../../adoc/libs/slide-notitle.adoc[]

Le `Switch` accepte des méthodes.

Passer au test suivant sans exécuter la commande  `{continue}`

Sortir du switch  `{break}`

[cols="1,1"]
|===
a| ```powershell
Switch ($AdGroup)
{
’User’  {CONTINUE}
  	’Administrator’ {Write-Host ’’Le groupe est Admin’’ } {BREAK}
  	’Default’ {Write-Host ’’ Le groupe n’est pas valide’’ }  
}
```
a|
[.highlight.bg-blue-500.text-white]
====
Si le groupe est User, on teste le groupe suivant sans exécuter de commande.
Si le groupe est **Administrator**, on arrête le switch.
====
|===

== Structure et imbrication

L’objectif des structures est de permettre leur imbrication. 

Toutes les structures vues précédemment peuvent donc s’imbriquer

Dans ce cas, la ponctuation permet de définir la portée de chaque structure

```powershell
Do {
    if ($x -gt 10){
        Switch($x) 
        {
            ‘11’ {Write-Host « La valeur est 11 »}
            ‘12’ {Write-Host « La valeur est 12 »}
        }
    } else 
        { 
            $x = Read-Host « Veuillez saisir une valeur supérieure à 10 »
        }
} while ($x –lt 100)
```

// tag::demo[]
== Démonstration

**Structures**

[NOTE.speaker]
--
**Structures de Contrôle en PowerShell**

**Structure `If`**

La structure `If` permet de tester une condition et d'exécuter un bloc de code si cette condition est vraie.

```powershell
$number = 10

if ($number -gt 5) {
    Write-Output "Le nombre est supérieur à 5"
}
```

**Structure `Else`**

La structure `Else` permet de définir un bloc de code à exécuter si la condition du `If` est fausse.

```powershell
$number = 3

if ($number -gt 5) {
    Write-Output "Le nombre est supérieur à 5"
} else {
    Write-Output "Le nombre est inférieur ou égal à 5"
}
```

**Structure `ElseIf`**

La structure `ElseIf` permet de tester plusieurs conditions de manière séquentielle.

```powershell
$number = 5

if ($number -gt 5) {
    Write-Output "Le nombre est supérieur à 5"
} elseif ($number -eq 5) {
    Write-Output "Le nombre est égal à 5"
} else {
    Write-Output "Le nombre est inférieur à 5"
}
```

**Structure `While`**

La structure `While` permet de répéter un bloc de code tant qu'une condition est vraie.

```powershell
$counter = 0

while ($counter -lt 5) {
    Write-Output "Le compteur est à $counter"
    $counter++
}
```

**Structure `Do While`**

La structure `Do While` est similaire à `While`, mais elle garantit que le bloc de code est exécuté au moins une fois.

```powershell
$counter = 0

do {
    Write-Output "Le compteur est à $counter"
    $counter++
} while ($counter -lt 5)
```

**Structure `Do Until`**

La structure `Do Until` exécute un bloc de code jusqu'à ce qu'une condition soit vraie.

```powershell
$counter = 0

do {
    Write-Output "Le compteur est à $counter"
    $counter++
} until ($counter -ge 5)
```

**Structure `ForEach`**

La structure `ForEach` permet de parcourir chaque élément d'une collection.

```powershell
$numbers = 1..5

foreach ($number in $numbers) {
    Write-Output "Le nombre est $number"
}
```

**Structure `ForEach {Break}`**

La commande `Break` permet de sortir prématurément d'une boucle `ForEach`.

```powershell
$numbers = 1..5

foreach ($number in $numbers) {
    if ($number -eq 3) {
        break
    }
    Write-Output "Le nombre est $number"
}
```

**Structure `ForEach {Continue}`**

La commande `Continue` permet de passer à l'itération suivante dans une boucle `ForEach`.

```powershell
$numbers = 1..5

foreach ($number in $numbers) {
    if ($number -eq 3) {
        continue
    }
    Write-Output "Le nombre est $number"
}
```

Structure `Switch`

La structure `Switch` permet de tester une variable contre plusieurs valeurs possibles.

```powershell
$day = "Mardi"

switch ($day) {
    "Lundi" { Write-Output "Aujourd'hui c'est Lundi" }
    "Mardi" { Write-Output "Aujourd'hui c'est Mardi" }
    "Mercredi" { Write-Output "Aujourd'hui c'est Mercredi" }
    default { Write-Output "Jour non reconnu" }
}
```

**Structure et Imbrication**

Il est souvent nécessaire d'imbriquer des structures de contrôle pour créer des logiques plus complexes.

```powershell
$numbers = 1..5

foreach ($number in $numbers) {
    if ($number % 2 -eq 0) {
        Write-Output "$number est pair"
    } else {
        Write-Output "$number est impair"
    }
}
```
--
// end::demo[]

// end::deroulement[]

== Conclusion
// tag::conclusion[]
Les structures sont essentielles en PowerShell pour automatiser les tâches répétitives.

Chaque type de structure a des scénarios d'utilisation spécifiques :

* `If`, `Else If`  pour les tests,
* `ForEach` pour les collections,
* `For` pour les itérations définies,
* `While` et `Do-While/Until` pour les conditions dynamiques.

Les instructions `Break` et `Continue` offrent un contrôle supplémentaire sur le flux de la boucle.

La compréhension et l'utilisation efficaces des boucles permettent d'écrire des scripts plus puissants et optimisés.
// end::conclusion[]