:titre: ps WMI et WMIC
:module: Scripting
:duree: 150
:description: Les fonctions et modules en Powershell
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../adoc/libs
endif::[]

== Objectifs pédagogiques
// tag::objectifs[]
* WMI, WMIC et CIM ?
* WMI
* WMI cas d’utilisation
* WMI Avantages inconvénients
* WMIC
* WMIC cas d’utilisation
* WMIC Avantages inconvénients
* CIM
* CIM cas d’utilisation
* CIM Avantages inconvénients
// end::objectifs[]

// tag::deroulement[]

== WMI, WMIC et CIM ?

**WMI (Windows Management Instrumentation) :**

* Un framework permettant la gestion des composants matériels et logiciels sur les systèmes Windows.
* Utilisé pour accéder aux informations système, surveiller les performances, et automatiser les tâches administratives.

**WMIC (Windows Management Instrumentation Command-line) :**

* Interface en ligne de commande simplifiée pour interagir avec WMI.
* Idéal pour les tâches d'administration rapide.

include::../../../../adoc/libs/slide-notitle.adoc[]

**CIM (Common Information Model) :**

* Standard international pour décrire la gestion des systèmes informatiques.
* Utilisé avec des cmdlets modernes dans PowerShell comme `Get-CimInstance`.

== WMI - Introduction et Utilisation de Base

**Syntaxe de base :**

`Get-WmiObject -Class <WMI_Class>`

**Explication :**

* `Get-WmiObject` : Cette cmdlet interroge WMI pour récupérer des instances d'une classe WMI spécifique.
* `-Class <WMI_Class>` : Spécifiez la classe WMI à interroger,

**Exemple :**

`Get-WmiObject -Class Win32_OperatingSystem`

include::../../../../adoc/libs/slide-notitle.adoc[]

**Explication ligne par ligne :**

* `Get-WmiObject` : Commande PowerShell pour interroger WMI.
* `-Class Win32_OperatingSystem` : Interroge la classe `Win32_OperatingSystem` pour obtenir des informations sur le système d'exploitation, telles que le nom de l'OS, la version, et plus encore.

**Résultat** : Affiche les détails du système d'exploitation en cours d'exécution sur la machine.

== WMI cas d’utilisation

**cas N°1 : Inventaire matériel **

`Get-WmiObject -Class Win32_Processor`

**Explication ligne par ligne :**

* `Get-WmiObject` : Interroge WMI pour récupérer des informations sur les composants matériels.
* `-Class Win32_Processor` : Interroge la classe Win32_Processor, qui contient des informations sur le processeur, telles que le nombre de cœurs, la vitesse d'horloge, et l'architecture.

**Résultat** : Affiche les caractéristiques du processeur installé sur la machine.

include::../../../../adoc/libs/slide-notitle.adoc[]

**Cas N°2 : Surveillance des processus :**

`Get-WmiObject -Class Win32_Process`

**Explication ligne par ligne :**

* `Get-WmiObject` : Cmdlet pour interroger WMI.
* `-Class Win32_Process` : Interroge la classe Win32_Process, qui contient des informations sur les processus en cours d'exécution, tels que leur nom, leur identifiant (PID), et leur utilisation de la mémoire.

**Résultat** : Affiche une liste de tous les processus en cours d'exécution sur la machine.

== WMI Avantages / inconvénients

=== Avantages :

* **Compatibilité étendue** : Get-WmiObject est disponible sur toutes les versions de PowerShell, ce qui le rend universellement applicable sur presque tous les systèmes Windows.
* **Accès complet au système** : WMI permet d'interroger un large éventail de classes représentant différents aspects du système fournissant ainsi une vue complète du système.
* **Utilisation pour des requêtes complexes** : WMI permet d'exécuter des requêtes complexes en utilisant le WMI Query Language (WQL), similaire au SQL, pour filtrer et récupérer des données spécifiques.

=== Inconvénients :

* **Performances** : Les commandes Get-WmiObject peuvent être plus lentes, en particulier lorsqu'elles sont utilisées pour interroger des systèmes distants ou lorsqu'elles retournent un grand nombre de résultats.
* **Sécurité** : WMI utilise DCOM pour la communication, qui est moins sécurisé que les protocoles modernes comme WS-Man, ce qui peut être un problème dans des environnements sensibles.
* **Obsolescence** : Get-WmiObject est considéré comme obsolète dans les versions récentes de PowerShell (à partir de la version 3.0), où Get-CimInstance est recommandé à la place.

== WMIC (Windows Management Instrumentation Command-line)

**Syntaxe de base :**

```powershell
wmic <alias> <commande>
```

**Explication :**

* `wmic` : Lance l'outil WMIC en ligne de commande.
* `<alias>` : Représente une classe WMI ou un groupe de classes (par exemple, os pour `Win32_OperatingSystem`).
* `<commande>` : Représente l'action à exécuter ou l'information à récupérer.

include::../../../../adoc/libs/slide-notitle.adoc[]

**Exemple :**

```powershell
wmic os get name
```

**Explication ligne par ligne :**

* `wmic` : Lance l'interface de commande WMIC.
* `os`: Utilise l'alias os pour interroger la classe Win32_OperatingSystem.
* `get name` : Récupère et affiche la propriété name de la classe Win32_OperatingSystem.

**Résultat** : Affiche le nom du système d'exploitation actuellement installé sur la machine.

== WMIC cas d’utilisation

**Cas N°1 : Gestion des processus :**

```powershell
wmic
wmic:root\cli> process where name='notepad.exe' call terminate
```

* `wmic`: Lance l'outil WMIC.
* `process`: Utilise l'alias process pour interroger la classe Win32_Process.
* `where name='notepad.exe'` : Filtre le processus nommés notepad.exe.
* `call terminate` : Envoie une commande pour terminer les processus filtrés.

**Résultat** : Termine tous les processus notepad.exe en cours d'exécution sur la machine.

include::../../../../adoc/libs/slide-notitle.adoc[]

**Cas N°2 : Configuration du système :**

```powershell
wmic:root\cli> computersystem where name='%computername%' call rename name='NewName'
```

**Explication ligne par ligne :**

* `computersystem` : Utilise l'alias computersystem pour interroger la classe Win32_ComputerSystem.
* `where name='%computername%'` : Filtre pour sélectionner le système actuel en utilisant la variable d'environnement `%computername%`
* `call rename name='NewName'`: Renomme l'ordinateur en NewName.

**Résultat** : Renomme l'ordinateur, un redémarrage est nécessaire pour que le changement prenne effet.

== WMIC Avantages / inconvénients

=== Avantages :

* **Simplicité et rapidité** : WMIC est facile à utiliser idéales pour des tâches administratives rapides.
* **Interface accessible** : WMIC offre une interface textuelle qui est intuitive pour les administrateurs habitués aux lignes de commande, avec des alias pour simplifier les requêtes.
* **Pas besoin de scripting** : WMIC est pratique pour exécuter des commandes ad hoc directement depuis la ligne de commande.

=== Inconvénients :

* **Moins de flexibilité** : Par rapport à Get-WmiObject ou Get-CimInstance, WMIC est moins flexible. Il est limité dans les types de requêtes qu'il peut exécuter et ne supporte pas le niveau de filtrage avancé que permet WQL.
* **Obsolescence** : Comme Get-WmiObject, WMIC est considéré comme obsolète et est remplacé par des cmdlets CIM dans les versions récentes de PowerShell.
* **Limitation des fonctionnalités** : WMIC ne peut pas réaliser certaines tâches complexes que l'on peut effectuer avec des scripts PowerShell utilisant WMI ou CIM.

== CIM

**Cmdlet principale :** `Get-CimInstance` :

```powershell
Get-CimInstance -ClassName <CIM_Class>
```

**Explication :**

* `Get-CimInstance` : Cmdlet moderne pour interroger les instances CIM, similaire à `Get-WmiObject` mais avec des avantages en termes de sécurité et de performance.
* `-ClassName <CIM_Class>` : Spécifie la classe CIM à interroger, par exemple, `Win32_OperatingSystem`.

include::../../../../adoc/libs/slide-notitle.adoc[]

**Exemple :**

```powershell
Get-CimInstance -ClassName Win32_OperatingSystem
```

**Explication ligne par ligne :**

* `Get-CimInstance` : Récupère des instances de la classe CIM spécifiée.
* `-ClassName Win32_OperatingSystem` : Spécifie la classe `Win32_OperatingSystem` pour récupérer des informations sur le système d'exploitation.

**Résultat** : Affiche les mêmes informations que `Get-WmiObject`, mais avec une meilleure performance et sécurité.

== CIM cas d'usage

**cas N°1 : Surveillance des performances :**

```powershell
Get-CimInstance -ClassName  Win32_PerfFormattedData_PerfOS_Processor
```

**Explication ligne par ligne :**

* `Get-CimInstance` : Cmdlet pour récupérer des données de performance.
* `-ClassName Win32_PerfFormattedData_PerfOS_Processor` : Spécifie la classe CIM qui fournit des données formatées sur les performances du processeur, 

**Résultat** : Affiche l'utilisation du processeur en temps réel

include::../../../../adoc/libs/slide-notitle.adoc[]

**Cas N°2 : Automatisation avancée :**

```powershell
Invoke-CimMethod -ClassName Win32_Process -MethodName “Create” -Arguments @{CommandLine="notepad.exe"}
```

**Explication ligne par ligne :**

* `Invoke-CimMethod` : Exécute une méthode sur une instance CIM.
* `-ClassName Win32_Process` : Spécifie la classe CIM `Win32_Process` pour manipuler les processus.
* `-MethodName Create` : Indique que nous voulons utiliser la méthode `Create` pour créer un nouveau processus.
* `-Arguments @{CommandLine="notepad.exe"}` : Passe des arguments à la méthode, ici pour lancer le programme notepad.exe.

**Résultat** : Ouvre Notepad sur la machine.

== CIM Avantages / inconvénients

=== Avantages :

* **Performance améliorée** : `Get-CimInstance` utilise le protocole `WS-Man`, qui est plus performant et consomme moins de ressources que DCOM. 
* **Sécurité renforcée** : CIM offre une communication plus sécurisée via `WS-Man`, et est plus aligné avec les standards de sécurité modernes
* **Interopérabilité** : CIM est basé sur des standards internationaux, ce qui facilite son utilisation dans des environnements hétérogènes et multiplateformes.
* **Compatibilité avec PowerShell moderne** : `Get-CimInstance` est conçu pour fonctionner avec les versions modernes de PowerShell, ce qui assure sa compatibilité avec les nouvelles fonctionnalités et les futures évolutions 

=== Inconvénients :

* **Nécessité de configurations supplémentaires** : Sur des systèmes plus anciens, CIM peut nécessiter des configurations supplémentaires pour être pleinement opérationnel (par exemple, la configuration de `WS-Man`).
* **Complexité accrue pour certains utilisateurs** : Pour les administrateurs habitués à `Get-WmiObject` ou WMIC, l'adoption de `Get-CimInstance` peut nécessiter un certain apprentissage, notamment en raison des différences dans la syntaxe et l'implémentation.

===  Comparaison entre WMI, WMIC et CIM

[cols="2,6,6"]
|===

a|
a| **Avantages**
a| **Inconvénients**

a| **WMI** (`Get-WmiObject`)
a| Très complet, compatible avec les anciennes versions de Windows.
a| Moins sécurisé et performant comparé à CIM.

a| **WMIC**
a| Simplicité, idéal pour des tâches rapides.
a| Moins flexible, commandes limitées par rapport à l'utilisation directe de WMI ou CIM.
|===

include::../../../../adoc/libs/slide-notitle.adoc[]

[cols="2,6,6"]
|===
a|
a| **Avantages**
a| **Inconvénients**

a| **CIM** (`Get-CimInstance`)
a| Plus sécurisé, meilleur pour les environnements modernes, performances améliorées.
a| Peut nécessiter des ajustements pour fonctionner avec des systèmes plus anciens.
|===

// tag::demo[]
== Démonstration

[NOTE.speaker]
--
**Démonstration WMI avec Get-WmiObject**

* **Récupération des informations sur le système d'exploitation**

```powershell
Get-WmiObject -Class Win32_OperatingSystem
```

**Explication :**

* `Get-WmiObject` : Cmdlet utilisée pour interroger WMI.
* `-Class Win32_OperatingSystem` : Interroge la classe `Win32_OperatingSystem` pour obtenir des informations sur le système d'exploitation.

**Résultat attendu** : Affiche des informations détaillées sur le système d'exploitation, telles que le nom, la version, le fabricant, et le type de construction.

* **Inventaire matériel - Informations sur le processeur**

```powershell
Get-WmiObject -Class Win32_Processor
```

**Explication :**

* `Win32_Processor` : Fournit des détails sur les processeurs installés, y compris le nombre de cœurs, la vitesse d'horloge et le modèle.

**Résultat attendu** : Liste des caractéristiques du ou des processeurs installés.

* **Surveillance des processus en cours**

```powershell
Get-WmiObject -Class Win32_Process
```

**Explication :**

* `Win32_Process` : Interroge la liste des processus en cours d'exécution, permettant de voir des détails tels que l'ID du processus (PID), le nom, l'utilisation de la mémoire, etc.

**Résultat attendu** : Affiche une liste de tous les processus en cours d'exécution.

**Démonstration WMIC**

* **Récupération du nom du système d'exploitation**

```powershell
wmic os get name
```

**Explication :**

* `wmic os get name` : Utilise l'alias os pour accéder à la classe `Win32_OperatingSystem` et récupérer le nom de l'OS.

**Résultat attendu** : Affiche le nom du système d'exploitation.

* **Terminer un processus en cours (exemple avec Notepad)**

```powershell
wmic 
process where name='notepad.exe' call terminate
```

**Explication :**

* `wmic process` : Interroge la classe Win32_Process.
* `where name='notepad.exe'` : Filtre pour ne sélectionner que le processus notepad.exe.
* `call terminate` : Termine le processus sélectionné.

**Résultat attendu** : Le processus Notepad est terminé.

* **Renommer l'ordinateur**

```powershell
wmic computersystem where name='%computername%' call rename name='NewName'
```

**Explication :**

* `computersystem` : Accède à la classe `Win32_ComputerSystem`.
* `where name='%computername%'` : Sélectionne le système actuel par son nom.
* `call rename name='NewName'` : Renomme l'ordinateur en NewName.

**Résultat attendu** : Le nom de l'ordinateur est changé (nécessite un redémarrage pour prendre effet).

**Démonstration CIM avec `Get-CimInstance` et `Invoke-CimMethod`**

* **Récupération des informations sur le système d'exploitation avec `Get-CimInstance`**

```powershell
Get-CimInstance -ClassName Win32_OperatingSystem
```

**Explication :**

* `Get-CimInstance` : Cmdlet moderne pour interroger CIM, offrant des performances améliorées.
* `-ClassName Win32_OperatingSystem` : Spécifie la classe `Win32_OperatingSystem`.

**Résultat attendu** : Affiche les informations sur le système d'exploitation, similaires à `Get-WmiObject`, mais plus rapide et sécurisé.

* **Surveillance des performances du processeur**

```powershell
Get-CimInstance -ClassName Win32_PerfFormattedData_PerfOS_Processor
```

**Explication :**

* `Win32_PerfFormattedData_PerfOS_Processor` : Classe qui fournit des données de performance formatées pour le processeur.

**Résultat attendu** : Affiche l'utilisation actuelle du processeur.

* **Créer un processus avec `Invoke-CimMethod`**

```powershell
Invoke-CimMethod -ClassName Win32_Process -MethodName Create -Arguments @{CommandLine="notepad.exe"}
```

**Explication :**

* `Invoke-CimMethod` : Exécute une méthode sur une instance CIM.
* `-ClassName Win32_Process` : Spécifie la classe Win32_Process.
* `-MethodName Create` : Indique que nous voulons utiliser la méthode Create pour créer un nouveau processus.
* `-Arguments @{CommandLine="notepad.exe"}` : Passe l'argument pour lancer notepad.exe.

**Résultat attendu** : Notepad est lancé sur la machine.
--
// end::demo[]
// end::deroulement[]

== Conclusion
// tag::conclusion[]
**WMI (Windows Management Instrumentation) : ** outil puissant avec une compatibilité étendue, particulièrement adapté aux environnements Windows traditionnels. Il permet une gestion approfondie des systèmes, mais peut être complexe à utiliser pour des tâches spécifiques.

**WMIC (WMI Command-line tool) : ** Offre une interface en ligne de commande simple et efficace pour l'exécution de tâches rapides. Il est idéal pour les administrateurs qui recherchent une solution rapide et facile d'accès sans nécessiter une configuration complexe.

**CIM (Common Information Model) :** Représente la solution la plus moderne, intégrant des performances optimisées et une sécurité renforcée. CIM est particulièrement bien adapté aux environnements multiplateformes et répond aux exigences de sécurité modernes
// end::conclusion[]