:titre: Syntaxe en Python
:module: Scripting
:duree: 180
:description: Apprendre la syntaxe de base du langage Python
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../adoc/libs
endif::[]

== Objectifs pédagogiques
// tag::objectifs[]
* Indentation
* Sensibilité à la Casse
* Les commentaires
* Mise en forme
* Variables
// end::objectifs[]

// tag::deroulement[]
== Indentation

* Python utilise l'indentation pour définir les blocs de code. 
* Seul les niveaux d'indentation permettent d’indiquer les blocs de code, comme les boucles ou les conditions.
* Importance de la cohérence : Utilisez un seul type d'indentation dans tout votre code. Par défaut, il est recommandé d'utiliser quatre espaces par niveau d'indentation.

include::../../../../adoc/libs/slide-notitle.adoc[]

Exemple :

```python
if x > 0:
    print("x est positif")
else:
    print("x est négatif ou nul")
```

Si l'indentation n'est pas cohérente, une erreur de syntaxe sera levée :

```python
if x > 0:
print("x est positif")  # Mauvaise indentation
else:
    print("x est négatif ou nul")
```

IndentationError: expected an indented block after 'if' statement on line 1

== Sensibilité à la Casse

* Python est sensible à la casse, ce qui signifie que `Variable` et `variable` sont deux identificateurs différents.
* Les noms de variables, fonctions et classes doivent être utilisés de manière cohérente avec leur casse.

Exemple :

```python
variable = 5
Variable = 10
print(variable)  # Affiche 5
print(Variable)  # Affiche 10
```

== Les commentaires

* Les commentaires sont utilisés pour expliquer le code et sont ignorés lors de l'exécution.
* Utilisez le symbole `#` pour ajouter des commentaires sur une seule ligne.
* Pour des commentaires sur plusieurs lignes, utilisez des triples guillemets (`'''` ou `"""`), bien que cela soit moins fréquent.

Exemple :

```python
# Ceci est un commentaire
print("Hello, World!")  # Affiche un message

"""
Ceci est un commentaire
sur plusieurs lignes
"""
```

== Mise en forme

**Lignes continues :**

Pour diviser une instruction longue sur plusieurs lignes, utilisez le caractère \ à la fin de la ligne.

Exemple :

```python
total = 1 + 2 + 3 + \
        4 + 5 + 6
print(total)  # Affiche 21
```

Cependant, dans de nombreux cas, les parenthèses peuvent également être utilisées pour regrouper les lignes, rendant le caractère `\` inutile.

Exemple avec parenthèses :

```python
total = (1 + 2 + 3 +
         4 + 5 + 6)
print(total)  # Affiche 21
```

include::../../../../adoc/libs/slide-notitle.adoc[]

**Chaînes de caractères multilignes :**

* Utilisez des triples guillemets (`'''` ou `"""`) pour définir des chaînes de caractères sur plusieurs lignes.
* Utile pour les docstrings (chaînes de documentation) dans les fonctions et classes.

Exemple :

```python
message = """Ceci est une chaîne
de caractères sur plusieurs
lignes."""
print(message)
```

Exemple de docstring dans une fonction :

```python
def ma_fonction():
    """
    Cette fonction fait quelque chose.
    Elle n'a pas de paramètres ni de valeur de retour.
    """
print("Faire quelque chose")
```

=== Pourquoi utiliser des Docstrings ?

* **Documentation** : fournissent une documentation en ligne accessible via la fonction help() de Python 
* **Clarté** : Elles aident les autres développeurs à comprendre le but et l'utilisation de votre code.
* **Conformité** : Elles font partie des bonnes pratiques de codage

**Exemple de docstring pour une fonction**

```python
def ajouter(a, b):
    """
    Additionne deux nombres.

    Parameters:
    a (int, float): Le premier nombre à additionner.
    b (int, float): Le second nombre à additionner.

    Returns:
    int, float: La somme de a et b.
    """
    return a + b
```

**Utilisation de la fonction `help()`**

```python
help(ajouter)
```

== Variables

Noms des variables :

* Les noms de variables doivent commencer par une lettre (a-z, A-Z) ou un soulignement (_), suivis de lettres, chiffres (0-9) ou soulignements.
* Les noms de variables ne peuvent pas être des mots-clés réservés par Python (comme if, for, while, etc.).

Exemple :

```python
_variable = 5
variable1 = 10
print(_variable, variable1)
```

**Bonnes pratiques de nommage :**

* Utilisez des noms de variables descriptifs pour améliorer la lisibilité du code.
* Pour les variables composées de plusieurs mots, utilisez la convention snake_case (tous les mots en minuscules, séparés par des underscores).

Exemple :

```python
nombre_utilisateurs = 100
nom_utilisateur = "Alice"
```

// tag::demo[]

== Démonstration

[NOTE.speaker]
--
* **Indentation**

L'indentation est cruciale en Python car elle détermine la structure du code. Les blocs de code (comme les boucles et les conditions) doivent être correctement indentés pour fonctionner correctement.

```python
# Exemple de fonction avec une mauvaise indentation
def mal_indente():
print("Ceci va causer une erreur")

# Exemple de fonction avec une bonne indentation
def bien_indente():
    print("Ceci est correctement indenté")

bien_indente()
```

* **Sensibilité à la casse**

Python est sensible à la casse, ce qui signifie que Variable et variable sont considérés comme deux identificateurs différents.

```python
# Exemple illustrant la sensibilité à la casse
nom = "Alice"
Nom = "Bob"

print(nom)  # Affiche "Alice"
print(Nom)  # Affiche "Bob"
```

* **Les commentaires**

Les commentaires sont des notes dans le code qui aident à expliquer ce que fait le code. Ils sont ignorés par l'interpréteur Python.

```python
# Ceci est un commentaire sur une ligne
print("Hello, world!")  # Ceci est un commentaire à la fin d'une ligne de code

'''
Ceci est un commentaire
multiligne.
Il peut être utilisé pour expliquer
des sections plus longues de code.
'''
```

* **Mise en forme (multiligne et docstring)**

La mise en forme multiligne permet de rendre le code plus lisible, surtout lorsqu'on écrit des chaînes de caractères longues ou des docstrings pour documenter des fonctions.

```python
# Exemple de chaîne de caractères multiligne
long_texte = """Ceci est une chaîne
de caractères sur plusieurs lignes.
Elle est utile pour écrire de longs textes."""

print(long_texte)

# Exemple de docstring
def ma_fonction():
    """
    Cette fonction fait quelque chose de très important.
    
    Elle est utilisée pour montrer comment documenter une fonction
    avec une docstring.
    """
    pass

print(ma_fonction.__doc__)
```

* **Variables**

Les variables sont des conteneurs utilisés pour stocker des valeurs. Elles peuvent être de différents types : chaînes de caractères, nombres, listes, etc.

```python
# Déclaration de différentes variables
chaine = "Bonjour"
nombre = 42
flottant = 3.14
liste = [1, 2, 3, 4, 5]
dictionnaire = {"nom": "Alice", "âge": 30}

# Utilisation de print pour voir le contenue des variables
print(chaine)       
print(nombre)       
print(flottant)     
print(liste)        
print(dictionnaire) 

# Utilisation de la fonction type() pour connaître le type des variables
print(type(chaine))       # <class 'str'>
print(type(nombre))       # <class 'int'>
print(type(flottant))     # <class 'float'>
print(type(liste))        # <class 'list'>
print(type(dictionnaire)) # <class 'dict'>
```

* **Exemple de mise en pratique globale**

Pour combiner toutes ces notions, voici un exemple de code complet :

```python
# Déclaration des variables
nom = "Alice"
age = 30
profession = "Développeur"

# Définition d'une fonction avec une docstring
def afficher_details(nom, age, profession):
    """
    Affiche les détails d'une personne.
    
    Args:
    nom (str): Le nom de la personne.
    age (int): L'âge de la personne.
    profession (str): La profession de la personne.
    """
    # Utilisation de l'indentation et de la mise en forme multiligne
    message = f"""
    Nom: {nom}
    Âge: {age}
    Profession: {profession}
    """
    print(message)

# Appel de la fonction
afficher_details(nom, age, profession)
```
--
// end::demo[]
// end::deroulement[]

== Conclusion
// tag::conclusion[]
* **Indentation** : En Python, l'indentation n'est pas seulement une question de style, elle est essentielle pour définir les blocs de code. Assurez-vous d'utiliser une indentation cohérente pour éviter les erreurs de syntaxe.
* **Sensibilité à la casse** : Python distingue les majuscules des minuscules, ce qui signifie que `Variable` et `variable` sont deux identifiants différents. Cela est crucial lors du nommage des variables et des fonctions.
* **Commentaires** : Les commentaires sont utilisés pour expliquer le code et ne sont pas exécutés. Utilisez le symbole `#` pour ajouter des commentaires, ce qui est essentiel pour rendre le code plus compréhensible et maintenable.
* **Nommage des variables** : Les bonnes pratiques de nommage incluent l'utilisation de noms descriptifs et le respect des conventions, cela aide à maintenir la clarté et la cohérence dans le code.
// end::conclusion[]