:titre: Gestion des fichiers
:module: Système
:duree: 60
:description: Manipuler des fichiers et des répertoires, éditer du texte, visualiser les logs et rechercher des fichiers et du texte.
include::../../../../adoc/libs/header-module.adoc[]

// tag::objectifs[]
// Sous forme de liste à puce, en utilisant la taxonomie de Bloom
* **Comprendre** le système de fichiers sous Linux
* **Appliquer** les commandes de base
// end::objectifs[]

// tag::deroulement[]
== Créer un fichier

=== `touch`

La commande `touch` permet de créer un fichier vide.

```bash
touch mon_fichier.txt
```

[NOTE.speaker]
--
Cela créera un fichier vide appelé `mon_fichier.txt` dans le répertoire courant.
--

=== `echo` + redirection

La commande `echo` permet d'afficher du texte dans le terminal. En utilisant la redirection `>`, on peut écrire ce texte dans un fichier.

```bash
echo "Hello, World!" > mon_fichier.txt
```

La redirection `>` écrase le contenu du fichier. Pour ajouter du texte à la fin du fichier, on utilise `>>`.

[NOTE.speaker]
--
Cela créera un fichier `mon_fichier.txt` contenant le texte `Hello, World!`.

Il est possible d'envoyer d'autres types de données dans un fichier, comme le résultat d'une commande.
`ll > liste_fichiers.txt` enverra le résultat de la commande `ll` dans le fichier `liste_fichiers.txt`.
--

=== Editeur de texte

Il est possible d'éditer un fichier texte directement dans le terminal avec la commande `nano`.

```bash
nano mon_fichier.txt
```

[NOTE.speaker]
--
`nano` est un éditeur de texte en ligne de commande. Il est simple à utiliser et permet de modifier le contenu d'un fichier texte.
--

== Gérer fichier

Les actions suivantes permettent de gérer les fichiers, mais aussi les répertoires.

=== Lister

La commande `ls` permet de lister les fichiers d'un répertoire.

```bash
ls
```

[NOTE.speaker]
--
La commande `ls -l` permet d'afficher les permissions, le propriétaire, le groupe, la taille, la date de modification et le nom des fichiers.

Souvent l'alias `ll` est utilisé pour `ls -l`.
--

=== Déplacer

La commande `mv` permet de déplacer un fichier.

```bash
mv mon_fichier.txt /chemin/vers/destination/
```

[NOTE.speaker]
--
Le premier argument est le fichier à déplacer, le second est le chemin de destination.
--

=== Renommer

Pour renommer un fichier, on utilise la commande `mv`.

```bash
mv mon_fichier.txt mon_fichier_renomme.txt
```

[NOTE.speaker]
--
Le premier argument est le fichier à renommer, le second est le nouveau nom.
--

=== Dupliquer

La commande `cp` permet de dupliquer un fichier.

```bash
cp mon_fichier.txt mon_fichier_copie.txt
```

[NOTE.speaker]
--
Le premier argument est le fichier à copier, le second est le nom de la copie avec éventuellement un chemin de destination.
--

=== Supprimer

La commande `rm` permet de supprimer un fichier.

```bash
rm mon_fichier.txt
```

[NOTE.speaker]
--
On peut supprimer plusieurs fichiers en une seule commande en ajoutant les noms des fichiers à supprimer en argument : `rm fichier1.txt fichier2.txt`.
--

Les options :

* `-r` permet de supprimer un répertoire et son contenu
* `-f` permet de forcer la suppression sans confirmation

== Visualiser le contenu

Ces commandes affiche le contenu en totalité ou partiellement dans le terminal.

=== `cat`

La commande `cat` permet d'afficher le contenu d'un fichier.

```bash
cat mon_fichier.txt
```

=== `less`

La commande `less` permet d'afficher le contenu d'un fichier page par page.

```bash
less mon_fichier.txt
```

[NOTE.speaker]
--
Pour naviguer dans le fichier, on utilise les flèches du clavier. Pour quitter, on appuie sur `q`.
--

=== `head`

La commande `head` permet d'afficher les premières lignes d'un fichier.

```bash
head mon_fichier.txt
```

=== `tail`

La commande `tail` permet d'afficher les dernières lignes d'un fichier.

```bash
tail mon_fichier.txt
```

[NOTE.speaker]
--
L'option `-n` permettent de spécifier le nombre de lignes à afficher.
--

== Éditer des fichiers

=== Nano

Nano est un éditeur de texte simple et intuitif pour les débutants. Il est préinstallé dans la plupart des distributions Linux.

```bash
nano fichier.txt
```

**Commandes importantes** :

* `Ctrl + O` pour enregistrer
* `Ctrl + X` pour quitter

**Avantages** : simplicité, facile à prendre en main.

=== Vim

Vim est un éditeur de texte puissant mais plus complexe que Nano. Il possède deux modes : **mode normal** et **mode insertion**.

```bash
vim fichier.txt
```

**Commandes importantes** :

* Appuyez sur `i` pour passer en mode insertion (pour écrire/modifier).
* `Esc` pour revenir en mode normal.
* Tapez `:w` pour sauvegarder, `:q` pour quitter, ou `:wq` pour sauvegarder et quitter.
* `:q!` pour quitter sans enregistrer.

**Avantages** : très puissant pour la manipulation avancée des fichiers (macros, recherche, remplacements complexes).

=== Emacs

Emacs est plus qu'un simple éditeur de texte ; il s'agit d'un environnement de travail extensible. Vous pouvez l'utiliser pour éditer des fichiers, gérer des projets, coder, etc.

```bash
emacs fichier.txt
```

**Commandes importantes** :

* `Ctrl + X` puis `Ctrl + S` pour sauvegarder.
* `Ctrl + X` puis `Ctrl + C` pour quitter.

**Avantages** : hautement personnalisable, très utilisé par les programmeurs expérimentés.

=== Quel éditeur choisir ?

* **Nano** : parfait pour les tâches rapides et simples.
* **Vim** : idéal pour ceux qui veulent un contrôle fin sur l'édition de texte et n'ont pas peur de la courbe d'apprentissage.
* **Emacs** : pour les utilisateurs expérimentés recherchant un environnement de travail très personnalisable.


== Logs

Les logs sous Linux sont généralement situés dans le répertoire `/var/log` :

* logs du système : `/var/log/syslog`
* logs des erreurs : `/var/log/error.log`

`tail -f` permet de suivre les logs en temps réel :

```bash
tail -f /var/log/syslog
```

== Recherches

=== Recherche de fichiers

`find` est utilisé pour rechercher des fichiers dans un répertoire (et sous-répertoires) en fonction de différents critères.

.Rechercher un fichier par son nom dans le répertoire courant
```bash
find . -name "fichier.txt"
```

.Rechercher dans tout le système
```bash
sudo find / -name "fichier.txt"
```

**Options utiles :**

  - `-type` : pour filtrer par type (f pour fichier, d pour répertoire).
  - `-mtime` : pour filtrer par date de modification.

=== Recherche de texte dans un fichier

`grep` est l'une des commandes les plus couramment utilisées pour rechercher du texte dans un fichier.

.Rechercher une chaîne de texte dans un fichier
```bash
grep "texte_recherché" fichier.txt
```

.Afficher le numéro de ligne où le texte apparaît
```bash
grep -n "texte_recherché" fichier.txt
```

=== Rechercher un texte dans plusieurs fichiers

Pour rechercher un texte dans plusieurs fichiers d’un répertoire et ses sous-répertoires, utilisez l'option `-r` pour une recherche récursive.

.Recherche dans tous les fichiers d'un répertoire
```bash
grep -r "texte_recherché" /chemin/du/dossier
```

.Recherche insensible à la casse
```bash
grep -ri "texte_recherché" /chemin/du/dossier
```

Cela permet de balayer un ensemble de fichiers et de retrouver les occurrences du texte recherché.
// end::deroulement[]

// tag::exercice[]
== Exercice 1

Rechercher dans tous les logs de la machine le mot `FATAL` et envoyer le résultat dans un fichier `~/errors.log`.

[NOTE.speaker]
--
Réponse : `sudo grep -ri "FATAL" /var/log > ~/errors.log`
--
// end::exercice[]

// tag::exercice[]
== Exercice 2

Filtrer le contenu du fichier `errors.log` généré précédemment pour ne conserver que les lignes contenant le mot `journal`.

[NOTE.speaker]
--
Réponse : `grep "journal" ~/errors.log > ~/errors.log`
--
// end::exercice[]

== Conclusion

// tag::conclusion[]
- **Visualiser le contenu** : utilisez `cat`, `less`, `head`, `tail`.
- **Éditer les fichiers** : choisissez entre Nano (simple), Vim (puissant mais complexe), ou Emacs (environnement extensible).
- **Voir les logs** : ils se trouvent souvent dans `/var/log`, et vous pouvez les suivre en temps réel avec `tail -f`.
- **Recherche de fichiers** : utilisez `find` pour rechercher des fichiers par nom ou autre critère.
- **Recherche de texte** : `grep` est l'outil par excellence pour rechercher du texte dans un ou plusieurs fichiers.

[NOTE.speaker]
--
Ces commandes sont fondamentales pour bien gérer les fichiers sous Linux, et elles couvrent les besoins courants en termes de manipulation de fichiers et de texte.
--
// end::conclusion[]
