:titre: Gestion des paquets
:module: Système
:duree: 60
:description: Découvrez les gestionnaires de paquets et leurs commandes de base suivant les distributions Linux.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]

// tag::objectifs[]
* **Comprendre** les gestionnaires de paquets
* **Appliquer** les commandes de base
// end::objectifs[]

// tag::deroulement[]
== Les paquets

Un paquet est un ensemble de fichiers, incluant généralement le binaire du logiciel ainsi que ses fichiers de configuration, dépendances et scripts d'installation.

[NOTE.speaker]
--
Exmples : 

* VSCode
* Firefox
* Apache
--

== Gestionnaires de paquets

Les gestionnaires de paquets sont des outils qui permettent d'installer, de mettre à jour et de supprimer des paquets logiciels.

[NOTE.speaker]
--
A l'aide de commandes simples, il facilite la gestion des logiciels.
--

=== Les différents types

* **Gestionnaires de paquets basés sur des distributions spécifiques** : Ils sont souvent liés à la structure et aux besoins de la distribution Linux particulière que vous utilisez.
* **Gestionnaires de paquets universels** : Ceux-ci fonctionnent indépendamment de la distribution et permettent une installation de logiciels de manière plus universelle à travers différentes distributions.

=== `apt` Debian, Ubuntu et dérivés

APT est le gestionnaire de paquets pour les distributions basées sur Debian. Il utilise des paquets au format .deb.

**Caractéristiques :**

* Les paquets .deb sont précompilés et contiennent le logiciel ainsi que ses dépendances.
* APT est un outil en ligne de commande qui permet la gestion des paquets via une base de données de dépôts.
* Il gère automatiquement les dépendances, ce qui signifie qu'il installe ou désinstalle les bibliothèques nécessaires avec le logiciel.

[NOTE.speaker]
--
APT est très apprécié pour sa stabilité et sa gestion efficace des dépendances, ce qui en fait un choix robuste pour les serveurs et les postes de travail.
--

=== `apt` commandes

* `sudo apt update` : Met à jour la liste des paquets disponibles à partir des dépôts configurés.
* `sudo apt install <nom_du_paquet>` : Installe un paquet.
* `sudo apt upgrade` : Met à jour tous les paquets installés.
* `sudo apt remove <nom_du_paquet>` : Désinstalle un paquet.

=== `apt` commandes avancées

* `sudo apt search <mot_clé>` : Recherche de paquets.
* `sudo apt policy <nom_du_paquet>` : Affiche la version du paquet installé et celles disponibles dans les dépôts.
* `sudo apt autoremove` : Supprime les paquets inutilisés.

=== `rpm` Red Hat, Fedora et dérivés

RPM est un gestionnaire de paquets utilisé dans les distributions dérivées de Red Hat comme Fedora, CentOS et OpenSUSE. Il utilise des paquets au format .rpm.

**Commandes clés :**

* `rpm -i <nom_du_paquet>` : Installe un paquet.
* `rpm -e <nom_du_paquet>` : Désinstalle un paquet.
* `rpm -q <nom_du_paquet>` : Interroge le système pour voir si un paquet est installé.

=== `pacman` Arch Linux

Pacman est le gestionnaire de paquets utilisé sur Arch Linux et ses dérivés comme Manjaro. Il est connu pour sa simplicité et sa rapidité, utilisant des paquets `.pkg.tar.zst`.

**Commandes clés :**

* `sudo pacman -Syu` : Met à jour la liste des paquets et les installe.
* `sudo pacman -S <nom_du_paquet>` : Installe un paquet.
* `sudo pacman -R <nom_du_paquet>` : Désinstalle un paquet.

=== `zypper` OpenSUSE

ZYpp est utilisé dans OpenSUSE et SUSE Enterprise Linux. Il est capable de gérer les dépendances de manière efficace et a des fonctionnalités de gestion de transactions, ce qui signifie qu’il peut annuler des modifications en cas de problème.

**Commandes clés :**

* `sudo zypper install <nom_du_paquet>` : Installe un paquet.
* `sudo zypper remove <nom_du_paquet>` : Désinstalle un paquet.

== Gestionnaires de paquets universels

Ces gestionnaires de paquets fonctionnent sur plusieurs distributions Linux, offrant une solution plus indépendante.

* Snap
* Flatpak
* AppImage

[NOTE.speaker]
--
Leur principal avantage est l’universalité et la portabilité, puisqu'ils sont indépendants de la distribution.

Ces gestionnaires modernes permettent également aux développeurs de déployer des logiciels plus rapidement et plus facilement, tout en offrant aux utilisateurs des applications isolées et sécurisées, sans avoir à gérer les dépendances manuellement.
--

=== Snap

[NOTE.speaker]
--
Snap est un gestionnaire de paquets universel développé par Canonical (les créateurs d'Ubuntu). Il permet d'installer des applications isolées, ou « conteneurisées », sur n'importe quelle distribution Linux.
--

**Caractéristiques :**

* Les paquets Snap sont auto-contenus : ils incluent toutes leurs dépendances, ce qui garantit que les applications fonctionnent de manière cohérente sur différentes distributions sans conflit.
* Snap fonctionne sur une grande variété de distributions (Debian, Ubuntu, Fedora, etc.).
* Il met l'accent sur la confinement des applications (sandboxing), ce qui renforce la sécurité.

**Commandes clés :**

* `snap install <nom_de_l_application>` : Installe un paquet Snap.
* `snap list` : Liste les paquets Snap installés.
* `snap remove <nom_de_l_application>` : Désinstalle une application Snap.

=== Flatpak

[NOTE.speaker]
--
Flatpak est un autre gestionnaire de paquets universel qui vise à fournir une plate-forme de distribution d'applications indépendante de la distribution.
--

**Caractéristiques :**

* Il utilise une approche similaire à Snap en emballant les applications avec leurs dépendances dans un environnement isolé.
* Flatpak est très utilisé dans les environnements GNOME et fonctionne également sur de nombreuses distributions Linux.

**Commandes clés :**

* `flatpak install <nom_de_l_application>` : Installe un paquet Flatpak.
* `flatpak list` : Liste les paquets Flatpak installés.
* `flatpak remove <nom_de_l_application>` : Désinstalle une application Flatpak.

=== AppImage

[NOTE.speaker]
--
AppImage est un format de paquets universel qui ne nécessite pas d'installation. Un fichier AppImage est exécutable directement sans avoir besoin d'un gestionnaire de paquets particulier.
--

**Caractéristiques :**

* Les applications sont autonomes : il suffit de télécharger le fichier `.AppImage` et de l'exécuter.
* Il n’y a pas de gestion de dépendances centralisée comme avec Snap ou Flatpak.

// end::deroulement[]

// tag::demo[]
== Démonstration

Installation de VsCode sur Debian

[NOTE.speaker]
--
* `sudo apt update` : Met à jour la liste des paquets disponibles.
* `apt-cache search code` : Recherche le paquet correspondant à Visual Studio Code.
** Il se peut qu'il ne soit pas dans la liste, dans ce cas, il faudra ajouter le dépôt.
** `wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -`
** `sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"`
** Vérifier qu'il est bien ajouté avec `apt-cache search code`
* `sudo apt install code` : Installe Visual Studio Code.
--
// end::demo[]

// tag::exercice[]
== Exercice 1

Installer Git sur la machine virtuelle Debian.

https://git-scm.com/download/linux[Instructions d'installation]
// end::exercice[]

// tag::exercice[]
== Exercice 2

Installer la CLI Github sur la machine virtuelle Debian.

https://github.com/cli/cli/blob/trunk/docs/install_linux.md[Instructions d'installation]
// end::exercice[]

== Conclusion

// tag::conclusion[]
* chaque gestionnaire de paquets a ses avantages et inconvénients
* le choix dépend soit
** de la distribution que vous utilisez 
** de vos besoins spécifiques en termes d'installation de logiciels

Sur Debian et ses dérivés, APT reste le gestionnaire le plus utilisé, tandis que Snap et Flatpak offrent une flexibilité accrue, quel que soit votre environnement Linux.
// end::conclusion[]
