:titre: Permissions
:module: Système
:duree: 120
:description: Tour d'horizon des permissions avancées sous Linux, avec les concepts de SUID, SGID, Sticky bit et les Access Control Lists (ACL).
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]

// https://docs.google.com/presentation/d/1dJsSKRMSRGALkldleJHTQAcO3TMPGaAj0n4TJlUzzow/edit

// tag::objectifs[]
// Sous forme de liste à puce, en utilisant la taxonomie de Bloom
* **Comprendre** les permissions sous Linux
* *Comprendre* le fonctionnement des SUID, SGID et Sticky bit.
* **Appliquer** les commandes pour gérer les permissions
* **Appliquer** les ACL pour gérer finement les permissions.
// end::objectifs[]

// tag::deroulement[]
== Gestion des permissions `chmod`

La commande chmod (change mode) est utilisée pour changer les permissions d'un fichier ou d'un répertoire.

.Les permissions sont définies pour :
* l'utilisateur propriétaire (u)
* le groupe propriétaire (g)
* les autres (o)

.Les permissions de base sont : 
* lecture (r)
* écriture (w)
* exécution (x)

[NOTE.speaker]
--
`chmod` permet de modifier les permissions de lecture, écriture et exécution pour l'utilisateur propriétaire, le groupe propriétaire et les autres utilisateurs.

Chaque fichier ou répertoire a des permissions distinctes pour l'utilisateur qui le possède, le groupe auquel il appartient et tous les autres utilisateurs. Ces permissions déterminent si un fichier peut être lu, modifié ou exécuté par les différents utilisateurs du système, influençant ainsi l'accès et l'utilisation des fichiers et répertoires.
--

=== Syntaxe

.Exemple de syntaxe pour définir les permissions
```bash
chmod u=rwx,g=rx,o=r fichier.txt
```

[NOTE.speaker]
--
* (u=rwx) : l'utilisateur propriétaire a les droits de lecture, écriture et exécution
* (g=rx) : le groupe propriétaire a les droits de lecture et exécution
* (o=r) : les autres utilisateurs ont le droit de lecture
--

=== Syntaxe abrégée

.Ajouter la permission d’exécution pour le propriétaire
```bash
chmod u+x script.sh
```

.Enlever la permission d’écriture pour les autres
```bash
chmod o-w document.txt
```

.Définir des permissions avec la notation numérique
```bash
chmod 755 programme
```

[NOTE.speaker]
--
* 7 : rwx lecture, écriture, exécution
* 6 : rw- lecture, écriture
* 5 : r-x lecture, exécution
* 4 : r-- lecture seule

--

== Changement de propriétaire et de groupe `chown`

La commande `chown` (change owner) est utilisée pour changer le propriétaire d'un fichier ou d'un répertoire.

On peut également changer le groupe propriétaire en utilisant la syntaxe `chown utilisateur:groupe`

[NOTE.speaker]
--
`chown` permet de transférer la propriété d'un fichier ou d'un répertoire à un autre utilisateur spécifié, ce qui est essentiel pour la gestion des accès et des permissions.

La syntaxe spécifique permet de changer à la fois le propriétaire et le groupe propriétaire d'un fichier ou d'un répertoire en une seule commande, offrant ainsi une gestion flexible et efficace des autorisations.
--

=== Syntaxe

.Changer le propriétaire
```bash
chown nouvel_utilisateur fichier.txt
```

.Changer le propriétaire et le groupe propriétaire
```bash
chown nouvel_utilisateur:nouveau_groupe fichier.txt
```

.Changer le propriétaire de tous les fichiers dans un répertoire de façon récursive
```bash
chown -R nouvel_utilisateur /chemin/du/repertoire
```

== Changement de groupe `chgrp`

La commande `chgrp` (change group) est utilisée pour changer le groupe propriétaire d'un fichier ou d'un répertoire.

.Changer le groupe
```bash
chgrp nouveau_groupe fichier.txt
```

.Changer le groupe propriétaire de tous les fichiers dans un répertoire de façon récursive
```bash
chgrp -R nouveau_groupe /chemin/du/repertoire
```

[NOTE.speaker]
--
`chgrp` permet de modifier le groupe auquel appartient un fichier ou un répertoire, influençant ainsi les permissions d'accès pour tous les membres de ce groupe.

Utilisez `chgrp nouveau_groupe fichier.txt` pour assigner le groupe nouveau_groupe comme propriétaire du fichier `fichier.txt`, ajustant ainsi les autorisations de groupe de manière spécifique.

Utilisez `chgrp -R nouveau_groupe /chemin/du/repertoire` pour appliquer récursivement le changement de groupe à tous les fichiers et sous-répertoires dans `/chemin/du/repertoire`, assurant une gestion cohérente des permissions sur tout le contenu.
--

// tag::demo[]
== Démonstration

Manipulation de chmod, chown et chgrp

[NOTE.speaker]
--
. Créer un fichier `document.txt`
. Contrôler les permission du fichier avec `ls -l `
. Modifier les permissions du fichier avec `chmod 655 document.txt`
. Contrôler les permissions du fichier et commenter les différences
. Créer un utilisateur avec `adduser nicole`
. Rendre nicole propriétaire du fichier avec `chown nicole document.txt`
. Contrôler les permissions du fichier et commenter les différences
. Changer le groupe propriétaire d’un fichier avec `chgrp staff document.txt`
. Contrôler les permissions du fichier et commenter les différences
--
// end::demo[]

// tag::exercice[]
== Exercice

. Créer un fichier `testfile.txt`
. Modifier les permissions pour que le propriétaire ait toutes les permissions, le groupe ait des permissions de lecture et d'exécution, et les autres n'aient que des permissions de lecture
. Changer le propriétaire du fichier en `nicole`
. Changer le groupe propriétaire en `devs`
// end::exercice[]

== Set User ID (SUID)

SUID (Set User ID) permet à un fichier d'être exécuté avec les permissions de son propriétaire plutôt que celles de l'utilisateur qui l'exécute.

=> Utile pour les programmes nécessitant des permissions élevées pour effectuer certaines opérations

[NOTE.speaker]
--
Ce bit spécial sur un fichier permet à celui-ci d'être exécuté avec les permissions de son propriétaire plutôt que celles de l'utilisateur qui l'exécute. Cela est particulièrement utile pour les programmes qui nécessitent des permissions élevées pour effectuer certaines opérations spécifiques, comme la modification des mots de passe des utilisateurs (passwd en est un exemple typique).

Le SUID permet à un programme d'exécuter des tâches sensibles tout en restreignant l'accès direct des utilisateurs ordinaires à ces fonctions critiques.
--

.Exemple avec le fichier passwd
```bash
-rwsr-xr-x 1 root root 68248 23 mars   2023 /usr/bin/passwd
# il y a un s à la place du x, on a donc les droits 
# car le script a les autorisations SUID
```

.Exemple avec le fichier apt
```bash
-rwxr-xr-x 1 root root 18752 25 mai	2023 /usr/bin/apt
# il y a un x, et le fichier appartient à root
# nous n’avons donc pas les droits
```

[NOTE.speaker]
--
Dans l'exemple passwd, le s à la place du x pour l'utilisateur propriétaire (root) indique que ce fichier a le bit SUID activé, lui permettant d'être exécuté avec les privilèges de root. En revanche, dans apt, où tous les x sont présents mais sans le s, l'exécution ne bénéficie pas des privilèges SUID.
--

=== Syntaxe abrégée

.Ajouter le SUID
```bash
chmod u+s script.sh
```

.Enlever le SUID
```bash
chmod u-s script.sh
```

// tag::demo[]
=== Démonstration

Utilisation de SUID

[NOTE.speaker]
--
. Montrer les permissions d’un exécutable restreint, exemple ls -l /usr/bin/apt
. Tenter de lancer la commande sans sudo (apt update) : permission denied
. Modifier les permissions avec SUID : sudo chmod u+s /usr/bin/apt
. Montrer le changement de permissions avec ls -l
. Tenter de lancer la commande sans sudo : apt update
. Remettre les permissions comme auparavant : sudo chmod u-s /usr/bin/apt
--
// end::demo[]

== Set Group ID (SGID)

SGID (Set Group ID) permet à un fichier d'être exécuté avec les permissions du groupe propriétaire plutôt que celles du groupe de l'utilisateur qui l'exécute.

=> Si utilisé sur un répertoire, permet aux fichiers créés à l’intérieur, d’hériter du groupe du répertoire

[NOTE.speaker]
--
Ce bit spécial sur un fichier permet à un utilisateur d'exécuter un fichier avec les permissions du groupe propriétaire plutôt que celles de son propre groupe. Cela est utile pour les fichiers qui nécessitent des permissions spécifiques de groupe pour fonctionner correctement.

Lorsque le SGID est appliqué à un répertoire avec `chmod g+s`, tous les fichiers et sous-répertoires créés à l'intérieur hériteront du groupe du répertoire parent, assurant ainsi une cohérence dans la gestion des permissions de groupe.
--

.Ajouter SGID
```bash
chmod g+s fichier.txt
```

.Retirer SGID
```bash
chmod g-s fichier.txt
```

[NOTE.speaker]
--
Utilisez `chmod g+s` pour activer le SGID sur un fichier, permettant à celui-ci d'être exécuté avec les permissions du groupe propriétaire.

Utilisez `chmod g-s` pour retirer le SGID d'un fichier spécifique, revenant ainsi aux permissions par défaut.
--

// tag::demo[]
=== Démonstration

Utilisation de SGID

[NOTE.speaker]
--
. Créer un dossier `webapp`
. Changer le groupe du dossier `webapp` pour, par exemple le groupe `devteam`
. Montrer les droits du dossier, par défaut le groupe est celui de l’utilisateur qui a créé le fichier
. A l’intérieur, créer un fichier par exemple `index.html`
. Montrer les droits du fichier nouvellement créé. Il a appartient toujours au même groupe
. Changer les droits de `webapp` via la `commande chmod g+s webapp`
. Créer un fichier dans `webapp`, par exemple `about.html`
. Contrôler les permissions, le fichier nouvellement créé a hérité du même groupe que le répertoire
--
// end::demo[]

== Sticky Bit

Empêche les utilisateurs de supprimer ou renommer des fichiers appartenant à d’autres utilisateurs

=> Souvent utilisé sur des répertoires comme /tmp

[NOTE.speaker]
--
Le sticky bit est un attribut spécial des fichiers et des répertoires qui empêche les utilisateurs ordinaires de supprimer ou de renommer des fichiers qui n'appartiennent pas à eux, même s'ils ont les permissions d'écriture sur le répertoire parent. C'est particulièrement utile pour des répertoires partagés comme /tmp, où plusieurs utilisateurs peuvent créer des fichiers temporaires sans risque d'interférence.

Il est couramment appliqué sur des répertoires tels que /tmp pour maintenir la sécurité et la séparation des données temporaires créées par différents utilisateurs.

--

.Ajouter Sticky bit
```bash
chmod +t fichier.txt
```

.Retirer Sticky bit
```bash
chmod -t fichier.txt
```

[NOTE.speaker]
--
Utilisez `chmod +t` pour activer le sticky bit sur un fichier ou un répertoire, restreignant ainsi la suppression ou le renommage par d'autres utilisateurs.

Utilisez `chmod -t` pour retirer le sticky bit d'un fichier ou d'un répertoire, permettant ainsi des modifications normales par d'autres utilisateurs.
--

// tag::demo[]
=== Démonstration

Utilisation de Sticky bit

[NOTE.speaker]
--
. Créer un dossier `/test` à côté de `/tmp`
. Donner l’accès total 777 à ce nouveau répertoire
. Montrer les permissions du répertoire
. Créer un fichier à l’intérieur de ce dossier
. Se connecter en tant qu’un autre utilisateur et créer un autre fichier
. Montrer les droits des deux fichiers dans `/test` pour confirmer que chaque fichier appartient à un utilisateur différent
. Appliquer un Sticky bit sur le dossier `/test` : `chmod +t test`
. Tenter de supprimer un fichier qui a été créé par un autre utilisateur : `permission denied`
--
// end::demo[]

== Access Control Lists (ACL)

* Les ACL permettent des permissions plus fines et spécifiques ¹
* Définit des permissions pour des utilisateurs et des groupes particuliers ²
* Nécessite une installation : `apt install acl` ³
* Visualiser les permissions ACL : `getfacl nom_dossier` ⁴
* Appliquer des permissions ACL : `setfacl -m u:utilisateur:rwx fichier` ⁵

[NOTE.speaker]
--
. Les Access Control Lists (ACL) sont des extensions des permissions traditionnelles Unix/Linux qui permettent de définir des autorisations très détaillées pour des utilisateurs et des groupes spécifiques sur des fichiers et des répertoires.
. Les ACL permettent de spécifier des permissions précises telles que la lecture, l'écriture et l'exécution pour des utilisateurs individuels ou des groupes spécifiques, offrant ainsi une granularité plus fine que les permissions traditionnelles basées sur les utilisateurs, groupes et autres.
. Pour utiliser les ACL, il est nécessaire d'installer le package ACL via la commande apt install acl sur les distributions basées sur Debian/Ubuntu.
. Utilisez getfacl nom_dossier pour afficher les permissions ACL d'un dossier spécifique, montrant clairement quelles permissions sont attribuées à quels utilisateurs et groupes.
. Utilisez setfacl -m u:utilisateur:rwx fichier pour ajouter des permissions ACL à un fichier spécifique pour un utilisateur donné, permettant ainsi une gestion flexible et sécurisée des accès aux fichiers.
--

// tag::demo[]
=== Démonstration

Utilisation des ACL

[NOTE.speaker]
--
. Créer un dossier dans le dossier `home` de l’utilisateur courant
. Contrôler les permissions de ce nouveau dossier via la commande `getfacl`
. Assigner des permissions pour un autre groupe via la commande `setfacl -m g:nomgroupe:rx nomdossier`
. Contrôler à nouveau les permissions pour voir les évolutions
. Assigner des permissions pour un autre utilisateur via la commande `setfacl -m u:nomuser:rwx nomdossier`
--
// end::demo[]

// end::deroulement[]

== Conclusion

// tag::conclusion[]
* Compréhension des bases des permissions de fichiers sous Linux et connaissance de leur représentation ¹
* Capacité à lire et interpréter les permissions des fichiers et répertoires ²
* Maîtrise de l'utilisation de la commande chmod pour modifier les permissions de fichiers et répertoires ³
* Connaissance des propriétés de base des fichiers sous Linux et capacité à les gérer efficacement ⁴
* Connaissance des commandes chown et chgrp pour changer le propriétaire et le groupe des fichiers et répertoires ⁵
* Connaissance des concepts de SUID, SGID, Sticky bit
* Capacité à gérer les permissions avancées avec les ACL

[NOTE.speaker]
--
. Cela implique la familiarisation avec les concepts de lecture (r), écriture (w) et exécution (x) pour l'utilisateur propriétaire, le groupe propriétaire et les autres utilisateurs, représentés sous forme de symboles ou de chiffres.
. Être capable de déchiffrer les symboles ou les chiffres qui définissent les permissions d'accès à un fichier ou un répertoire, déterminant ainsi qui peut effectuer quelles actions.
. Savoir comment utiliser chmod pour ajuster les autorisations de lecture, écriture et exécution, en précisant les modifications pour l'utilisateur, le groupe et les autres utilisateurs.
. Comprendre les informations comme le propriétaire du fichier, le groupe propriétaire, les dates de création et de modification, et savoir comment ces propriétés peuvent être gérées pour assurer une organisation efficace des fichiers.
. Utiliser chown pour attribuer un nouveau propriétaire à un fichier ou répertoire, et chgrp pour changer le groupe propriétaire, permettant ainsi une gestion flexible et sécurisée des permissions.
--
// end::conclusion[]
