:titre: Vulnérabilités
:module: Docker
:duree: 60
:description: Bonnes pratiques basées sur les règles de SonarQube pour comprendre les vulnérabilités potentielles et à adopter des pratiques sécurisées lors de la création et du déploiement de conteneurs.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]

// tag::objectifs[]
// Sous forme de liste à puce, en utilisant la taxonomie de Bloom
* *Appliquer* les bonnes pratiques
// end::objectifs[]

// tag::deroulement[]
== Qu'est-ce ?

* Défaut ou faiblesse
* Exploitable par un attaquant
* Compromet la sécurité du système

[NOTE.speaker]
--
Les vulnérabilités peuvent permettre diverses attaques, telles que l'exécution de code malveillant, l'accès non autorisé à des données sensibles ou la perturbation du fonctionnement normal des applications.
--

=== Rappels sur SonarQube

* Analyse de la qualité du code
* Détection des bugs, code smells et vulnérabilités
* Gestion de règles de qualité personnalisées
    ** Réduction de la dette technique
    ** Sécurité renforcée du code
* Intégration dans les pipelines CI/CD

https://www.sonarsource.com/products/sonarqube/

[NOTE.speaker]
--
Les développeurs utilisent SonarQube pour obtenir des feedbacks immédiats sur la qualité de leur code et pour s'assurer qu'ils respectent les normes de codage.

Les équipes peuvent suivre la qualité globale du projet et identifier les zones nécessitant une attention particulière.

Managers et responsables techniques peuvent utiliser les rapports pour prendre des décisions éclairées sur les améliorations à apporter et pour suivre la conformité aux normes de qualité.
--

// tag::demo[]
=== Démonstration 

Analyse de code avec SonarQube en local.

[NOTE.speaker]
--
. Utiliser l'image docker pour lancer SonarQube en local.

```bash
docker run --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube
```

[start=2]
. Se rendre sur http://localhost:9000 et se connecter avec les identifiants par défaut (admin/admin).
. Configurer un projet local (de type "Other")
. Ouvrir un terminal et se placer à la racine du projet à analyser.
. Utiliser docker pour sonar-scanner (https://docs.sonarsource.com/sonarqube-server/10.7/analyzing-source-code/scanners/sonarscanner/#sonarscanner-from-docker-image[Doc]) 

```bash
docker run \
    --rm \
    --network="host" \
    -e SONAR_HOST_URL="http://localhost:9000"  \
    -e SONAR_TOKEN="${TOKEN}" \
    -v ".:/usr/src" \
    sonarsource/sonar-scanner-cli \
    -Dsonar.projectKey=${PROJECT_KEY}
```

[start=6]
. Examiner les résultats dans le tableau de bord SonarQube.
. Faire une des corrections suggérées et relancer l'analyse.
--
// end::demo[]


== Règles d'après SonarQube

[NOTE.speaker]
--
Parcourir chaque règle, expliquer son importance et montrer des exemples.
--

=== Credentials Hardcoded

https://rules.sonarsource.com/docker/type/Vulnerability/RSPEC-6437/[Lien]

Les informations d'identification ne doivent pas être codées en dur dans l'image Docker.

=== Permissions should be restrictive

https://rules.sonarsource.com/docker/type/Vulnerability/RSPEC-6469/[Lien]

Les permissions des fichiers et répertoires doivent être les plus restrictives possibles.

=== Certificates should be verified

https://rules.sonarsource.com/docker/type/Vulnerability/RSPEC-4830/[Lien]

Les certificats doivent être vérifiés pour éviter les attaques de type "man-in-the-middle" ou l'utilisation de certificats non valides.

=== Weak SSL/TLS protocols should not be used

https://rules.sonarsource.com/docker/type/Vulnerability/RSPEC-4423/[Lien]

Les protocoles SSL/TLS faibles ne doivent pas être utilisés pour éviter les attaques

// end::deroulement[]

== Conclusion

// tag::conclusion[]
* Les vulnérabilités peuvent compromettre la sécurité du système
* Les règles de SonarQube aident à les identifier
// end::conclusion[]
