:titre: Bugs
:module: Docker
:duree: 60
:description: Bonnes pratiques basées sur les règles de SonarQube pour comprendre les bugs potentielles et à adopter des pratiques lors de la création et du déploiement de conteneurs.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]

// tag::objectifs[]
// Sous forme de liste à puce, en utilisant la taxonomie de Bloom
* *Appliquer* les bonnes pratiques
// end::objectifs[]

// tag::deroulement[]
== Qu'est-ce ?

* Erreurs de configuration ou de définition de l'image
* Peut entraîner des comportements inattendus
* Peuvent affecter le bon fonctionnement de l'application ou du service contenu dans le conteneur

[NOTE.speaker]
--
Par exemple, un bug pourrait être une instruction dans le Dockerfile qui ne copie pas correctement les fichiers nécessaires, ou qui expose des ports de manière incorrecte, ou encore des commandes qui ne s'exécutent pas comme prévu, ce qui pourrait entraîner un échec au démarrage du conteneur ou un comportement inattendu pendant son exécution.
--

== Règles d'après SonarQube

[NOTE.speaker]
--
Parcourir chaque règle, expliquer son importance et montrer des exemples.
--

=== Malformed JSON in Exec form leads to unexpected behavior

https://rules.sonarsource.com/docker/type/Bug/RSPEC-7030/[Lien]

Un JSON mal formé dans la forme Exec peut entraîner un comportement inattendu.

=== Dockerfile should only have one ENTRYPOINT and CMD instruction

https://rules.sonarsource.com/docker/type/Bug/RSPEC-6589/[Lien]

Un Dockerfile ne doit contenir qu'une seule instruction ENTRYPOINT et CMD.

=== Access variable which is not available in the current scope

https://rules.sonarsource.com/docker/type/Bug/RSPEC-6579/[Lien]

Accéder à une variable qui n'est pas disponible dans la portée actuelle.

=== A space before the equal sign in key-value pair may lead to unintended behavior

https://rules.sonarsource.com/docker/type/Bug/RSPEC-6574/[Lien]

Un espace avant le signe égal dans une paire clé-valeur peut entraîner un comportement non intentionnel.
// end::deroulement[]

== Conclusion

// tag::conclusion[]
* Les bugs peuvent entraîner des comportements inattendus
* Les règles de SonarQube aident à les identifier
// end::conclusion[]
