:titre: Security hotspots
:module: Docker
:duree: 120
:description: Identifier les mauvaises pratiques et adopter les bonnes lors de la création et du déploiement de conteneurs.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]

// tag::objectifs[]
// Sous forme de liste à puce, en utilisant la taxonomie de Bloom
* *Appliquer* les bonnes pratiques
// end::objectifs[]

// tag::deroulement[]
== Qu'est-ce ?

* partie du code ou de la configuration qui mérite une attention particulière en matière de sécurité
* pas nécessairement une vulnabilité avérée
* endroit où des problèmes de sécurité pourraient potentiellement se manifester si le code ou la configuration n'est pas soigneusement analysé et validé

[NOTE.speaker]
--
Les "Security Hotspots" nécessitent une révision manuelle par les développeurs ou les équipes de sécurité pour déterminer si un risque de sécurité réel existe. Ils attirent l'attention sur des pratiques qui, si elles sont mal gérées, pourraient introduire des failles de sécurité.

. Utilisation de commandes potentiellement dangereuses : Par exemple, l'utilisation de RUN apt-get install sans verrouiller les versions des paquets peut introduire des logiciels vulnérables.
. Gestion des secrets : Stocker des secrets, des clés API ou des mots de passe en clair dans un Dockerfile ou une image.
. Permissions excessives : Exécution de processus avec des privilèges root quand ce n'est pas nécessaire.
. Ports exposés inutilement : Ouverture de ports qui ne sont pas nécessaires pour le fonctionnement de l'application, augmentant ainsi la surface d'attaque.
--

== Règles d'après SonarQube

[NOTE.speaker]
--
Parcourir chaque règle, expliquer son importance et montrer des exemples.
--

=== Using ENV or ARG to handle secrets is security-sensitive

https://rules.sonarsource.com/docker/type/Security%20Hotspot/RSPEC-6472/[lien]

Utiliser les instructions ARG et ENV dans un Dockerfile pour gérer des secrets peut entraîner la divulgation d'informations sensibles, car ces valeurs peuvent être conservées dans l'image finale, exposant ainsi les secrets dans l'environnement du conteneur, les métadonnées de l'image ou les journaux de construction, ce qui peut avoir des conséquences financières, compromettre des applications ou des composants d'infrastructure.

=== Disabling builder sandboxes is security-sensitive

https://rules.sonarsource.com/docker/type/Security%20Hotspot/RSPEC-6502/[lien]

Désactiver les sandbox des constructeurs peut permettre à un attaquant d'exécuter du code malveillant sur le système hôte, ce qui peut entraîner des conséquences financières, compromettre des applications ou des composants d'infrastructure.

=== Exposing administration services in containers is security-sensitive

https://rules.sonarsource.com/docker/type/Security%20Hotspot/RSPEC-6473/[lien]

Exposer des services d'administration dans des conteneurs peut permettre à un attaquant d'interagir avec le conteneur et d'exécuter des commandes malveillantes, ce qui peut entraîner des conséquences financières, compromettre des applications ou des composants d'infrastructure.

=== Recursively copying context directories is security-sensitive

https://rules.sonarsource.com/docker/type/Security%20Hotspot/RSPEC-6470/[lien]

Copier récursivement des répertoires de contexte peut entraîner la copie de fichiers sensibles ou de répertoires entiers, ce qui peut avoir des conséquences financières, compromettre des applications ou des composants d'infrastructure.

=== Using clear-text protocols is security-sensitive

https://rules.sonarsource.com/docker/type/Security%20Hotspot/RSPEC-5332/[lien]

L'utilisation de protocoles en clair pour les communications réseau peut permettre à un attaquant d'intercepter et de lire les données, ce qui peut entraîner des conséquences financières, compromettre des applications ou des composants d'infrastructure.

=== Using weak hashing algorithms is security-sensitive

https://rules.sonarsource.com/docker/type/Security%20Hotspot/RSPEC-4790/[lien]

L'utilisation d'algorithmes de hachage faibles pour stocker des mots de passe ou des données sensibles peut permettre à un attaquant de dev

=== Allowing downgrades to a clear-text protocol is security-sensitive

https://rules.sonarsource.com/docker/type/Security%20Hotspot/RSPEC-6506/[lien]

Permettre des rétrogradations vers un protocole en clair peut permettre à un attaquant d'intercepter et de lire les données, ce qui peut entraîner des conséquences financières, compromettre des applications ou des composants d'infrastructure.

=== Allowing shell scripts execution during package installation is security-sensitive

https://rules.sonarsource.com/docker/type/Security%20Hotspot/RSPEC-6505/[lien]

Permettre l'exécution de scripts shell pendant l'installation de paquets peut permettre à un attaquant d'exécuter du code malveillant sur le système hôte, ce qui peut entraîner des conséquences financières, compromettre des applications ou des composants d'infrastructure.

=== Using host operating system namespaces is security-sensitive

https://rules.sonarsource.com/docker/type/Security%20Hotspot/RSPEC-6431/[lien]

Utiliser les espaces de noms du système d'exploitation hôte peut permettre à un attaquant d'accéder à des ressources sensibles sur le système hôte, ce qui peut entraîner des conséquences financières, compromettre des applications ou des composants d'infrastructure.

=== Setting loose POSIX file permissions is security-sensitive

https://rules.sonarsource.com/docker/type/Security%20Hotspot/RSPEC-2612/[lien]

Définir des autorisations de fichiers POSIX lâches peut permettre à un attaquant d'accéder à des fichiers sensibles, ce qui peut entraîner des conséquences financières, compromettre des applications ou des composants d'infrastructure.

=== Allowing non-root users to modify resources copied to an image is security-sensitive

https://rules.sonarsource.com/docker/type/Security%20Hotspot/RSPEC-6504/[lien]

Permettre à des utilisateurs non root de modifier des ressources copiées dans une image peut permettre à un attaquant d'exécuter du code malveillant sur le système hôte, ce qui peut entraîner des conséquences financières, compromettre des applications ou des composants d'infrastructure.

=== Automatically installing recommended packages is security-sensitive

https://rules.sonarsource.com/docker/type/Security%20Hotspot/RSPEC-6500/[lien]

Installer automatiquement des paquets recommandés peut entraîner l'installation de logiciels vulnérables, ce qui peut avoir des conséquences financières, compromettre des applications ou des composants d'infrastructure.

=== Running containers as a privileged user is security-sensitive

https://rules.sonarsource.com/docker/type/Security%20Hotspot/RSPEC-6471/[lien]

Exécuter des conteneurs en tant qu'utilisateur privilégié peut permettre à un attaquant d'accéder à des ressources sensibles sur le système hôte, ce qui peut entraîner des conséquences financières, compromettre des applications ou des composants d'infrastructure.

=== Delivering code in production with debug features activated is security-sensitive

https://rules.sonarsource.com/docker/type/Security%20Hotspot/RSPEC-4507/[lien]

Livrer du code en production avec des fonctionnalités de débogage activées peut permettre à un attaquant d'accéder à des informations sensibles, ce qui peut entraîner des conséquences financières, compromettre des applications ou des composants d'infrastructure.

=== Pulling an image based on its digest is security-sensitive

https://rules.sonarsource.com/docker/type/Security%20Hotspot/RSPEC-6497/[lien]

Tirer une image basée sur son hachage peut entraîner l'utilisation d'une image obsolète, ce qui peut avoir des conséquences financières, compromettre des applications ou des composants d'infrastructure.
// end::deroulement[]

== Conclusion

// tag::conclusion[]
* Les "Security Hotspots" sont des parties du code ou de la configuration qui méritent une attention particulière en matière de sécurité
* Les règles de SonarQube aident à les identifier
// end::conclusion[]
