:titre: Compose : Base de données
:module: Docker
:duree: 120
:description: Mise en place d'un environnement de développement complet avec compose en finissant avec une base de données.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]

// tag::objectifs[]
// Sous forme de liste à puce, en utilisant la taxonomie de Bloom
* *Appliquer* compose
* *Appliquer* un environnement de développement complet
* *Analyser* la configuration
// end::objectifs[]

// tag::deroulement[]
== Base de données

Pour finaliser notre environnement de développement, nous allons ajouter une base de données Pgsql.

https://hub.docker.com/_/postgres[Postgres sur Docker Hub]

[NOTE.speaker]
--
Toutes les bases de données sont compatibles avec Docker, pour rappel un BDD est un service comme un autre.
--

=== Ajout du service

```yml
services:
  back:
    image: directus/directus
    ports:
      - 8055:8055
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
```

Un conteneur `db` va démarrer une base de données Pgsql avec les paramètres spécifiés. Le service `back` dépend du service `db`, donc le service `db` sera démarré avant le service `back`.

[NOTE.speaker]
--
* `depends_on` : permet de spécifier l'ordre de démarrage des services
* `environment` : variables d'environnement pour la base de données
** `POSTGRES_USER` : nom d'utilisateur
** `POSTGRES_PASSWORD` : mot de passe
** `POSTGRES_DB` : nom de la base de données
--

== Data

Il est possible de charger des données dans la base de données au démarrage du conteneur. Cela permet de l'initialiser avec des données de test par exemple.

.init.sql
```sql
CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL
);

INSERT INTO users (name) VALUES ('Alice');
INSERT INTO users (name) VALUES ('Bob');
```

[NOTE.speaker]
--
Ce fichier contient des instructions SQL pour créer une table `users` et y insérer deux utilisateurs.
--

=== Feed

Pour fournir ce fichier au conteneur `db`, on ajoute une instruction `volumes` :

```yml
db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
```

[NOTE.speaker]
--
L'instruction `volumes` permet de monter le fichier `init.sql` dans le conteneur `db`. Le fichier `init.sql` sera exécuté lors du démarrage de la base de données.
--
// end::deroulement[]

// tag::demo[]
== Démonstration

[NOTE.speaker]
--
* Créer un fichier `compose.yml` avec une base de données Pgsql
** Fournir une fichier `init.sql` pour initialiser la base de données
** Spécifier les variables d'environnement pour la base de données
* Ajouter un service adminer
** Définir les ports
** Définir la dépendance avec la base de données
** Definir les variables ADMINER_DEFAULT_SERVER et ADMINER_PLUGINS ou ADMINER_DESIGN
* Démarrer les services avec `docker compose up -d`
* Se connecter à l'interface d'adminer
* Vérifier que les données ont bien été insérées dans la base de données
* Modifier les données avec l'interface d'adminer
* Arrêter les services avec `docker compose down`
* Relancer les services avec `docker compose up -d`
* Constater que les données sont perdues
--
// end::demo[]

// tag::exercice[]
== Exercice 1

Créer une application avec wordpress, mysql, adminer.

. Trouver les images sur Docker Hub
. Créer un fichier `compose.yml` avec les services
. Paramétrer les services pour les faire fonctionner ensemble et rendre les ports accessibles

== Exercice 2

Garder la configuration précédente.

. Faire l'initialisation de Wordpress via l'interface web
. Se connecter à l'interface d'adminer pour voir la base de données
. Se connecter au terminal du conteneur mysql
. Faire un dump de la base de données
. Copier le contenu du dump dans un fichier `init.sql` sur la machine hôte
. Stopper les conteneurs
. Ajouter le fichier `init.sql` dans le volume de la base de données
. Relancer les conteneurs
. Vérifier que les données sont bien présentes dans la base de données et que Wordpress fonctionne
// end::exercice[]

== Conclusion

// tag::conclusion[]
* On a toutes les briques d'une application classique
* On peut initialiser une base de données avec des données de test

[NOTE.speaker]
--
On verra plus tard comment conserver les données entre les redémarrages.
--
// end::conclusion[]
