:titre: Dockerfile
:module: Docker
:duree: 120
:description: Découverte de la syntaxe d'un Dockerfile pour créer ses propres images Docker.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]

// tag::objectifs[]
// Sous forme de liste à puce, en utilisant la taxonomie de Bloom
* *Comprendre* l'intérêt d'un Dockerfile
* *Appliquer* la syntaxe d'un Dockerfile
// end::objectifs[]

// tag::deroulement[]
== Problématique

On l'a vu avec les service nécessitant des dépendances, c'est lourd de devoir installer les dépendances à chaque fois.

Dockerfile permet de définir une image de base et d'exécuter les instructions nécessaires à notre application.

== Syntaxe

Un Dockerfile est un fichier texte qui contient une liste d'instructions pour créer une image Docker. Les 5 principales sont :

* `FROM` : image de base
* `RUN` : commande à exécuter
* `COPY` : copie de fichiers
* `WORKDIR` : répertoire de travail
* `CMD` : commande à exécuter au lancement du conteneur

=== Backend

.Dockerfile
```dockerfile
FROM node:20-alpine

WORKDIR /app

COPY package*.json .
RUN npm i

COPY . .

CMD ["node", "index.js"]
```

[NOTE.speaker]
--
Ici, on part de l'image `node:20-alpine`, on définit le répertoire de travail, on copie le `package.json`, on installe les dépendances, on copie le reste des fichiers et on lance le serveur.
--

=== Compose

On peut modifier le service pour utiliser notre image.

.compose.yml
```yaml
back:
  build: ./back
  ports:
    - 3000:3000
```

[NOTE.speaker]
--
Le paramètre `build` permet de construire l'image à partir du Dockerfile situé dans le dossier `back`.

Il n'y a plus de volume à monter, car les fichiers de l'application sont copiés dans le conteneur lors de la construction de l'image. Dans cette configuration, si nous modifions le fichier `index.js` ou `package.json`, nous devons reconstruire l'image
--

== Commandes

=== Via Compose

* `docker compose build` : construire les images des services
* `docker compose build back` : construire l'image du service `back`
* `docker compose build --no-cache back` : construire l'image sans utiliser le cache
* `docker compose up --build` : lancer les services après la construction des images

=== Via Docker

* `docker build ./back` : construire l'image `back` à partir du Dockerfile situé dans le dossier `back`

== Théorie du build

Le build d'une image Docker est un processus en plusieurs étapes :

. Docker récupère l'image de base
. Docker exécute les instructions du Dockerfile
. Docker crée une couche pour chaque instruction
. Docker crée une image à partir des couches
. Docker crée un conteneur à partir de l'image

[NOTE.speaker]
--
Le build d'une image est un processus incrémental. Si une instruction change, Docker ne reconstruit que les instructions suivantes.

C'est pour cela que l'on copie d'abord le `package.json` puis le reste des fichiers. Les fichiers sources changent plus souvent que les dépendances, et donc pas besoin de les réinstaller à chaque modification.
--
// end::deroulement[]

// tag::demo[]
== Démonstration 1

[NOTE.speaker]
--
* Créer un Dockerfile d'un back node js
* Créer un service dans le compose
* Lancer le service
* Voir le build puis le lancement dans le terminal
--

== Démonstration 2

[NOTE.speaker]
--
* Modifier le fichier `index.js`
* Relancer le service sans forcer le build
* Constater que le résultat n'a pas changé
* Forcer le build avec `docker compose up --build`
** Constater les couches (_layers_) récupérées depuis le cache
* Constater que le résultat a changé
--

== Démonstration 3

[NOTE.speaker]
--
* Ajouter une dépendance dans le fichier `package.json`
* Rebuilder avec`docker compose build`
* Ajouter une volume pour voir le dossier `node_modules`
* Relancer le service
* Constater que la dépendance est installée
--
// end::demo[]

// tag::exercice[]
== Exercice

Créer une application front avec Vite + Vue + TS.

Le Dockerfile doit :

* Partir de l'image `node:lts-alpine`
* Définir le répertoire de travail
* Gérer les dépendances

Le service doit :

* Utiliser l'image créée
* Monter le dossier `front` dans le conteneur
* Lancer le serveur de développement

> *TIP* pensez à exposer votre URL Vite…

// end::exercice[]

== Conclusion

// tag::conclusion[]
* On peut créer des images personnalisées avec Dockerfile
* On peut automatiser le build d'une image
// end::conclusion[]
