:titre: Variables d'environnement
:module: Docker
:duree: 60
:description: Mise en place de variables d'environnement dans la configuration du compose pour introduire les bonnes pratiques.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
// Sous forme de liste à puce, en utilisant la taxonomie de Bloom
* *Comprendre* l'intérêt des fichiers .env
* *Appliquer* les variables d'environnement
// end::objectifs[]

// tag::deroulement[]
== Environnements

Les variables d'environnement sont des valeurs qui peuvent être utilisées par les applications pour modifier leur comportement. Elles sont souvent utilisées pour stocker des informations sensibles comme des mots de passe ou des clés d'API.

[NOTE.speaker]
--
Elle servent aussi à définir par exemple la base url de l'api pour le service front.
--

== Configuration

Il y a plusieurs moyens de définir des variables d'environnement dans un compose :

* directement dans le fichier `compose.yml`
* dans un fichier `.env` à la racine du projet partagé par plusieurs services
* dans un fichier `.env` spécifique à un service

=== En direct

On l'a déjà vu dans les exemples précédents avec Directus ou la base de données.

```yaml
services:
  front:
    image: nginx
    environment:
      - ENV_VAR_1=value1
      - ENV_VAR_2=value2
```

[NOTE.speaker]
--
Dans cet exemple, deux variables d'environnement `ENV_VAR_1` et `ENV_VAR_2` sont définies pour le service `front`. Ces variables seront injectées dans le conteneur au moment du démarrage et pourront être utilisées par l'application.
--

=== Fichier .env

Le fichier `.env` est un fichier texte qui contient des paires clé/valeur.

```environment
ENV_VAR_1=value1
ENV_VAR_2=value2
```

```yaml
services:
  front:
    image: nginx
    environment:
      - VAR_1=${ENV_VAR_1}
      - VAR_2=${ENV_VAR_2}
  back:
    image: node:20-alpine
    env_file:
      - .env
```

[NOTE.speaker]
--
Dans cet exemple, les variables d'environnement `ENV_VAR_1` et `ENV_VAR_2` sont définies dans le fichier `.env`. Elles sont ensuite injectées dans les services `front` et `back` au moment du démarrage.

`front` utilise les variables `VAR_1` et `VAR_2` qui sont initialisées avec les valeurs de `ENV_VAR_1` et `ENV_VAR_2`. C'est une syntaxe qui permet de lui fournir uniquement les variables dont il a besoin.

`back` utilise le paramètre `env_file` pour charger l'intégralité des variables du fichier `.env`.
--

=== Fichier .env spécifique

Il est possible de définir un fichier `.env` spécifique à un service.

back.env
```yaml
ENV_VAR=value1
```

front.env
```yaml
ENV_VAR=value2
```

```yaml
services:
  front:
    image: nginx
    env_file:
      - front.env
  back:
    image: node:20-alpine
    env_file:
      - back.env
```

[NOTE.speaker]
--
Cette pratique permet de mieux isoler les variables d'environnement et de les associer directement au service qui en a besoin. Elle facilite la maintenance et la compréhension du projet.
--
// end::deroulement[]

// tag::demo[]
== Démonstration

[NOTE.speaker]
--
* Créer un fichier `.env` à la racine du projet
* Ajouter des variables d'environnement de Directus et de la base de données
* Utiliser ces variables dans le fichier `compose.yml`
** Utiliser la syntaxe `${VAR}` pour les variables d'environnement de la base de données (ne donner que le strict nécessaire)
** Fournir le fichier complet pour Directus (il a besoin de tout !)
* Lancer les services
* Vérifier que les variables d'environnement sont bien injectées dans les conteneurs

.compose.yml
```yml
services:
  front:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - ./front:/usr/share/nginx/html
    networks:
      - front-network

  back:
    image: directus/directus
    env_file:
      - .env
    ports:
      - 8055:8055
    depends_on:
      - db
    networks:
      - db-network
      - front-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    networks:
      - db-network

volumes:
  db-data:

networks:
  db-network:
  front-network:
```
--
// end::demo[]

== Conclusion

// tag::conclusion[]
* Les variables d'environnement permettent de stocker des informations sensibles
* Elles facilitent la configuration des services
* Elles permettent de mieux isoler les configurations
// end::conclusion[]
