:titre: Healthcheck
:module: Docker
:duree: 60
:description: Amélioration du lancement des containers dans le compose à l'aide du healthcheck.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
// Sous forme de liste à puce, en utilisant la taxonomie de Bloom
* *Appliquer* le healthcheck dans un compose
* *Analyser* les problématiques d'organisation des services 
// end::objectifs[]

// tag::deroulement[]
== Problématique

Nous savons cadencer le démarrage des services avec `depends_on`, mais comment savoir si un service est prêt à recevoir des requêtes ?

* Dans le cas d'un back, il est fréquent qu'il soit prêt avant l'init complet des données dans la base de données. La connexion à la bdd peut échouer et faire crasher le service.
* Dans le cas d'un front, il est fréquent qu'il soit prêt avant le back. Les requêtes seront rejetées et le front sera en erreur.

== Healthcheck

Le `healthcheck` est une instruction qui permet de vérifier l'état de santé d'un conteneur. Il permet de déterminer si un conteneur est prêt à recevoir des requêtes.

[NOTE.speaker]
--
Le `healthcheck` permet de définir une commande qui sera exécutée pour vérifier si le conteneur est en bonne santé.
--

== Configuration

Pour ajouter un `healthcheck` à un service, il suffit de définir une instruction `healthcheck` dans le service.

```yaml
db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
        interval: 10s
        timeout: 5s
        retries: 5
```

[NOTE.speaker]
--
* `test` : commande à exécuter pour vérifier l'état de santé
* `interval` : fréquence de vérification
* `timeout` : temps d'attente avant de considérer le test comme échoué
* `retries` : nombre de tentatives avant de considérer le test comme échoué
--

=== Attente

Maintenant, le but est d'attendre que le service `db` soit prêt avant de démarrer le service `back`.

Pour cela, on peut utiliser un script qui attend que le `healthcheck` soit OK.

```yaml
back:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
```

[NOTE.speaker]
--
* `depends_on` : permet de spécifier l'ordre de démarrage des services
* `condition: service_healthy` : attend que le service soit en bonne santé
--

=== Healthy vs Started

* `service_healthy` attend que le service soit en bonne santé avant de démarrer le service dépendant. 
* `service_started` attend que le service soit démarré avant de démarrer le service dépendant.

Dans le cas d'une utilisation d'un reverse proxy, certains services n'ont pas de healtcheck configuré et d'autres oui. On peut alors mixer les deux conditions pour attendre que les services soient prêts.

```yaml
reverseproxy:
  image: nginx:latest
  ports:
    - 80:80
  volumes:
    - ./nginx/local.conf:/etc/nginx/nginx.conf
  depends_on:
    back: # Attend que le service backend soit en bonne santé
      condition: service_healthy
    front: # Attend que le service frontend soit démarré
      condition: service_started
```
// end::deroulement[]

// tag::demo[]
== Démonstration 1

[NOTE.speaker]
--
* Supprimer les volumes éventuels
* Créer une configuration avec un back node et une base de données
* Ajouter un healthcheck pour la base de données
* Faire attendre le back pour que la base de données soit prête
* Lancer les services
* Vérifier que le back est bien démarré après la base de données

```yml
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  back:
    image: node:lts-alpine
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
```
--

== Démonstration 2

[NOTE.speaker]
--
* Supprimer les volumes éventuels
* Ajouter un healthcheck sur le back
* Ajouter un service front qui dépend du back
* Lancer les services
* Vérifier l'ordre de lancement des services : db, back, front

```yaml
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    
  back:
    image: node:lts-alpine
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 12

  front:
    image: nginx:alpine
    depends_on:
      back:
        condition: service_healthy
```

→ Error : on a rien pour démarrer un serveur ; `docker ps` nous montre bien que back et front ne sont pas lancés

→ Solution : créer une application back avec Express pour lancer le serveur
--

== Démonstration 3

[NOTE.speaker]
--
* Supprimer les volumes éventuels
* Ajouter un reverse proxy comme vu précédemment
* Lancer les services
* Vérifier l'ordre de lancement des services : db, back, front, reverseproxy
--
// end::demo[]




== Conclusion

// tag::conclusion[]
* Le `healthcheck` permet de vérifier l'état de santé d'un conteneur
* On s'assure que les services sont prêts avant de démarrer les services dépendants
// end::conclusion[]
