:titre: Multi-staging : analyse approfondie
:module: Docker
:duree: 120
:description: Faire une comparaison détaillée entre les Dockerfiles traditionnels et les Dockerfiles multi-stage. Montrer comment les utiliser dans un compose avec l'attribut `target` pour construire des images spécifiques.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
* Analyser les différences entre Dockerfiles traditionnels et multi-stage
* Comprendre l'utilisation de l'attribut `target` dans Docker Compose
* Évaluer l'impact du multi-staging sur la taille de l'image et le temps de build
* Appliquer les concepts de multi-staging dans des scénarios concrets
// end::objectifs[]

// tag::deroulement[]

== Comparaison des Dockerfiles

=== Dockerfile traditionnel

```dockerfile
FROM node:14
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
RUN yarn build
CMD ["node", "dist/main"]
```

[NOTE.speaker]
--
Ce Dockerfile traditionnel effectue toutes les opérations dans une seule étape, incluant à la fois les dépendances de développement et de production. Cela peut rendre l'image finale volumineuse, ce qui augmente le temps de téléchargement et d'exécution.
--

=== Dockerfile multi-stage

```dockerfile
FROM node:14 AS base
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install

FROM base AS dev
COPY . .
CMD ["npm", "run", "start:dev"]

FROM base AS build
COPY . .
RUN npm run build

FROM node:14-alpine AS prod
WORKDIR /app
COPY --from=build /app/dist ./dist
CMD ["node", "dist/main"]
```

[NOTE.speaker]
--
Dans ce Dockerfile multi-stage, nous avons séparé les étapes de développement et de production. Le premier stage `base` installe les dépendances communes. Ensuite, nous avons un stage `dev` pour le développement local, un stage `build` pour construire l'application, et enfin un stage `prod` pour l'image de production finale. Cette séparation permet de réduire la taille de l'image finale en excluant les dépendances de développement et les fichiers temporaires.
--

=== Analyse de la taille de l'image et du temps de build

* **Taille de l'image** : Les Dockerfiles multi-stage produisent généralement des images plus petites en excluant les dépendances de développement.
* **Temps de build** : Le multi-staging peut réduire le temps de build en minimisant le nombre de fichiers copiés dans les étapes finales.

[NOTE.speaker]
--
Le multi-staging est particulièrement efficace pour réduire la taille des images car seule la partie nécessaire pour exécuter l'application est incluse dans l'image finale. Cela améliore également le temps de build et de déploiement, en réduisant la quantité de données à traiter.
--

=== Extension Dive

https://www.docker.com/blog/reduce-your-image-size-with-the-dive-in-docker-extension/[Lien]

https://github.com/wagoodman/dive[GitHub]

Un outils pour explorer les couches d'une image Docker et identifier les fichiers qui contribuent le plus à la taille de l'image.


// tag::demo[]
=== Démonstration

Installation et utilisation de l'extension Dive pour analyser les images Docker.

// end::demo[]

== Utilisation de l'attribut `target` dans Docker Compose

* Permet de cibler des étapes spécifiques d'un Dockerfile multi-stage
* Utile pour différents environnements (dev, test, prod)

```yaml
services:
  app:
    build:
      context: .
      target: prod
```

[NOTE.speaker]
--
L'utilisation de `target` dans Docker Compose vous permet de spécifier quelle étape d'un Dockerfile multi-stage vous souhaitez construire. Cela est particulièrement utile pour adapter l'image à différents environnements sans modifier le Dockerfile lui-même. Dans cet exemple, la cible `prod` est utilisée pour construire l'image de production.
--

// tag::demo[]
=== Démonstration

Création d'un Dockerfile multi-stage avec `target`

[NOTE.speaker]
--
1. Créer un fichier nommé `Dockerfile` avec les étapes `base`, `dev`, `build`, et `prod`.
2. Utiliser Docker Compose pour cibler l'étape `prod`.
3. Construire et exécuter l'image en spécifiant la cible désirée.
4. Expliquer comment chaque étape est optimisée pour son environnement spécifique.
--
// end::demo[]


== Exercices

// tag::exercice[]
=== Exercice 1 : Transformer un Dockerfile traditionnel en multi-stage

Transformez le Dockerfile suivant en un Dockerfile multi-stage :

```dockerfile
FROM node:14
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
RUN yarn build
CMD ["node", "dist/main"]
```
// end::exercice[]

// tag::exercice[]
=== Exercice 2 : Utiliser `target` dans Docker Compose

Utilisez Docker Compose avec l'attribut `target` pour créer une configuration qui construit uniquement l'étape de production du Dockerfile multi-stage.

[NOTE.speaker]
--
Dans l'exercice 1, identifiez les étapes de développement et de production, puis séparez-les en utilisant plusieurs instructions FROM. Dans l'exercice 2, configurez Docker Compose pour utiliser l'attribut `target` afin de cibler le stage de production.
--
// end::exercice[]

// end::deroulement[]

== Conclusion

// tag::conclusion[]
* Le multi-staging permet une optimisation significative des images Docker en séparant les étapes de développement et de production.
* L'utilisation de l'attribut `target` dans Docker Compose offre une grande flexibilité pour gérer différents environnements.
* Ces techniques améliorent la performance, la sécurité, et facilitent la gestion des workflows Docker, tout en réduisant la taille des images et le temps de build.
// end::conclusion[]