:titre: Réseaux
:module: Docker
:duree: 60
:description: On plonge dans les détails des networks Docker appliqués avec Docker Compose.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
// Sous forme de liste à puce, en utilisant la taxonomie de Bloom
* *Appliquer* les network Docker
* *Analyser* les différentes options de configuration
// end::objectifs[]

// tag::deroulement[]
== Réseaux

Les `networks` permettent de connecter plusieurs conteneurs entre eux. Cela permet de communiquer entre les conteneurs sans exposer les ports sur le réseau de l'hôte.

[NOTE.speaker]
--
Par défaut, Compose crée un réseau par projet. Ce réseau est utilisé par défaut pour tous les services du projet. Il est possible de créer des réseaux supplémentaires pour isoler des services.
--

== Configuration

Dans une application classique, le front n'a pas accès directement à la base de données. Il doit passer par le back pour récupérer les données.

```yaml
services:
  front:
    image: nginx:alpine
    ports:
      - 8080:80

  back:
    image: nginx:alpine
    ports:
      - 3000:80
    networks:
      - db-network

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    networks:
      - db-network

networks:
  db-network:
```

[NOTE.speaker]
--
Ici le réseau `db-network` est créé pour isoler les services `db` et `back`. Le service `front` n'a pas besoin d'y accéder.
--

== Multi-réseaux

Toujours dans une application classique, le front communique avec le back uniquement.

```yaml
services:
  front:
    image: nginx:alpine
    ports:
      - 8080:80
    networks:
      - front-network

  back:
    image: nginx:alpine
    ports:
      - 3000:80
    networks:
      - db-network
      - front-network

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    networks:
      - db-network

networks:
  db-network:
  front-network:
```

[NOTE.speaker]
--
Ici, le réseau `front-network` est créé pour isoler le service `front`. Le service `back` a besoin d'accéder aux deux réseaux.
--

// end::deroulement[]

// tag::demo[]
== Démonstration

[NOTE.speaker]
--
* Reprendre le code ci-dessus
* Lancer les services → `docker compose up -d`
* Vérifier les conteneurs → `docker ps` (3 services)
* Ouvrir un Shell interactif dans front → `docker exec -it <nom_du_front> /bin/sh`
** contacter le back → `ping back` (puis `CTRL + C`) > OK
** contacter la DB → `ping db` > KO « ping: bad address 'db' »
** quitter le shell du front → `CTRL + D`
* Ouvrir un Shell interactif dans back → `docker exec -it <nom_du_back> /bin/sh`
** contacter la DB → `ping db` (puis `CTRL + C`) > OK
** quitter le shell du back → `CTRL + D`

> vous pouvez inspecter les réseaux et les conteneurs connectés : `docker network inspect <nom_du_réseau>` (`docker network ls` pour lister les réseaux)
--
// end::demo[]

// tag::exercice[]
== Exercice

Compilez toutes les connaissances acquises pour créer une application avec un front, un back et une base de données : 

* Un front statique avec Nginx
* Un back avec Directus
* Une base de données Postgres
* Un Adminer pour gérer la base de données

Les volumes et les réseaux doivent être correctement configurés pour que les services puissent communiquer entre eux.
// end::exercice[]

== Conclusion

// tag::conclusion[]
* Les réseaux permettent d'isoler les services
* Les services peuvent être connectés à plusieurs réseaux
// end::conclusion[]
