:titre: Dynamisation
:module: nestJs
:duree: 120
:description: Comprendre la Dynamisation
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../adoc/libs
endif::[]

== Objectifs pédagogiques
// tag::objectifs[]
* **Comprendre** le fonctionnement des vues dynamiques avec NestJS et EJS
* **Appliquer** les opérations CRUD complètes dans une application NestJS
* **Créer** des routes et contrôleurs pour gérer les ressources
* **Comprendre** l'utilisation des décorateurs @Render et @Redirect
// end::objectifs[]

// tag::deroulement[]
== Création de ressources

Nous allons finir la fonctionnalité de création de notes en respectant les recommandations de sécurité. Ça nous permettra aussi de voir comment retourner des vues dynamiques (EJS).

Nous allons modifier la méthode de création de notes pour la brancher sur la BDD, et faire en sorte d'afficher les notes créées sur une page dynamique.


== Création et lecture de ressources : les méthodes

. _index_ : retourne une liste de resources.
. _create_ : retourne un formulaire pour créer une ressource.
. _store_ : afficher le détail d'une ressource précise.

== Create & Read

S'agissant de la création de notes, nous avons déjà implémenté quelques éléments, qui sont incomplets, mais qui ont eu le mérite d'illustrer le fonctionnement de NestJS.

Nous allons finir la fonctionnalité de création de notes, et nous passerons aux suivantes.

On commence par les vues, on a besoin d'une page d'accueil et d'une page pour afficher un formulaire.

On a déjà configuré le framework pour qu'il prenne en compte `EJS`, voyons comment lui dire de nous renvoyer ces fichiers.

== Read

[NOTE.speaker]
--
On fournit les fichiers `ejs`
--

Dans `main.ts`, nous avons la ligne suivante `app.setBaseViewsDir(join(__dirname, '..', 'views'));` qui indique que le répertoire des vues s'appelle **views** , et qu'il est situé en dehors du répertoire **src**.

On peut déjà créer ce répertoire. Pour gagner du temps les fichiers **ejs** sont fournis.

On va créer un contrôleur de base qui va rediriger nos requêtes de la route `/` vers la route `/notes`.

[NOTE.speaker]
--
Pourquoi on contourne la route `/` ? Juste pour montrer que c'est possible.
--

Voici le contenu du contrôleur `app.controller.ts` qui se situe à côté de `app.modules.ts`.


== Read : demo

____
Vous êtes libres d'organiser les fichiers **app.*.ts** comme vous voulez, du moment que **main.ts** sait où trouver **app.module.ts**
____

[source,typescript]
----
import { Controller, Get, Redirect } from '@nestjs/common';
@Controller()
export class AppController {
    // ! redirige toutes les requêtes vers /notes
    @Redirect('/notes')
    @Get()
    index() {}
}
----


== Read : démo

Ensuite, on peut faire les méthodes de rendu des notes dans `Notescontroller`

____
Notez le nouveau décorateur @Render(), il ne faut pas oublier de l'importer
____

[source,typescript]
----
// notes.controller.ts
import { Controller, Get, Post, Body, Render } from '@nestjs/common';
@Get()
@Render('index')
index() {
    return {notes: this.notesService.getNotes()};
}

@Get('create')
@Render('notesForm')
create() {}
----

Le décorateur `@Render` sert à envoyer les vues au navigateur.


== Create : démo

Et c'est tout, avec ces deux méthodes, on devrait avoir des vues dans le navigateur sur les URLs suivantes :

* http://localhost:3000/notes
* http://localhost:3000/notes/create


== Create : demo

On a un formulaire et l'API qui fonctionne, créons donc une note dans la BDD, nous n'aurons pas de validation pour le moment, on s'occupera de tout ça en même temps lorsque nous implémenterons l'authentification.

Il s'agit de modifier le service `notes.service.ts`, dans la méthode `create`, on change _build_ pour https://sequelize.org/docs/v6/core-concepts/model-instances/#a-very-useful-shortcut-the-create-method[_create_] et on change la signature de la méthode :

[source,typescript]
----
// notes.service.ts
async create(noteBody): Promise<Note> {
    const note: Note = await this.noteModel.create(noteBody);
    return note;
}
----


== Create : demo

Dans la méthode `index` de `notesController`, on retourne un objet avec une propriété `notes` qui contient le résultat de la méthode `getNotes` du `notesService`:

[source,typescript]
----
// notes.controller.ts
async index() {
    return { notes: await this.notesService.getNotes() };
}
----


== Create : demo

On ajoute un décorateur à la méthode `store` afin qu'elle nous redirige vers la page `/notes` après qu'on a créé une note.

Ne pas oublier **d'importer** le décorateur :).

[source,typescript]
----
// notes.controller.ts
@Post()
@Redirect('/notes')
store(@Body() createNoteDto: CreateNoteDto): Note {
    const notesObj = this.notesService.create(createNoteDto);

    return notesObj;
}
----

[background-color=var(--r-oclock-color)]
== Create : demo

On peut maintenant voir les notes sur la page http://localhost:3000/notes[].

On peut aussi tester le formulaire pour créer une note.

Ne pas oublier de lire les fichiers ejs pour constater qu'ils ne sont pas différents de ceux que l'on ferait si on utilisait `Express` seul.

// Les fichiers suivants :  Si on a besoin de montrer le CRUD en mode monolith : dans ce cas pas de verbes http, que du GET et POST.

== show

Afficher une ressource devrait être plus direct et plus simple, il y a juste deux particularités à prendre en compte :

* on récupère le paramètre d'URL avec un décorateur

* on convertit explicitement ce paramètre en nombre `(+id)` pour que typescript nous laisse tranquille :

[source ,typescript]
----
// notes.controller.ts
// * On paramètre la route avec l'id
@Get(':id')
@Render('noteDetail')
// * On récupère l'ID avec un décorateur que l'on doit importer
async show(@Param('id') id: string): Promise<object> {
    // * Le + devant une string convertit celle-ci en nombre : '1' devient alors 1
    return { note: await this.notesService.find(+id) };
}
----


== show

On doit créer la méthode `find` dans le service et on fait appelle à https://sequelize.org/docs/v6/core-concepts/model-querying-finders/#findbypk[la méthode `findByPk`  de sequelize] :

[source ,typescript]
----
// notes.service.ts
async find(noteId: number): Promise<Note> {
    return await this.noteModel.findByPk(noteId);
}
----

On peut customiser le paramètre d'URL, si on souhaite paramétrer les URL avec le titre d'une note plutôt qu'un ID, dans ce cas, il faudra aussi changer la requête du service et utiliser https://sequelize.org/docs/v6/core-concepts/model-querying-finders/#findone[la méthode `findOne` de sequelize].


== edit

La partie édition concerne la fonctionnalité de mise à jour d'une ressource, `edit` signifie que l'on souhaite apporter des changements à l'existant, on doit donc récupérer une ressource et l'afficher dans un formulaire pour pouvoir l'éditer. C'est la première partie de la fonctionnalité de mise à jour.

On a déjà une méthode dans le service `notes` qui nous permet d'aller chercher une ressource, on n'a qu'à s'en resservir pour l'éditer. C'est pareil pour le formulaire, on se ressert du formulaire de création de notes.

[background-color=var(--r-oclock-color)]
:tip-caption: 💡
[TIP]
===
*__
Pour l'instant, nous n'avons pas de système d'authentification en place, dans la vie réelle, il faudra s'assurer que la personne qui tente de modifier un élément soit autorisé à le faire.
__*
===


== edit : le contrôleur

Voici la méthode `edit` de `NotesController` :

[source ,typescript]
----
// notes.controller.ts
@Get(':id/edit')
@Render('notesForm')
async edit(@Param('id') id: string) {
    return { note: await this.notesService.find(+id) };
}
----

L'URL complète est `/notes/:id/edit`, il faut faire attention avec les URL dynamiques, si on ne mettait que l'ID, on pourrait potentiellement avoir un conflit avec l'URL `/create`.

Dans ce cas, il faudrait jouer avec l'ordre des méthodes dans le contrôleur, ce qui n'est pas bien pratique, (mais on va peut-être rencontrer le problème sous peu quand meme..).


== update

Dans cette seconde partie de la fonctionnalité de mise à jour, on souhaite persister les données en BDD, il nous faut une nouvelle méthode, un nouveau DTO qui héritera du précédent.

N'oublions pas d'importer les nouveaux éléments dans le contrôleur.

Voici la méthode update du contrôleur, cette méthode n'a rien de particulier, on a juste ajouté le suffix `/update` à l'URL pour être constant :

[source ,typescript]
----
// notes.controller.ts
@Post(':id/update')
@Redirect('/notes')
update(@Param('id') id: string, @Body() updateNoteDto: UpdateNoteDto) {
    return this.notesService.update(+id, updateNoteDto);
}
----


== update : le service

Voyons la méthode update du service `notes` :

[source ,typescript]
----
// notes.service.ts
async update(id: number, updateNoteDto: UpdateNoteDto) {
    return await this.noteModel.update(updateNoteDto, { where: { id } });
}
----

Rien de particulier, si ce n'est que l'on continue à utiliser le DTO.


== update : le DTO

Enfin, l'élément "_le plus important_", le DTO :

[source ,typescript]
----
// dto/update-note.dto.ts
import { PartialType } from '@nestjs/mapped-types'; // il faudra l'installer
import { CreateNoteDto } from './create-note.dto';

export class UpdateNoteDto extends PartialType(CreateNoteDto) {}
----

Comme préciser dans https://docs.nestjs.com/techniques/validation#mapped-types[la documentation de Nest], on a une classe qui étend le précédent DTO, on évite de se répéter, et au moment voulu, on pourra le modifier pour y inclure l'ID de ceux qui ont modifié une note, ajouter des collaborateurs etc, etc.

== delete

L'effacement de données est la plus simple des fonctionnalités, tellement simple qu'il faut demander à l'utilisateur s'il est sûr de lui, on vous laissera implémenter ça côté front, on a choisi un formulaire et une route POST pour cette fonctionnalité.

Voici ce que ça donne dans le contrôleur et le service :

[source ,typescript]
----
// notes.controller.ts
@Post(':id/delete')
@Redirect('/notes')
async destroy(@Param('id') id: string) {
    return await this.notesService.destroy(+id);
}
----

[source ,typescript]
----
// notes.service.ts
async destroy(id: number) {
    return await this.noteModel.destroy({ where: { id } });
}
----

// end::deroulement[]

== Conclusion
// tag::conclusion[]
* Maîtrise de la création et l'affichage de vues dynamiques avec EJS
* Capacité à implémenter un CRUD complet (Create, Read, Update, Delete)
* Compréhension de l'utilisation des décorateurs spécifiques aux vues
* Aptitude à gérer les redirections et le rendu des pages
* Maîtrise de l'interaction entre les contrôleurs, services et vues
// end::conclusion[]