:titre: Associations
:module: nestJs
:duree: 120
:description: Comprendre les Associations
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../adoc/libs
endif::[]

== Objectifs pédagogiques
// tag::objectifs[]
* **Comprendre** les différents types d'associations dans NestJS avec Sequelize
* **Appliquer** la mise en place d'associations many-to-many
* **Créer** des tables de liaison entre entités
* **Comprendre** l'utilisation des décorateurs d'association (@BelongsToMany)
// end::objectifs[]

// tag::deroulement[]
== Associations et clés primaires

Il est temps de s'attaquer aux associations entre les modèles, sequelize offre des méthodes simples pour faire cela, l'intégration à NestJS est simple, mais il y a beaucoup d'étapes à respecter.

Quelques lignes suffisent à intégrer les associations.

== Associations : tables de liaisons

On a prévu une application collaborative, ainsi qu'une authentification dite RBAC (https://fr.wikipedia.org/wiki/Contr%C3%B4le_d'acc%C3%A8s_%C3%A0_base_de_r%C3%B4les[Role Based Access Control]), ou un utilisateur peut avoir plusieurs rôles et ces rôles peuvent avoir plusieurs permissions.

Cela signifie que nous allons avoir des associations avec des tables de liaisons, on va donc devoir créer des modèles à part pour mettre en place les associations.

=== Associations : tables de liaisons

On commence avec `User` et `Notes`, on a dit qu'un utilisateur pourrait éditer plusieurs notes et qu'une note pourrait être éditée par plusieurs utilisateurs, la table de liaison devra référencer les ID des deux entités.

On commence par faire un répertoire `associations`, on y mettra des répertoires correspondants aux modèles qu'on souhaite associer.

// tag::demo[]
== Démonstration 01

NoteHasUser

[NOTE.speaker]
--

Démonstration 01 Associations : noteHasUser


Voici le code de l'entité `NoteHasUser` de la table de liaison :


[source ,typescript]
----
// src/associations/noteHasUser/noteHasUser.entity.ts
import { Column, Model, Table, ForeignKey } from 'sequelize-typescript';
import { User } from '../../users/entities/user.entity';
import { Note } from '../../notes/entities/note.entity';
@Table({ tableName: 'note_has_user' })

class NoteHasUser extends Model {
    @ForeignKey(() => User)
    @Column
    userId: number;

    @ForeignKey(() => Note)
    @Column
    noteId: number;
}

export { NoteHasUser };
----
--
// end::demo[]

// tag::demo[]
== Démonstration 02

Un module pour brancher la table de liaison

[NOTE.speaker]
--
*Démonstration 02 Associations : Le module*

== Description

Dans le même répertoire, on va mettre un module pour brancher la table de liaison dans l'application, enfin, on ira dire à nos modèles qu'ils sont associés, et `NestJS` devrait faire le reste.

*Code*

[source ,typescript]
----
// src/associations/noteHasUser/noteHasUser.module.ts
import { Module } from '@nestjs/common';
import { SequelizeModule } from '@nestjs/sequelize';
import { NoteHasUser } from './noteHasUser.entity';

@Module({
    imports: [SequelizeModule.forFeature([NoteHasUser])],
    exports: [SequelizeModule],
})
export class UsersHaveNotesModule {}
----
--
// end::demo[]

// tag::demo[]
== Démonstration 03

Modifications du modèle `Note`

[NOTE.speaker]
--
Démonstration 03 Associations : Les modèles

*Description*

Voici les modifications du modèle `Note` :

*Code*

[source ,typescript]
----
import { Column, Model, Table, BelongsToMany } from 'sequelize-typescript';
import { User } from '../../users/entities/user.entity';
import { NoteHasUser } from '../../associations/noteHasUser/noteHasUser.entity';

@Table({ tableName: 'notes' })
class Note extends Model {
    // ...
    @BelongsToMany(() => User, () => NoteHasUser)
    users: User[];
}
----

--
// end::demo[]

// tag::demo[]
== Démonstration 04

Modifications du modèle `User`

[NOTE.speaker]
--

Démonstration 04 Associations : Les modèles

Description

Voici les modifications du modèle `User` :

Code

[source ,typescript]
----
import { Column, Model, Table, BelongsToMany } from 'sequelize-typescript';
import { NoteHasUser } from '../../associations/noteHasUser/noteHasUser.entity';
import { Note } from '../../notes/entities/note.entity';
@Table({ tableName: 'users' })
class User extends Model {
    // ...
    @Column({
        allowNull: false,
        validate: {
            isEmail: true,
        },
    })
    email: string;

    @BelongsToMany(() => Note, () => NoteHasUser)
    users: User[];
}

export { User };
----

--
// end::demo[]

=== Association UserHasNote : Fin

Si tout se passe bien, on devrait obtenir les tables avec leurs associations en BDD. (on peut vérifier avec un outil de type dbeaver ou autre adminer)

// tag::exercice[]
== Exos du jour

* Faire un module complet `Role`
* Faire un module complet `Permissions`
* Mettre en place l'association `many-to-many` entre `Role` et `Permission`.

== Correction

[NOTE.speaker]
--
* Faire un module complet `Role`
** Grâce à la CLI de NestJS, on peut générer un module complet (module, controller, service, DTO et modèle) avec la commande :
*** `nest g res roles`
+
[source, bash]
----
➜ nest g res roles --no-spec
? What transport layer do you use? REST API
? Would you like to generate CRUD entry points? Yes
CREATE src/roles/roles.controller.ts (894 bytes)
CREATE src/roles/roles.module.ts (248 bytes)
CREATE src/roles/roles.service.ts (609 bytes)
CREATE src/roles/dto/create-role.dto.ts (30 bytes)
CREATE src/roles/dto/update-role.dto.ts (169 bytes)
CREATE src/roles/entities/role.entity.ts (21 bytes)
UPDATE src/app.module.ts (604 bytes)

----
** On peut maintenant aller détailler le modèle role dans le fichier `role.entity.ts` :
+
[source,typescript]
----
import { Column, Model, Table, BelongsToMany } from 'sequelize-typescript';
@Table({ tableName: 'roles' })

class Role extends Model {
    @Column
    name: string;
}

export { Role };
----
** On connecte le modèle à Sequelize dans le module role :
+
[source,typescript]
----
import { Module } from '@nestjs/common';
import { SequelizeModule } from '@nestjs/sequelize';
import { RolesService } from './roles.service';
import { RolesController } from './roles.controller';
import { Role } from './entities/role.entity';

@Module({
    imports: [SequelizeModule.forFeature([Role])], // On vient connecter le modèle à l'ORM
    controllers: [RolesController],
    providers: [RolesService],
    exports: [SequelizeModule, RolesService], // on n'oublie pas de l'exporter pour pouvoir l'utiliser dans d'autres modules
})
export class RolesModule {}
----

* Faire un module complet `Permissions`
** On répète exactement les mêmes étapes que pour le module `Role`.

* Mettre en place l'association `many-to-many` entre `Role` et `Permission`.

** On commence par créer un nouveau répertoire `roleHasPermission` dans le répertoire `src/associations/authorizations`.

** On crée un nouveau fichier `roleHasPermission.entity.ts` dans le répertoire `src/associations/authorizations/roleHasPermission` qui contiendra le modèle de notre table de liaison :
+
[source, typescript]
----
import { Column, Model, Table, ForeignKey } from 'sequelize-typescript';
import { Role } from '../../../roles/entities/role.entity';
import { Permission } from '../../../permissions/entities/permission.entity';
@Table({ tableName: 'role_has_permission' })
class RoleHasPermission extends Model {
    @ForeignKey(() => Role)
    @Column
    roleId: number;

    @ForeignKey(() => Permission)
    @Column
    permissionId: number;
}
export { RoleHasPermission };
----
** On crée un nouveau module `RoleHasPermission` dans le répertoire `src/associations/authorizations/roleHasPermission` :
+
[source, bash]
----
nest g mo role-has-permission --no-spec
----
** Et on y met le code suivant :
+
[source, typescript]
----
import { Module } from '@nestjs/common';
import { SequelizeModule } from '@nestjs/sequelize';
import { RoleHasPermission } from './roleHasPermission.entity';

@Module({
    imports: [SequelizeModule.forFeature([RoleHasPermission])],
    exports: [SequelizeModule],
})
export class RoleHasPermissionModule {}
----
** On va connecter ce module à notre application dans le fichier `app.module.ts` :
+
[source, typescript]
----
//imports
import { RoleHasPermissionModule } from './associations/authorizations/rolePermission/roleHasPermission.module';

@Module({
    imports: [
          // ...
        RoleHasPermissionModule

    ],
// ...
})
----
** On ajoute les décorateurs `@BelongsToMany` dans les modèles `Role` et `Permission`.

*** Dans le modèle `Role` :
+
[source, typescript]
----
import { Column, Model, Table, BelongsToMany } from 'sequelize-typescript';
import { Permission } from '../../permissions/entities/permission.entity';
import { RoleHasPermission } from '../../associations/authorizations/rolePermission/roleHasPermission.entity';

@Table({ tableName: 'roles' })

class Role extends Model {
    @Column
    name: string;

    @BelongsToMany(() => Permission, () => RoleHasPermission)
    permissions: Permission[];

}

export { Role };
----
*** Dans le modèle `Permission` :
+
[source, typescript]
----
import { Column, Model, Table, BelongsToMany } from 'sequelize-typescript';
import { Role } from '../../roles/entities/role.entity';
import { RoleHasPermission } from '../../associations/authorizations/rolePermission/roleHasPermission.entity';

@Table({ tableName: 'permissions' })

class Permission extends Model {
    @Column
    name: string;

    @BelongsToMany(() => Role, () => RoleHasPermission)
    roles: Role[];
}
----

Si tout s'est bien passé, on devrait obtenir les tables avec leurs associations en BDD.
--
// end::exercice[]

// end::deroulement[]

== Conclusion
// tag::conclusion[]
* Maîtrise de la création d'associations entre entités avec Sequelize
* Compréhension de la structure nécessaire pour les relations many-to-many
* Capacité à implémenter des tables de liaison
* Aptitude à utiliser les décorateurs d'association appropriés
* Maîtrise de l'organisation modulaire des associations dans NestJS
// end::conclusion[]