:titre: Liste de lecture
:module: Bases web
:duree: 60
:description: On part du fichier txt et on le copie dans un fichier HTML vide, puis on créé les balises HTML en fonction.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]


== Objectifs
// tag::objectifs[]
* *Comprendre* la structure d'un document HTML
* *Analyse* les différentes balises HTML
* *Utiliser* GitHub Copilot pour convertir efficacement du texte en HTML structuré
* *Évaluer* la pertinence des suggestions de balises proposées par Copilot
// end::objectifs[]

// tag::deroulement[]
// tag::demo[]
== Démonstration

ifeval::["{visible-on-html}" !=  "yes"]

[.tips]
--
💡 Appuyer sur la touche "*s*" pour le mode speaker
--

endif::[]

Utiliser le support https://github.com/O-clock-FS-JS/Fond-forme/tree/master/[Fiche de lecture,window=_blank].

[NOTE.speaker]
====
1. Conversion du fichier texte en HTML :
+
On commence par copier le contenu du fichier texte dans un fichier HTML vide, puis on structure le contenu en ajoutant les balises HTML appropriées.

2. Choix des balises basé sur le sens du contenu :
+
Le choix des balises HTML (comme <h1>, <h2>, etc.) dépend du sens et de l'importance des éléments. Les robots ne peuvent pas interpréter le contexte ou l'importance d'une page sans indication explicite, d’où l’importance d’utiliser des balises sémantiques.

3. Finalisation de la structure HTML :
+
Une fois tout le contenu structuré avec des balises HTML, vous pouvez considérer cet exercice comme terminé.
(Exercice possible : convertir un autre texte en HTML pour s’entraîner.)

4. Ajout de liens et d’images :
+
Vous pouvez ajouter un lien vers le dossier 2-modele pour introduire la balise <a> et éventuellement aborder l’attribut target="_blank". De même, insérer une image permet de présenter la balise <img>.

5. Introduction à GitHub Copilot :
+
En guise d'optimisation, vous pouvez utiliser GitHub Copilot pour accélérer la conversion. En écrivant des commentaires comme `<!-- Convertir ce texte en structure HTML -->` ou `<!-- Créer une liste de livres avec titre et auteur -->`, Copilot suggérera automatiquement la structure HTML appropriée. Il est important de vérifier et d'ajuster les suggestions pour s'assurer qu'elles respectent la sémantique souhaitée.
====
// end::demo[]

// end::deroulement[]