:titre: Démo Chaussons
:module: Bases web
:duree: 120
:description: Utilisation du repo https://github.com/O-clock-FS-JS/Chaussons-box-model[Démo Chaussons,window=_blank] pour réaliser une démonstration complète en live.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
* *Comprendre* ce qu'est le box model
* *Analyser* les propriétés CSS pour dimensionner les éléments
// end::objectifs[]

// tag::deroulement[]


// tag::demo[]
== Démonstration

ifeval::["{visible-on-html}" !=  "yes"]

[.tips]
--
💡 Appuyer sur la touche "*s*" pour le mode speaker
--

endif::[]

Se baser sur le https://github.com/O-clock-FS-JS/Chaussons-box-model[repo Chaussons,window=_blank].

[NOTE.speaker]
--
* A ce niveau, on peut montrer emmet `lorem` ( `lorem*3`, `lorem50`, ou même `lorem50*3`)
* On peut d'ailleurs parler un peu plus en détail de emmet en montrant la CheatSheet → https://docs.emmet.io/cheat-sheet/

Les balises ancres peuvent avoir des liens spéciaux ( mailto: et tel: ), on peut en parler sans forcément y passer des heures

On rajoute de nouvelles balises sémantiques : 

* `header` ( contenu introductif, on peut en mettre plusieurs ), suivant l’ancêtre, ils auront pas le même contexte sémantique
* `footer` ( contenu complémentaire, on peut en mettre plusieurs ) , suivant l’ancêtre, ils auront pas le même contexte sémantique
* `main` ( contenu principal limité à 1 par page )

On introduit les **reset css**, puisqu’il y a des styles par défaut qui peuvent être différents d'un navigateur à l'autre, alors on va surcharger, il faut être sûr que la base est la même partout. https://codepen.io/ncerminara/pen/RLMwmy[Comparaison,window=_blank] et https://meyerweb.com/eric/tools/css/reset/[Reset,window=_blank]

On doit faire un container, on parle de box-model, on explique la différence entre block et inline :

* `block` c’est des gros patapouf et qui impose un retour à la ligne après et qui occupent toute la ligne, ils sait pousser ses voisins au dessus et en dessous
* `inline` c’est un timide, qui n’impose pas un retour à la ligne, et qui ne sait pas pousser ses voisins au dessus et en dessous

On peut montrer sur http://cssreference.io que chaque balises est soit `inline` soit `block` ( sauf rares exceptions comme img se comporte un peu comme les 2 )

Il existe 2 balises vide de sens, div et span, qu’on peut utiliser si on a besoin d’un conteneur qui n’a pas de sens particulier ( sémantiquement parlant ) à la différence que la `div` est `block` et le `span` est `inline`

* Faire un dimensionnement du container avec `width` et `height`
** On s'arrête une minute, l’image dépasse du conteneur, elle fausse tout, pour l’instant on ne va pas gérer le problème, on la cache, on la met en `display: none`, et on en profite de parler de `display` sert à changer le type de boite.

On parle des sélecteurs CSS principalement pour l'image : * pour tout sélectionner, espace (tous les éléments dans la descendance), `>` enfant directs, `+` le premier élément, ... on présente le site qui permet de s'entrainer https://flukeout.github.io/[Bento CSS]

**Durée restante** : 1h

> ⌚ S'il reste plus d'1h devant vous, privilégier la `width` en `%` avec une `max-width` en `px` par exemple - aspect responsive qui sera traité en épisode 8 plus en détail

* Maintenant que le conteneur est bien dimensionné, on met une `width: 100%` à l’image pour plus qu’elle dépasse et on enlève le `display: none`
* Puis on explique `margin` pour l'extérieur, `margin: auto` qui centre dans le parent, on applique un `margin` en haut et en bas des paragraphes et on voit on constate ceci : 

> Les marges supérieure et inférieure des blocs sont parfois combinées (réduites) en une seule marge dont la taille est la plus grande des marges individuelles (ou juste l'une d'entre elles, si elles sont égales), un comportement connu sous le nom de réduction des marges.

* On explique `padding` pour l'intérieur avec par exemple l’image du corps humain : 
  ** La zone de contenu c’est les boyaux
  ** Le `padding` c’est le gras
  ** La peau la bordure
  ** L’espace vitale autour c’est le margin
* On parle de `box-sizing: border-box` au lieu de `box-sizing: content box`
** **content-box:** sur une boite de 500px avec 20px de padding, la div fera `540px`
** **border-box:** sur une boite de 500px avec 20px de padding, la div fera toujours `500px`, mais zone de contenu plus petite
* Parler des propriété raccourcies, `padding` au lieu de `padding-left` `padding-right` ect … ( pareil pour `margin` ) on part à midi et on tourne dans le sens des aiguilles d’une montre, 
* Puis on fini en parlant de border, les types et les tailles et les couleurs de bords
--
// end::demo[]

// end::deroulement[]

// tag::conclusion[]
// end::conclusion[]