:title: Playbook avancé
:number: 03
include::../../../../../../adoc/libs/header-episode.adoc[]

// tag::intro[]
Les apprenants approfondiront leurs compétences en Ansible en utilisant des playbooks plus complexes pour la gestion de bases de données et la configuration de politiques de sécurité. Ils exploreront des concepts avancés et l’utilisation de variables et de rôles.
// end::intro[]

== Objectifs pédagogiques

// tag::objectifs[]
*  *Application* : Appliquer des playbooks avancés pour gérer des bases de données et des politiques de sécurité
*  *Analyse* : Utiliser des variables et des rôles pour améliorer la modularité des playbooks
*  *Analyse* : Analyser les besoins spécifiques de configuration et adapter les playbooks en conséquence
// end::objectifs[]

// tag::prerequis[]
// end::prerequis[]

== Déroulement

// tag::deroulement[]
=== Correction

NOTE: 60 minutes

link:https://github.com/O-clock-Devops-Peda/S08-Challenge[Challenge S08]

TIP: ☕ Pause café

include::../../../../modules/ansible/playbook-databases.adoc[options=modules]

TIP: 🍕 Pause déjeuner

include::../../../../modules/ansible/playbook-policies.adoc[options=modules]

include::../../../../modules/ansible/callbacks.adoc[options=modules]

:challenge: https://github.com/O-clock-Devops-Peda/S08-Challenge
:description: Exploratoire : installer mongodb avec un role ansible galaxy
:correction: 
include::../../../../../../adoc/libs/intro-challenge.adoc[]

// end::deroulement[]