:titre: Dockerfile
:module: Devops
:duree: 60
:description: Rendre le front fonctionnel en exécutant les étapes nécessaires pour lancer le bundler Vite
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
* **Se rappeler** des concepts de Dockerfile
* **Appliquer** les commandes docker
// end::objectifs[]

// tag::deroulement[]
== Introduction

* **Définition** : Fichier script pour construire une image Docker.
* **Structure** : Instructions pour définir les couches de l'image.

[NOTE.speaker]
====
Un Dockerfile est un fichier texte qui contient des instructions pour assembler une image Docker. Chaque instruction dans le Dockerfile crée une nouvelle couche dans l'image, permettant de construire des environnements personnalisés adaptés aux besoins spécifiques de l'application.
====

== Différence en Dockerfile et docker-compose

La différence principale entre un Dockerfile et un docker-compose.yml réside dans leur usage et leur portée.

* Dockerfile : Création d'une image Docker
* Docker Compose : Définition d'un environnement multi-conteneurs

[NOTE.speaker]
====

*Dockerfile : Création d'une image Docker*

Un Dockerfile est un script contenant une série d'instructions qui définissent comment construire une image Docker. Il sert à créer un environnement de conteneur reproductible.

Utilisation :

* Décrit comment construire une image (base, dépendances, configurations…).
* Utilisé avec docker build pour générer une image.
* Définit un seul conteneur.

Cas d'usage : Quand on veut définir une image personnalisée pour un projet.

Commandes associées : docker build, docker run

*Docker-compose.yml : Orchestration de plusieurs conteneurs*

Comme vu précédemmment, Docker Compose est un outil pour définir et gérer des applications multi-conteneurs. Il permet de définir les services, les réseaux, les volumes, etc. pour un environnement complet.

Commandes associées : docker-compose up, docker-compose down
====

== Différence en Dockerfile et docker-compose

* Nom du fichier pour docker-compose : `docker-compose.yml`
* Nom du fichier pour Dockerfile : `Dockerfile`

== Concepts clés

* **FROM** : Déclare l'image de base à utiliser comme point de départ.
* **COPY** : Copie des fichiers ou répertoires de l'hôte vers le système de fichiers de l'image.
* **RUN** : Exécute des commandes en ligne de commande pendant la construction de l'image.
* **CMD** : Spécifie la commande par défaut à exécuter lorsque le conteneur démarre.
* **ENV** : Définit des variables d'environnement dans l'image.
* **ARG** : Définit des variables qui peuvent être passées à l'image lors de la construction.

[NOTE.speaker]
====
Ces instructions sont essentielles pour construire des Dockerfiles efficaces. 

* `FROM` initialise une image de base
* `COPY` transfère des fichiers dans l'image
* `RUN` exécute des commandes durant la construction
* `CMD` définit la commande de démarrage du conteneur
* `ENV` ou `ARG` configurent des variables.

====

=== ARG vs ENV

* **ARG** : Variables utilisées lors de la construction de l'image.
* **ENV** : Variables d'environnement utilisées lors de l'exécution du conteneur.

[NOTE.speaker]
====
Les variables définies avec `ARG` sont accessibles pendant la construction de l'image, tandis que celles définies avec `ENV` sont disponibles lors de l'exécution du conteneur. Il est important de comprendre la différence pour éviter les erreurs de configuration.
====

== Syntaxe et fonctionnement

* **Instruction** : Chaque ligne du Dockerfile est une instruction qui effectue une action.
* **Argument** : La plupart des instructions prennent un ou plusieurs arguments.
* **Commentaires** : Les lignes commençant par `#` sont des commentaires.

[NOTE.speaker]
====
Chaque ligne d'un Dockerfile est interprétée comme une instruction spécifique. Les instructions doivent être en majuscules et suivies des arguments nécessaires. Les commentaires aident à documenter le fichier pour une meilleure compréhension.
====

== Syntaxe pour utiliser ENV pour définir une variable statique

```dockerfile
FROM node:18

# Définition d'une variable d'environnement
ENV PORT=3000
ENV NODE_ENV=production

# Définition du répertoire de travail
WORKDIR /app

# Copie des fichiers et installation des dépendances
COPY package.json ./
RUN npm install

# Copie du code source
COPY . .

# Exposition du port
EXPOSE $PORT

# Commande exécutée au démarrage du conteneur
CMD ["node", "server.js"]
```

[NOTE.speaker]
====
Ici, PORT et NODE_ENV sont accessibles dans le conteneur.
====

=== Exemple de Dockerfile pour Vite

```dockerfile
ARG PORT=3000

# Étape 1 : Utiliser une image de base Node.js
FROM node:20-alpine

# Étape 2 : Définir le répertoire de travail
WORKDIR /app

# Étape 3 : Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Étape 4 : Installer les dépendances
RUN npm install

# Étape 5 : Copier le reste des fichiers du projet
COPY . .

# Étape 6 : Exposer le port utilisé par Vite
EXPOSE ${PORT}

# Étape 7 : Démarrer le serveur de développement Vite
CMD ["npm", "run", "dev", "--host"]
```

[NOTE.speaker]
====
Ce Dockerfile utilise une image Node.js comme base, copie les fichiers de configuration du projet, installe les dépendances nécessaires, et démarre le serveur de développement Vite. 

* Les images alpines sont des images légères basées sur Alpine Linux, idéales pour les conteneurs Docker en raison de leur taille réduite.
* Par défaut, le port définit à 3000. L'argument `PORT` peut être modifié lors de la construction de l'image. Le port est exposé pour permettre l'accès à l'application front-end.

====

== Commandes principales

* **Lister les images** : `docker images`
* **Construire une image** : `docker build -t my-vite-app .`
* **Exécuter un conteneur** : `docker run -p 3000:3000 my-vite-app`
* **Lister les conteneurs en cours d'exécution** : `docker ps`
* **Arrêter un conteneur** : `docker stop <container_id>`
* **Supprimer une image** : `docker rmi my-vite-app`

[NOTE.speaker]
====
Pour créer une image Docker à partir d'un Dockerfile, utilisez la commande `docker build`. L'option `-t` permet de taguer l'image avec un nom. Pour exécuter l'image sous forme de conteneur, utilisez `docker run` et exposez les ports nécessaires. Les commandes `docker ps` et `docker stop` permettent de gérer les conteneurs en cours d'exécution.
====

// tag::demo[]
== Démonstration

Construction et exécution de l'image Docker

[NOTE.speaker]
====
* Créer un nouveau projet `Vite`
** `npm create vite@latest my-vue-app -- --template vue`
* Positionnez vous dans le projet `Vite`
** `cd my-vue-app`
* Créer un fichier nommé `Dockerfile` à la racine du projet `Vite`.
* Insérer le contenu de l'exemple de Dockerfile.
* Ouvrir un terminal et naviguer vers le répertoire du projet.
* Exécuter `docker build -t my-vite-app .` pour construire l'image.
* Exécuter `docker run -p 3000:3000 my-vite-app` pour lancer le conteneur.
* L'application n'est pas accessible car le serveur de développement Vite tourne sur le port 5173.
* Re builder l'image en passant le port 5173 en argument : `docker build --build-arg PORT=5173 -t my-vite-app .`.
* Exécuter à nouveau le conteneur avec `docker run -p 3000:5173 my-vite-app`.
* Accéder à l'application via `http://localhost:3000`.
* Pour exposer l'application vite sur le port 3000, il faut modifier le script `dev` dans le `package.json` pour ajouter l'option `--host`.
** 
```json
{
  "name": "my-vue-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite --host",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.5.13"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.2.1",
    "vite": "^6.2.0"
  }
}
```
====
// end::demo[]

// tag::exercice[]
== Exercice

Ajouter une variable d'environnement pour modifier le titre h1 de l'application

⚠️ VITE_ est un préfixe obligatoire réservé pour les variables d'environnement dans Vite.

1. Modifier le Dockerfile pour ajouter une variable d'environnement personnalisée à l'aide de `ENV`.
2. Utiliser cette variable dans l'application pour afficher un message personnalisé.
3. Reconstruire l'image Docker avec la nouvelle configuration.
4. Lancer le conteneur et vérifier que la variable est correctement affichée dans l'application.

[NOTE.speaker]
====
Il existe plusieurs façons de passer des variables, notamment avec un fichier `.env` ou des arguments de ligne de commande. L'important est de savoir faire au moins d'une manière et adapter la méthode lorsque vous aurez plus d'expérience.
====

== Correction

.Fichier Dockerfile
```dockerfile
ARG PORT=3000

# Étape 1 : Utiliser une image de base Node.js
FROM node:20-alpine

ENV VITE_MESSAGE_IN_THE_BOTTLE="Wololo from Docker!"

# Étape 2 : Définir le répertoire de travail
WORKDIR /app

# Étape 3 : Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Étape 4 : Installer les dépendances
RUN npm install

# Étape 5 : Copier le reste des fichiers du projet
COPY . .

# Étape 6 : Exposer le port utilisé par Vite
EXPOSE ${PORT}

# Étape 7 : Démarrer le serveur de développement Vite
CMD ["npm", "run", "dev", "--host"]
```

.Fichier package.json
```json
{
  "name": "my-vue-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite --host",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.5.13"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.2.1",
    "vite": "^6.2.0"
  }
}
```

.fichier .App.vue
```vue	
<script setup>
import HelloWorld from './components/HelloWorld.vue'

const message = import.meta.env.VITE_MESSAGE_IN_THE_BOTTLE;
</script>

<template>

  <h1>{{ message }}</h1>

  <div>
    <a href="https://vite.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Vite + Vue" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
```
// end::exercice[]

// end::deroulement[]

== Conclusion

// tag::conclusion[]
* Un Dockerfile est un script pour construire des images Docker.
* Les instructions de base incluent `FROM`, `COPY`, `RUN`, `CMD`, `ENV`, et `ARG`.
* Les commandes Docker essentielles permettent de construire et exécuter des images.

[NOTE.speaker]
====
Vous avez appris à créer une image Docker pour une application front-end avec Vite. Il est possible de faire de même pour un back-end.
====
// end::conclusion[]