:titre: Docker compose avancé
:module: Devops
:duree: 120
:description: Aborder les notions plus avancées pour améliorer notre environnement : volumes, networks, ports, variables d'environnement, healthchecks.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
* **Appliquer** les options de configuration avancées
* **Analyser** la qualité d'une configuration docker compose
// end::objectifs[]

// tag::deroulement[]
== Introduction

* Utilisation avancée de Docker Compose pour optimiser les environnements.
* Concepts clés : volumes, networks, ports, variables d'environnement, healthchecks.
* Objectif : Rendre les configurations plus robustes et flexibles.

[NOTE.speaker]
====
En DevOps, un healthcheck (ou vérification de l'état de santé) est une technique utilisée pour surveiller l'état et la disponibilité d'une application, d'un service ou d'une infrastructure. Il permet de s'assurer qu'un service fonctionne correctement et de détecter automatiquement les dysfonctionnements.
====

== Volumes et persistance des données

* **Volumes** : Conservent les données entre les arrêts de conteneurs.
* Types de volumes : Volumes nommés et volumes anonymes.

```yaml
services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
  front:
    image: nginx
    volumes:
      - /path/to/local:/usr/share/nginx/html

volumes:
    db_data:
```

[NOTE.speaker]
====
Les volumes permettent de préserver les données même lorsque les conteneurs sont redémarrés ou supprimés. Les volumes nommés sont partagés entre plusieurs conteneurs, tandis que les volumes anonymes sont spécifiques à un conteneur.

Pour supprimer les volumes, exécutez `docker compose down -v`.
====

== Variables d'environnement

Il est possible d'utiliser des variables d'environnement dans les compose pour les rendre plus flexibles. Ces variables peuvent être définies dans :

* Un fichier `.env`.
* Directement dans le fichier `docker-compose.yml`.

== Variables d'environnement

```yaml
services:
  adminer:
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=pgsql 
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
```

== Variables d'environnement

.Fichier .env
```
POSTGRES_USER=user
POSTGRES_PASSWORD=password
```

== Ports et exposition des services

* **Ports** : Exposent les services à l'extérieur du conteneur.
* Syntaxe de mappage : `host_port:container_port`.

```yaml
services:
  front:
    image: nginx
    ports:
      - 80:80
  adminer:
    image: adminer
    ports:
      - 81:8080
```

[NOTE.speaker]
====
Le mappage de ports permet d'accéder aux services des conteneurs depuis l'extérieur. La syntaxe `host_port:container_port` associe un port de l'hôte à un port du conteneur.

Ici, le service front est accessible sur le port 80 de l'hôte, tandis que le service adminer est accessible sur le port 81.
====

// tag::demo[]
=== Démonstration

Exposition des services sur des ports spécifiques

[NOTE.speaker]
====
* Créer un fichier `docker-compose.yml`.
* Définir un service front sans mappage de port.
```yaml
services:
  front:
    image: nginx
```

* Lancer docker compose up.
`docker compose up`

* Vérifier l'inaccessibilitée du service front.
`http://localhost:80`

* Ajouter un mappage de port pour le service front.
```yaml	
services:
  front:
    image: nginx
    ports:
      - 80:80
```

* Relancer docker compose up.
`docker compose up`

* Vérifier l'accessibilité du service front.
`http://localhost:80`
====
// end::demo[]

== Networks et communication

* **Networks** : Facilitent la communication sécurisée entre conteneurs.
* Types de réseaux : Bridge, Host, None.

```yaml
services:
  front:
    image: nginx
    ports:
      - 80:80
    networks:
      - frontend
  db:
    image: postgres
    networks:
      - backend
    env_file:
      - .env
  adminer:
    image: adminer
    ports:
      - 81:8080
    networks:
      - backend
networks:
    frontend:
    backend:
```
[NOTE.speaker]
====
Les réseaux Docker permettent aux conteneurs de communiquer entre eux. Le réseau "bridge" est le plus utilisé pour connecter les conteneurs, "host" partage le réseau de l'hôte, et "none" isole le conteneur.

Ici les volumes sont de type "bridge" et le service frontend ne peut pas communiquer avec le service db car ils ne sont pas sur le même réseau.
====

// tag::exercice[]
=== Exercice 

Créer un compose avec les services suivants :

- db : postgres
- adminer

. Ajouter un network `db_network` et le spécifier uniquement pour le service `db`. La connexion depuis adminer ne sera pas possible.
. Ajouter le network à adminer pour permettre la connexion à la base de données.
// end::exercice[]

== Dépendances entre services

* **depends_on** : Définit l'ordre de démarrage des services.
* Utilisé pour les services qui dépendent d'autres services.

```yaml
services:
  adminer:
    image: adminer
    depends_on:
      - db
  db:
    image: postgres
```

[NOTE.speaker]
====
Les services type backend ou interface d'admin de bdd dépendent généralement d'une base de donnée. La directive `depends_on` permet de s'assurer que les services sont démarrés dans le bon ordre.

Si on ne démarre que le service adminer, le service db sera démarré également : `docker compose up adminer`.
====

// tag::demo[]
=== Démonstration

Rentre les services dépendants

[NOTE.speaker]
====
. Créer un fichier `docker-compose.yml` et utiliser l'exemple ci-dessus.
. Exécuter `docker compose up`.
. Observer l'ordre de démarrage des services.
. Eteindre les services avec `docker compose down`.
. Relancer avec `docker compose up adminer`.
. Observer que les services dépendants sont démarrés.
====
// end::demo[]

=== Healthchecks

Vérifient l'état de santé des conteneurs.

```yaml
services:
  db:
    image: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    depends_on:
      db:
        condition: service_healthy
```

[NOTE.speaker]
====
Les healthchecks assurent que les services des conteneurs fonctionnent correctement. Ils sont définis dans le fichier `docker-compose.yml` et permettent de réaliser des actions si un service est défaillant.

Dans le cas d'une base de données initialisée avec un grand jeu de données, le healthcheck peut vérifier que la base de données est prête avant de démarrer les autres services.
====
// end::deroulement[]

== Conclusion

// tag::conclusion[]
* Les options avancées de Docker Compose améliorent la configuration des environnements.
* La gestion des volumes, réseaux, ports, et variables d'environnement est essentielle pour des déploiements efficaces.
* Les healthchecks assurent le bon fonctionnement des services.
// end::conclusion[]