:titre: Github Action
:module: Devops
:duree: 120
:description: Découverte de la syntaxe et des possibilité (actions, déclencheurs, marketplace...) Mise en pratique des Github Actions pour mettre en place un premier pipeline CI/CD de build d'une application frontend.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
- **Comprendre** un workflow Github Actions
- **Appliquer** un pipeline Github Actions
// end::objectifs[]

// tag::deroulement[]
== Introduction

* Définition : Outil d'automatisation des workflows.
* Utilité : Faciliter l'intégration et le déploiement continus.
* Composants : Actions, workflows, déclencheurs.

https://github.com/features/actions

[NOTE.speaker]
====
Les Github Actions permettent d'automatiser divers aspects du développement logiciel, comme les tests, le déploiement et l'intégration. Comprendre leur structure est essentiel pour les utiliser efficacement.
====

== Syntaxe de base

=== Fichier de configuration YAML

* Chaque workflow est défini dans un fichier YAML.
* Structure : Nom, déclencheurs, jobs, et étapes.

```yaml
name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
```

[NOTE.speaker]
====
Les workflows sont décrits dans des fichiers YAML qui définissent les conditions de déclenchement, les tâches à réaliser et les environnements sur lesquels elles s'exécutent.
====

=== Déclencheurs

Ils définissent quand le workflow doit être exécuté. Il existe différents types :

* `push` : Lorsqu'un commit est poussé.
* `pull_request` : Lorsqu'une pull request est ouverte.
* `schedule` : A intervalles réguliers.
* ...

https://docs.github.com/fr/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows[Documentation]

=== Actions

Une action est une tâche à réaliser dans un workflow. Elles sont imbriquées dans un `job` et peuvent être :

* Un script shell.
* Un conteneur Docker.
* Une action prédéfinie.

https://docs.github.com/fr/actions/writing-workflows/choosing-what-your-workflow-does/using-jobs-in-a-workflow[Documentation]

=== Marketplace

* Actions prédéfinies : Disponibles sur le marketplace.
* Utilisation : Réduction du temps de développement.

https://github.com/marketplace

[NOTE.speaker]
====
Le Marketplace des Github Actions propose de nombreuses actions prêtes à l'emploi, ce qui permet de gagner du temps lors de la configuration des workflows.
====

// tag::demo[]
=== Démonstration

Créer un workflow qui fait un echo.

[NOTE.speaker]
====
1. Créer un fichier `.github/workflows/echo.yml`.
2. Configurer le déclencheur `on: [push]`.
3. Ajouter un job avec une étape `run: echo "Hello, World!"`.
4. Pousser le code et observer le résultat dans l'onglet Actions de Github.
====
// end::demo[]

== Mise en place d'un pipeline CI simple

Dans notre cas, nous allons faire :

* Installer les dépendances
* Tester le code
* Build de l'application

[NOTE.speaker]
====
Les pipelines CI/CD automatisent les processus de tests et de déploiement, garantissant que le code est toujours prêt pour la production. Les Github Actions facilitent cette automatisation.
====

// tag::demo[]
=== Démonstration

Créer un workflow qui récupère le code source et installe les dépendances d'un front avec Vite.

[NOTE.speaker]
====
. Créer un projet Vite avec `npm init vite@latest`.
. Créer un fichier `.github/workflows/front.yml`.
. Configurer le déclencheur `on: [push]`.
. Ajouter un job avec l'action `actions/checkout@v4`.
. Ajouter une étape pour installer les dépendances avec `run: npm install`.
====
// end::demo[]

// tag::exercice[]
=== Exercice

Continuer le workflow pour qu'il lance les tests et fait un build du front.
// end::exercice[]

// end::deroulement[]

== Conclusion

// tag::conclusion[]
* Les Github Actions automatisent les workflows de développement.
* Compréhension des éléments de base : 
** workflows : fichiers YAML
** actions : tâches à réaliser
** déclencheurs : événements déclencheurs
* Importance de l'automatisation pour la CI/CD dans le DevOps.

[NOTE.speaker]
====
Les Github Actions sont un outil puissant pour intégrer l'automatisation dans les projets de développement, facilitant ainsi la livraison continue de logiciels de qualité.

A terme, un projet complètement automatisé sera capable de déployer automatiquement l'application sur des serveurs provisionnés à la demande (type AWS).
====
// end::conclusion[]