:title: Algorithmique et découverte de python
:number: 01
include::../../../../../../adoc/libs/header-episode.adoc[]

// tag::intro[]
Explorer les fondements de l'algorithmique et découvrir le langage Python, en mettant l'accent sur les compétences essentielles qui permettront aux apprenants de concevoir des solutions efficaces et de développer des programmes simples.
// end::intro[]

== Objectifs pédagogiques

// tag::objectifs[]
* **Comprendre** les concepts fondamentaux de l'algorithmique.
* **Découvrir** le langage Python et ses principales caractéristiques.
// end::objectifs[]

== Prérequis formateur

// tag::prerequis[]
- VsCode
- Devcontainer
- Docker

**Facultatifs :**

* S’entraîner à faire les démonstrations, notamment si l’on risque de ne pas être à l’aise pour les faire en direct
On peut aussi prendre le parti de découvrir la démonstration en plein cours, mais il ne faut pas que cela impacte trop le rythme de la journée
* Préparer des documents ou des ressources de référence sur les commandes de base de Linux, à partager aux apprenants

// end::prerequis[]

== Déroulement

// tag::deroulement[]
WARNING: *Fournir l'ebook de la saison aux apprenants : link:./pdf.html[Ebook]*
include::../../../../modules/algo/introduction.adoc[options=modules]

TIP: 🍕 Pause déjeuner

include::../../../../modules/python/introduction.adoc[options=modules]

Montrer aux apprenants l’installation de Python, savoir configurer leur environnement et s’assurer que tous les apprenants affichent un “Hello World”

:challenge: https://github.com/O-clock-Devops-Peda/S02-Challenge
:description: Démarrage du projet fil rouge : Concevoir l'algorithme du système de gestion des tâches en utilisant du pseudo-code et créer la structure de base de l'outil.
:correction: 
include::../../../../../../adoc/libs/intro-challenge.adoc[]

.👨‍🏫 Référent de promo
[.suivi]
[sidebar]
--
include::../../../../suivi.adoc[tags=s02e01]
--

// end::deroulement[]