:titre: Modules, classes et méthodes
:module: Python
:duree: 120
:description: Les modules, classes et méthodes permettent de structurer le code en le découpant en blocs réutilisables. 
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]

// tag::objectifs[]
// Sous forme de liste à puce, en utilisant la taxonomie de Bloom
* Définir des classes et créer des objets en Python
* Utiliser des méthodes d'instance et des attributs dans les classes
* Importer et utiliser des modules Python pour organiser le code
* Créer des modules personnalisés et les utiliser dans d'autres scripts
// end::objectifs[]

// tag::deroulement[]
== Modules

Un module est un fichier contenant du code Python (fonctions, classes, variables) qui peut être importé et réutilisé dans d'autres programmes Python.

*Utilisation :*

* Organiser le code en plusieurs fichiers pour une meilleure gestion.
* Réutiliser du code commun dans plusieurs parties d'un programme ou dans plusieurs projets.

.Exemple de déclaration
```python
# Exemple de module : mymodule.py
def saluer():
    print("Bonjour, tout le monde!")
```

=== Utilisation d'un module

Le module peut être importé de différente façon plus ou moins sélectives

.Importer tout le module
```python
import mymodule
mymodule.saluer()
```

.Importer une fonction spécifique
```python
from mymodule import saluer
saluer()
```

[NOTE.speaker]
--
Bonnes pratiques :

* Utiliser des noms de modules explicites.
* Grouper les importations en haut des fichiers pour une meilleure lisibilité.
--

=== Modules standards

Python possède de nombreux modules standards qui peuvent être importés et utilisés directement.

.Exemple d'utilisation
```python
import math
print(math.pi)
```

=== Modules personnalisés

Créés par les développeurs ou vos propres modules pour des besoins spécifiques.

* Exemple de module personnalisé : `utilities.py`.
* Utiliser des conventions de nommage claires et organiser les modules dans des dossiers logiques.

== Les classes

Une classe est un plan pour créer des objets définis par un ensemble d'attributs et de méthodes.

Une classe est un plan pour créer des objets, également nommés *instances*.
Elle définit un ensemble d'attributs (variables) et de méthodes (fonctions) que les objets créés à partir de la classe auront.

*Utilisation :*

* Modéliser des entités complexes en regroupant données et comportements.
* Faciliter la réutilisation et la modularité du code.

Il existe deux grands types de classe

* Classe sans constructeur
* Classe avec constructeur

== Classe sans constructeur

Une classe sans constructeur n'a pas de méthode spéciale pour initialiser ses attributs lors de la création d'une instance.

.Exemple de déclaration
```python
class Person:
    pass # permet d'initialiser la classe sans implémentation

personne1 = Person() # instanciation → création d'un objet
personne1.nom = "Dave" # ajout d'attributs dynamiques
personne1.age = 42

print(personne1.nom)  # Dave
print(personne1.age)  # 42
```

=== Avantages

* Simplicité : Utile pour des objets très simples ou temporaires.
* Flexibilité : Les attributs peuvent être ajoutés ou modifiés dynamiquement.
* Rapidité : Pas besoin de définir un constructeur pour des cas très basiques.

=== Inconvénients

* Risque d'erreurs : Possibilité d'oublier d'initialiser certains attributs, ce qui peut causer des erreurs.
* Manque de Structure : Moins organisé, peut rendre le code difficile à maintenir et à comprendre.
* Pas de contrôle d'initialisation : Impossible d'assurer que l'objet est dans un état valide dès sa création.

=== Cas d'utilisation

* Prototypes Rapides : Utile lors de la phase de prototypage où la structure de l'objet peut changer fréquemment.
* Objets Temporaires : Pour des objets à vie courte où la formalisation d'un constructeur n'est pas nécessaire.

.Exemple
```python
class Config:
    pass

config = Config()
config.debug = True
config.verbose = False

print(config.debug)   # True
print(config.verbose) # False
```

== Classe avec constructeur

Une classe avec constructeur utilise une méthode spéciale pour initialiser ses attributs lors de la création d'une instance.

.Exemple de déclaration
```python
class Personne:
    def __init__(self, nom, age):
        self.nom = nom
        self.age = age

personne1 = Personne("Alice", 30)

print(personne1.nom)  # Alice
print(personne1.age)  # 30
```

[NOTE.speaker]
--
* `__init__` est une méthode spéciale nommée constructeur. Elle est appelée automatiquement lors de la création d'une instance.
* `self` est une référence à l'instance actuelle de la classe. Elle est utilisée pour accéder aux attributs et méthodes de l'instance.
--

== Les méthodes

Une méthode est une fonction définie à l'intérieur d'une classe qui opère sur les instances de cette classe.

*Utilisation :*

* Manipuler les attributs des objets de manière contrôlée.
* Encapsuler des comportements spécifiques à l'intérieur des objets.

.Exemple de déclaration
```python
class Personne:
    def saluer(self):
        print(f"Bonjour, je m'appelle {self.nom} et j'ai {self.age} ans.")
```

[NOTE.speaker]
--
* `class Personne:` définit une classe Personne.
* `def saluer(self):` définit une méthode saluer qui affiche un message de salutation.
* `self` est une référence à l'instance actuelle de la classe.
* `self.nom` et `self.age` accèdent aux attributs de l'instance.
* `print(...)` affiche le message de salutation.
--

=== Utilisation

.Exemple
```python
personne1 = Personne()
personne1.nom = "Alice"
personne1.age = 30
personne1.saluer()  # Bonjour, je m'appelle Alice et j'ai 30 ans.
```

[NOTE.speaker]
--
* `personne1 = Personne()` crée une instance de la classe Personne.
* `personne1.nom = "Alice"` et `personne1.age = 30` initialisent les attributs de l'instance.
* `personne1.saluer()` appelle la méthode saluer de l'instance.
--

=== Amélioration

Pour améliorer la lisibilité et la structure du code, il est recommandé de définir les attributs lors de la création de l'instance.

.Exemple
```python
class Personne:
    def __init__(self, nom, age):
        self.nom = nom
        self.age = age

    def saluer(self):
        print(f"Bonjour, je m'appelle {self.nom} et j'ai {self.age} ans.")

personne1 = Personne("Alice", 30)
personne1.saluer()  # Bonjour, je m'appelle Alice et j'ai 30 ans.
```

== Méthodes spéciales

=== `+++__str__+++`

La méthode `+++__str__+++` est une méthode spéciale qui renvoie une représentation sous forme de chaîne de l'objet.

.Exemple de déclaration
```python
class Personne:
    def __init__(self, nom, age):
        self.nom = nom
        self.age = age

    def __str__(self):
        return f"{self.nom} ({self.age} ans)"

personne1 = Personne("Alice", 30)
print(personne1)  # Alice (30 ans)
```

[NOTE.speaker]
--
* `def __str__(self):` définit une méthode spéciale `__str__` qui renvoie une chaîne représentant l'objet.
* `return f"{self.nom} ({self.age} ans)"` renvoie une chaîne formatée avec le nom et l'âge de la personne.
* `print(personne1)` appelle automatiquement la méthode `__str__` pour afficher une représentation de l'objet.
--
// end::deroulement[]

// tag::demo[]
// end::demo[]

// tag::exercice[]
== Exercice

=== Modules en Python

* Créez un module appelé simple_string_utils.py contenant les fonctions suivantes :
** to_upper(s) : Convertit et retourne la chaîne s en majuscules.
** to_lower(s) : Convertit et retourne la chaîne s en minuscules.
* Dans un autre fichier Python (par exemple, main.py), importez le module simple_string_utils et utilisez ses fonctions pour convertir 
** cette chaîne de caractères en majuscules "This is a Test." 
** cette chaîne de caractères en minuscule  "ANOTHER TEST STRING."

=== Classes et Fonctions en Python

Créez une classe SimpleTextProcessor avec un constructeur __init__() qui prend une chaîne de caractères et la stocke comme attribut.

Ajoutez les méthodes suivantes :

* to_upper() : Retourne la chaîne en majuscules.
* to_lower() : Retourne la chaîne en minuscules.

Dans main.py, créez un objet SimpleTextProcessor avec une chaîne donnée, puis utilisez les méthodes pour afficher la chaîne en majuscules et en minuscules.

[NOTE.speaker]
--
Correction Exercice

Partie 1 : Modules en Python (50 minutes)

Création des fichiers

* simple_string_utils.py
+
[source,python]
----
def to_upper(s):
    """
    Convertit et retourne la chaîne `s` en majuscules.
    """
    return s.upper()

def to_lower(s):
    """
    Convertit et retourne la chaîne `s` en minuscules.
    """
    return s.lower()
----

* main.py
+
[source,python]
----
import simple_string_utils

# Chaînes à utiliser
sentence1 = "This is a Test."
sentence2 = "ANOTHER TEST STRING."

# Convertir en majuscules
upper_sentence = simple_string_utils.to_upper(sentence1)
print(f"Uppercase: {upper_sentence}")

# Convertir en minuscules
lower_sentence = simple_string_utils.to_lower(sentence2)
print(f"Lowercase: {lower_sentence}")
----

* Explication du code

[cols="1,2"]
|===
|Ligne de code |Explication

|`import simple_string_utils`
|Importation du module simple_string_utils pour utiliser ses fonctions

|`sentence1 = "This is a Test."`
|Déclaration d'une chaîne de caractères pour la conversion en majuscules

|`sentence2 = "ANOTHER TEST STRING."`
|Déclaration d'une chaîne de caractères pour la conversion en minuscules

|`upper_sentence = simple_string_utils.to_upper(sentence1)`
|Utilisation de la fonction to_upper pour convertir sentence1 en majuscules

|`print(f"Uppercase: {upper_sentence}")`
|Affichage de la chaîne convertie en majuscules

|`lower_sentence = simple_string_utils.to_lower(sentence2)`
|Utilisation de la fonction to_lower pour convertir sentence2 en minuscules

|`print(f"Lowercase: {lower_sentence}")`
|Affichage de la chaîne convertie en minuscules
|===

Partie 2 : Classes et Fonctions en Python (70 minutes)

Implémentation

* simple_string_utils.py
+
[source,python]
----
class SimpleTextProcessor:
    """
    Classe pour manipuler une chaîne de caractères.
    """
    def __init__(self, s):
        """
        Constructeur qui initialise la chaîne de caractères.
        """
        self.string = s

    def to_upper(self):
        """
        Retourne la chaîne en majuscules.
        """
        return self.string.upper()

    def to_lower(self):
        """
        Retourne la chaîne en minuscules.
        """
        return self.string.lower()
----

* main.py
+
[source,python]
----
from simple_string_utils import SimpleTextProcessor

# Créer un objet SimpleTextProcessor avec une chaîne par défaut
processor = SimpleTextProcessor("Simple Text Example")

# Afficher la chaîne en majuscules
print(f"Uppercase: {processor.to_upper()}")

# Afficher la chaîne en minuscules
print(f"Lowercase: {processor.to_lower()}")
----

* Explication du code

[cols="1,2"]
|===
|Ligne de code |Explication

|`from simple_string_utils import SimpleTextProcessor`
|Importation de la classe SimpleTextProcessor depuis le module simple_string_utils

|`processor = SimpleTextProcessor("Simple Text Example")`
|Création d'un objet SimpleTextProcessor avec la chaîne "Simple Text Example"

|`print(f"Uppercase: {processor.to_upper()}")`
|Utilisation de la méthode to_upper pour afficher la chaîne en majuscules

|`print(f"Lowercase: {processor.to_lower()}")`
|Utilisation de la méthode to_lower pour afficher la chaîne en minuscules
|===

--

// end::exercice[]

== Conclusion

// tag::conclusion[]
* Modules :
** Permettent de structurer le code en plusieurs fichiers
** Facilitent la réutilisation et l'importation de fonctions, classes et variables
** Supportent l'importation sélective et l'utilisation d'alias
* Classes :
** Modèles pour créer des objets avec des attributs et des méthodes
** Encapsulation des données et des comportements
** Supportent l'héritage pour réutiliser et étendre des fonctionnalités
* Méthodes :
** Fonctions définies à l'intérieur des classes
** Interagissent avec les attributs des objets via `self`
** Incluent des méthodes spéciales comme `__init__` (constructeur) et `__str__` (représentation)

[NOTE.speaker]
--
Ces concepts sont essentiels pour la programmation orientée objet en Python, permettant de créer des programmes modulaires, réutilisables et maintenables.
--
// end::conclusion[]
