:titre: Les variables
:module: Python
:duree: 120
:description: Les variables permettent de stocker des valeurs en mémoire.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]

// tag::objectifs[]
// Sous forme de liste à puce, en utilisant la taxonomie de Bloom
* Déclarer et initialiser des variables de différents types
* Comprendre les spécificités des différents types
* Utiliser des structures de données
// end::objectifs[]

// tag::deroulement[]
== Les entiers

*Type* : `int` (entiers)

Représente des nombres entiers (sans partie décimale), positifs ou négatifs.

.Exemple de déclaration
```python
age = 42
```

.Exemple d'utilisation
```python
moitie_age = age / 2
print(moitie_age)
```

[NOTE.speaker]
--
- `age = 42` est une déclaration classique d'une variable de type entier
- `moitie_age = age / 2` est une division classique et stocke le résultat dans une variable
- `print(moitie_age)` affiche le résultat de la division
--

== Les flottants

*Type* : `float` (flottants)

Représente des nombres à virgule, positifs ou négatifs.

.Exemple de déclaration
```python
pi = 3.14
```

.Exemple d'utilisation
```python
demi_pi = pi / 2
print(demi_pi)
```

[NOTE.speaker]
--
- `pi = 3.14` est une déclaration classique d'une variable de type flottant
- `demi_pi = pi / 2` est une division classique et stocke le résultat dans une variable
- `print(demi_pi)` affiche le résultat de la division
--

== Range

*Type* : `range` (plage)

Représente une séquence d'entiers.

.Exemple de déclaration
```python
nombres = range(0, 10, 2)
```

.Exemple d'utilisation
```python
for nombre in nombres:
    print(nombre)
```

[NOTE.speaker]
--
- `nombres = range(0, 10, 2)` est une déclaration classique d'une variable de type range
- `for nombre in nombres:` parcourt la séquence et affiche chaque élément
--

== Les chaînes de caractères

*Type* : `str` (chaînes de caractères)

Représente des séquences de caractères, utilisées pour stocker et manipuler du texte.

.Exemple de déclaration
```python
prenom = "Dave" # double quotes
nom = 'Lopper' # ou simple
```

.Exemple d'utilisation
```python
initiales = prenom[0] + nom[0]
print(initiales)
```

[NOTE.speaker]
--
- les chaînes utilisent des simples guillemets ou des doubles… restons cohérent dans le code
- `prenom = "Dave"` est une déclaration classique d'une variable de type chaîne de caractères
- `initiales = prenom[0] + nom[0]` stocke la première lettre du prénom dans une variable
- `print(initiales)` affiche la première lettre du prénom
--

== Les booléens

*Type* : `bool` (booléens)

Représente des valeurs de vérité, `True` ou `False`.

.Exemple de déclaration
```python
est_majeur = True
```

.Exemple d'utilisation
```python
est_mineur = not est_majeur
print(est_mineur)
```

[NOTE.speaker]
--
- `est_majeur = True` est une déclaration classique d'une variable de type booléen
- `est_mineur = not est_majeur` inverse la valeur de la variable
- `print(est_mineur)` affiche la valeur de la variable
--

== Les listes

*Type* : `list` (listes)

Représente une collection ordonnée de valeurs, modifiable (mutable).

.Exemple de déclaration
```python
nombres = [1, 2, 3, 4, 5]
```

.Exemple d'utilisation
```python
nombres.append(6)
print(nombres)
```

[NOTE.speaker]
--
- `nombres = [1, 2, 3, 4, 5]` est une déclaration classique d'une variable de type liste
- `nombres.append(6)` ajoute un élément à la liste
- `print(nombres)` affiche la liste
--

== Les tuples

*Type* : `tuple` (tuples)

Représente une collection ordonnée de valeurs, non modifiable (immutable).

.Exemple de déclaration
```python
coordonnees = (44.338353, 1.208687)
```

.Exemple d'utilisation
```python
latitude, longitude = coordonnees
print(latitude)
```

[NOTE.speaker]
--
- `coordonnees = (44.338353, 1.208687)` est une déclaration classique d'une variable de type tuple
- `latitude, longitude = coordonnees` décompose le tuple en deux variables
- `print(latitude)` affiche la latitude
--


== Dictionnaires

*Type* : `dict` (dictionnaires)

Représente une collection non ordonnée de paires clé-valeur.

.Exemple de déclaration
```python
personne = {
    "prenom": "Dave",
    "nom": "Lopper",
    "age": 42
}
``` 

.Exemple d'utilisation
```python
personne["sexe"] = "M"
print(personne["prenom"])
```

[NOTE.speaker]
--
- `personne = { ... }` est une déclaration classique d'une variable de type dictionnaire
- `personne["sexe"] = "M"` ajoute une nouvelle paire clé-valeur
- `print(personne["prenom"])` affiche la valeur associée à la clé "prenom"
--

== Les ensembles

*Type* : `set` (ensembles)

Représente une collection non ordonnée d'éléments uniques. La différence avec les listes est que les ensembles ne peuvent pas contenir de doublons.

.Exemple de déclaration
```python
nombres = {1, 2, 3, 4, 5}
```

.Exemple d'utilisation
```python
nombres.add(5)
print(nombres)
```

[NOTE.speaker]
--
- `nombres = {1, 2, 3, 4, 5}` est une déclaration classique d'une variable de type ensemble
- `nombres.add(5)` ajoute un élément à l'ensemble, mais ne modifie pas l'ensemble car il est déjà présent
- `print(nombres)` affiche l'ensemble
--

== Les ensembles figés

*Type* : `frozenset` (ensembles figés)

Représente une collection non ordonnée d'éléments uniques, non modifiable (immutable).

.Exemple de déclaration
```python
nombres = frozenset({1, 2, 3, 4, 5})
```

.Exemple d'utilisation
```python
nombres.add(6)
print(nombres)
```

[NOTE.speaker]
--
- `nombres = frozenset({1, 2, 3, 4, 5})` est une déclaration classique d'une variable de type ensemble figé
- `nombres.add(6)` lève une exception car l'ensemble est figé
- `print(nombres)` affiche l'ensemble
--

== None

*Type* : `NoneType` (None)

Représente l'absence de valeur.

.Exemple de déclaration
```python
valeur = None
```

.Exemple d'utilisation
```python
if valeur is None:
    print("La valeur est nulle")
``` 

[NOTE.speaker]
--
- `valeur = None` est une déclaration classique d'une variable de type None
- `if valeur is None:` teste si la valeur est nulle
- `print("La valeur est nulle")` affiche un message si la valeur est nulle
--

== Tableau récapitulatif

|===
| Type | Description | Exemple de déclaration | Exemple d'utilisation

| `int` | Entiers | `age = 42` | `moitier_age = age / 2`
| `float` | Flottants | `pi = 3.14` | `demi_pi = pi / 2`
| `range` | Plage | `nombres = range(0, 10, 2)` | `for nombre in nombres: ...`
| `str` | Chaînes de caractères | `prenom = "Jean"` | `premiere_lettre = prenom[0]`
| `bool` | Booléens | `est_majeur = True` | `est_mineur = not est_majeur`
| `list` | Listes | `nombres = [1, 2, 3, 4, 5]` | `nombres.append(6)`
| `tuple` | Tuples | `coordonnees = (44.338353, 1.208687)` | `latitude, longitude = coordonnees`
| `dict` | Dictionnaires | `personne = { ... }` | `personne["sexe"] = "M"`
| `set` | Ensembles | `nombres = {1, 2, 3, 4, 5}` | `nombres.add(5)`
| `frozenset` | Ensembles figés | `nombres = frozenset({1, 2, 3, 4, 5})` | `nombres.add(6)`
| `NoneType` | None | `valeur = None` | `if valeur is None: ...`
|===
// end::deroulement[]

// tag::demo[]
// end::demo[]

// tag::exercice[]
== Exercice

=== Variables et Structures de Données

*Variables Numériques et Textuelles :*

* Créer une variables de type entier (int) avec comme valeur 10, un flottant (float) avec comme valeur 5,5 et une chaîne de caractères (str) avec comme valeur "Le résultat est" .
* Stocker dans des variable le résultat des opérations somme et produit des variables int et float 
* Stocker dans une variable la concaténation de la variable message et de la variable somme convertit en str 
* afficher : la variable concaténée et le résultat du produit 

*Structures de Données :*

* Créez une liste contenant “1,2,3”  (list) 
* Ajoutez, le nombre 4 à la liste puis afficher la liste
* Retirer le nombre 2 de la liste puis afficher la liste
* Créez un dictionnaire (dict) pour stocker des paires clé-valeur. "nom": "Alice", "age": 30
* Ajouter une nouvelle paires clé-valeur "ville: paris" 
* Afficher le dictionnaire

=== Boucles et Contrôle de Flux

*Boucle for :*

* Utilisez une boucle `for` pour calculer la somme de tous les éléments de la liste générée en partie 1.
* Parcourez avec une boucle `for` pour afficher chaque paire clé-valeur du dictionnaire généré en partie 1.

*Boucle while et Conditions :*

* Utilisez une boucle while pour simuler un système de mot de passe où l'utilisateur doit entrer le bon mot de passe pour sortir de la boucle.
* le mot de passe sera définie dans une variable à l’intérieur du script
* La boucle continue de demander le mot de passe jusqu'à ce que l'utilisateur fournisse le bon mot de passe ou atteigne un nombre maximal de 3 tentatives.

[NOTE.speaker]
--
Correction Exercice

Partie 1 : Variables et Structures de Données

Variables Numériques et Textuelles

* Créer des variables de type entier, flottant et chaîne de caractères
+
[source,python]
----
# Créer des variables numériques et textuelles
nombre_entier = 10 # Variable entière (int)
nombre_flottant = 5.5 # Variable flottante (float)
message = "Le résultat est" # Variable texte (str)

# Opérations arithmétiques
somme = nombre_entier + nombre_flottant
produit = nombre_entier * nombre_flottant

# Manipulation de la chaîne de caractères
message_complet = message + " " + str(somme) # Concaténation et conversion du nombre en chaîne

# Affichage des résultats
print(message_complet) # Affiche "Le résultat est 15.5"
print("Produit:", produit) # Affiche le produit des nombres
----

Structures de Données

. Listes
+
[source,python]
----
# Créer une liste et la manipuler
ma_liste = [1, 2, 3]
ma_liste.append(4) # Ajouter un élément à la liste
print("Liste après ajout:", ma_liste) # Affiche [1, 2, 3, 4]

ma_liste.remove(2) # Retirer un élément de la liste
print("Liste après retrait:", ma_liste) # Affiche [1, 3, 4]
----

. Dictionnaires
+
[source,python]
----
# Créer un dictionnaire et y accéder
mon_dict = {"nom": "Alice", "age": 30}
mon_dict["ville"] = "Paris" # Ajouter une nouvelle paire clé-valeur
print("Dictionnaire:", mon_dict) # Affiche le dictionnaire avec les trois paires clé-valeur
----

Partie 2 : Boucles et Contrôle de Flux

. Boucle for
+
[source,python]
----
# Boucle for pour calculer la somme de la liste partie 1
somme_totale = 0
for nombre in nombres:
    somme_totale += nombre # Ajoute chaque nombre à la somme totale
print("Somme totale des nombres:", somme_totale) # Affiche 8

# Boucle for pour parcourir un dictionnaire
for cle, valeur in mon_dict.items():
    print(f"{cle}: {valeur}") # Affiche chaque clé et valeur
----

. Boucle while et Conditions
+
[source,python]
----
# Définir le mot de passe correct
mot_de_passe_correct = "python123"

# Initialiser une variable pour suivre le nombre de tentatives
tentatives = 0

# Limite de tentatives
limite_tentatives = 3

# Boucle while pour demander le mot de passe
while tentatives < limite_tentatives:
    # Demander à l'utilisateur d'entrer le mot de passe
    mot_de_passe = input("Entrez le mot de passe : ")
    
    # Vérifier si le mot de passe est correct
    if mot_de_passe == mot_de_passe_correct:
        print("Accès accordé !")
        break # Sortir de la boucle si le mot de passe est correct
    else:
        tentatives += 1 # Incrémenter le nombre de tentatives
        print(f"Mot de passe incorrect. Tentatives restantes : {limite_tentatives - tentatives}")
    
    # Vérifier si le nombre maximal de tentatives est atteint
    if tentatives == limite_tentatives:
        print("Accès refusé. Nombre maximal de tentatives atteint.")
----
--

// end::exercice[]

== Conclusion

// tag::conclusion[]
* Les variables sont des composants fondamentaux en Python pour stocker et manipuler les données. 
* Chaque type de variable offre des fonctionnalités spécifiques adaptées à des besoins variés, qu'il s'agisse de manipuler des nombres, du texte, des séquences ou des collections de données uniques. 
* La compréhension des différents types de variables et de leurs utilisations est cruciale pour écrire du code Python efficace, clair et maintenable.
// end::conclusion[]
