:title: 🌱 Intégration
:number: 01
:duration: 35
include::../../../../adoc/libs/header-saison.adoc[]

// tag::intro[]
Introduction au monde du développement web et à la formation O’clock. Elle pose les bases nécessaires pour entamer ce parcours en toute confiance, tout en favorisant la cohésion de groupe et l'adaptation au nouvel environnement de travail.
// end::intro[]

== Objectifs pédagogiques

// tag::objectifs[]
* *Comprendre* les fondamentaux du web et du développement
* *Utiliser* l'environnement de travail et les outils nécessaires à la formation
// end::objectifs[]

== Notions

// tag::notions[]
* WEB
* IDE
* Terminal
* Navigateur
* Méthodo
// end::notions[]

== Prérequis formateur

// tag::prerequis[]
* Capacité à accompagner des débutants dans la découverte du développement web
* Bonne maîtrise des outils d’apprentissage en ligne (plateforme, IDE, DevContainer)
* Sens de l'écoute et aptitude à créer une atmosphère bienveillante
* Expérience dans la gestion de groupes et d’activités de team-building
// end::prerequis[]

== Résumé

// tag::resume[]
La première saison accompagne les apprenants dans leurs premiers pas en développement web. Elle combine découverte des fondamentaux techniques et adaptation au nouvel environnement, tout en mettant l'accent sur la création d'une dynamique de groupe propice à l'apprentissage.
// end::resume[]

== Déroulement

link:./overview.html[Vue kanban]

// tag::deroulement[]
include::episodes/*/*.adoc[opts=episodes]
// end::deroulement[]