:title: Démarrage J1
:number: 01
include::../../../../../../adoc/libs/header-episode.adoc[]

// tag::intro[]
Prise de connaissances des docs, du sujet, planification du projet
// end::intro[]

== Objectifs pédagogiques

// tag::objectifs[]
- **Comprendre** ce qui est attendu lors du passage du titre pro
- **Planifier** le projet
// end::objectifs[]

// tag::prerequis[]
// end::prerequis[]

== Déroulement

// tag::deroulement[]
Partager ce repo aux apprenants : https://github.com/O-clock-Devops-Peda/S15-Projet

NOTE: Le **référent de promo** présente en 30 minutes comme suit et répond aux questions.

**Durée :** 14 jours

**Objectifs :**

Mettre en production une application full stack avec une architecture trois tiers, sécurisée et supervisée, avec un serveur pour le front, un pour le back et un pour la bdd.

**Attendus** (par ordre de priorité) **:**

1. Ansible
2. Terraform
3. Github actions
4. Supervision de l’infrastructure
5. Containers en production
6. Reverse proxy et load balancer
7. Sonarqube et intégration des vérifications dans les github actions

**Détails :**

- La partie dev n’est pas la plus importante. Vous pouvez partir de template vite pour le front et d’un CMS au choix pour le backend (Wordpress, Directus, Pocketbase…).
- En cas de modification du code (à minima le frontend), un workflow github action doit le répercuter en production.
- En parallèle de la production applicative, une supervision des serveurs est à mettre en place, avec si possible un sonarqube en plus.
- Les serveurs linux doivent être configurés de façon restrictive pour éviter toute compromission : droits d’accès, firewall, ssl…

**Cerise sur le gâteau :**

- Automatisation complète de la livraison en production from scratch.
- Communication entre le front et le back via une API.
- Empaqueter un environnement de développement pour l’équipe de dev.

**Déroulement :**

- Démarrage j1 : prise de connaissances des docs, du sujet, planification du projet
- Présentation J2 matin : RE, soft skills, montage de dossier
- J2 aprèm à J14 : go go go

// end::deroulement[]