:titre: Syntaxe HCL (HashiCorp Configuration Language)
:module: Virtualisation
:duree: 60
:description: Ce module présente les principes de base de HCL (HashiCorp Configuration Language) et sa structure de base.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]


== Objectifs pédagogiques

// tag::objectifs[]
* Comprendre les principes de base de HCL (HashiCorp Configuration Language)
* Découvrir la structure d'un fichier HCL
* Apprendre à définir des blocs, des attributs et des variables en HCL
// end::objectifs[]

// tag::deroulement[]

== Introduction à HCL

* langage de configuration
* humainement lisible et analysable par les machines
* utilisé principalement dans l'écosystème HashiCorp pour définir l'infrastructure et la configuration des applications

=== Outils principaux utilisant HCL

* **Terraform** : 
** pour de l'infra as code
** pour définir des ressources cloud ou on-premise
** pour versionner l'infra et la partager

* **Vault** :
** pour la gestion des secrets
** HCL sert à configurer les politiques et les accès dans Vault

=== Avantages de HCL

* **Lisibilité** :
** syntaxe simple et lisible même pour les non développeurs
** structure claire et facile à comprendre

* **Compatibilité** :
** compatible avec les outils HashiCorp ce qui permet une gestion fluide
** compatible avec les outils de versionning afin de suivre les changements

include::../../../../adoc/libs/slide-notitle.adoc[]

* **Flexibilité** :
** permet de définir des variables, des fonctions et des modules (configuration dynamique)
** capable de gérer des configurations complexes grâce à la structure et l'imbrication des blocs

* **Communauté et écosystème** :
** HCL est utilisé par une large communauté qui contribue à son évolution
** documentation abondant et nombreux modules préconstruits

== Structure de base d'un fichier HCL

Les éléments principaux de la syntaxe HCL comportent :

* des **blocs**
* des **attributs**
* des **variables**, avec des **types de données** spécifiques


=== Blocs

* éléments de base d'un fichier HCL
* définissent une unité de configuration comme une ressource ou une variable

[cols="1,1"]
|===
| Syntaxe générale | Exemple

a|
```hcl
bloc "type" "nom" {
  # Contenu du bloc
}
```

a|
```hcl
resource "aws_instance" "example" {
  ami           = "ami-123456"
  instance_type = "t2.micro"
}
```
|===

== Attributs

* définissent les propriétés d'un bloc
* spécifient les détails de la configuration
* peuvent être des valeurs statiques ou des références à d'autres blocs

[cols="1,1"]
|===
| Syntaxe générale | Exemple

a|
```shell
clé = valeur
```

a|
```shell
ami           = "ami-123456"
instance_type = "t2.micro"
```
|===

== Variables

* permettent de définir des valeurs dynamiques
* peuvent être utilisées dans les attributs des blocs
* peuvent être définies dans un fichier séparé ou directement dans le fichier HCL

[cols="1,1"]
|===
| Syntaxe générale | Exemple

a|
```shell
variable "nom" {
  type = type
  default = valeur
}
```

a|
```shell
variable "region" {
  type    = string
  default = "us-west-1"
}
```
|===

== Types de données

* **Chaînes de caractères (strings)** : Définies entre guillemets. Exemple : `"t2.micro"`
* **Nombres** : Entiers ou flottants. Exemple : `42`, `3.14`
* **Booléens** : `true` ou `false`
* **Listes** : Séquence ordonnée de valeurs. Exemple : `["a", "b", "c"]`
* **Maps** : Ensemble de paires clé-valeur. Exemple : `{ key1 = "value1", key2 = "value2" }`

== Comparaison avec d'autres langages de configuration

Pourquoi utiliser HCL plutôt que d'autres langages de configuration populaires ?

=== JSON

* format de configuration largement utilisé
* syntaxe plus verbeuse et moins lisible, surtout pour les configurations complexes

[cols="1,1"]
|===
| Exemple | Différences avec HCL

a|
```json
{
  "resource": {
    "aws_instance": {
      "example": {
        "ami": "ami-123456",
        "instance_type": "t2.micro"
      }
    }
  }
}
```

a|
JSON nécessite des guillemets autour des clés et des valeurs, ainsi que des virgules pour séparer les éléments.
|===

=== YAML

* populaire également, plus lisible que JSON
* peut être sujet à des erreurs d'indentation

[cols="1,1"]
|===
| Exemple | Différences avec HCL

a|
```yaml
resource:
  aws_instance:
    example:
      ami: "ami-123456"
      instance_type: "t2.micro"
```

a|
YAML utilise l'indentation pour représenter la hiérarchie et n'a pas besoin de guillemets pour les clés.
|===

== Exemples pratiques de HCL

Bien que la structure d'un projet HCL soit flexible, il est recommandé de suivre une convention pour faciliter la lecture et la maintenance du code.

=== Fichier principal `main.tf`

* contient la définition des ressources à déployer
* exemple simple pour déployer une instance EC2 sur AWS :

```hcl
provider "aws" {
  region = "us-west-2"
}

resource "aws_instance" "example" {
  ami           = "ami-123456"
  instance_type = "t2.micro"
}
```

=== Fichier de variables `variables.tf`

* contient la définition des variables utilisées pour rendre le code plus dynamique
* exemple de définition de variable :

```hcl
variable "instance_type" {
  description = "Type d'instance EC2"
  default     = "t2.micro"
}
```

=== Fichier de sortie `outputs.tf`

* définit les valeurs à afficher une fois l'infra déployée
* exemple de définition de sortie :

```hcl
output "instance_id" {
  value = aws_instance.example.id
}
```

== Types de blocs

HCL utilise différents types de blocs pour définir :

* des **ressources**
* des **variables**
* des **fournisseurs** (ou _providers_)

=== Blocs de ressources

* utilisé pour définir une ressource à créer dans l'infra

[cols="1,1"]
|===
| Syntaxe générale | Exemple

a|
```hcl
resource "type" "nom" {
  # Attributs de la ressource
}
```
a| 
```hcl
resource "aws_instance" "example" {
  ami           = "ami-123456"
  instance_type = "t2.micro"
}
```
|===

=== Blocs de variables

* permettent de déclarer des variables pour rendre le code plus flexible

[cols="1,1"]
|===
| Syntaxe générale | Exemple

a|
```hcl
variable "nom" {
  # Attributs de la variable
}
```
a|
```hcl
variable "instance_type" {
  description = "Type d'instance EC2"
  default     = "t2.micro"
}
```
|===

=== Blocs de fournisseurs

* utilisés pour définir les fournisseurs de services cloud ou on-premise

[cols="1,1"]
|===
| Syntaxe générale | Exemple

a|
```hcl
provider "nom" {
  # Attributs du fournisseur
}
```
a|
```hcl
provider "aws" {
  region = "us-west-2"
}
```
|===

// end::deroulement[]

== Conclusion
// tag::conclusion[]
* HCL est un langage de configuration utilisé par HashiCorp pour définir l'infrastructure et la configuration des applications.
* Sa syntaxe simple et lisible en fait un choix populaire pour l'infrastructure as code.
* Les blocs, attributs, variables et types de données permettent de définir des configurations dynamiques et flexibles.
// end::conclusion[]