:titre: Exécution et modification de configuration Terraform
:module: Virtualisation
:duree: 120
:description: 
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]


== Objectifs pédagogiques

// tag::objectifs[]
* Comprendre le processus de déploiement des ressources Terraform
* Savoir utiliser la commande `terraform apply` pour déployer des ressources
* Connaître les options avancées d'exécution de la commande `terraform apply`
// end::objectifs[]

// tag::deroulement[]

== Commande `terraform apply`

* permet de déployer les ressources définies dans le fichier de configuration Terraform
* demande une confirmation avant de déployer les ressources
* affiche un résumé des ressources à déployer

=== Exemple

[cols="1,1"]
|===
| Configuration | Résultat de la commande `apply`

a|
```hcl
resource "aws_instance" "example" {
  ami           = "ami-0c55b159cbfafe1f0"
  instance_type = "t2.micro"
}
```
a|
```shell
$ terraform apply
Terraform will perform the following actions:

  # aws_instance.example will be created
  + resource "aws_instance" "example" {
      + ami                          = "ami-0c55b159cbfafe1f0"
      + arn                          = (known after apply)
      + associate_public_ip_address  = (known after apply)
      + availability_zone            = (known after apply)
      + cpu_core_count               = (known after apply)
      + cpu_threads_per_core         = (known after apply)
      + disable_api_termination      = (known after apply)
      + ebs_optimized                = (known after apply)
      + get_password_data            = false
      + host_id                      = (known after apply)
      + id                           = (known after apply)
      + instance_state               = (known after apply)
      + instance_type                = "t2.micro"
      + ipv6_address_count           = (known after apply)
      + ipv6_addresses               = (known after apply)
      + key_name                     = (known after apply)
      + network_interface_id         = (known after apply)
      + password_data                = (known after apply)
      + placement_group              = (known after apply)
      + primary_network_interface_id = (known after apply)
      + private_dns                  = (known after apply)
      + private_ip                   = (known after apply)
      + public_dns                   = (known after apply)
      + public_ip                    = (known after apply)
      + security_groups              = (known after apply)
      + source_dest_check            = true
      + subnet_id                    = (known after apply)
      + tags_all                     = (known after apply)
      + tenancy                      = (known after apply)
      + vpc_security_group_ids       = (known after apply)

      + timeouts {
          + create = "10m"
          + delete = "10m"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 
```
|===

include::../../../../adoc/libs/slide-notitle.adoc[]

* Lorsqu'on valide avec `yes`, Terraform déploie les ressources

```shell
aws_instance.example: Creating...
aws_instance.example: Still creating... [10s elapsed]
aws_instance.example: Still creating... [20s elapsed]
aws_instance.example: Still creating... [30s elapsed]
aws_instance.example: Creation complete after 35s [id=i-0abcdef1234567890]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

instance_id = "i-0abcdef1234567890"
```

* Bien entendu, on peut ajuster l'output de la commande directement dans la configuration avec un bloc `output`

== Options avancées d'exécution

* `-auto-approve`: permet d'automatiser le processus d'application des changements
* `-var-file` : permet de spécifier un fichier de variables
* `-var` : permet de spécifier une variable directement en ligne de commande
* `-state` : permet de spécifier un fichier de state Terraform
* `-state-out` : permet de spécifier un fichier de state Terraform de sortie

include::../../../../adoc/libs/slide-notitle.adoc[]

* `-lock` : permet de verrouiller le state Terraform
* `-parallelism` : permet de spécifier le nombre de ressources à déployer en parallèle
* `-refresh` : permet de forcer le rafraîchissement de l'état Terraform avant de déployer les ressources

== Gestion des états avec `terraform state`

* on a déjà vu l'utilité du fichier de state Terraform
* la commande `terraform state` permet de gérer le state Terraform

=== Exemples

* `terraform state list` : liste les ressources dans le state
* `terraform state show <resource>` : affiche les détails d'une ressource
* `terraform state rm <resource>` : retire une ressource du state
* `terraform state mv <resource> <new-resource>` : renomme une ressource dans le state

== Mise à jour des ressources existantes

* on sait comment créer et appliquer une nouvelle configuration Terraform
* mais comment mettre à jour une configuration existante ? Sans tout casser ? 😱

=== Etape 1 : Réflexion

* on commence par réfléchir à ce qu'on veut modifier
** type d'instance ? nombre d'instances ? tags ?
* on doit s'assurer de comprendre l'impact potentiel des modifications sur l'infrastructure actuelle

=== Etape 2 : Modification de la configuration

* on modifie la configuration Terraform directement dans le fichier `.tf`
* on peut ajouter, modifier ou supprimer des ressources

=== Etape 3 : Planification des changements

* on utilise la commande `terraform plan` pour voir les changements proposés
* on vérifie que les changements correspondent bien à ce qu'on attend

**Il est important de prendre le temps de lire le plan de changements avant de l'appliquer**

=== Etape 4 : Application des changements

* une fois le plan validé, on peut appliquer les changements avec `terraform apply`
* on suit le processus habituel de confirmation

**Observez le message de sortie de la commande `apply` pour vous assurer que tout s'est passé comme prévu**

=== Etape 5 : Vérification des changements

* on vérifie que les changements ont bien été appliqués dans l'infrastructure
* on utilise des outils de monitoring et de vérification pour confirmer l'état des ressources
* il est judicieux de vérifier le state Terraform pour s'assurer que tout est à jour avec la commande `terraform state list`

=== Bonnes pratiques

* **Toujours vérifier le plan** : utiliser systématiquement `terraform plan` avant d'appliquer des changements
* **Sauvegarder l'état** : toujours sauvegarder le fichier de state Terraform avant d'appliquer des changements
* **Environnements de test** : tester les changements dans un environnement de test avant de les appliquer en production
* **Documentation** : documenter les changements apportés à l'infrastructure pour faciliter la maintenance et le dépannage

== En cas d'incident

* **Stopper et évaluer** : 
** stopper toute action en cours et proscrire toute action supplémentaire afin d'éviter d'aggraver la situation
** identifier les symptômes et évaluer l'impact sur l'infrastructure

* **Restaurer l'état précédent** :
** restaurer l'état précédent de l'infrastructure en utilisant le fichier de state Terraform sauvegardé
** vérifier que l'infrastructure est revenue à un état stable

include::../../../../adoc/libs/slide-notitle.adoc[]

* **Analyser et corriger** :
** analyser les logs et les données disponibles pour identifier la cause de l'incident
** corriger le problème en appliquant les correctifs nécessaires
** réappliquer les changements en suivant les étapes de mise à jour des ressources existantes

* **Documenter et communiquer** :
** documenter l'incident, les causes et les actions correctives prises
** communiquer avec les parties prenantes pour les informer de la situation et des actions entreprises

// end::deroulement[]

== Conclusion
// tag::conclusion[]
* La commande `terraform apply` permet de déployer les ressources Terraform
* Les options avancées d'exécution permettent de personnaliser le processus de déploiement
* La gestion des états avec `terraform state` est essentielle pour maintenir l'intégrité de l'infrastructure
* La mise à jour des ressources existantes nécessite une planification et une exécution minutieuses
// end::conclusion[]