:titre: Introduction à Terraform
:module: Virtualisation
:duree: 90
:description: Ce module d'introduction à Terraform permet de découvrir les cas d'utilisation de Terraform, les concepts de base (providers, ressources, state) et les commandes de base de Terraform.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]


== Objectifs pédagogiques

// tag::objectifs[]
* Découvrir les cas d'utilisation de Terraform
* Explorer les concepts de base de Terraform : providers, ressources, state
* connaître les commandes de base de Terraform
// end::objectifs[]

// tag::deroulement[]

== Cas d'utilisation de Terraform

Terraform est un point central dans la gestion de l'infrastructure et du déploiement d'applications.

=== Gestion de l'infrastructure cloud

* largement utilisé pour proivisionner des ressources cloud notamment sur AWS, Azure, Google Cloud
* permet aux équipes de décrire leur infrastructure via des fichiers de configuration
* facilite la réplication et le déploiement dans différents environnements

=== Déploiement de micro-services

* clusters Kubernetes, services serverless, etc.
* assure la cohérence et la reproductibilité des déploiements
* simplifie la gestion des dépendances entre les services

=== Automatisation de l'infrastructure hybride

* gestion de ressources cloud et on-premise
* permet de gérer des environnements hétérogènes
* assure la cohérence des configurations
* une seule interface de gestion pour tous les environnements

=== Gestion des configurations multi-cloud

* permet de gérer des ressources sur plusieurs clouds
* permet de tirer parti des avantages de chaque cloud
* évite le lock-in avec un fournisseur cloud

=== Déploiement d'applications à grande échelle

* permet de gérer efficacement des milliers de ressources
* utile pour les plateformes SaaS qui nécessitent une infrastructure flexible et évolutive

== Etudes de cas

=== Uber

**Scénario :**

En 2017, Uber était en phase de croissance et possédait une infrastructure complexe multi-cloud incluant AWS, Google Cloud et Azure. Chaque plateforme avait ses propres outils de gestion et l'équipe d'infrastructure de Uber avait des difficultés à assurer une cohérence et une efficacité dans la gestion de l'infrastructure.

**Solution :**

En adoptant Terraform, Uber a pu :

* Standardiser le déploiement de l'infrastructure sur les différents clouds
* Mettre à l'échelle rapidement pendant les périodes de forte demande
* Automatiser le provisionnement des ressources, réduisant les erreurs manuelles

=== Slack

**Scénario :**

En 2020, Slack a souhaité construire un plan robuste de reprise après sinistre pour garantir la disponibilité de son service en cas de panne majeure.

**Solution :**

En utilisant Terraform, Slack a pu :

* Automatiser le déploiement de l'infrastructure multi-cloud et multi-régions
* Maintenir une sauvegarde des configurations pour une reprise rapide
* Basculer rapidement sur l'infrastructure d'urgence avec une intervention manuelle minimale

=== Shopify 

**Scénario :**

Shopify subissait des pics massifs de trafic pendant les Black Fridays et Cyber Mondays. Afin d'éviter de surcharger son infrastructure, Shopify a souhaité passer à une stratégie multi-cloud.

**Solution :**

En utilisant Terraform, Shopify a pu :

* Déployer une infrastructure identique sur plusieurs clouds
* Gérer les pics de trafic en provisionnant les ressources à la demande
* Gérer les changements d'infrastructure sans interruption de service

== Providers

* plugins permettant à Terraform d'interagir avec des API
* chaque provider expose des ressources spécifiques que Terraform peut gérer
* Exemples : AWS, Azure, Google Cloud, Docker, Kubernetes, etc.

=== Exemple de déclaration d'un provider

```hcl
provider "aws" {
  region = "us-west-2"
}
```

* `provider` : mot-clé pour déclarer un provider
* `aws` : nom du provider
* `region` : paramètre spécifique au provider

=== Récupération des plugins

* Terraform télécharge automatiquement les plugins nécessaires
* `terraform init` : commande pour initialiser un projet Terraform
* On peut consulter la documentation du provider sur le site https://registry.terraform.io/[Terraform Registry]
* Exemple pour le provider AWS : https://registry.terraform.io/providers/hashicorp/aws/latest/docs

// tag::demo[]

=== Démonstration

Comprendre le fonctionnement d'un provider

[NOTE.speaker]
--

* Créer un fichier `main.tf`

```hcl
provider "aws" {
  region = "us-west-2"
}
```

* Exécuter `terraform init`

* Terraform reconnaît le mot-clé `provider` et va chercher automatiquement le plugin correspondant
* Exemple pour `"aws"` : Terraform va télécharger le plugin `terraform-provider-aws`
* La documentation du provider se trouve ici : https://registry.terraform.io/providers/hashicorp/aws/latest/docs

* Autre exemple avec le provider `google` :

```hcl
provider "google" {
  project = "my-project-id"
  region  = "us-central1"
}
```

* Exécuter `terraform init`

* Terraform va télécharger le plugin `terraform-provider-google`
* La documentation du provider se trouve ici : https://registry.terraform.io/providers/hashicorp/google/latest/docs
--

// end::demo[]

== Ressources

* Composants de l'infrastructure que l'on souhaite gérer
* chaque ressource est définie dans un fichier de configuration avec ses propriétés spécifiques
* Exemples : instances de VM, bases de données, réseaux...

=== Exemple de déclaration d'une ressource

```hcl
resource "aws_instance" "example" {
  ami           = "ami-0c55b159cbfafe1f0"
  instance_type = "t2.micro"
}
```

* `resource` : mot-clé pour déclarer une ressource
* `aws_instance` : type de ressource
* `example` : nom de la ressource
* `ami` et `instance_type` : propriétés spécifiques à la ressource

== State

* fichier JSON stockant l'état actuel de l'infrastructure
* Terraform utilise ce fichier pour déterminer les actions à effectuer
* ce fichier est essentiel pour Terraform, il ne doit pas être modifié manuellement

=== Exemple de fichier state

```json
{
  "version": 4,
  "terraform_version": "1.0.0",
  "serial": 1,
  "lineage": "b7b3b3b3-7b3b-7b3b-7b3b-7b3b7b3b7b3b",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "aws_instance",
      "name": "example",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "ami": "ami-0c55b159cbfafe1f0",
            "instance_type": "t2.micro"
          }
        }
      ]
    }
  ]
}
```

* Il n'est pas nécessaire de comprendre le contenu du fichier state
* Il est important de savoir que Terraform utilise ce fichier pour gérer l'infrastructure
* C'est un fichier critique à sauvegarder et à ne pas modifier manuellement

// tag::demo[]

== Démonstration

Première utilisation de Terraform

[NOTE.speaker]
--

**Bien observer l'output des commandes dans le terminal tout au long de cette démo**

* Créer un fichier `main.tf`

```hcl
provider "local" {}

resource "local_file" "example" {
  content  = "Hello, World!"
  filename = "example.txt"
}
```

* Exécuter `terraform init`

* Terraform va télécharger le plugin `terraform-provider-local`

* Exécuter `terraform plan`

* Exécuter `terraform apply`

* Terraform va créer un fichier `example.txt` avec le contenu `Hello, World!`

* Observer le fichier `terraform.tfstate` pour voir l'état actuel de l'infrastructure

* Exécuter `terraform destroy`

* Terraform va supprimer le fichier `example.txt`

* Consulter le fichier `terraform.tfstate` pour voir l'état actuel de l'infrastructure

--

// end::demo[]

== Installation & Commandes de base

* Installer Terraform : https://developer.hashicorp.com/terraform/install?product_intent=terraform
* Vérifier l'installation : `terraform --version`

=== `terraform init`

Initialise un répertoire contenant des fichiers de configuration Terraform. Cette commande télécharge les plugins requis par le fournisseur et prépare le répertoire pour d'autres commandes Terraform.

=== `terraform plan`

Affiche les actions que Terraform va effectuer pour atteindre l'état désiré de l'infrastructure. Cette commande permet de vérifier les changements avant de les appliquer.

=== `terraform apply`

Applique les changements nécessaires pour atteindre l'état désiré de l'infrastructure. Cette commande crée, met à jour ou supprime des ressources selon les fichiers de configuration Terraform.

* Possibilité d'ajouter l'option `-auto-approve` pour éviter la confirmation manuelle (utile pour les scripts)

=== `terraform destroy`

Détruit toutes les ressources gérées par Terraform. Cette commande supprime toutes les ressources créées par Terraform.

* Possibilité d'ajouter l'option `-auto-approve` pour éviter la confirmation manuelle (utile pour les scripts)

=== `terraform show`

Affiche l'état actuel de l'infrastructure Terraform. Cette commande affiche les ressources créées et leurs propriétés.

=== `terraform state`

Permet de gérer l'état de l'infrastructure Terraform. Cette commande permet de lister, afficher, supprimer ou modifier les ressources dans le fichier state.

=== `terraform output`

Affiche les sorties (outputs) des ressources Terraform. Cette commande affiche les valeurs des sorties définies dans les fichiers de configuration.

=== `terraform fmt`

Formate les fichiers de configuration Terraform. Cette commande permet de standardiser la syntaxe des fichiers Terraform.

=== `terraform validate`

Valide la syntaxe des fichiers de configuration Terraform. Cette commande vérifie la syntaxe des fichiers sans exécuter d'actions.

// end::deroulement[]

== Conclusion
// tag::conclusion[]
* Terraform est un outil puissant pour gérer l'infrastructure comme du code
* Il permet de décrire l'infrastructure dans des fichiers de configuration
* Terraform utilise des providers pour interagir avec des API
// end::conclusion[]