:titre: Provider AWS Terraform
:module: Cloud Computing
:duree: 120
:description: Ce module aborde la configuration du provider AWS dans Terraform pour gérer des ressources AWS.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
* Savoir configurer le provider AWS dans Terraform
* Comprendre les paramètres nécessaires pour se connecter à l'API AWS
* Savoir tester la connexion avec une source de données
// end::objectifs[]

// tag::deroulement[]

== Descriptif du provider

https://registry.terraform.io/providers/hashicorp/aws/latest[🔗 hashicorp/aws]

* permet d'interfacer Terraform avec les services AWS
* nécessite une configuration spécifique pour se connecter à l'API AWS
* permet de gérer les ressources AWS (EC2, S3, VPC, etc.)

=== Tour d'horizon des possibilités

* **Connexion à l'API AWS** :
** configuration des paramètres de connexion
** gestion des clés d'accès et des secrets

* **Gestion des utilisateurs IAM** :
** création, modification, suppression
** gestion des rôles, permissions, etc.

include::../../../../adoc/libs/slide-notitle.adoc[]

* **Gestion des instances EC2** :
** création, modification, suppression
** gestion des volumes, interfaces réseau, etc.

* **Gestion des ressources** :
** stockage S3, réseau VPC, snapshots, etc.

// tag::demo[]

== Démonstration

Connecter Terraform avec AWS

[NOTE.speaker]
--

**On voit après en détail comment configurer le provider AWS dans Terraform, cette démo permet une première approche rapide**

Cette démonstration nécessite une configuration AWS IAM préalablement configurée et fonctionnelle

* Dans AWS, créer une clé d'accès et un secret et les stocker en lieu sûr

* Dans Terraform, configurer le provider AWS avec les informations de connexion suivantes :

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}

provider "aws" {
  region     = "us-west-2"
  access_key = "YOUR_ACCESS_KEY"
  secret_key = "YOUR_SECRET_KEY"
}
```

* En l'état cela ne permet pas de tester si la connexion fonctionne correctement car notre configuration ne contient aucune requête

* Pour tester la connexion, ajouter une source de données :

```hcl
data "aws_iam_user" "current" {
  user_name = "your-username"
}

output "aws_user_arn" {
  value = data.aws_iam_user.current.arn
}
```

* Exécuter `terraform init` puis `terraform apply` pour vérifier que la connexion fonctionne correctement, si c'est le cas on récupère l'ARN de l'utilisateur

* Montrer le comportement lorsque la connexion ne fonctionne pas :
** Si les clés sont invalides, on obtient une erreur `InvalidClientTokenId`
** Si la région est incorrecte, on obtient une erreur `InvalidEndpoint`
--

// end::demo[]

== Préparer l'environnement AWS

* pour pouvoir connecter Terraform à AWS, une configuration IAM doit être préalablement configurée
* les clés d'accès doivent être accessibles depuis le système où Terraform est exécuté
* un utilisateur IAM avec les permissions nécessaires doit être créé

=== Créer un moyen d'authentification avec AWS

* Créer un utilisateur IAM avec les permissions nécessaires
* Générer une clé d'accès et un secret

* pour des raisons de sécurité, il est recommandé d'utiliser des rôles IAM et des profils d'instance lorsque cela est possible

=== Configurer le provider

Ajouter le provider dans le fichier de configuration Terraform

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}
```

**Cela permet de s'assurer que Terraform utilise le bon provider**

=== Configurer le provider

Comme pour tout provider il faut consulter la https://registry.terraform.io/providers/hashicorp/aws/latest/docs[documentation] pour connaître les paramètres nécessaires

Le provider hashicorp/aws nécessite les paramètres suivants :

* `region` : la région AWS
* `access_key` : la clé d'accès AWS
* `secret_key` : le secret AWS

=== Arguments optionnels mais recommandés

* `profile` : permet d'utiliser un profil AWS configuré dans le fichier de configuration AWS CLI
* `shared_credentials_file` : permet de spécifier un fichier de configuration alternatif pour les credentials AWS

=== Exemple de configuration

```hcl
provider "aws" {
  region     = "us-west-2"
  access_key = "YOUR_ACCESS_KEY"
  secret_key = "YOUR_SECRET_KEY"
}
```

**En l'état cette configuration ne permet pas de tester la connexion, il faut ajouter une interaction avec l'API AWS**

=== Tester la connexion

Pour vérifier que la connexion fonctionne correctement, il est possible d'ajouter une source de données, comme https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_user[indiqué dans la documentation du provider]

```hcl
data "aws_iam_user" "current" {
  user_name = "your-username"
}
```

=== Afficher un résultat

Pour afficher un résultat, il est possible d'utiliser une sortie Terraform

```hcl
output "aws_user_arn" {
  value = data.aws_iam_user.current.arn
}
```

=== Exécuter Terraform

Pour tester la connexion, il suffit d'exécuter les commandes suivantes :

```shell
terraform init
terraform apply
```

**Si la connexion fonctionne correctement, Terraform affiche l'ARN de l'utilisateur**

// end::deroulement[]

== Conclusion
// tag::conclusion[]
* le provider hashicorp/aws permet de gérer des ressources AWS avec Terraform
* il nécessite une configuration spécifique pour se connecter à l'API AWS
* il est possible de tester la connexion avec une source de données
// end::conclusion[]