:titre: Brise-glace
:module: Onboarding
:duree: 60
:description: Mieux connaître sa promo
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../adoc/libs
endif::[]

// tag::objectifs[]
// end::objectifs[]

// tag::deroulement[]
== Apprenons à nous connaître !

**Activités au choix :**

* Défi des trois faits

* Les Associations de Mots

* Le tour du monde virtuel

* Emoji story

* Proposez vos idées d’activités !

[NOTE.speaker]
--
**Défi des trois faits**

Chaque participant doit donner trois faits à son sujet. Deux de ces faits doivent être vrais, et un doit être faux.
Les autres personnes sont invitées à deviner quel fait est faux

**Les Associations de Mots**

Le formateur propose un mot en lien avec la formation (par exemple : "sécurité", "collaboration", "infrastructure").
Chaque participant doit, à tour de rôle, dire le premier mot qui lui vient à l'esprit en entendant ce mot.
Après un tour complet, engagez une discussion sur les associations les plus intéressantes ou inattendues.


**Le tour du monde virtuel**

Demandez à chaque participant de partager où il se trouve actuellement et une particularité ou un fait intéressant sur sa ville ou région. Cela aide à créer un lien entre les participants, surtout s'ils viennent de différents endroits.

**Emoji story**

Demandez à chaque participant de raconter ce qu'il a fait ce matin ou ce week-end uniquement à l'aide d'emojis. Les autres doivent deviner l'histoire. C'est léger et permet de rire ensemble.
--
// end::deroulement[]