graph TD
    A[Matériel physique] --> B[Système d'exploitation hôte]
    B --> C[Docker Engine]
    
    C --> D[Conteneur 1]
    C --> E[Conteneur 2]

    D --> D1[Application 1]
    D --> D2[Librairies et dépendances 1]

    E --> E1[Application 2]
    E --> E2[Librairies et dépendances 2]
