:title: BDD Avancée 
:number: 02
:duration: 35
include::../../../../adoc/libs/header-saison.adoc[]

// tag::intro[]
Approfondissement des techniques de gestion et optimisation de bases de données.
// end::intro[]

== Objectifs pédagogiques

// tag::objectifs[]
Maîtriser les concepts avancés des bases de données
Optimiser les performances des requêtes
Gérer des bases de données pour des projets de grande envergure
// end::objectifs[]

== Notions

// tag::notions[]
Modélisation avancée des données
Indexation et optimisation des requêtes
Transactions et gestion de concurrence
Architectures distribuées de bases de données
Sécurité et contrôle d'accès
// end::notions[]

== Prérequis formateur

// tag::prerequis[]
Expertise en bases de données relationnelles et non relationnelles
Connaissance approfondie des techniques d'optimisation
Expérience en gestion de bases de données avancée
// end::prerequis[]

== Résumé

// tag::resume[]
Cette saison permet aux apprenants de se lancer sereinement dans leur formation. On les aide à installer tous les outils, on leur présente quelques notions d'introduction, on les prépare à savoir cloner les challenges et lancer des DevContainer.
// end::resume[]

== Déroulement

link:./overview.html[Vue kanban]

// tag::deroulement[]
include::episodes/*/*.adoc[opts=episodes]
// end::deroulement[]