:title: Python 
:number: 03
:duration: 140
include::../../../../adoc/libs/header-saison.adoc[]

// tag::intro[]
Maîtrise de Python pour le développement de scripts, l'analyse de données, et la manipulation de grands ensembles de données.
// end::intro[]

== Objectifs pédagogiques

// tag::objectifs[]
Acquérir une maîtrise des fondamentaux de Python
Savoir manipuler des données et automatiser des processus
Développer des scripts pour l’analyse et le traitement de données
// end::objectifs[]

== Notions

// tag::notions[]
Syntaxe et structures de données
Manipulation de fichiers et traitement de données
Programmation orientée objet
Librairies data science (Pandas, NumPy)
Visualisation de données
Gestion des erreurs et debugging
// end::notions[]

== Prérequis formateur

// tag::prerequis[]
Expertise en Python
Connaissance des bibliothèques de data science
Expérience en manipulation et analyse de données
// end::prerequis[]

== Résumé

// tag::resume[]
Cette saison permet aux apprenants de se lancer sereinement dans leur formation. On les aide à installer tous les outils, on leur présente quelques notions d'introduction, on les prépare à savoir cloner les challenges et lancer des DevContainer.
// end::resume[]

== Déroulement

link:./overview.html[Vue kanban]

// tag::deroulement[]
include::episodes/*/*.adoc[opts=episodes]
// end::deroulement[]