timeline
    Début : Titre et objectifs
    Partie 1 : slide
    Partie 2 : slide
    Partie 3 : slide 3.1 : slide 3.2
    [Démo] : slide sans contenu
    [Exercice] : slide
    Conclusion : points synthétiques