:titre: Boucles avancées
:module: JavaScript
:duree: 60
:description: Ce module aborde des méthodes avancées pour parcourir des tableaux en JavaScript.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" != "yes"]
:docinfo: shared
:docinfodir: ../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
* Connaître des méthodes avancées pour parcourir des tableaux
* Savoir utiliser des boucles imbriquées
* Savoir utiliser les structures de contrôle `break` et `continue`
// end::objectifs[]

// tag::deroulement[]

== Boucles avancées

=== `for...in`

**Description** : Parcourt les propriétés d'un tableau.

**Exemple** :

```js
const tableau = [1, 2, 3];

for (const index in tableau) {
  console.log(index);
}
```

=== `for...of`

**Description** : Parcourt les éléments d'un objet itérable.

**Exemple** :

```js
const tableau = [1, 2, 3];

for (const element of tableau) {
  console.log(element);
}
```

=== `forEach`

**Description** : Exécute une fonction donnée sur chaque élément d'un tableau.

**Exemple** :

```js
const tableau = [1, 2, 3];

tableau.forEach((element) => {
  console.log(element);
});
```

== Boucles imbriquées

* il s'agit de boucles qui sont placées à l'intérieur d'autres boucles
* elles sont souvent utilisées pour parcourir des tableaux multidimensionnels

=== Exemple

**Parcours d'une matrice**

```js
const matrice = [
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
];

for (let i = 0; i < matrice.length; i++) {
  for (let j = 0; j < matrice[i].length; j++) {
    console.log(`Élément à [${i}][${j}] : ${matrice[i][j]}`);
  }
}
```

**Explication** : La boucle extérieure parcourt chaque ligne de la matrice, tandis que la boucle intérieure parcourt chaque élément de la ligne.

// tag::demo[]

== Démonstration

Utilisation de boucles imbriquées

[NOTE.speaker]
====

Tester l'exemple vu précédemment dans la console du navigateur.

====

// end::demo[]

== Structures de contrôle

=== `break`

**Description** : Permet de sortir d'une boucle.

**Exemple** :

```js
for (let i = 0; i < 10; i++) {
  if (i === 5) {
    break; // Arrête la boucle lorsque i est égal à 5
  }
  console.log(i);
}
```

=== `continue`

**Description** : Passe à l'itération suivante d'une boucle.

**Exemple** :

```js
for (let i = 0; i < 10; i++) {
  if (i % 2 === 0) {
    continue; // Saute l'itération si i est pair
  }
  console.log(i); // Affiche uniquement les nombres impairs
}
```

// tag::demo[]

== Démonstration

Utilisation des structures de contrôle

[NOTE.speaker]
====

Tester les exemples vus précédemment dans la console du navigateur.

====

// end::demo[]

// end::deroulement[]

== Conclusion

// tag::conclusion[]
* Les boucles avancées permettent de parcourir des tableaux de manière efficace
* Les boucles imbriquées sont utiles pour parcourir des tableaux multidimensionnels
* Les structures de contrôle `break` et `continue` permettent de contrôler le flux d'exécution des boucles
// end::conclusion[]