:titre: Fonctions avancées
:module: JavaScript
:duree: 60
:description: Ce module a pour objectif de découvrir les concepts de paramètres et d'arguments en JavaScript.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" != "yes"]
:docinfo: shared
:docinfodir: ../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
* Découvrir les concepts de paramètre et d'argument
* Apprendre à passer des paramètres à une fonction
* Comprendre les paramètres par défaut
// end::objectifs[]

// tag::deroulement[]

== Paramètres et arguments

Prenons ce code

```js
function hello(info) {
  console.log("Bonjour " + info + " !");
}

hello("monsieur");
```

L'exécution de la fonction `hello` va déclencher l'affichage de 'Bonjour monsieur !' en console.

En effet, lors de l'exécution la valeur du paramètre `info` sera égale à la valeur de l'argument passé, ici `'monsieur'`.

> Ok, mais la c'est comme d'hab.

include::../../../../adoc/libs/slide-notitle.adoc[]

Il est possible de définir plusieurs paramètres à une fonction et de fait, transmettre plusieurs arguments

```js
function hello(message, info) {
  console.log(message + " " + info + " !");
}

hello("Coucou", "madame");
```

L'exécution de la fonction `hello` va déclencher l'affichage de 'Coucou madame !' en console.

Dans cet exemple, `message` sera égal à `'Coucou'` et `info` à `'madame'`.

=== Par défaut

Il est même possible de définir une valeur par défaut dans les paramètres. Si la donnée n'est pas transmise en argument, la valeur par défaut sera utilisée.

```js
function hello(message, info = "inconnu") {
  console.log(message + " " + info + " !");
}

hello("Salut");
```

L'exécution de la fonction `hello` va déclencher l'affichage de 'Coucou inconnu !' en console.

== Retour à l'envoyeur

include::../../../../adoc/libs/slide-notitle.adoc[]

Un principe très important / puissant est qu'une fonction peut retourner de l'information.

Dans l'exemple précédent

```js
function hello(info) {
  console.log("Bonjour " + info + " !");
}

hello("monsieur");
```

notre fonction ne retourne rien, elle se contente de déclencher un message en console.

> "Ne retourne rien" ???

include::../../../../adoc/libs/slide-notitle.adoc[]

Retourner signifie que la fonction nous donne une valeur après son exécution.

Mais pour le moment ...

```js
function hello(info) {
  console.log("Bonjour " + info + " !");
}

const phrase = hello("monsieur");
```

la variable `phrase` va contenir `undefined`. La fonction n'a rien renvoyé / retourné.

include::../../../../adoc/libs/slide-notitle.adoc[]

Les fonctions sont pratiques pour rassembler du code mais également pour réaliser des opérations bien définies.

Par exemple :

- "Donne moi un chiffre aléatoire"
- `const aleatoire = getRandom();`

Si on écrit un code comme ça, pour le moment, la variable sera forcément `undefined`

include::../../../../adoc/libs/slide-notitle.adoc[]

Ajoutons un retour.

```js
function hello(info) {
  return "Bonjour " + info + " !";
}

const phrase = hello("monsieur");
```

La fonction, lors de son exécution va retourner (`return`) la chaîne de caractères `'Bonjour ' + info + ' !'`. Cette chaîne va être stockée dans la variable `phrase`.

Ainsi, si plus tard dans le programme nous déclenchons `console.log(phrase);`, la console affichera bien la valeur générée par la fonction et stockée dans la variable.

// tag::demo[]

## Place au concret

Allons tester.

[NOTE.speaker]
====

* Créer une fonction simple

```js
function addition(a, b) {
  return a + b;
}
```

* Ici, les paramètres sont `a` et `b`

* Appeler la fonction avec des arguments

```js
let resultat = addition(5, 3);
console.log(resultat); // Affiche 8
```

* Ici, les arguments sont `5` et `3`

* Essayer avec d'autres arguments

```js
console.log(addition(10, 15)); // Affiche 25
console.log(addition(-3, 7));  // Affiche 4
```

* Définir des valeurs par défaut

```js
function additionAvecDefaut(a = 0, b = 0) {
  return a + b;
}
console.log(additionAvecDefaut()); // Affiche 0
```

====

// end::demo[]

// tag::exercice[]

== Exercice

Écrivez une fonction en JavaScript appelée calculerTotal qui prend plusieurs paramètres pour effectuer un calcul mathématique simple. La fonction doit :

* Prendre trois paramètres : `prix`, `quantite`, et `taxe`.
* Utiliser des valeurs par défaut pour `quantite` (1) et `taxe` (0.2).
* Calculer le coût total en utilisant la formule : `total = prix * quantite * (1 + taxe)`.
* Retourner le coût total.
* Tester la fonction avec différents ensembles d'arguments pour vérifier son bon fonctionnement.

// end::exercice[]

// end::deroulement[]

== Conclusion

// tag::conclusion[]
* Les fonctions permettent de regrouper du code et de le réutiliser
* Les fonctions peuvent accepter des paramètres et retourner des valeurs
* Les paramètres peuvent avoir des valeurs par défaut
// end::conclusion[]