:titre: Tableaux
:module: JavaScript
:duree: 60
:description: Ce module aborde la syntaxe des tableaux en JavaScript et leur manipulation.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" != "yes"]
:docinfo: shared
:docinfodir: ../../../adoc/libs
endif::[]

== Objectifs pédagogiques

// tag::objectifs[]
* Comprendre la syntaxe des tableaux en JavaScript
* Savoir manipuler les tableaux
// end::objectifs[]

// tag::deroulement[]

== Variables et types

Une variable peut stocker différents types de données :

- `Boolean`
- `String`
- `Number`

mais d'autres types existent... notamment les tableaux : `Array` !

_Ptsss, `Array` n'est pas vraiment un `type`. Mais en première approche, ça ira très bien !_

=== Tableaux, c'est à dire ?

Les tableaux servent à stocker plusieurs données dans une même variable.

Une sorte d'étagère de boîtes.

Partons du stockage d'un prénom

```js
const prenom = "lucie";
```

Comment stocker plusieurs prénons ? Plusieurs variables ?

```js
const prenom1 = "lucie";
const prenom2 = "frank";
// ... Mouais c'est pas idéal :/
```

Si nous avons 5 ou 10 prénoms ou plus encore ?

== Place au code

=== Définir un tableau

un tableau vide

```js
const prenoms = [];
```

Voici notre étagère `prenoms`, pour le moment vide.

=== Ajouter des valeurs dans un tableau

à la création

```js
const prenoms = ["lucie", "frank"];
```

Les valeurs sont séparées par une virgule.

=== Lire les valeurs

Les valeurs d'un tableau sont accessible par leur index, leur "adresse".

```js
const prenoms = ["lucie", "frank", "marie"];
// Index :        0        1        2
```

Les index commencent à `0`.

Pour la lecture

```js
// prenoms[0] contient lucie
// prenoms[1] contient frank
// prenoms[2] contient marie

console.log(prenoms[1]); // frank
```

=== Insérer une valeur après la création

```js
const prenoms = ["lucie", "frank", "marie"];
// Index :        0        1        2
```

Ajoutons 'sam'

```js
prenoms[3] = "sam";

// prenoms : ['lucie', 'frank', 'marie', 'sam']
```

=== Entrées vides

```js
const prenoms = ["lucie", "frank", "marie"];
// Index :        0        1        2
```

Attention à l'index utilisé

```js
prenoms[4] = "sam";

// prenoms : ['lucie', 'frank', 'marie', empty, 'sam']
```

`prenoms[3]` sera vide

=== Écrasement

```js
const prenoms = ["lucie", "frank", "marie"];
// Index :        0        1        2
```

Méfiance avec les index et leur valeur

```js
prenoms[1] = "sam";

// prenoms : ['lucie', 'sam', 'marie']
```

la valeur 'frank' a été écrasée

== Contenus

=== Stockage libre

Un tableau peut stocker n'importe quel type.

```js
const unTableau = ["info", 12, false, "Du texte"];
```

=== et même...

...d'autres tableaux ! oO

> TABLEAU-CEPTION

```js
const details = ["homme", ["sam", "dujean", 33, "dijon"]];
// details[0] : 'homme'
// details[1] : Array
```

Et pour la lecture, `details[1]` contient donc un tableau

```js
details[1][3]; // dijon | index 3 de l'index 1
```

=== Présentation

Il est possible de présenter les tableaux de manière plus agréable

```js
const unTableau = ["info", 12, false, "Du texte"];
```

```js
const unTableau = ["info", 12, false, "Du texte"];
```

// tag::exercice[]

== Exercice

* Déclarer un tableau contenant une liste de fruits.
* Afficher une valeur du tableau de votre choix
* Afficher l'index de la valeur

[NOTE.speaker]
====
Pendant la correction, aborder les méthodes `push`, `length` et l'ajout d'un élément via un nouvel index.
====

// end::exercice[]

// tag::exercice[]

== Vous en voulez encore ?

* https://stackblitz.com/edit/vitejs-vite-uvlaqf?file=src%2Fmain.js[Bonus 1]
* https://stackblitz.com/edit/vitejs-vite-bpdfn5?file=src%2Fmain.js[Bonus 2]

// end::exercice[]

// end::deroulement[]

== Conclusion

// tag::conclusion[]
* Les tableaux permettent de stocker plusieurs valeurs dans une seule variable
* Les valeurs sont accessibles par leur index
* Les tableaux peuvent contenir n'importe quel type de données
// end::conclusion[]