:title: Déploiement et orchestration
:number: 06
:duration: 35
include::../../../../adoc/libs/header-saison.adoc[]

// tag::intro[]
Mise en place et gestion de solutions data en production, avec des outils de containerisation et d'orchestration.
// end::intro[]

== Objectifs pédagogiques

// tag::objectifs[]
Savoir déployer des applications dans des environnements de production
Utiliser les outils de containerisation et orchestration
Assurer la maintenance et l’optimisation en production
// end::objectifs[]

== Notions

// tag::notions[]
Docker et containerisation
Kubernetes et orchestration de containers
Gestion des environnements et versions
Monitoring et logging
Résilience et scalabilité
// end::notions[]

== Prérequis formateur

// tag::prerequis[]
Maîtrise de Docker et Kubernetes
Expérience en déploiement et maintenance d’applications
Connaissance en monitoring et optimisation des performances
// end::prerequis[]

== Résumé

// tag::resume[]
Cette saison permet aux apprenants de se lancer sereinement dans leur formation. On les aide à installer tous les outils, on leur présente quelques notions d'introduction, on les prépare à savoir cloner les challenges et lancer des DevContainer.
// end::resume[]

== Déroulement

link:./overview.html[Vue kanban]

// tag::deroulement[]
include::episodes/*/*.adoc[opts=episodes]
// end::deroulement[]