:title: Remise à niveau réseau et teamwork
:number: 04
include::../../../../../../adoc/libs/header-episode.adoc[]


// tag::intro[]
Remise à niveau réseau, sensibilisation à l'entraide et élection de délégué
// end::intro[]

== Objectifs pédagogiques

// tag::objectifs[]
* Comprendre les différentes couches des modèles OSI et TCP/IP, leurs fonctions et comment elles interagissent.
* Maîtriser l’adressage IP, y compris les concepts de sous-réseautage et d’adressage privé/public.
* Connaître les principes du routage et de la commutation, et savoir comment les implémenter dans des réseaux réels.
* Identifier et comprendre les principaux protocoles de communication réseau.
* Comprendre les objectifs et le contenu de la certification CCNA.
* Apprendre les bases de la préparation à l’examen, y compris les ressources disponibles et les stratégies de révision.
* Favoriser la collaboration et l’entraide entre les participants.
* Comprendre l’intérêt des soft skills dans un environnement d’administration système
// end::objectifs[]

== Prérequis formateur

// tag::prerequis[]
* Du courage et de la patience, beaucoup de théorie aujourd’hui
// end::prerequis[]

== Déroulement

// tag::deroulement[]

include::../../../../modules/reseau/remise-a-niveau.adoc[options=modules]

TIP: ☕ Pause café pendant le module de réseau

TIP: 🍕 Pause déjeuner

include::../../../../modules/programme/certification.adoc[options=modules]

include::../../../../modules/onboarding/teamwork.adoc[options=modules]

WARNING: Journée async demain, programmer les activités.

:description: Pas de challenge
include::../../../../../../adoc/libs/intro-challenge.adoc[]

.👨‍🏫 Référent de promo
[.suivi]
[sidebar]
--
include::../../../../suivi.adoc[tags=s01e04]
--

// end::deroulement[]