:title: Infrastructure de serveurs
:number: 08
:duration: 35
include::../../../../adoc/libs/header-saison.adoc[]

// tag::intro[]
Déploiement automatisé de serveurs et mise en communication.
// end::intro[]

== Objectifs pédagogiques

// tag::objectifs[]
- **Comprendre** les outils de déploiement
- **Appliquer** des recettes de déploiement
// end::objectifs[]

== Notions

// tag::notions[]
- Ansible
- Ansible Galaxy
- Docker
// end::notions[]

== Prérequis formateur

// tag::prerequis[]
* Avoir une VM kourou fonctionnelle
* Bien connaître Docker et compose
* Penser à fournir le ebook O'clock
// end::prerequis[]

== Résumé

// tag::resume[]
Les apprenants ont les connaissances nécessaires pour administrer des machines du point de vu système et réseau, ainsi que Docker. Cette saison va leur permettre de mettre en place des serveurs et de les configurer automatiquement. Ils vont apprendre à utiliser Ansible pour déployer des serveurs. Pour simplifier l'infrastructure nécessaire, ils utiliseront un environnement de tests en local entièrement géré par Docker. Un mise en pratique réelle se fera sur la VM serveur de Kourou le premier jour.
// end::resume[]

== Déroulement

link:./overview.html[Vue kanban]

// tag::deroulement[]
include::episodes/*/*.adoc[opts=episodes]
// end::deroulement[]
