:titre: Introduction à l'Infrastructure as Code (IaC)
:module: Virtualisation
:duree: 60
:description: Ce module introduit les concepts de l'Infrastructure as Code (IaC), ses avantages et inconvénients, et les outils principaux utilisés pour automatiser la gestion de l'infrastructure.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]


== Objectifs pédagogiques

// tag::objectifs[]

* Comprendre les principes de l'Infrastructure as Code (IaC)
* Identifier les avantages et inconvénients de l'IaC
* Connaître les outils principaux d'IaC (Terraform, Ansible, etc.)

// end::objectifs[]

// tag::deroulement[]

== Définition de l'IaC

* permet la gestion de l'infrastructure via des fichiers de configuration
** (réseaux, machines virtuelles, équilibreurs de charge, connexions, etc.)
* principes essentiels :
** automatisation
** versionning
** réutilisabilité
** consistance

== Avantages et inconvénients de l'IaC

[cols="1,1"]
|===

| Avantages | Inconvénients

a| 
* Automatisation et rapidité
* Consistance et réduction des erreurs
* Versionning et historique
* Collaboration et partage

a|
* Complexité initiale
* Gestion des états et dépendances
* Risques de sécurité
* Dépendance à l'outil

|===

[NOTE.speaker]
--

**Avantages** :

* Automatisation et rapidité
** L'IaC permet l'automatisation des déploiements d'infrastructure, réduisant le temps nécessaire pour mettre en place et configurer des environnements.
** **Exemple** : Déploiement d'une infrastructure complète en quelques minutes grâce à un fichier de configuration pré-écrit.
* Consistance et Réduction des Erreurs
** Les configurations étant définies dans le code, elles sont répétables et consistent à chaque déploiement, minimisant les erreurs humaines.
** **Exemple** : Un fichier de configuration IaC assure que chaque environnement de développement, test et production est identique.
* Versionnement et Historisation
** Les fichiers IaC peuvent être stockés dans des systèmes de contrôle de version (comme Git), permettant de suivre les modifications et de revenir à des versions antérieures si nécessaire.
** **Exemple** : Capacité à revenir à une configuration précédente en cas de problème de déploiement.
* Collaboration et Partage
** Facilite la collaboration entre équipes, car les configurations sont documentées et peuvent être partagées facilement.
** **Exemple** : Équipes de développement et d'opérations travaillant ensemble sur la même base de code pour l'infrastructure.

**Inconvénients** :

* Complexité Initiale
** La mise en place de l'IaC peut nécessiter une courbe d'apprentissage et une complexité initiale, surtout pour les équipes non familières avec la gestion de code.
** **Exemple** : Temps d'apprentissage pour comprendre les outils et langages de configuration comme Terraform ou Ansible.
*  Gestion des États et Dépendances
** Certains outils IaC nécessitent une gestion des états de l'infrastructure, ce qui peut être compliqué à gérer et source de problèmes si mal configuré.
** **Exemple** : Les fichiers d'état Terraform qui doivent être gérés correctement pour éviter des incohérences.
* Risques de Sécurité
** Les fichiers de configuration peuvent contenir des informations sensibles (comme des clés d'accès), nécessitant des pratiques de sécurité rigoureuses.
** **Exemple** : Nécessité de chiffrer les secrets et de gérer les accès aux fichiers IaC.
* Dépendance à l'Outil
** Dépendance à un outil spécifique peut être un inconvénient si l'outil n'est plus maintenu ou si l'entreprise souhaite changer de solution.
** **Exemple** : Difficulté à migrer d'un outil IaC à un autre en raison des spécificités de chaque outil.
--

== IaC vs Gestion traditionnelle

[cols="1,1"]
|===

| IaC | Gestion Traditionnelle

a|
* Fichiers de configuration : consistance
* Gestion de l'infrastructure comme du code
* Automatisation des déploiements
* Traçabilité via le contrôle de version
* Scalabilité de l'infrastructure

a| 
* Configuration manuelle
* Scripts et procédures ad-hoc
* Déploiements manuels
* Dépendance élevée à l'intervention humaine, propice aux erreurs

|===

// tag::demo[]

== Démonstration

Exemple de config IaC avec Docker

[NOTE.speaker]
--
**Il n'est pas nécessaire d'approfondir le fonctionnement de Docker pour cette démonstration, nous utiliserons Terraform par la suite. Le but de cette démonstration est de comprendre l'intérêt d'utiliser des fichiers de configuration pour automatiser le déploiement d'une infrastructure**

Utilisons Docker et Docker Compose pour illustrer un exemple simple d'Infrastructure as Code.

Docker compose permet de définir une série de services à lancer dans des conteneurs Docker, avec des configurations spécifiques pour chaque service.

* On crée un fichier `docker-compose.yml` avec la configuration suivante :

```yml
services:
  web:
    image: httpd:latest
    ports:
      - "8080:80"
    networks:
      - webnet

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
```

* On lance les services avec la commande `docker-compose up`

* On accède à l'application web sur `http://localhost:8080` : cela doit afficher **It works**

* On accède à Adminer sur `http://localhost:8081` : on peut se connecter à la base de données MySQL avec les identifiants `root` et `example`

* En quelques secondes, on a déployé une application web et une base de données MySQL avec Docker Compose.

* Qu'est-ce qu'il aurait fallu faire manuellement si l'on n'avait pas utilisé un outil d'IaC ?

--

// end::demo[]

// tag::exercice[]

== Exercice

**Quels services la configuration plus bas permet-elle de lancer ?**

**Quelle procédure aurait-on dû suivre pour les lancer manuellement ?**

**Est-ce que cette procédure manuelle est viable si l'on doit déployer ces services sur de nombreuses machines ?**

```yml
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    environment:
      - ENV=production
    networks:
      - app-network

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exampledb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
```

[NOTE.speaker]
--
Services lancés : 

* Un serveur web Nginx
* Une base de données PostgreSQL

Procédure manuelle :

* Installation de Nginx et configuration du serveur web
* Installation de PostgreSQL et création d'une base de données

Cette procédure est viable pour un petit nombre de machines, mais devient rapidement complexe et fastidieuse à l'échelle.
--

// end::exercice[]

== Outils courants d'IaC

=== Terraform

* Outil d'orchestration d'infrastructure open-source
* permet de définir et fournir des datacenters entiers avec un fichier de configuration
* supporte de nombreux fournisseurs cloud et on-premise
* écrit en Go, maintenu par HashiCorp

=== Exemple de configuration Terraform

```hcl
# Définir le fournisseur (fictif)
provider "fictitious" {
  # Configuration du fournisseur, par exemple des identifiants d'authentification
  api_key = "your_api_key"
}

# Réseau virtuel
resource "fictitious_network" "main" {
  name = "main-network"
  cidr_block = "10.0.0.0/16"
}

# Serveur web 1
resource "fictitious_compute_instance" "web1" {
  name         = "web-server-1"
  instance_type = "t2.micro"
  network_id   = fictitious_network.main.id

  # Configuration simplifiée
  image_id     = "web-server-image"
}

# Serveur web 2
resource "fictitious_compute_instance" "web2" {
  name         = "web-server-2"
  instance_type = "t2.micro"
  network_id   = fictitious_network.main.id

  # Configuration simplifiée
  image_id     = "web-server-image"
}

# Base de données
resource "fictitious_database_instance" "db" {
  name         = "database-server"
  instance_type = "db.t2.micro"
  network_id   = fictitious_network.main.id

  # Configuration simplifiée
  engine       = "postgres"
  version      = "12"
  storage_size = 20
}

# Sorties
output "web_server_ips" {
  value = [
    fictitious_compute_instance.web1.public_ip,
    fictitious_compute_instance.web2.public_ip
  ]
}

output "database_ip" {
  value = fictitious_database_instance.db.public_ip
}
```

[NOTE.speaker]
--
Pas la peine de tout retenir maintenant, on verra Terraform plus en détail après. Il faut surtout comprendre ici que Terraform permet de définir une infrastructure entière avec un fichier de configuration.
--

=== Ansible

* Outil de gestion de configuration open-source
* permet de déployer des applications et de gérer des configurations sur des machines distantes
* basé sur YAML, agentless et utilise SSH pour se connecter aux machines
* écrit en Python, maintenu par Red Hat

=== Exemple de configuration Ansible

```yaml
---
- name: Configure web servers
  hosts: webservers
  become: yes
  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure Apache is started and enabled
      service:
        name: apache2
        state: started
        enabled: true

    - name: Deploy a simple index.html
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Welcome to the Web Server</h1>"

- name: Configure database server
  hosts: databases
  become: yes
  tasks:
    - name: Ensure PostgreSQL is installed
      apt:
        name: postgresql
        state: present
        update_cache: yes

    - name: Ensure PostgreSQL is started and enabled
      service:
        name: postgresql
        state: started
        enabled: true

    - name: Create database and user
      become_user: postgres
      postgresql_db:
        name: exampledb
      postgresql_user:
        name: dbuser
        password: dbpassword
        priv: "ALL"
```

[NOTE.speaker]
--
L'approche d'Ansible est différente de Terraform : Ansible est plus orienté sur la configuration des machines et le déploiement d'applications, tandis que Terraform est plus orienté sur la définition de l'infrastructure elle-même.
--

=== Chef

* Outil de gestion de configuration open-source
* permet de définir des configurations sous forme de code Ruby
* basé sur un modèle client-serveur, avec un serveur Chef et des agents Chef sur les machines
* écrit en Ruby, maintenu par Chef Software

=== Exemple de configuration Chef

Chef utilise plusieurs "recettes" qui sont définies comme ceci :

**Recette webserver**

```ruby
apt_update 'update'

# Installe et configure Apache
package 'apache2'

service 'apache2' do
  action [:enable, :start]
end

file '/var/www/html/index.html' do
  content '<h1>Welcome to the Web Server</h1>'
  mode '0644'
  owner 'www-data'
  group 'www-data'
end
```

[NOTE.speaker]
--
Chef est un peu plus fastidieux à utiliser que Terraform ou Ansible, car il nécessite de définir des recettes en Ruby, il est donc nécessaire de connaître un peu la syntaxe Ruby. Il est cependant très puissant pour des configurations complexes.
--

=== Puppet

* Outil de gestion de configuration open-source
* permet de définir des configurations sous forme de code Puppet
* basé sur un modèle client-serveur, avec un serveur Puppet et des agents Puppet sur les machines
* écrit en Ruby, maintenu par Puppet Labs

=== Exemple de configuration Puppet

Puppet utilise des manifestes pour définir les configurations :

**Manifeste webserver**

```puppet
class my_datacenter_module::webserver {

  # Mise à jour du cache des paquets
  exec { 'apt_update':
    command => '/usr/bin/apt-get update',
    path    => ['/usr/bin', '/usr/sbin'],
  }

  # Installation et configuration d'Apache
  package { 'apache2':
    ensure => installed,
    require => Exec['apt_update'],
  }

  service { 'apache2':
    ensure => running,
    enable => true,
    require => Package['apache2'],
  }

  file { '/var/www/html/index.html':
    ensure  => file,
    content => '<h1>Welcome to the Web Server</h1>',
    mode    => '0644',
    owner   => 'www-data',
    group   => 'www-data',
  }
}
```

[NOTE.speaker]
--
Comme avec Chef, Puppet nécessite de connaître la syntaxe Ruby pour définir des configurations. Il est également très puissant pour des configurations complexes, mais peut être plus difficile à prendre en main.
--

== Pourquoi Terraform ?

Nous allons nous concentrer sur Terraform pour les raisons suivantes.

=== Langage déclaratif

* HashiCorp Configuration Langugage
* permet de décrire l'état souhaité de l'infrastructure
* simplifie la compréhension et la maintenance des configurations complexes

```hcl
provider "fictitious" {
  # Configuration du fournisseur fictif
  api_key = "your_api_key"
}

resource "fictitious_compute_instance" "web" {
  # Nom de l'instance
  name = "simple-web-server"

  # Type d'instance
  instance_type = "t2.micro"

  # Identifiant de l'image
  image_id = "web-server-image"

  # Adresse IP publique
  public_ip = true
}

output "web_server_ip" {
  # Affiche l'adresse IP publique de l'instance
  value = fictitious_compute_instance.web.public_ip
}
```

[NOTE.speaker]
--
**Provider :**

* `provider "fictitious"` : Indique le fournisseur d'infrastructure que Terraform va utiliser. Ici, nous utilisons un fournisseur fictif pour illustrer le concept. Dans un cas réel, cela pourrait être AWS, Azure, ou Google Cloud.
* `api_key = "your_api_key"` : Exemple de configuration d'authentification pour accéder au fournisseur.

**Resource :**

* `resource "fictitious_compute_instance" "web"` : Déclare une ressource de type fictitious_compute_instance avec un identifiant web. Les ressources sont les éléments que Terraform gère.
* `name = "simple-web-server"` : Définit le nom de l'instance à créer.
instance_type = "t2.micro" : Spécifie le type d'instance, ici une petite instance pour un serveur web.
* `image_id = "web-server-image"` : Identifiant de l'image à utiliser pour créer l'instance. Cela pourrait être une image préconfigurée pour un serveur web.
* `public_ip = true` : Indique que l'instance doit avoir une adresse IP publique pour être accessible depuis l'extérieur.

**Output :**

* `output "web_server_ip"` : Déclare une sortie qui affiche l'adresse IP publique de l'instance après la création. Cela permet de récupérer facilement des informations utiles sur les ressources créées.
--

=== Multi-cloud

* Terraform est conçu pour être cloud-agnostique
* il peut gérer des infrastructures sur plusieurs fournisseurs cloud
* il permet aussi de gérer des ressources on-premise
* il offre une flexbilité maximale pour les environnements hybrides et multi-cloud

```hcl
# Fournisseur AWS
provider "aws" {
  region = "us-west-2"
}

# Fournisseur Google Cloud
provider "google" {
  project = "your-gcp-project-id"
  region  = "us-central1"
}

# Ressource AWS: Instance EC2
resource "aws_instance" "web" {
  ami           = "ami-0c55b159cbfafe1f0" # Ubuntu Server
  instance_type = "t2.micro"

  tags = {
    Name = "AWS-Web-Server"
  }
}

# Ressource Google Cloud: Instance Compute Engine
resource "google_compute_instance" "web" {
  name         = "gcp-web-server"
  machine_type = "f1-micro"
  zone         = "us-central1-a"

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }

  network_interface {
    network = "default"
    access_config {}
  }

  labels = {
    Name = "GCP-Web-Server"
  }
}

# Outputs
output "aws_instance_ip" {
  value = aws_instance.web.public_ip
}

output "gcp_instance_ip" {
  value = google_compute_instance.web.network_interface[0].access_config[0].nat_ip
}
```

[NOTE.speaker]
--
**Fournisseurs :**

* `provider "aws"` : Configure Terraform pour utiliser AWS comme fournisseur. La région spécifiée est "us-west-2".
* `provider "google"` : Configure Terraform pour utiliser Google Cloud Platform. Le projet et la région doivent être spécifiés.

**Ressource AWS :**

* `resource "aws_instance" "web"` : Crée une instance EC2 sur AWS avec une image Ubuntu et le type d'instance t2.micro. Les tags sont utilisés pour identifier la ressource.

**Ressource Google Cloud :**

* `resource "google_compute_instance" "web"` : Crée une instance Compute Engine sur GCP avec une image Debian. La configuration inclut le type de machine, la zone, et l'interface réseau.

**Outputs :**

* `output "aws_instance_ip"` : Affiche l'adresse IP publique de l'instance AWS.
* `output "gcp_instance_ip"` : Affiche l'adresse IP NAT de l'instance Google Cloud.
--

=== Extensibilité

* Terraform est extensible via des plugins
* de nombreux fournisseurs cloud et outils tiers sont supportés
* il est possible de créer ses propres plugins pour des intégrations personnalisées

=== Planification des modifications

* Terraform permet de planifier les modifications avant de les appliquer
* il affiche les changements à apporter à l'infrastructure
* cela permet de vérifier les modifications avant de les appliquer

```shell
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  - destroy
  ~ update in-place

Terraform will perform the following actions:

  # aws_instance.web will be updated in-place
  ~ resource "aws_instance" "web" {
        id               = "i-0abcd1234efgh5678"
        instance_type    = "t2.micro" -> "t2.small"
        tags             = {
            "Name"       = "MyWebServer"
          + "Environment" = "Production"
        }
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee to take exactly these actions if you run "terraform apply"
now.
```

[NOTE.speaker]
--
**Résumé Initial :**

Terraform commence par rafraîchir l'état actuel des ressources. Cela garantit que le plan est basé sur l'état réel de l'infrastructure avant d'appliquer les changements.

**Symboles d'Action :**

* `+ create` : Indique que la ressource sera créée.
* `- destroy` : Indique que la ressource sera supprimée.
* `~ update in-place` : Indique que la ressource sera modifiée sur place.

**Changements Planifiés :**

* `aws_instance.web will be updated in-place`: Indique que l'instance EC2 web sera mise à jour sans être recréée.
* `instance_type = "t2.micro" -> "t2.small"` : Montre que le type d'instance passera de t2.micro à t2.small.
* `tags`: Un nouveau tag "Environment" = "Production" sera ajouté.

**Résumé des Actions :**

* `Plan: 0 to add, 1 to change, 0 to destroy.` : Un résumé clair des actions planifiées par Terraform : aucune nouvelle ressource à ajouter, une ressource à modifier, et aucune ressource à supprimer.
--

=== Gestion des états

* Terraform gère un état de l'infrastructure
* il garde une trace des ressources déployées et de leur configuration
* cela permet de gérer les dépendances et de suivre l'évolution de l'infrastructure

=== Modularité et réutilisabilité

* Terraform permet de définir des modules réutilisables
* les modules peuvent être partagés et utilisés dans différentes configurations
* cela permet de standardiser et de réutiliser des composants d'infrastructure

== Quid des autres outils ?

* **Ansible**, **Chef**, **Puppet** : sont généralement utilisés pour la configuration et la gestion d'applications et de systèmes **une fois que l'infrastructure est en place**. Bien qu'ils puissent gérer une infrastructure, ils sont souvent plus orientés vers la **configuration continue** et l'**automatisation des tâches opérationnelles**.

* **CloudFormation** (AWS) ou **ARM Templates** (Azure) : Ces outils sont **spécifiques à leurs fournisseurs respectifs**. Terraform offre l'avantage de **gérer plusieurs fournisseurs avec un seul outil**.

// end::deroulement[]

== Conclusion
// tag::conclusion[]
* L'Infrastructure as Code (IaC) est une approche pour gérer l'infrastructure via des fichiers de configuration.
* Les avantages de l'IaC incluent l'automatisation, la consistance, le versionning et la collaboration.
* Les outils principaux d'IaC incluent Terraform, Ansible, Chef et Puppet.
// end::conclusion[]