:titre: API Proxmox
:module: Virtualisation
:duree: 60
:description: Ce module présente l'API Proxmox, qui permet d'automatiser les tâches de gestion de Proxmox.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]


== Objectifs pédagogiques

// tag::objectifs[]
* Comprendre l'architecture de l'API Proxmox
* Utiliser l'API Proxmox pour automatiser des tâches de gestion
* Savoir utiliser l'API Proxmox pour des opérations avancées
// end::objectifs[]

// tag::deroulement[]

== Architecture de l'API

* construite sur une architecture REST : utilise les verbes HTTP standards (GET, POST, PUT, DELETE)
* offre des endpoints pour gérer toutes les fonctionnalités Proxmox :
** gestion des VM
** gestion des conteneurs
** gestion des sauvegardes
** gestion des snapshots
** gestion des utilisateurs
* nécessite une authentification pour chaque requête

=== Intérêts d'utiliser l'API

* automatiser les tâches de gestion de Proxmox (notamment avec Terraform)
** réduction du temps passé sur des tâches manuelles grâce à des scripts
** possibilité de lancer des processus à intervalles réguliers
* intégrer Proxmox dans des workflows plus larges
* admninistrer Proxmox à distance

== Structure de l'API

3 concepts clés :

* **Endpoints** : URL pour accéder à une ressource
* **Requêtes HTTP** : permettent de manipuler les ressources
* **Authentification** : nécessaire pour chaque requête

=== Endpoints de l'API

* URL spécifiques pour interagir avec l'API de Proxmox
* chaque endpoint correspond à une ressource ou action de Proxmox
* exemple : `/api2/json/nodes` pour obtenir la liste des noeuds

=== Requêtes HTTP

* utilisent les verbes HTTP standards

* **GET** : récupérer une ressource (ex. : lister les machines virtuelles)
* **POST** : créer une ressource (ex. : créer une nouvelle machine virtuelle)
* **PUT** : mettre à jour une ressource (ex. : modifier les configurations d'une machine virtuelle)
* **DELETE** : supprimer une ressource (ex. : supprimer une machine virtuelle)

=== Authentification

* nécessaire pour chaque requête
* deux méthodes d'authentification possibles :
** Basic Auth : c'est la méthode la plus simple, mais la moins sécurisée (combinaison login/mot de passe)
** Token : méthode plus sécurisée, nécessite de générer un token d'authentification

Disponible à l'adresse : https://<ip_proxmox>:8006/api2/json/access/ticket en méthode **POST**

=== Documentation de l'API

https://pve.proxmox.com/pve-docs/api-viewer/index.html[🔗 Proxmox API Documentation]

* liste l'ensemble des endpoints disponibles
* détaille les paramètres nécessaires pour chaque requête
* fournit des exemples de requêtes

// tag::demo[]

== Démonstration

Utilisation de l'API Proxmox

[NOTE.speaker]
--
* Commencer par parcourir la https://pve.proxmox.com/pve-docs/api-viewer/index.html[documentation de l'API] pour se familiariser avec les endpoints disponibles

**Étape 2 : Authentification**

* **Ouvrir Postman/Insomnia** :

Lancez le client HTTP de votre choix.

* **Créer une nouvelle requête** :

Sélectionnez le type de requête `POST`.

* **Configurer l'URL d'authentification** :

Entrez l'URL suivante : https://<proxmox-server>:8006/api2/json/access/ticket.

* **Configurer les paramètres de la requête** :

Dans l'onglet "Body", choisissez le format `x-www-form-urlencoded`.

Ajoutez les clés et valeurs suivantes :

* `username` : `<votre-username>@pam`
* `password` : `<votre-mot-de-passe>`

* **Envoyer la requête** :

Cliquez sur "Envoyer" pour obtenir un ticket d'authentification.

Notez les valeurs `ticket` et `CSRFPreventionToken` dans la réponse pour les requêtes futures.

**Étape 3 : Récupérer des informations sur les VM**

* **Créer une nouvelle requête GET** :

Sélectionnez le type de requête `GET`.

* **Configurer l'URL pour lister les VM** :

Entrez l'URL suivante : https://<proxmox-server>:8006/api2/json/nodes/<node>/qemu.

* **Ajouter les en-têtes d'authentification** :

Dans l'onglet "Headers", ajoutez :

* `Cookie` : `PVEAuthCookie=<votre-ticket>`
* `CSRFPreventionToken` : `<votre-CSRF-token>`

* **Envoyer la requête** :

Cliquez sur "Envoyer" pour obtenir la liste des machines virtuelles disponibles sur le nœud spécifié.

**Étape 4 : Démarrer une VM**

* **Créer une nouvelle requête POST** :

Sélectionnez le type de requête `POST`.

* **Configurer l'URL pour démarrer une VM** :

Entrez l'URL suivante : https://<proxmox-server>:8006/api2/json/nodes/<node>/qemu/<vmid>/status/start.

Remplacez `<vmid>` par l'identifiant de la machine virtuelle à démarrer.

* **Ajouter les en-têtes d'authentification** :

Réutilisez les mêmes en-têtes d'authentification que précédemment.

* **Envoyer la requête** :

Cliquez sur "Envoyer" pour démarrer la VM spécifiée.
--

// end::demo[]

== Utilisation de l'API pour des opérations avancées

**Même si les opérations sont réalisables avec Terraform, il est important de connaître le fonctionnement de l'API pour des cas d'usage plus avancés.**

=== Opérations courantes via l'API

* Lancer, arrêter, redémarrer des machines virtuelles : via l'URL `/api2/json/nodes/<node>/qemu/<vmid>/status/<action>`

* Créer et supprimer des machines virtuelles : via les URLs `/api2/json/nodes/<node>/qemu` et `/api2/json/nodes/<node>/qemu/<vmid>`

include::../../../../adoc/libs/slide-notitle.adoc[]

* Gérer les snapshots : via les URLs `/api2/json/nodes/<node>/qemu/<vmid>/snapshot` et `/api2/json/nodes/<node>/qemu/<vmid>/snapshot/<snapname>`

* Gérer les sauvegardes : via les URLs `/api2/json/nodes/<node>/backup` et `/api2/json/nodes/<node>/backup/<backupid>`

include::../../../../adoc/libs/slide-notitle.adoc[]

* Gérer les utilisateurs : via les URLs `/api2/json/access/users` et `/api2/json/access/users/<userid>`

* Gérer les groupes : via les URLs `/api2/json/access/groups` et `/api2/json/access/groups/<groupid>`

=== Automatiser les tâches grâce à l'API

Exemple de script Bash pour démarrer toutes les machines virtuelles d'un nœud :

```sh
#!/bin/bash

# Variables à configurer
PVE_SERVER="https://<proxmox-server>:8006"
USERNAME="<votre-username>@pam"
PASSWORD="<votre-mot-de-passe>"
NODE="<votre-nœud>"

# Fonction pour obtenir un ticket d'authentification
get_auth_ticket() {
    response=$(curl -s -k -X POST "$PVE_SERVER/api2/json/access/ticket" \
        -d "username=$USERNAME&password=$PASSWORD")
    ticket=$(echo $response | jq -r '.data.ticket')
    csrf_token=$(echo $response | jq -r '.data.CSRFPreventionToken')
}

# Fonction pour lister toutes les machines virtuelles
list_vms() {
    vms=$(curl -s -k -X GET "$PVE_SERVER/api2/json/nodes/$NODE/qemu" \
        -H "Cookie: PVEAuthCookie=$ticket" | jq -r '.data[].vmid')
}

# Fonction pour démarrer une machine virtuelle
start_vm() {
    local vmid=$1
    curl -s -k -X POST "$PVE_SERVER/api2/json/nodes/$NODE/qemu/$vmid/status/start" \
        -H "Cookie: PVEAuthCookie=$ticket" \
        -H "CSRFPreventionToken: $csrf_token"
}

# Obtenir le ticket d'authentification
get_auth_ticket

# Lister toutes les machines virtuelles
list_vms

# Démarrer chaque machine virtuelle
for vmid in $vms; do
    echo "Démarrage de la VM avec l'ID $vmid..."
    start_vm $vmid
done

echo "Toutes les machines virtuelles ont été démarrées."
```

// end::deroulement[]

== Conclusion
// tag::conclusion[]
* L'API Proxmox permet d'automatiser les tâches de gestion de Proxmox
* Elle offre des endpoints pour gérer toutes les fonctionnalités de Proxmox
* L'authentification est nécessaire pour chaque requête
// end::conclusion[]