:titre: Provider BPG Proxmox Terraform
:module: Virtualisation
:duree: 120
:description: Ce module aborde la configuration du provider Proxmox dans Terraform pour gérer des ressources Proxmox.
include::../../../../adoc/libs/header-module.adoc[]

ifeval::["{visible-on-html}" !=  "yes"]
:docinfo: shared
:docinfodir: ../../../../adoc/libs
endif::[]


== Objectifs pédagogiques

// tag::objectifs[]
* Savoir configurer le provider Proxmox dans Terraform
* Comprendre les paramètres nécessaires pour se connecter à l'API Proxmox
* Savoir tester la connexion avec une source de données
// end::objectifs[]

// tag::deroulement[]

== Descriptif du provider

https://registry.terraform.io/providers/bpg/proxmox/latest[🔗 bpg/proxmox]

* permet d'interfacer Terraform avec une instance Proxmox
* nécessite une configuration spécifique pour se connecter à l'API Proxmox
* permet de gérer les ressources Proxmox (VM, stockage, réseau, etc.)

=== Tour d'horizon des possibilités

* **Connexion à l'API Proxmox** :
** configuration des paramètres de connexion
** gestion des tokens d'authentification

* **Gestion des utilisateurs** :
** création, modification, suppression
** gestion des rôles, permissions, etc.

include::../../../../adoc/libs/slide-notitle.adoc[]

* **Gestion des VM** :
** création, modification, suppression
** gestion des disques, interfaces réseau, etc.

* **Gestion des ressources** :
** stockage, réseau, snapshots, etc.

// tag::demo[]

== Démonstration

Connecter Terraform avec une instance Proxmox 

[NOTE.speaker]
--

**On voit après en détail comment configurer le provider Proxmox dans Terraform, cette démo permet une première approche rapide**

Cette démonstration nécessite une instance Proxmox préalablement configurée et fonctionnelle

* Dans Proxmox, créer un jeton d'API et le stocker en lieu sûr

* Dans Terraform, configurer le provider Proxmox avec les informations de connexion suivantes :

```hcl
terraform {
  required_providers {
    proxmox = {
      source = "bpg/proxmox"
      version = "0.42.0"
    }
  }
}

provider "proxmox" {
    endpoint = "https://localhost:8006/ap2/json"
    api_token = "username@pam!token_name=e38ece8c-541c-402b-af73-6d1b45925f6f"
    insecure = true # modifier si l'instance proxmox est en SSL
    ssh {
      agent = true
      username = "root"
    }
}
```

* En l'état cela ne permet pas de tester si la connexion fonctionne correctement car notre configuration ne contient aucune requête

* Pour tester la connexion, ajouter une source de données :

```hcl
data "proxmox_virtual_environment_users" "available_users" {}

output "proxmox_user_id" {
  value = data.proxmox_virtual_environment_users.available_users
}
```

* Exécuter `terraform init` puis `terraform apply` pour vérifier que la connexion fonctionne correctement, si c'est le cas on récupère une liste d'utilisateurs

* Montrer le comportement lorsque la connexion ne fonctionne pas :
** Si l'URL est invalide, on obtient une erreur `connection refused`
** Si le token est invalide, on obtient une erreur `401 Unauthorized`
--

// end::demo[]

== Préparer l'instance Proxmox

* pour pouvoir connecter Terraform à Proxmox, une instance Proxmox doit être préalablement configurée
* l'instance doit être accessible depuis le réseau où Terraform est exécuté
* un utilisateur ou jeton API avec les permissions nécessaires doit être créé

=== Créer un moyen d'authentification avec Proxmox

* 2 options pour s'authentifier avec Proxmox :
** créer un utilisateur avec un mot de passe
** créer un jeton d'API

* pour des raisons de sécurité, il est recommandé d'utiliser un jeton d'API

=== Créer un jeton d'API

* se connecter à l'interface web de Proxmox
* dans le menu `Datacenter`, sélectionner `Permissions`
* cliquer sur `API Tokens` puis `Create API Token`
* donner un nom au jeton et sélectionner les permissions nécessaires
* copier le jeton et le stocker en lieu sûr

== Utiliser le provider

Ajouter le provider dans le fichier de configuration Terraform

```hcl
terraform {
  required_providers {
    proxmox = {
      source = "bpg/proxmox"
      version = "0.42.0"
    }
  }
}
```

**Cela permet de s'assurer que Terraform utilise le bon provider**

=== Configurer le provider

Comme pour tout provider il faut consulter la https://registry.terraform.io/providers/bpg/proxmox/latest/docs[documentation] pour connaître les paramètres nécessaires

Le provider bpg/proxmox nécessite les paramètres suivants :

* `endpoint` : l'URL de l'API Proxmox
* `api_token` : le jeton d'API

**OU** (_déconseillé_)

* `username` : le nom d'utilisateur
* `password` : le mot de passe de l'utilisateur

=== Arguments optionnels mais recommandés

* `insecure` : permet de désactiver la vérification du certificat SSL (utile pour les environnements de test)
* `ssh` : permet de configurer une connexion SSH pour les opérations de provisioning
* `timeout` : permet de définir un timeout pour les requêtes API

=== Structure du jeton API

Le jeton d'API Proxmox est structuré de la manière suivante :

```
username@pam!token_name=token_value
```

**Il faut remplacer les valeurs par ce que vous avez créé dans Proxmox**

=== Exemple de configuration

```hcl
provider "proxmox" {
    endpoint = "https://localhost:8006/ap2/json"
    api_token = "root@pam!oclock=e38ece8c-541c-402b-af73-6d1b45925f6f"
    insecure = true
    ssh {
      agent = true
      username = "root"
    }
}
```

**En l'état cette configuration ne permet pas de tester la connexion, il faut ajouter une interaction avec l'API Proxmox**

=== Tester la connexion

Pour vérifier que la connexion fonctionne correctement, il est possible d'ajouter une source de données, comme https://registry.terraform.io/providers/bpg/proxmox/latest/docs/data-sources/virtual_environment_users[indiqué dans la documentation du provider]

```hcl
data "proxmox_virtual_environment_users" "available_users" {}
```

=== Afficher un résultat

Pour afficher un résultat, il est possible d'utiliser une sortie Terraform

```hcl
output "proxmox_user_id" {
  value = data.proxmox_virtual_environment_users.available_users
}
```

=== Exécuter Terraform

Pour tester la connexion, il suffit d'exécuter les commandes suivantes :

```shell
terraform init
terraform apply
```

**Si la connexion fonctionne correctement, Terraform affiche une liste d'utilisateurs**

// end::deroulement[]

== Conclusion
// tag::conclusion[]
* le provider bpg/proxmox permet de gérer des ressources Proxmox avec Terraform
* il nécessite une configuration spécifique pour se connecter à l'API Proxmox
* il est possible de tester la connexion avec une source de données
// end::conclusion[]