:title: Layout
:number: 03
include::../../../../../../adoc/libs/header-episode.adoc[]

// tag::intro[]
Utilisation du CSS pour placer les éléments sur la page avec 2 approches (ancienne et moderne).
// end::intro[]

== Objectifs pédagogiques

// tag::objectifs[]
* *Appliquer* des positionnement en CSS
* *Comprendre* les avantages de Flexbox
// end::objectifs[]

== Prérequis formateur

// tag::prerequis[]
* Pas de pré-requis
// end::prerequis[]

== Déroulement

// tag::deroulement[]
WARNING: Ne pas aborder **grid**, **position** et les unités **vh** et **vw**

:correction: https://github.com/O-clock-FS-JS/Hero-corp-fan-page/tree/correction
:temps: 135 minutes
:description: Pensez à bien commenter votre code. Vous pouvez ajouter des commentaires pour expliquer vos choix, vos réflexions, ou pour donner des indications sur la structure de votre code.
include::../../../../../../adoc/libs/intro-correction.adoc[]

.Voir le détail de la correction
[%collapsible]
====
**Durée** : 2h15  

**Support** : https://github.com/O-clock-FS-JS/Hero-corp-fan-page/tree/correction[Hero corps correction,window=_blank]

> 💡 Il est possible d'introduire les variables CSS pour les couleurs : https://developer.mozilla.org/fr/docs/Web/CSS/Using_CSS_custom_properties[Variables,window=_blank] 
> Il est aussi possible de parler de cette astuce : https://www.aleksandrhovhannisyan.com/blog/62-5-percent-font-size-trick/[10px,window=_blank]

Pose de tout le HTML ( hors bonus ) avec toutes les balises sémantiques

`article` c'est nouveau on peut revenir un peu dessus  

Utilisez le plus de classes possible  

Pour le `Hero Corp ( la série )` on peut faire : 

- soit un `h1` et un `h2` avec un `display: inline;`
- soit mettre un `span` dans le `h1` (Ici em/rem possible si vous le sentez)

S'ls savent pas quelle balise utiliser, on leurs dit de voir suivant le sens, en second choix si c'est thématique qui n'est pas un `header` ou un `footer`, ni autonome, alors on met `section` et en dernier choix si c'est vide de sens on prends une `div`. https://developer.mozilla.org/fr/docs/Web/HTML/Element[(Eléments MDN),window=_blank]

Mettre en background-image l'image principale en haut du site : 

- On utilise background image si cela ne gêne pas pour l'accessibilité / SEO car pas d'attribut alt
- En CSS la manipulation est plus complète

Bien montrer la différence entre margin (aérer les éléments entre eux) et padding (agrandir la taille du fond, aérer avec le bord le contenu) par rapport au `box-sizing`. Notez que parfois on peut prendre l'un ou l'autre sans trop de différence.

Prendre le temps sur l'inclusion de la font google :

  - Bien expliquer `font-face`, on vient juste linker une feuille de style
  - On parle bien de récupérer les fonts en fonction des styles utilisés ( bold ) 100, 200, 300, etc ...

Si pas déjà fait, au niveau du css, introduire le rem, on peut changer la font size du navigateur pour prouver le concept.

Le conteneur, on peut le mettre en `pourcentage` avec une `max-width` en pixel pour borner : si on réduit le navigateur par exemple. Vous pouvez commencer à parler de responsive.

Si en avance, commencer à placer les liens des acteurs et les styliser, sinon le faire après la pause repas.

On va manger ! 🍕 
====

TIP: 🍕 Pause déjeuner

include::../../../../modules/bases-web/045-block.adoc[options=modules]

include::../../../../modules/bases-web/046-flex.adoc[options=modules]

*Fin du cours*

Jeu à proposer pour ceux qui veulent : https://flexboxfroggy.com/#fr[Flexbox froggy,window=_blank], préciser que cela permet de s'entrainer mais la doc sera toujours essentielle. 

Le jeu peut être proposé le lendemain car déjà le challenge à faire

:challenge: https://github.com/O-clock-FS-JS/oFig-home
:description: une vitrine d'un site de vente de figurines. Flexbox essentiel pour ce challenge.
:correction:
include::../../../../../../adoc/libs/intro-challenge.adoc[]
// end::deroulement[]
